import test from 'node:test';
import assert from 'node:assert/strict';

import { buildRunProductFinalizationSummary } from '../src/features/indexing/orchestration/finalize/buildRunProductFinalizationSummary.js';

test('buildRunProductFinalizationSummary captures runtime usage and builds the canonical run summary payload', () => {
  const calls = [];
  const summary = { runId: 'run-1', validated: true };
  const normalizeAmbiguityLevelFn = (payload) => payload;
  const isHelperSyntheticSourceFn = (payload) => payload;
  const buildTopEvidenceReferencesFn = (payload) => payload;

  const result = buildRunProductFinalizationSummary({
    llmRuntime: {
      getUsageState: () => {
        calls.push('getUsageState');
        return {
          llmCallCount: 6,
          llmCostUsd: 0.12,
          llmEstimatedUsageCount: 4,
          llmRetryWithoutSchemaCount: 1,
        };
      },
    },
    productId: 'product-1',
    runId: 'run-1',
    category: 'mouse',
    config: { runProfile: 'thorough' },
    runtimeMode: 'aggressive',
    identityFingerprint: 'brand:model',
    identityLockStatus: 'locked',
    dedupeMode: 'strict',
    gate: { validated: true },
    validatedReason: 'validated',
    confidence: 0.91,
    completenessStats: { completenessRequired: 0.88 },
    coverageStats: { coverageOverall: 0.84 },
    targets: { targetCompleteness: 0.9 },
    anchors: { shape: 'symmetrical' },
    allAnchorConflicts: [{ severity: 'MAJOR' }],
    anchorMajorConflictsCount: 1,
    identityConfidence: 0.92,
    identityGate: { validated: true },
    extractionGateOpen: true,
    identityLock: { family_model_count: 2 },
    publishable: true,
    publishBlockers: [],
    identityReport: { status: 'ok' },
    fieldsBelowPassTarget: ['weight_g'],
    criticalFieldsBelowPassTarget: [],
    newValuesProposed: [{ field: 'weight_g', value: '59' }],
    provenance: { weight_g: [{ url: 'https://example.com/spec' }] },
    sourceResults: [{ url: 'https://example.com/spec' }],
    discoveryResult: { enabled: true },
    indexingHelperFlowEnabled: true,
    helperContext: { active: true },
    helperSupportiveSyntheticSources: [{ url: 'helper://supportive/one' }],
    helperFilledFields: ['weight_g'],
    helperFilledByMethod: { supportive: 1 },
    helperMismatches: [{ field: 'dpi' }],
    componentPriorFilledFields: ['shape'],
    componentPriorMatches: ['shell'],
    criticDecisions: { accept: [] },
    llmValidatorDecisions: { enabled: false },
    runtimeFieldRulesEngine: { version: 'v1' },
    runtimeGateResult: { failures: [] },
    curationSuggestionResult: { appended_count: 1 },
    llmTargetFields: ['shape'],
    goldenExamples: [{ id: 1 }],
    llmCandidatesAccepted: 3,
    llmSourcesUsed: 2,
    contribution: { llmFields: ['shape'] },
    llmContext: { verification: { done: true } },
    aggressiveExtraction: { enabled: false },
    categoryConfig: { category: 'mouse' },
    fetcherMode: 'playwright',
    fetcherStartFallbackReason: null,
    indexingResumeKey: 'resume/key',
    resumeMode: 'resume',
    resumeMaxAgeHours: 24,
    previousResumeStateAgeHours: 2,
    resumeReextractEnabled: true,
    resumeReextractAfterHours: 48,
    resumeSeededPendingCount: 1,
    resumeSeededLlmRetryCount: 2,
    resumeSeededReextractCount: 3,
    resumePersistedPendingCount: 4,
    resumePersistedLlmRetryCount: 5,
    resumePersistedSuccessCount: 6,
    manufacturerSources: [{ url: 'https://example.com/spec' }],
    manufacturerMajorConflicts: 0,
    plannerStats: { pending: 2 },
    endpointMining: { endpoint_count: 3 },
    temporalEvidence: { hits: 1 },
    inferenceResult: { filled_fields: ['shape'] },
    hypothesisQueue: [{ field: 'shape' }],
    hypothesisFollowupRoundsExecuted: 1,
    hypothesisFollowupSeededUrls: ['https://seed.example.com'],
    constraintAnalysis: { conflicts: [] },
    fieldReasoning: { shape: { reason: 'anchored' } },
    trafficLight: { green: ['shape'] },
    needSet: { needs: [{ field_key: 'shape' }] },
    phase07PrimeSources: { summary: { refs_selected_total: 2 } },
    phase08Extraction: { summary: { accepted_candidate_count: 3 } },
    parserHealthRows: [{ score: 1 }],
    parserHealthAverage: 0.44,
    fingerprintCount: 7,
    durationMs: 1234,
    roundContext: { round: 2 },
    normalizeAmbiguityLevelFn,
    isHelperSyntheticSourceFn,
    buildTopEvidenceReferencesFn,
    buildRunSummaryPayloadPhaseCallsiteContextFn: (payload) => {
      calls.push(['buildRunSummaryPayloadPhaseCallsiteContextFn', payload]);
      return payload;
    },
    buildRunSummaryPayloadContextFn: (payload) => {
      calls.push(['buildRunSummaryPayloadContextFn', payload]);
      return { summaryContext: payload };
    },
    buildRunSummaryPayloadFn: (payload) => {
      calls.push(['buildRunSummaryPayloadFn', payload]);
      return summary;
    },
  });

  assert.deepEqual(calls, [
    'getUsageState',
    ['buildRunSummaryPayloadPhaseCallsiteContextFn', {
      productId: 'product-1',
      runId: 'run-1',
      category: 'mouse',
      config: { runProfile: 'thorough' },
      runtimeMode: 'aggressive',
      identityFingerprint: 'brand:model',
      identityLockStatus: 'locked',
      dedupeMode: 'strict',
      gate: { validated: true },
      validatedReason: 'validated',
      confidence: 0.91,
      completenessStats: { completenessRequired: 0.88 },
      coverageStats: { coverageOverall: 0.84 },
      targets: { targetCompleteness: 0.9 },
      anchors: { shape: 'symmetrical' },
      allAnchorConflicts: [{ severity: 'MAJOR' }],
      anchorMajorConflictsCount: 1,
      identityConfidence: 0.92,
      identityGate: { validated: true },
      extractionGateOpen: true,
      identityLock: { family_model_count: 2 },
      publishable: true,
      publishBlockers: [],
      identityReport: { status: 'ok' },
      fieldsBelowPassTarget: ['weight_g'],
      criticalFieldsBelowPassTarget: [],
      newValuesProposed: [{ field: 'weight_g', value: '59' }],
      provenance: { weight_g: [{ url: 'https://example.com/spec' }] },
      sourceResults: [{ url: 'https://example.com/spec' }],
      discoveryResult: { enabled: true },
      indexingHelperFlowEnabled: true,
      helperContext: { active: true },
      helperSupportiveSyntheticSources: [{ url: 'helper://supportive/one' }],
      helperFilledFields: ['weight_g'],
      helperFilledByMethod: { supportive: 1 },
      helperMismatches: [{ field: 'dpi' }],
      componentPriorFilledFields: ['shape'],
      componentPriorMatches: ['shell'],
      criticDecisions: { accept: [] },
      llmValidatorDecisions: { enabled: false },
      runtimeFieldRulesEngine: { version: 'v1' },
      runtimeGateResult: { failures: [] },
      curationSuggestionResult: { appended_count: 1 },
      llmTargetFields: ['shape'],
      goldenExamples: [{ id: 1 }],
      llmCandidatesAccepted: 3,
      llmSourcesUsed: 2,
      contribution: { llmFields: ['shape'] },
      llmRetryWithoutSchemaCount: 1,
      llmEstimatedUsageCount: 4,
      llmContext: { verification: { done: true } },
      llmCallCount: 6,
      llmCostUsd: 0.12,
        aggressiveExtraction: { enabled: false },
      categoryConfig: { category: 'mouse' },
      fetcherMode: 'playwright',
      fetcherStartFallbackReason: null,
      indexingResumeKey: 'resume/key',
      resumeMode: 'resume',
      resumeMaxAgeHours: 24,
      previousResumeStateAgeHours: 2,
      resumeReextractEnabled: true,
      resumeReextractAfterHours: 48,
      resumeSeededPendingCount: 1,
      resumeSeededLlmRetryCount: 2,
      resumeSeededReextractCount: 3,
      resumePersistedPendingCount: 4,
      resumePersistedLlmRetryCount: 5,
      resumePersistedSuccessCount: 6,
      manufacturerSources: [{ url: 'https://example.com/spec' }],
      manufacturerMajorConflicts: 0,
      plannerStats: { pending: 2 },
      endpointMining: { endpoint_count: 3 },
      temporalEvidence: { hits: 1 },
      inferenceResult: { filled_fields: ['shape'] },
      hypothesisQueue: [{ field: 'shape' }],
      hypothesisFollowupRoundsExecuted: 1,
      hypothesisFollowupSeededUrls: ['https://seed.example.com'],
      constraintAnalysis: { conflicts: [] },
      fieldReasoning: { shape: { reason: 'anchored' } },
      trafficLight: { green: ['shape'] },
      needSet: { needs: [{ field_key: 'shape' }] },
      phase07PrimeSources: { summary: { refs_selected_total: 2 } },
      phase08Extraction: { summary: { accepted_candidate_count: 3 } },
      parserHealthRows: [{ score: 1 }],
      parserHealthAverage: 0.44,
      fingerprintCount: 7,
      durationMs: 1234,
      roundContext: { round: 2 },
      normalizeAmbiguityLevel: normalizeAmbiguityLevelFn,
      isHelperSyntheticSource: isHelperSyntheticSourceFn,
      buildTopEvidenceReferences: buildTopEvidenceReferencesFn,
    }],
    ['buildRunSummaryPayloadContextFn', {
      productId: 'product-1',
      runId: 'run-1',
      category: 'mouse',
      config: { runProfile: 'thorough' },
      runtimeMode: 'aggressive',
      identityFingerprint: 'brand:model',
      identityLockStatus: 'locked',
      dedupeMode: 'strict',
      gate: { validated: true },
      validatedReason: 'validated',
      confidence: 0.91,
      completenessStats: { completenessRequired: 0.88 },
      coverageStats: { coverageOverall: 0.84 },
      targets: { targetCompleteness: 0.9 },
      anchors: { shape: 'symmetrical' },
      allAnchorConflicts: [{ severity: 'MAJOR' }],
      anchorMajorConflictsCount: 1,
      identityConfidence: 0.92,
      identityGate: { validated: true },
      extractionGateOpen: true,
      identityLock: { family_model_count: 2 },
      publishable: true,
      publishBlockers: [],
      identityReport: { status: 'ok' },
      fieldsBelowPassTarget: ['weight_g'],
      criticalFieldsBelowPassTarget: [],
      newValuesProposed: [{ field: 'weight_g', value: '59' }],
      provenance: { weight_g: [{ url: 'https://example.com/spec' }] },
      sourceResults: [{ url: 'https://example.com/spec' }],
      discoveryResult: { enabled: true },
      indexingHelperFlowEnabled: true,
      helperContext: { active: true },
      helperSupportiveSyntheticSources: [{ url: 'helper://supportive/one' }],
      helperFilledFields: ['weight_g'],
      helperFilledByMethod: { supportive: 1 },
      helperMismatches: [{ field: 'dpi' }],
      componentPriorFilledFields: ['shape'],
      componentPriorMatches: ['shell'],
      criticDecisions: { accept: [] },
      llmValidatorDecisions: { enabled: false },
      runtimeFieldRulesEngine: { version: 'v1' },
      runtimeGateResult: { failures: [] },
      curationSuggestionResult: { appended_count: 1 },
      llmTargetFields: ['shape'],
      goldenExamples: [{ id: 1 }],
      llmCandidatesAccepted: 3,
      llmSourcesUsed: 2,
      contribution: { llmFields: ['shape'] },
      llmRetryWithoutSchemaCount: 1,
      llmEstimatedUsageCount: 4,
      llmContext: { verification: { done: true } },
      llmCallCount: 6,
      llmCostUsd: 0.12,
        aggressiveExtraction: { enabled: false },
      categoryConfig: { category: 'mouse' },
      fetcherMode: 'playwright',
      fetcherStartFallbackReason: null,
      indexingResumeKey: 'resume/key',
      resumeMode: 'resume',
      resumeMaxAgeHours: 24,
      previousResumeStateAgeHours: 2,
      resumeReextractEnabled: true,
      resumeReextractAfterHours: 48,
      resumeSeededPendingCount: 1,
      resumeSeededLlmRetryCount: 2,
      resumeSeededReextractCount: 3,
      resumePersistedPendingCount: 4,
      resumePersistedLlmRetryCount: 5,
      resumePersistedSuccessCount: 6,
      manufacturerSources: [{ url: 'https://example.com/spec' }],
      manufacturerMajorConflicts: 0,
      plannerStats: { pending: 2 },
      endpointMining: { endpoint_count: 3 },
      temporalEvidence: { hits: 1 },
      inferenceResult: { filled_fields: ['shape'] },
      hypothesisQueue: [{ field: 'shape' }],
      hypothesisFollowupRoundsExecuted: 1,
      hypothesisFollowupSeededUrls: ['https://seed.example.com'],
      constraintAnalysis: { conflicts: [] },
      fieldReasoning: { shape: { reason: 'anchored' } },
      trafficLight: { green: ['shape'] },
      needSet: { needs: [{ field_key: 'shape' }] },
      phase07PrimeSources: { summary: { refs_selected_total: 2 } },
      phase08Extraction: { summary: { accepted_candidate_count: 3 } },
      parserHealthRows: [{ score: 1 }],
      parserHealthAverage: 0.44,
      fingerprintCount: 7,
      durationMs: 1234,
      roundContext: { round: 2 },
      normalizeAmbiguityLevel: normalizeAmbiguityLevelFn,
      isHelperSyntheticSource: isHelperSyntheticSourceFn,
      buildTopEvidenceReferences: buildTopEvidenceReferencesFn,
    }],
    ['buildRunSummaryPayloadFn', {
      summaryContext: {
        productId: 'product-1',
        runId: 'run-1',
        category: 'mouse',
        config: { runProfile: 'thorough' },
        runtimeMode: 'aggressive',
        identityFingerprint: 'brand:model',
        identityLockStatus: 'locked',
        dedupeMode: 'strict',
        gate: { validated: true },
        validatedReason: 'validated',
        confidence: 0.91,
        completenessStats: { completenessRequired: 0.88 },
        coverageStats: { coverageOverall: 0.84 },
        targets: { targetCompleteness: 0.9 },
        anchors: { shape: 'symmetrical' },
        allAnchorConflicts: [{ severity: 'MAJOR' }],
        anchorMajorConflictsCount: 1,
        identityConfidence: 0.92,
        identityGate: { validated: true },
        extractionGateOpen: true,
        identityLock: { family_model_count: 2 },
        publishable: true,
        publishBlockers: [],
        identityReport: { status: 'ok' },
        fieldsBelowPassTarget: ['weight_g'],
        criticalFieldsBelowPassTarget: [],
        newValuesProposed: [{ field: 'weight_g', value: '59' }],
        provenance: { weight_g: [{ url: 'https://example.com/spec' }] },
        sourceResults: [{ url: 'https://example.com/spec' }],
        discoveryResult: { enabled: true },
        indexingHelperFlowEnabled: true,
        helperContext: { active: true },
        helperSupportiveSyntheticSources: [{ url: 'helper://supportive/one' }],
        helperFilledFields: ['weight_g'],
        helperFilledByMethod: { supportive: 1 },
        helperMismatches: [{ field: 'dpi' }],
        componentPriorFilledFields: ['shape'],
        componentPriorMatches: ['shell'],
        criticDecisions: { accept: [] },
        llmValidatorDecisions: { enabled: false },
        runtimeFieldRulesEngine: { version: 'v1' },
        runtimeGateResult: { failures: [] },
        curationSuggestionResult: { appended_count: 1 },
        llmTargetFields: ['shape'],
        goldenExamples: [{ id: 1 }],
        llmCandidatesAccepted: 3,
        llmSourcesUsed: 2,
        contribution: { llmFields: ['shape'] },
        llmRetryWithoutSchemaCount: 1,
        llmEstimatedUsageCount: 4,
        llmContext: { verification: { done: true } },
        llmCallCount: 6,
        llmCostUsd: 0.12,
            aggressiveExtraction: { enabled: false },
        categoryConfig: { category: 'mouse' },
        fetcherMode: 'playwright',
        fetcherStartFallbackReason: null,
        indexingResumeKey: 'resume/key',
        resumeMode: 'resume',
        resumeMaxAgeHours: 24,
        previousResumeStateAgeHours: 2,
        resumeReextractEnabled: true,
        resumeReextractAfterHours: 48,
        resumeSeededPendingCount: 1,
        resumeSeededLlmRetryCount: 2,
        resumeSeededReextractCount: 3,
        resumePersistedPendingCount: 4,
        resumePersistedLlmRetryCount: 5,
        resumePersistedSuccessCount: 6,
        manufacturerSources: [{ url: 'https://example.com/spec' }],
        manufacturerMajorConflicts: 0,
        plannerStats: { pending: 2 },
        endpointMining: { endpoint_count: 3 },
        temporalEvidence: { hits: 1 },
        inferenceResult: { filled_fields: ['shape'] },
        hypothesisQueue: [{ field: 'shape' }],
        hypothesisFollowupRoundsExecuted: 1,
        hypothesisFollowupSeededUrls: ['https://seed.example.com'],
        constraintAnalysis: { conflicts: [] },
        fieldReasoning: { shape: { reason: 'anchored' } },
        trafficLight: { green: ['shape'] },
        needSet: { needs: [{ field_key: 'shape' }] },
        phase07PrimeSources: { summary: { refs_selected_total: 2 } },
        phase08Extraction: { summary: { accepted_candidate_count: 3 } },
        parserHealthRows: [{ score: 1 }],
        parserHealthAverage: 0.44,
        fingerprintCount: 7,
        durationMs: 1234,
        roundContext: { round: 2 },
        normalizeAmbiguityLevel: normalizeAmbiguityLevelFn,
        isHelperSyntheticSource: isHelperSyntheticSourceFn,
        buildTopEvidenceReferences: buildTopEvidenceReferencesFn,
      },
    }],
  ]);

  assert.equal(result.summary, summary);
  assert.equal(result.llmCallCount, 6);
  assert.equal(result.llmCostUsd, 0.12);
  assert.equal(result.llmEstimatedUsageCount, 4);
  assert.equal(result.llmRetryWithoutSchemaCount, 1);
});
