export function buildIndexingResumePersistenceContext({
  storage,
  logger,
  indexingResumeKey,
  category,
  productId,
  runId,
  planner,
  resumeCooldownSkippedUrls,
  resumeFetchFailedUrls,
  previousResumePendingUnseeded,
  resumePersistLimit,
  previousResumeRetryRows,
  llmRetryReasonByUrl,
  attemptedSourceUrls,
  resumeRetryPersistLimit,
  previousResumeSuccessRows,
  successfulSourceMetaByUrl,
  resumeSeededPendingCount,
  resumeSeededLlmRetryCount,
  resumeSeededReextractCount,
  indexingResumeSuccessPersistLimit,
  toInt,
  normalizeHttpUrlList,
  collectPlannerPendingUrls,
  buildNextLlmRetryRows,
  buildNextSuccessRows,
} = {}) {
  return {
    storage,
    logger,
    indexingResumeKey,
    category,
    productId,
    runId,
    planner,
    resumeCooldownSkippedUrls,
    resumeFetchFailedUrls,
    previousResumePendingUnseeded,
    resumePersistLimit,
    previousResumeRetryRows,
    llmRetryReasonByUrl,
    attemptedSourceUrls,
    resumeRetryPersistLimit,
    previousResumeSuccessRows,
    successfulSourceMetaByUrl,
    resumeSeededPendingCount,
    resumeSeededLlmRetryCount,
    resumeSeededReextractCount,
    indexingResumeSuccessPersistLimit,
    toIntFn: toInt,
    normalizeHttpUrlListFn: normalizeHttpUrlList,
    collectPlannerPendingUrlsFn: collectPlannerPendingUrls,
    buildNextLlmRetryRowsFn: buildNextLlmRetryRows,
    buildNextSuccessRowsFn: buildNextSuccessRows,
  };
}
