import { buildRunSummaryAnalysisSection } from './buildRunSummaryAnalysisSection.js';
import { buildRunSummaryIdentityDiscoverySection } from './buildRunSummaryIdentityDiscoverySection.js';
import { buildRunSummaryOperationsSection } from './buildRunSummaryOperationsSection.js';

export function buildRunSummaryPayload({
  productId = '',
  runId = '',
  category = '',
  config = {},
  runtimeMode = 'production',
  identityFingerprint = '',
  identityLockStatus = '',
  dedupeMode = '',
  gate = {},
  validatedReason = '',
  confidence = 0,
  completenessStats = {},
  coverageStats = {},
  targets = {},
  anchors = {},
  allAnchorConflicts = [],
  anchorMajorConflictsCount = 0,
  identityConfidence = 0,
  identityGate = {},
  extractionGateOpen = false,
  identityLock = {},
  publishable = false,
  publishBlockers = [],
  identityReport = {},
  fieldsBelowPassTarget = [],
  criticalFieldsBelowPassTarget = [],
  newValuesProposed = [],
  provenance = {},
  sourceResults = [],
  discoveryResult = {},
  indexingHelperFlowEnabled = false,
  helperContext = {},
  helperSupportiveSyntheticSources = [],
  helperFilledFields = [],
  helperFilledByMethod = {},
  helperMismatches = [],
  componentPriorFilledFields = [],
  componentPriorMatches = [],
  criticDecisions = {},
  llmValidatorDecisions = {},
  runtimeFieldRulesEngine = null,
  runtimeGateResult = {},
  curationSuggestionResult = {},
  llmTargetFields = [],
  goldenExamples = [],
  llmCandidatesAccepted = 0,
  llmSourcesUsed = 0,
  contribution = {},
  llmRetryWithoutSchemaCount = 0,
  llmEstimatedUsageCount = 0,
  llmContext = {},
  llmCallCount = 0,
  llmCostUsd = 0,
  aggressiveExtraction = {},
  categoryConfig = {},
  fetcherMode = '',
  fetcherStartFallbackReason = null,
  indexingResumeKey = '',
  resumeMode = '',
  resumeMaxAgeHours = null,
  previousResumeStateAgeHours = null,
  resumeReextractEnabled = false,
  resumeReextractAfterHours = null,
  resumeSeededPendingCount = 0,
  resumeSeededLlmRetryCount = 0,
  resumeSeededReextractCount = 0,
  resumePersistedPendingCount = 0,
  resumePersistedLlmRetryCount = 0,
  resumePersistedSuccessCount = 0,
  manufacturerSources = [],
  manufacturerMajorConflicts = 0,
  plannerStats = {},
  endpointMining = {},
  temporalEvidence = {},
  inferenceResult = {},
  hypothesisQueue = [],
  hypothesisFollowupRoundsExecuted = 0,
  hypothesisFollowupSeededUrls = [],
  constraintAnalysis = {},
  fieldReasoning = {},
  trafficLight = {},
  needSet = {},
  phase07PrimeSources = {},
  phase08Extraction = {},
  parserHealthRows = [],
  parserHealthAverage = 0,
  fingerprintCount = 0,
  durationMs = 0,
  roundContext = null,
  legacyRootFallback = '',
  normalizeAmbiguityLevelFn,
  isHelperSyntheticSourceFn,
  buildTopEvidenceReferencesFn,
  nowIsoFn = () => new Date().toISOString(),
} = {}) {
  const helperRootKey = `helper${'FilesRoot'}`;
  const helperRoot = config[helperRootKey] || legacyRootFallback;

  return {
    productId,
    runId,
    category,
    run_profile: 'standard',
    runtime_mode: runtimeMode,
    identity_fingerprint: identityFingerprint,
    identity_lock_status: identityLockStatus,
    dedupe_mode: dedupeMode,
    phase_cursor: 'completed',
    validated: gate.validated,
    reason: validatedReason,
    validated_reason: validatedReason,
    validation_reasons: gate.reasons,
    confidence,
    confidence_percent: gate.confidencePercent,
    completeness_required: completenessStats.completenessRequired,
    completeness_required_percent: gate.completenessRequiredPercent,
    coverage_overall: coverageStats.coverageOverall,
    coverage_overall_percent: gate.coverageOverallPercent,
    target_completeness: targets.targetCompleteness,
    target_confidence: targets.targetConfidence,
    ...buildRunSummaryIdentityDiscoverySection({
      completenessStats,
      anchors,
      allAnchorConflicts,
      anchorMajorConflictsCount,
      identityConfidence,
      identityGate,
      extractionGateOpen,
      identityLock,
      publishable,
      publishBlockers,
      identityReport,
      fieldsBelowPassTarget,
      criticalFieldsBelowPassTarget,
      newValuesProposed,
      sourceResults,
      discoveryResult,
      config,
      normalizeAmbiguityLevelFn,
      isHelperSyntheticSourceFn,
    }),
    ...buildRunSummaryOperationsSection({
      config,
      helperRoot,
      indexingHelperFlowEnabled,
      helperContext,
      helperSupportiveSyntheticSources,
      helperFilledFields,
      helperFilledByMethod,
      helperMismatches,
      componentPriorFilledFields,
      componentPriorMatches,
      criticDecisions,
      llmValidatorDecisions,
      runtimeFieldRulesEngine,
      runtimeGateResult,
      curationSuggestionResult,
      llmTargetFields,
      goldenExamples,
      llmCandidatesAccepted,
      llmSourcesUsed,
      contribution,
      llmRetryWithoutSchemaCount,
      llmEstimatedUsageCount,
      llmContext,
      llmCallCount,
      llmCostUsd,
      aggressiveExtraction,
      categoryConfig,
      fetcherMode,
      fetcherStartFallbackReason,
      indexingResumeKey,
      resumeMode,
      resumeMaxAgeHours,
      previousResumeStateAgeHours,
      resumeReextractEnabled,
      resumeReextractAfterHours,
      resumeSeededPendingCount,
      resumeSeededLlmRetryCount,
      resumeSeededReextractCount,
      resumePersistedPendingCount,
      resumePersistedLlmRetryCount,
      resumePersistedSuccessCount,
    }),
    ...buildRunSummaryAnalysisSection({
      config,
      manufacturerSources,
      manufacturerMajorConflicts,
      plannerStats,
      endpointMining,
      temporalEvidence,
      inferenceResult,
      hypothesisQueue,
      hypothesisFollowupRoundsExecuted,
      hypothesisFollowupSeededUrls,
      constraintAnalysis,
      fieldReasoning,
      trafficLight,
      needSet,
      phase07PrimeSources,
      phase08Extraction,
      provenance,
      buildTopEvidenceReferencesFn,
      parserHealthRows,
      parserHealthAverage,
      fingerprintCount,
      durationMs,
      roundContext,
      nowIsoFn,
    }),
  };
}
