export function buildRunSummaryOperationsSection({
  config = {},
  helperRoot = '',
  indexingHelperFlowEnabled = false,
  helperContext = {},
  helperSupportiveSyntheticSources = [],
  helperFilledFields = [],
  helperFilledByMethod = {},
  helperMismatches = [],
  componentPriorFilledFields = [],
  componentPriorMatches = [],
  criticDecisions = {},
  llmValidatorDecisions = {},
  runtimeFieldRulesEngine = null,
  runtimeGateResult = {},
  curationSuggestionResult = {},
  llmTargetFields = [],
  goldenExamples = [],
  llmCandidatesAccepted = 0,
  llmSourcesUsed = 0,
  contribution = {},
  llmRetryWithoutSchemaCount = 0,
  llmEstimatedUsageCount = 0,
  llmContext = {},
  llmCallCount = 0,
  llmCostUsd = 0,
  llmBudgetLimits = {},
  llmBudgetState = {},
  llmBudgetBlockedReason = null,
  aggressiveExtraction = {},
  categoryConfig = {},
  fetcherMode = '',
  fetcherStartFallbackReason = null,
  indexingResumeKey = '',
  resumeMode = '',
  resumeMaxAgeHours = null,
  previousResumeStateAgeHours = null,
  resumeReextractEnabled = false,
  resumeReextractAfterHours = null,
  resumeSeededPendingCount = 0,
  resumeSeededLlmRetryCount = 0,
  resumeSeededReextractCount = 0,
  resumePersistedPendingCount = 0,
  resumePersistedLlmRetryCount = 0,
  resumePersistedSuccessCount = 0,
} = {}) {
  return {
    category_authority: {
      enabled: indexingHelperFlowEnabled,
      global_category_authority_enabled: Boolean(config.categoryAuthorityEnabled),
      indexing_category_authority_enabled: Boolean(config.indexingCategoryAuthorityEnabled),
      root: helperRoot,
      active_filtering_match: Boolean(helperContext.active_match),
      active_filtering_source: helperContext.active_match?.source || null,
      active_filtering_record_id: helperContext.active_match?.record_id ?? null,
      seed_urls_from_active_count: (helperContext.seed_urls || []).length,
      seed_urls_from_active: (helperContext.seed_urls || []).slice(0, 25),
      active_total_rows: helperContext.stats?.active_total || 0,
      supportive_total_rows: helperContext.stats?.supportive_total || 0,
      supportive_file_count: helperContext.stats?.supportive_file_count || 0,
      supportive_match_count: helperContext.stats?.supportive_matched_count || 0,
      supportive_synthetic_sources_used: helperSupportiveSyntheticSources.length,
      supportive_fill_missing_enabled: Boolean(
        indexingHelperFlowEnabled && config.helperSupportiveFillMissing,
      ),
      supportive_fields_filled_count: helperFilledFields.length,
      supportive_fields_filled: helperFilledFields,
      supportive_fields_filled_by_method: helperFilledByMethod,
      supportive_mismatch_count: helperMismatches.length,
      supportive_mismatches: helperMismatches,
    },
    components: {
      prior_fields_filled_count: componentPriorFilledFields.length,
      prior_fields_filled: componentPriorFilledFields,
      matched_components: componentPriorMatches,
    },
    critic: {
      accept_count: (criticDecisions.accept || []).length,
      reject_count: (criticDecisions.reject || []).length,
      unknown_count: (criticDecisions.unknown || []).length,
      decisions: criticDecisions,
      llm_validator: {
        enabled: Boolean(llmValidatorDecisions.enabled),
        accept_count: (llmValidatorDecisions.accept || []).length,
        reject_count: (llmValidatorDecisions.reject || []).length,
        unknown_count: (llmValidatorDecisions.unknown || []).length,
        decisions: llmValidatorDecisions,
      },
    },
    runtime_engine: {
      enabled: Boolean(runtimeFieldRulesEngine),
      enforce_evidence: Boolean(config.fieldRulesEngineEnforceEvidence),
      failure_count: (runtimeGateResult.failures || []).length,
      warning_count: (runtimeGateResult.warnings || []).length,
      change_count: (runtimeGateResult.changes || []).length,
      curation_suggestions_count: (runtimeGateResult.curation_suggestions || []).length,
      curation_suggestions_appended_count: curationSuggestionResult?.appended_count || 0,
      curation_suggestions_total_count: curationSuggestionResult?.total_count || 0,
      curation_suggestions_path: curationSuggestionResult?.path || null,
      failures: runtimeGateResult.failures || [],
      warnings: runtimeGateResult.warnings || [],
    },
    llm: {
      enabled: Boolean(config.llmApiKey),
      provider: config.llmProvider || 'openai',
      model_extract: config.llmModelPlan || null,
      model_plan: config.llmModelPlan || null,
      model_validate: config.llmModelPlan || null,
      target_field_count: llmTargetFields.length,
      target_fields: llmTargetFields.slice(0, 80),
      golden_examples_count: goldenExamples.length,
      candidates_added: llmCandidatesAccepted,
      sources_with_llm_candidates: llmSourcesUsed,
      fields_filled_by_llm_count: (contribution.llmFields || []).length,
      fields_filled_by_llm: contribution.llmFields,
      fields_filled_by_component_db_count: (contribution.componentFields || []).length,
      fields_filled_by_component_db: contribution.componentFields,
      retry_without_schema_count: llmRetryWithoutSchemaCount,
      estimated_usage_count: llmEstimatedUsageCount,
      verify_mode_enabled: Boolean(config.llmVerifyMode),
      verify_trigger: llmContext.verification?.trigger || 'disabled',
      verify_performed: Boolean(llmContext.verification?.done),
      verify_report_key: llmContext.verification?.report_key || null,
      call_count_run: llmCallCount,
      cost_usd_run: Number.parseFloat((llmCostUsd || 0).toFixed(8)),
      budget: {
        monthly_budget_usd: llmBudgetLimits.monthlyBudgetUsd,
        monthly_spent_usd_after_run: llmBudgetState.monthlySpentUsd,
        per_product_budget_usd: llmBudgetLimits.productBudgetUsd,
        per_product_spent_usd_after_run: llmBudgetState.productSpentUsd,
        max_calls_per_product_total: llmBudgetLimits.maxCallsPerProductTotal,
        calls_per_product_total_after_run: llmBudgetState.productCallsTotal,
        max_calls_per_round: llmBudgetLimits.maxCallsPerRound,
        calls_used_current_round: llmBudgetState.roundCalls,
        blocked_reason: llmBudgetBlockedReason || null,
      },
    },
    aggressive_extraction: aggressiveExtraction,
    source_registry: {
      override_key: categoryConfig.sources_override_key || null,
    },
    crawl_profile: {
      fetcher_mode: fetcherMode,
      fetcher_fallback_reason: fetcherStartFallbackReason || null,
      max_run_seconds: config.maxRunSeconds,
      max_urls_per_product: config.maxUrlsPerProduct,
      max_pages_per_domain: config.maxPagesPerDomain,
      endpoint_signal_limit: config.endpointSignalLimit,
      endpoint_suggestion_limit: config.endpointSuggestionLimit,
      endpoint_network_scan_limit: config.endpointNetworkScanLimit,
    },
    indexing_resume: {
      key: indexingResumeKey,
      mode: resumeMode,
      max_age_hours: resumeMaxAgeHours,
      state_age_hours: Number.isFinite(previousResumeStateAgeHours)
        ? Number(previousResumeStateAgeHours.toFixed(2))
        : null,
      reextract_enabled: resumeReextractEnabled,
      reextract_after_hours: resumeReextractAfterHours,
      seeded_pending_count: resumeSeededPendingCount,
      seeded_llm_retry_count: resumeSeededLlmRetryCount,
      seeded_reextract_count: resumeSeededReextractCount,
      persisted_pending_count: resumePersistedPendingCount,
      persisted_llm_retry_count: resumePersistedLlmRetryCount,
      persisted_success_count: resumePersistedSuccessCount,
    },
  };
}
