function freezeContract(contract = {}) {
  return Object.freeze({ ...contract });
}

export function buildProductFinalizationPipelineContracts({ context = {} } = {}) {
  const derivation = freezeContract({
    adapterManager: context.adapterManager,
    job: context.job,
    runId: context.runId,
    storage: context.storage,
    helperSupportiveSyntheticSources: context.helperSupportiveSyntheticSources,
    adapterArtifacts: context.adapterArtifacts,
    sourceResults: context.sourceResults,
    anchors: context.anchors,
    config: context.config,
    productId: context.productId,
    categoryConfig: context.categoryConfig,
    fieldOrder: context.fieldOrder,
    category: context.category,
    runtimeFieldRulesEngine: context.runtimeFieldRulesEngine,
    terminalReason: context.terminalReason,
    learnedConstraints: context.learnedConstraints,
    logger: context.logger,
    llmContext: context.llmContext,
    roundContext: context.roundContext,
    discoveryResult: context.discoveryResult,
    artifactsByHost: context.artifactsByHost,
    requiredFields: context.requiredFields,
    targets: context.targets,
    startMs: context.startMs,
    nowFn: context.nowFn,
    sourceIntel: context.sourceIntel,
    identityLock: context.identityLock,
    learnedFieldAvailability: context.learnedFieldAvailability,
    learnedFieldYield: context.learnedFieldYield,
    phase08BatchRows: context.phase08BatchRows,
    phase08FieldContexts: context.phase08FieldContexts,
    phase08PrimeRows: context.phase08PrimeRows,
    llmValidatorDecisions: context.llmValidatorDecisions,
    buildCandidateFieldMapFn: context.buildCandidateFieldMapFn,
    evaluateAnchorConflictsFn: context.evaluateAnchorConflictsFn,
    evaluateSourceIdentityFn: context.evaluateSourceIdentityFn,
    evaluateIdentityGateFn: context.evaluateIdentityGateFn,
    buildIdentityReportFn: context.buildIdentityReportFn,
    bestIdentityFromSourcesFn: context.bestIdentityFromSourcesFn,
    buildIdentityObjectFn: context.buildIdentityObjectFn,
    buildSourceSummaryFn: context.buildSourceSummaryFn,
    mergeAnchorConflictListsFn: context.mergeAnchorConflictListsFn,
    executeConsensusPhaseFn: context.executeConsensusPhaseFn,
    buildAbortedNormalizedFn: context.buildAbortedNormalizedFn,
    buildValidatedNormalizedFn: context.buildValidatedNormalizedFn,
    createEmptyProvenanceFn: context.createEmptyProvenanceFn,
    selectAggressiveEvidencePackFn: context.selectAggressiveEvidencePackFn,
    aggregateTemporalSignalsFn: context.aggregateTemporalSignalsFn,
    applyInferencePoliciesFn: context.applyInferencePoliciesFn,
    computeCompletenessRequiredFn: context.computeCompletenessRequiredFn,
    computeCoverageOverallFn: context.computeCoverageOverallFn,
    computeConfidenceFn: context.computeConfidenceFn,
    evaluateValidationGateFn: context.evaluateValidationGateFn,
    aggregateEndpointSignalsFn: context.aggregateEndpointSignalsFn,
    evaluateConstraintGraphFn: context.evaluateConstraintGraphFn,
    passTargetExemptFields: context.passTargetExemptFields,
  });

  const summary = freezeContract({
    llmRuntime: context.llmRuntime,
    productId: context.productId,
    runId: context.runId,
    category: context.category,
    config: context.config,
    runtimeMode: context.runtimeMode,
    identityFingerprint: context.identityFingerprint,
    identityLockStatus: context.identityLockStatus,
    dedupeMode: context.dedupeMode,
    targets: context.targets,
    anchors: context.anchors,
    identityLock: context.identityLock,
    sourceResults: context.sourceResults,
    discoveryResult: context.discoveryResult,
    indexingHelperFlowEnabled: context.indexingHelperFlowEnabled,
    helperContext: context.helperContext,
    helperSupportiveSyntheticSources: context.helperSupportiveSyntheticSources,
    helperFilledFields: context.helperFilledFields,
    helperFilledByMethod: context.helperFilledByMethod,
    helperMismatches: context.helperMismatches,
    runtimeFieldRulesEngine: context.runtimeFieldRulesEngine,
    llmTargetFields: context.llmTargetFields,
    goldenExamples: context.goldenExamples,
    llmCandidatesAccepted: context.llmCandidatesAccepted,
    llmSourcesUsed: context.llmSourcesUsed,
    llmContext: context.llmContext,
    categoryConfig: context.categoryConfig,
    fetcherMode: context.fetcherMode,
    fetcherStartFallbackReason: context.fetcherStartFallbackReason,
    indexingResumeKey: context.indexingResumeKey,
    resumeMode: context.resumeMode,
    resumeMaxAgeHours: context.resumeMaxAgeHours,
    previousResumeStateAgeHours: context.previousResumeStateAgeHours,
    resumeReextractEnabled: context.resumeReextractEnabled,
    resumeReextractAfterHours: context.resumeReextractAfterHours,
    resumeSeededPendingCount: context.resumeSeededPendingCount,
    resumeSeededLlmRetryCount: context.resumeSeededLlmRetryCount,
    resumeSeededReextractCount: context.resumeSeededReextractCount,
    resumePersistedPendingCount: context.resumePersistedPendingCount,
    resumePersistedLlmRetryCount: context.resumePersistedLlmRetryCount,
    resumePersistedSuccessCount: context.resumePersistedSuccessCount,
    plannerStats: context.plannerStats,
    hypothesisFollowupRoundsExecuted: context.hypothesisFollowupRoundsExecuted,
    hypothesisFollowupSeededUrls: context.hypothesisFollowupSeededUrls,
    roundContext: context.roundContext,
    normalizeAmbiguityLevelFn: context.normalizeAmbiguityLevelFn,
    isHelperSyntheticSourceFn: context.isHelperSyntheticSourceFn,
    buildTopEvidenceReferencesFn: context.buildTopEvidenceReferencesFn,
  });

  const completion = freezeContract({
    storage: context.storage,
    runArtifactsBase: context.runArtifactsBase,
    category: context.category,
    productId: context.productId,
    runId: context.runId,
    runtimeMode: context.runtimeMode,
    startMs: context.startMs,
    categoryConfig: context.categoryConfig,
    sourceResults: context.sourceResults,
    config: context.config,
    logger: context.logger,
    identityFingerprint: context.identityFingerprint,
    identityLockStatus: context.identityLockStatus,
    dedupeMode: context.dedupeMode,
    llmCandidatesAccepted: context.llmCandidatesAccepted,
    resumeMode: context.resumeMode,
    resumeMaxAgeHours: context.resumeMaxAgeHours,
    resumeReextractEnabled: context.resumeReextractEnabled,
    resumeReextractAfterHours: context.resumeReextractAfterHours,
    resumeSeededPendingCount: context.resumeSeededPendingCount,
    resumeSeededLlmRetryCount: context.resumeSeededLlmRetryCount,
    resumeSeededReextractCount: context.resumeSeededReextractCount,
    resumePersistedPendingCount: context.resumePersistedPendingCount,
    resumePersistedLlmRetryCount: context.resumePersistedLlmRetryCount,
    resumePersistedSuccessCount: context.resumePersistedSuccessCount,
    hypothesisFollowupRoundsExecuted: context.hypothesisFollowupRoundsExecuted,
    hypothesisFollowupSeededUrls: context.hypothesisFollowupSeededUrls,
    fieldOrder: context.fieldOrder,
    llmContext: context.llmContext,
    sourceIntelBrand: context.sourceIntelBrand,
    job: context.job,
    runtimeFieldRulesEngine: context.runtimeFieldRulesEngine,
    learningProfile: context.learningProfile,
    discoveryResult: context.discoveryResult,
    artifactsByHost: context.artifactsByHost,
    adapterArtifacts: context.adapterArtifacts,
    frontierDb: context.frontierDb,
    uberOrchestrator: context.uberOrchestrator,
    previousFinalSpec: context.previousFinalSpec,
    writeSummaryMarkdownLLMFn: context.writeSummaryMarkdownLLMFn,
    buildMarkdownSummaryFn: context.buildMarkdownSummaryFn,
    tsvRowFromFieldsFn: context.tsvRowFromFieldsFn,
    buildIndexingSchemaPacketsFn: context.buildIndexingSchemaPacketsFn,
    validateIndexingSchemaPacketsFn: context.validateIndexingSchemaPacketsFn,
    persistSourceIntelFn: context.persistSourceIntelFn,
    updateCategoryBrainFn: context.updateCategoryBrainFn,
    updateComponentLibraryFn: context.updateComponentLibraryFn,
    evaluateFieldLearningGatesFn: context.evaluateFieldLearningGatesFn,
    emitLearningGateEventsFn: context.emitLearningGateEventsFn,
    importSpecDbFn: context.importSpecDbFn,
    UrlMemoryStoreClass: context.UrlMemoryStoreClass,
    DomainFieldYieldStoreClass: context.DomainFieldYieldStoreClass,
    FieldAnchorsStoreClass: context.FieldAnchorsStoreClass,
    ComponentLexiconStoreClass: context.ComponentLexiconStoreClass,
    populateLearningStoresFn: context.populateLearningStoresFn,
    persistLearningProfileFn: context.persistLearningProfileFn,
    exportRunArtifactsFn: context.exportRunArtifactsFn,
    writeFinalOutputsFn: context.writeFinalOutputsFn,
    writeProductReviewArtifactsFn: context.writeProductReviewArtifactsFn,
    writeCategoryReviewArtifactsFn: context.writeCategoryReviewArtifactsFn,
    runLearningExportPhaseFn: context.runLearningExportPhaseFn,
    finalizeRunLifecycleFn: context.finalizeRunLifecycleFn,
    emitFieldDecisionEventsFn: context.emitFieldDecisionEventsFn,
  });

  return Object.freeze({
    derivation,
    summary,
    completion,
  });
}
