export function buildRunSummaryAnalysisSection({
  config = {},
  manufacturerSources = [],
  manufacturerMajorConflicts = 0,
  plannerStats = {},
  endpointMining = {},
  temporalEvidence = {},
  inferenceResult = {},
  hypothesisQueue = [],
  hypothesisFollowupRoundsExecuted = 0,
  hypothesisFollowupSeededUrls = [],
  constraintAnalysis = {},
  fieldReasoning = {},
  trafficLight = {},
  needSet = {},
  phase07PrimeSources = {},
  phase08Extraction = {},
  provenance = {},
  buildTopEvidenceReferencesFn = () => [],
  parserHealthRows = [],
  parserHealthAverage = 0,
  fingerprintCount = 0,
  durationMs = 0,
  roundContext = null,
  nowIsoFn = () => new Date().toISOString(),
} = {}) {
  return {
    manufacturer_research: {
      attempted_sources: manufacturerSources.length,
      identity_matched_sources: manufacturerSources.filter((source) => source.identity?.match).length,
      major_anchor_conflict_sources: manufacturerMajorConflicts,
      planner: plannerStats,
    },
    endpoint_mining: endpointMining,
    temporal_evidence: temporalEvidence,
    inference: inferenceResult,
    hypothesis_queue: hypothesisQueue,
    hypothesis_followup: {
      configured_rounds: Math.max(0, Number(config.hypothesisAutoFollowupRounds || 0)),
      urls_per_round: Math.max(1, Number(config.hypothesisFollowupUrlsPerRound || 12)),
      rounds_executed: hypothesisFollowupRoundsExecuted,
      seeded_urls: hypothesisFollowupSeededUrls,
    },
    constraint_analysis: constraintAnalysis,
    field_reasoning: fieldReasoning,
    traffic_light: trafficLight,
    needset: {
      size: Array.isArray(needSet.fields)
        ? needSet.fields.filter((f) => f.state !== 'accepted').length
        : 0,
      total_fields: needSet.total_fields || (Array.isArray(needSet.fields) ? needSet.fields.length : 0),
      summary: needSet.summary || {},
      blockers: needSet.blockers || {},
      identity_state: needSet.identity?.state || null,
      top_fields: Array.isArray(needSet.fields)
        ? needSet.fields.filter((f) => f.state !== 'accepted').slice(0, 12).map((f) => f.field_key)
        : [],
      generated_at: needSet.generated_at,
    },
    phase07: {
      fields_attempted: Number(phase07PrimeSources?.summary?.fields_attempted || 0),
      fields_with_hits: Number(phase07PrimeSources?.summary?.fields_with_hits || 0),
      fields_satisfied_min_refs: Number(phase07PrimeSources?.summary?.fields_satisfied_min_refs || 0),
      fields_unsatisfied_min_refs: Number(phase07PrimeSources?.summary?.fields_unsatisfied_min_refs || 0),
      refs_selected_total: Number(phase07PrimeSources?.summary?.refs_selected_total || 0),
      distinct_sources_selected: Number(phase07PrimeSources?.summary?.distinct_sources_selected || 0),
      avg_hits_per_field: Number(phase07PrimeSources?.summary?.avg_hits_per_field || 0),
      generated_at: String(phase07PrimeSources?.generated_at || '').trim() || null,
    },
    phase08: {
      batch_count: Number(phase08Extraction?.summary?.batch_count || 0),
      batch_error_count: Number(phase08Extraction?.summary?.batch_error_count || 0),
      schema_fail_rate: Number(phase08Extraction?.summary?.schema_fail_rate || 0),
      raw_candidate_count: Number(phase08Extraction?.summary?.raw_candidate_count || 0),
      accepted_candidate_count: Number(phase08Extraction?.summary?.accepted_candidate_count || 0),
      dangling_snippet_ref_count: Number(phase08Extraction?.summary?.dangling_snippet_ref_count || 0),
      dangling_snippet_ref_rate: Number(phase08Extraction?.summary?.dangling_snippet_ref_rate || 0),
      evidence_policy_violation_count: Number(
        phase08Extraction?.summary?.evidence_policy_violation_count || 0,
      ),
      evidence_policy_violation_rate: Number(
        phase08Extraction?.summary?.evidence_policy_violation_rate || 0,
      ),
      min_refs_satisfied_count: Number(phase08Extraction?.summary?.min_refs_satisfied_count || 0),
      min_refs_total: Number(phase08Extraction?.summary?.min_refs_total || 0),
      min_refs_satisfied_rate: Number(phase08Extraction?.summary?.min_refs_satisfied_rate || 0),
      validator_context_field_count: Number(phase08Extraction?.validator?.context_field_count || 0),
      validator_prime_source_rows: Number(phase08Extraction?.validator?.prime_source_rows || 0),
      generated_at: String(phase08Extraction?.generated_at || '').trim() || null,
    },
    top_evidence_references: buildTopEvidenceReferencesFn(provenance, 100),
    parser_health: {
      source_count: parserHealthRows.length,
      average_health_score: Number.parseFloat(parserHealthAverage.toFixed(6)),
      fingerprints_seen: fingerprintCount,
    },
    duration_ms: durationMs,
    round_context: roundContext || null,
    generated_at: nowIsoFn(),
  };
}
