export function buildRunCompletedPayload({
  productId,
  runId,
  config = {},
  runtimeMode = 'production',
  identityFingerprint = '',
  identityLockStatus = '',
  dedupeMode = '',
  summary = {},
  confidence = 0,
  llmCandidatesAccepted = 0,
  llmCallCount = 0,
  llmCostUsd = 0,
  contribution = {},
  llmEstimatedUsageCount = 0,
  llmRetryWithoutSchemaCount = 0,
  llmBudgetBlockedReason = '',
  indexingHelperFlowEnabled = false,
  helperContext = {},
  helperFilledFields = [],
  componentPriorFilledFields = [],
  criticDecisions = {},
  llmValidatorDecisions = {},
  phase08Extraction = {},
  trafficLight = {},
  resumeMode = '',
  resumeMaxAgeHours = 0,
  resumeReextractEnabled = false,
  resumeReextractAfterHours = 0,
  resumeSeededPendingCount = 0,
  resumeSeededLlmRetryCount = 0,
  resumeSeededReextractCount = 0,
  resumePersistedPendingCount = 0,
  resumePersistedLlmRetryCount = 0,
  resumePersistedSuccessCount = 0,
  hypothesisFollowupRoundsExecuted = 0,
  hypothesisFollowupSeededUrls = 0,
  aggressiveExtraction = null,
  durationMs = 0,
} = {}) {
  return {
    productId,
    runId,
    run_profile: 'standard',
    runtime_mode: runtimeMode,
    identity_fingerprint: identityFingerprint,
    identity_lock_status: identityLockStatus,
    dedupe_mode: dedupeMode,
    phase_cursor: 'completed',
    validated: summary.validated,
    validated_reason: summary.validated_reason,
    confidence,
    completeness_required: summary.completeness_required,
    coverage_overall: summary.coverage_overall,
    llm_candidates_added: llmCandidatesAccepted,
    llm_call_count_run: llmCallCount,
    llm_cost_usd_run: llmCostUsd,
    llm_fields_filled_count: Array.isArray(contribution.llmFields) ? contribution.llmFields.length : 0,
    llm_estimated_usage_count: llmEstimatedUsageCount,
    llm_retry_without_schema_count: llmRetryWithoutSchemaCount,
    llm_budget_blocked_reason: llmBudgetBlockedReason || null,
    indexing_helper_flow_enabled: indexingHelperFlowEnabled,
    helper_active_match: Boolean(helperContext?.active_match),
    helper_supportive_matches: helperContext?.supportive_matches?.length || 0,
    helper_supportive_fields_filled: helperFilledFields?.length || 0,
    component_prior_fields_filled: componentPriorFilledFields?.length || 0,
    critic_reject_count: (criticDecisions.reject || []).length,
    llm_validator_accept_count: (llmValidatorDecisions.accept || []).length,
    llm_validator_reject_count: (llmValidatorDecisions.reject || []).length,
    phase08_batch_count: Number(phase08Extraction?.summary?.batch_count || 0),
    phase08_schema_fail_rate: Number(phase08Extraction?.summary?.schema_fail_rate || 0),
    phase08_dangling_ref_rate: Number(phase08Extraction?.summary?.dangling_snippet_ref_rate || 0),
    phase08_min_refs_satisfied_rate: Number(phase08Extraction?.summary?.min_refs_satisfied_rate || 0),
    traffic_green_count: trafficLight?.counts?.green || 0,
    traffic_yellow_count: trafficLight?.counts?.yellow || 0,
    traffic_red_count: trafficLight?.counts?.red || 0,
    resume_mode: resumeMode,
    resume_max_age_hours: resumeMaxAgeHours,
    resume_reextract_enabled: resumeReextractEnabled,
    resume_reextract_after_hours: resumeReextractAfterHours,
    resume_seeded_pending_count: resumeSeededPendingCount,
    resume_seeded_llm_retry_count: resumeSeededLlmRetryCount,
    resume_seeded_reextract_count: resumeSeededReextractCount,
    resume_persisted_pending_count: resumePersistedPendingCount,
    resume_persisted_llm_retry_count: resumePersistedLlmRetryCount,
    resume_persisted_success_count: resumePersistedSuccessCount,
    hypothesis_queue_count: Array.isArray(summary.hypothesis_queue) ? summary.hypothesis_queue.length : 0,
    hypothesis_followup_rounds: hypothesisFollowupRoundsExecuted,
    hypothesis_followup_seeded_urls: hypothesisFollowupSeededUrls,
    aggressive_enabled: Boolean(aggressiveExtraction?.enabled),
    aggressive_stage: aggressiveExtraction?.stage || 'disabled',
    contradiction_count: summary?.constraint_analysis?.contradiction_count,
    duration_ms: durationMs,
  };
}
