import { buildRunSummaryPayloadPhaseCallsiteContext } from './buildRunSummaryPayloadPhaseCallsiteContext.js';
import { buildRunSummaryPayloadContext } from './buildRunSummaryPayloadContext.js';
import { buildRunSummaryPayload } from './buildRunSummaryPayload.js';

export function buildRunProductFinalizationSummary({
  llmRuntime,
  llmBudgetGuard,
  productId = '',
  runId = '',
  category = '',
  config = {},
  runtimeMode = '',
  identityFingerprint = '',
  identityLockStatus = '',
  dedupeMode = '',
  gate = {},
  validatedReason = '',
  confidence = 0,
  completenessStats = {},
  coverageStats = {},
  targets = {},
  anchors = {},
  allAnchorConflicts = [],
  anchorMajorConflictsCount = 0,
  identityConfidence = 0,
  identityGate = {},
  extractionGateOpen = false,
  identityLock = {},
  publishable = false,
  publishBlockers = [],
  identityReport = {},
  fieldsBelowPassTarget = [],
  criticalFieldsBelowPassTarget = [],
  newValuesProposed = [],
  provenance = {},
  sourceResults = [],
  discoveryResult = {},
  indexingHelperFlowEnabled = false,
  helperContext = null,
  helperSupportiveSyntheticSources = [],
  helperFilledFields = [],
  helperFilledByMethod = {},
  helperMismatches = [],
  componentPriorFilledFields = [],
  componentPriorMatches = [],
  criticDecisions = {},
  llmValidatorDecisions = {},
  runtimeFieldRulesEngine = null,
  runtimeGateResult = {},
  curationSuggestionResult = {},
  llmTargetFields = [],
  goldenExamples = [],
  llmCandidatesAccepted = 0,
  llmSourcesUsed = 0,
  contribution = {},
  llmContext = {},
  llmBudgetBlockedReason = '',
  cortexSidecar = null,
  aggressiveExtraction = null,
  categoryConfig = {},
  fetcherMode = '',
  fetcherStartFallbackReason = null,
  indexingResumeKey = '',
  resumeMode = '',
  resumeMaxAgeHours = 0,
  previousResumeStateAgeHours = 0,
  resumeReextractEnabled = false,
  resumeReextractAfterHours = 0,
  resumeSeededPendingCount = 0,
  resumeSeededLlmRetryCount = 0,
  resumeSeededReextractCount = 0,
  resumePersistedPendingCount = 0,
  resumePersistedLlmRetryCount = 0,
  resumePersistedSuccessCount = 0,
  manufacturerSources = [],
  manufacturerMajorConflicts = 0,
  plannerStats = {},
  endpointMining = {},
  temporalEvidence = {},
  inferenceResult = {},
  hypothesisQueue = [],
  hypothesisFollowupRoundsExecuted = 0,
  hypothesisFollowupSeededUrls = 0,
  constraintAnalysis = {},
  fieldReasoning = {},
  trafficLight = {},
  needSet = {},
  phase07PrimeSources = {},
  phase08Extraction = {},
  parserHealthRows = [],
  parserHealthAverage = 0,
  fingerprintCount = 0,
  durationMs = 0,
  roundContext = {},
  normalizeAmbiguityLevelFn = (payload) => payload,
  isHelperSyntheticSourceFn = (payload) => payload,
  buildTopEvidenceReferencesFn = (payload) => payload,
  buildRunSummaryPayloadPhaseCallsiteContextFn = buildRunSummaryPayloadPhaseCallsiteContext,
  buildRunSummaryPayloadContextFn = buildRunSummaryPayloadContext,
  buildRunSummaryPayloadFn = buildRunSummaryPayload,
} = {}) {
  const {
    llmCallCount,
    llmCostUsd,
    llmEstimatedUsageCount,
    llmRetryWithoutSchemaCount,
  } = llmRuntime.getUsageState();
  const llmBudgetSnapshot = llmBudgetGuard.snapshot();

  const summary = buildRunSummaryPayloadFn({
    ...buildRunSummaryPayloadContextFn({
      ...buildRunSummaryPayloadPhaseCallsiteContextFn({
        productId,
        runId,
        category,
        config,
        runtimeMode,
        identityFingerprint,
        identityLockStatus,
        dedupeMode,
        gate,
        validatedReason,
        confidence,
        completenessStats,
        coverageStats,
        targets,
        anchors,
        allAnchorConflicts,
        anchorMajorConflictsCount,
        identityConfidence,
        identityGate,
        extractionGateOpen,
        identityLock,
        publishable,
        publishBlockers,
        identityReport,
        fieldsBelowPassTarget,
        criticalFieldsBelowPassTarget,
        newValuesProposed,
        provenance,
        sourceResults,
        discoveryResult,
        indexingHelperFlowEnabled,
        helperContext,
        helperSupportiveSyntheticSources,
        helperFilledFields,
        helperFilledByMethod,
        helperMismatches,
        componentPriorFilledFields,
        componentPriorMatches,
        criticDecisions,
        llmValidatorDecisions,
        runtimeFieldRulesEngine,
        runtimeGateResult,
        curationSuggestionResult,
        llmTargetFields,
        goldenExamples,
        llmCandidatesAccepted,
        llmSourcesUsed,
        contribution,
        llmRetryWithoutSchemaCount,
        llmEstimatedUsageCount,
        llmContext,
        llmCallCount,
        llmCostUsd,
        llmBudgetSnapshot,
        llmBudgetBlockedReason,
        cortexSidecar,
        aggressiveExtraction,
        categoryConfig,
        fetcherMode,
        fetcherStartFallbackReason,
        indexingResumeKey,
        resumeMode,
        resumeMaxAgeHours,
        previousResumeStateAgeHours,
        resumeReextractEnabled,
        resumeReextractAfterHours,
        resumeSeededPendingCount,
        resumeSeededLlmRetryCount,
        resumeSeededReextractCount,
        resumePersistedPendingCount,
        resumePersistedLlmRetryCount,
        resumePersistedSuccessCount,
        manufacturerSources,
        manufacturerMajorConflicts,
        plannerStats,
        endpointMining,
        temporalEvidence,
        inferenceResult,
        hypothesisQueue,
        hypothesisFollowupRoundsExecuted,
        hypothesisFollowupSeededUrls,
        constraintAnalysis,
        fieldReasoning,
        trafficLight,
        needSet,
        phase07PrimeSources,
        phase08Extraction,
        parserHealthRows,
        parserHealthAverage,
        fingerprintCount,
        durationMs,
        roundContext,
        normalizeAmbiguityLevel: normalizeAmbiguityLevelFn,
        isHelperSyntheticSource: isHelperSyntheticSourceFn,
        buildTopEvidenceReferences: buildTopEvidenceReferencesFn,
      }),
    }),
  });

  return {
    summary,
    llmCallCount,
    llmCostUsd,
    llmEstimatedUsageCount,
    llmRetryWithoutSchemaCount,
    llmBudgetSnapshot,
  };
}
