import { createProductCompletionRuntime } from './createProductCompletionRuntime.js';

export async function runProductCompletionLifecycle({
  constrainedFinalizationConfig = {},
  storage,
  runArtifactsBase = '',
  category = '',
  productId = '',
  runId = '',
  runtimeMode = '',
  startMs = 0,
  summary = {},
  categoryConfig = {},
  sourceResults = [],
  normalized = { fields: {} },
  provenance = {},
  needSet = {},
  phase08Extraction = {},
  phase07PrimeSources = {},
  config = {},
  logger,
  identityFingerprint = '',
  identityLockStatus = '',
  dedupeMode = '',
  confidence = 0,
  llmCandidatesAccepted = 0,
  llmCallCount = 0,
  llmCostUsd = 0,
  contribution = {},
  llmEstimatedUsageCount = 0,
  llmRetryWithoutSchemaCount = 0,
  llmBudgetBlockedReason = '',
  indexingHelperFlowEnabled = false,
  helperContext = null,
  helperFilledFields = [],
  componentPriorFilledFields = [],
  criticDecisions = {},
  llmValidatorDecisions = {},
  trafficLight = {},
  resumeMode = '',
  resumeMaxAgeHours = 0,
  resumeReextractEnabled = false,
  resumeReextractAfterHours = 0,
  resumeSeededPendingCount = 0,
  resumeSeededLlmRetryCount = 0,
  resumeSeededReextractCount = 0,
  resumePersistedPendingCount = 0,
  resumePersistedLlmRetryCount = 0,
  resumePersistedSuccessCount = 0,
  hypothesisFollowupRoundsExecuted = 0,
  hypothesisFollowupSeededUrls = 0,
  aggressiveExtraction = null,
  durationMs = 0,
  fieldOrder = [],
  llmContext,
  identityReport = {},
  sourceIntelBrand = '',
  constraintAnalysis = {},
  job = {},
  runtimeFieldRulesEngine = null,
  learningProfile = null,
  discoveryResult = null,
  artifactsByHost = {},
  adapterArtifacts = {},
  candidates = [],
  runtimeEvidencePack = null,
  frontierDb = null,
  fieldReasoning = [],
  uberOrchestrator = null,
  previousFinalSpec = null,
  writeSummaryMarkdownLLMFn = async () => '',
  buildMarkdownSummaryFn = () => '',
  tsvRowFromFieldsFn = () => '',
  buildIndexingSchemaPacketsFn = (payload) => payload,
  validateIndexingSchemaPacketsFn = (payload) => payload,
  persistSourceIntelFn = async () => {},
  updateCategoryBrainFn = async () => null,
  updateComponentLibraryFn = async () => null,
  evaluateFieldLearningGatesFn = () => ({}),
  emitLearningGateEventsFn = () => {},
  importSpecDbFn = async () => ({}),
  UrlMemoryStoreClass,
  DomainFieldYieldStoreClass,
  FieldAnchorsStoreClass,
  ComponentLexiconStoreClass,
  populateLearningStoresFn = async () => {},
  persistLearningProfileFn = async () => null,
  exportRunArtifactsFn = async () => null,
  writeFinalOutputsFn = async () => null,
  writeProductReviewArtifactsFn = async () => null,
  writeCategoryReviewArtifactsFn = async () => null,
  runLearningExportPhaseFn = async () => ({}),
  finalizeRunLifecycleFn = async () => {},
  emitFieldDecisionEventsFn = () => {},
  buildResearchArtifactsPhaseContextFn,
  applyResearchArtifactsContextFn,
  buildAnalysisArtifactKeyPhaseContextFn,
  buildAnalysisArtifactKeyContextFn,
  buildIndexingSchemaArtifactsPhaseCallsiteContextFn,
  buildIndexingSchemaArtifactsPhaseContextFn,
  runIndexingSchemaArtifactsPhaseFn,
  resolveIndexingSchemaValidationFn,
  buildIndexingSchemaSummaryPayloadFn,
  persistAnalysisArtifactsFn,
  buildFinalizationEventPayloadsFn,
  buildFinalizationTelemetryPhaseCallsiteContextFn,
  buildFinalizationTelemetryContextFn,
  runFinalizationTelemetryPhaseFn,
  emitFinalizationEventsFn,
  buildRunCompletedPayloadPhaseCallsiteContextFn,
  buildRunCompletedPayloadContextFn,
  buildRunCompletedPayloadFn,
  buildRunCompletedEventCallsiteContextFn,
  buildRunCompletedEventContextFn,
  emitRunCompletedEventFn,
  buildSummaryArtifactsPhaseCallsiteContextFn,
  buildSummaryArtifactsPhaseContextFn,
  buildSummaryArtifactsContextFn,
  buildIdentityReportPersistencePhaseCallsiteContextFn,
  buildIdentityReportPersistenceContextFn,
  runIdentityReportPersistencePhaseFn,
  buildSourceIntelFinalizationPhaseCallsiteContextFn,
  buildSourceIntelFinalizationContextFn,
  runSourceIntelFinalizationPhaseFn,
  buildPostLearningUpdatesPhaseCallsiteContextFn,
  buildPostLearningUpdatesContextFn,
  runPostLearningUpdatesPhaseFn,
  buildLearningGatePhaseCallsiteContextFn,
  buildLearningGateContextFn,
  runLearningGatePhaseFn,
  buildSelfImproveLearningStoresPhaseCallsiteContextFn,
  buildSelfImproveLearningStoresContextFn,
  persistSelfImproveLearningStoresFn,
  buildLearningExportPhaseCallsiteContextFn,
  buildLearningExportPhaseContextFn,
  buildTerminalLearningExportLifecyclePhaseCallsiteContextFn,
  buildTerminalLearningExportLifecycleContextFn,
  runTerminalLearningExportLifecycleFn,
  buildRunResultPayloadPhaseCallsiteContextFn,
  buildRunResultPayloadContextFn,
  buildRunResultPayloadFn,
  completionRuntime = null,
  createProductCompletionRuntimeFn = createProductCompletionRuntime,
} = {}) {
  const resolvedCompletionRuntime = completionRuntime || createProductCompletionRuntimeFn({
    context: {
      constrainedFinalizationConfig,
      storage,
      runArtifactsBase,
      runBase: runArtifactsBase,
      category,
      productId,
      runId,
      runtimeMode,
      startMs,
      summary,
      categoryConfig,
      sourceResults,
      normalized,
      provenance,
      needSet,
      phase08Extraction,
      phase07PrimeSources,
      config,
      logger,
      identityFingerprint,
      identityLockStatus,
      dedupeMode,
      confidence,
      llmCandidatesAccepted,
      llmCallCount,
      llmCostUsd,
      contribution,
      llmEstimatedUsageCount,
      llmRetryWithoutSchemaCount,
      llmBudgetBlockedReason,
      indexingHelperFlowEnabled,
      helperContext,
      helperFilledFields,
      componentPriorFilledFields,
      criticDecisions,
      llmValidatorDecisions,
      trafficLight,
      resumeMode,
      resumeMaxAgeHours,
      resumeReextractEnabled,
      resumeReextractAfterHours,
      resumeSeededPendingCount,
      resumeSeededLlmRetryCount,
      resumeSeededReextractCount,
      resumePersistedPendingCount,
      resumePersistedLlmRetryCount,
      resumePersistedSuccessCount,
      hypothesisFollowupRoundsExecuted,
      hypothesisFollowupSeededUrls,
      aggressiveExtraction,
      durationMs,
      fieldOrder,
      llmContext,
      identityReport,
      sourceIntelBrand,
      constraintAnalysis,
      job,
      runtimeFieldRulesEngine,
      learningProfile,
      discoveryResult,
      artifactsByHost,
      adapterArtifacts,
      candidates,
      runtimeEvidencePack,
      frontierDb,
      fieldReasoning,
      uberOrchestrator,
      previousFinalSpec,
      writeSummaryMarkdownLLMFn,
      buildMarkdownSummaryFn,
      tsvRowFromFieldsFn,
      buildIndexingSchemaPacketsFn,
      validateIndexingSchemaPacketsFn,
      persistSourceIntelFn,
      updateCategoryBrainFn,
      updateComponentLibraryFn,
      evaluateFieldLearningGatesFn,
      emitLearningGateEventsFn,
      importSpecDbFn,
      UrlMemoryStoreClass,
      DomainFieldYieldStoreClass,
      FieldAnchorsStoreClass,
      ComponentLexiconStoreClass,
      populateLearningStoresFn,
      persistLearningProfileFn,
      exportRunArtifactsFn,
      writeFinalOutputsFn,
      writeProductReviewArtifactsFn,
      writeCategoryReviewArtifactsFn,
      runLearningExportPhaseFn,
      finalizeRunLifecycleFn,
      emitFieldDecisionEventsFn,
      buildResearchArtifactsPhaseContextFn,
      applyResearchArtifactsContextFn,
      buildAnalysisArtifactKeyPhaseContextFn,
      buildAnalysisArtifactKeyContextFn,
      buildIndexingSchemaArtifactsPhaseCallsiteContextFn,
      buildIndexingSchemaArtifactsPhaseContextFn,
      runIndexingSchemaArtifactsPhaseFn,
      resolveIndexingSchemaValidationFn,
      buildIndexingSchemaSummaryPayloadFn,
      persistAnalysisArtifactsFn,
      buildFinalizationEventPayloadsFn,
      buildFinalizationTelemetryPhaseCallsiteContextFn,
      buildFinalizationTelemetryContextFn,
      runFinalizationTelemetryPhaseFn,
      emitFinalizationEventsFn,
      buildRunCompletedPayloadPhaseCallsiteContextFn,
      buildRunCompletedPayloadContextFn,
      buildRunCompletedPayloadFn,
      buildRunCompletedEventCallsiteContextFn,
      buildRunCompletedEventContextFn,
      emitRunCompletedEventFn,
      buildSummaryArtifactsPhaseCallsiteContextFn,
      buildSummaryArtifactsPhaseContextFn,
      buildSummaryArtifactsContextFn,
      buildIdentityReportPersistencePhaseCallsiteContextFn,
      buildIdentityReportPersistenceContextFn,
      runIdentityReportPersistencePhaseFn,
      buildSourceIntelFinalizationPhaseCallsiteContextFn,
      buildSourceIntelFinalizationContextFn,
      runSourceIntelFinalizationPhaseFn,
      buildPostLearningUpdatesPhaseCallsiteContextFn,
      buildPostLearningUpdatesContextFn,
      runPostLearningUpdatesPhaseFn,
      buildLearningGatePhaseCallsiteContextFn,
      buildLearningGateContextFn,
      runLearningGatePhaseFn,
      buildSelfImproveLearningStoresPhaseCallsiteContextFn,
      buildSelfImproveLearningStoresContextFn,
      persistSelfImproveLearningStoresFn,
      buildLearningExportPhaseCallsiteContextFn,
      buildLearningExportPhaseContextFn,
      buildTerminalLearningExportLifecyclePhaseCallsiteContextFn,
      buildTerminalLearningExportLifecycleContextFn,
      runTerminalLearningExportLifecycleFn,
      buildRunResultPayloadPhaseCallsiteContextFn,
      buildRunResultPayloadContextFn,
      buildRunResultPayloadFn,
    },
    buildResearchArtifactsPhaseContextFn,
    applyResearchArtifactsContextFn,
    buildAnalysisArtifactKeyPhaseContextFn,
    buildAnalysisArtifactKeyContextFn,
    buildIndexingSchemaArtifactsPhaseCallsiteContextFn,
    buildIndexingSchemaArtifactsPhaseContextFn,
    runIndexingSchemaArtifactsPhaseFn,
    resolveIndexingSchemaValidationFn,
    buildIndexingSchemaSummaryPayloadFn,
    persistAnalysisArtifactsFn,
    buildFinalizationEventPayloadsFn,
    buildFinalizationTelemetryPhaseCallsiteContextFn,
    buildFinalizationTelemetryContextFn,
    runFinalizationTelemetryPhaseFn,
    emitFinalizationEventsFn,
    buildRunCompletedPayloadPhaseCallsiteContextFn,
    buildRunCompletedPayloadContextFn,
    buildRunCompletedPayloadFn,
    buildRunCompletedEventCallsiteContextFn,
    buildRunCompletedEventContextFn,
    emitRunCompletedEventFn,
    buildSummaryArtifactsPhaseCallsiteContextFn,
    buildSummaryArtifactsPhaseContextFn,
    buildSummaryArtifactsContextFn,
    buildIdentityReportPersistencePhaseCallsiteContextFn,
    buildIdentityReportPersistenceContextFn,
    runIdentityReportPersistencePhaseFn,
    buildSourceIntelFinalizationPhaseCallsiteContextFn,
    buildSourceIntelFinalizationContextFn,
    runSourceIntelFinalizationPhaseFn,
    buildPostLearningUpdatesPhaseCallsiteContextFn,
    buildPostLearningUpdatesContextFn,
    runPostLearningUpdatesPhaseFn,
    buildLearningGatePhaseCallsiteContextFn,
    buildLearningGateContextFn,
    runLearningGatePhaseFn,
    buildSelfImproveLearningStoresPhaseCallsiteContextFn,
    buildSelfImproveLearningStoresContextFn,
    persistSelfImproveLearningStoresFn,
    buildLearningExportPhaseCallsiteContextFn,
    buildLearningExportPhaseContextFn,
    buildTerminalLearningExportLifecyclePhaseCallsiteContextFn,
    buildTerminalLearningExportLifecycleContextFn,
    runTerminalLearningExportLifecycleFn,
    buildRunResultPayloadPhaseCallsiteContextFn,
    buildRunResultPayloadContextFn,
    buildRunResultPayloadFn,
  });

  await resolvedCompletionRuntime.applyResearchArtifacts();
  const analysisArtifactKeys = resolvedCompletionRuntime.resolveAnalysisArtifactKeys();
  const { indexingSchemaPackets } = await resolvedCompletionRuntime.runIndexingSchemaArtifacts({
    keys: analysisArtifactKeys,
  });
  resolvedCompletionRuntime.emitFinalizationTelemetry({
    keys: analysisArtifactKeys,
    indexingSchemaPackets,
  });
  const runCompletedPayload = resolvedCompletionRuntime.buildRunCompletedPayload();
  resolvedCompletionRuntime.emitRunCompletedEvent({ runCompletedPayload });
  const { rowTsv, markdownSummary } = await resolvedCompletionRuntime.buildSummaryArtifacts();
  await resolvedCompletionRuntime.persistIdentityReport();
  await resolvedCompletionRuntime.runSourceIntelFinalization();
  const { categoryBrain } = await resolvedCompletionRuntime.runPostLearningUpdates();
  const learningGateResult = resolvedCompletionRuntime.runLearningGate();
  await resolvedCompletionRuntime.persistSelfImproveLearningStores({ learningGateResult });
  const learningExportPhaseContext = resolvedCompletionRuntime.buildLearningExportPhaseContext({
    rowTsv,
    markdownSummary,
  });
  const { exportInfo, finalExport, learning } =
    await resolvedCompletionRuntime.runTerminalLearningExportLifecycle({
      learningExportPhaseContext,
    });

  return resolvedCompletionRuntime.buildRunResultPayload({
    exportInfo,
    finalExport,
    learning,
    learningGateResult,
    categoryBrain,
  });
}
