import {
  type RuntimeAutomationQueueStorageEngine,
  type RuntimeRepairDedupeRule,
  type RuntimeSelectableSearchProvider,
  type RuntimeSettingDefaults,
} from '../../../stores/settingsManifest';
import { type RuntimeSettings } from './runtimeSettingsAuthority';
import { parseRuntimeLlmTokenCap } from './runtimeSettingsDomain';
import {
  AUTOMATION_QUEUE_STORAGE_ENGINE_OPTIONS,
  OCR_BACKEND_OPTIONS,
  parseBoundedNumber,
  REPAIR_DEDUPE_RULE_OPTIONS,
  RESUME_MODE_OPTIONS,
  RUNTIME_NUMBER_BOUNDS,
  SEARCH_PROVIDER_OPTIONS,
  type RuntimeDraft,
} from './RuntimeFlowDraftContracts';

function parseBoolean(value: unknown, fallback: boolean): boolean {
  if (typeof value === 'boolean') return value;
  if (value === 1 || value === '1' || value === 'true' || value === 'yes' || value === 'on') return true;
  if (value === 0 || value === '0' || value === 'false' || value === 'no' || value === 'off') return false;
  return fallback;
}

function parseString(value: unknown, fallback: string, allowEmpty = false): string {
  if (typeof value !== 'string') return fallback;
  if (allowEmpty) return value;
  const token = value.trim();
  return token || fallback;
}

function parseEnum<T extends readonly string[]>(
  value: unknown,
  options: T,
  fallback: T[number],
): T[number] {
  const token = String(value || '').trim();
  if (!token) return fallback;
  return options.includes(token as T[number]) ? (token as T[number]) : fallback;
}

export function normalizeRuntimeDraft(
  source: RuntimeSettings | undefined,
  fallback: RuntimeSettingDefaults,
): RuntimeDraft {
  const raw = source || {};
  const fallbackSearchProvider: RuntimeSelectableSearchProvider =
    fallback.searchProvider === 'none' ? 'dual' : fallback.searchProvider;
  return {
    searchProvider: parseEnum(raw.searchProvider, SEARCH_PROVIDER_OPTIONS, fallbackSearchProvider),
    searxngBaseUrl: parseString(raw.searxngBaseUrl, fallback.searxngBaseUrl, true),
    llmPlanApiKey: parseString(raw.llmPlanApiKey, fallback.llmPlanApiKey, true),
    llmModelPlan: parseString(raw.llmModelPlan ?? raw.phase2LlmModel, fallback.llmModelPlan),
    phase2LlmModel: parseString(raw.phase2LlmModel ?? raw.llmModelPlan, fallback.phase2LlmModel),
    llmModelTriage: parseString(raw.llmModelTriage ?? raw.phase3LlmModel, fallback.llmModelTriage),
    phase3LlmModel: parseString(raw.phase3LlmModel ?? raw.llmModelTriage, fallback.phase3LlmModel),
    llmModelFast: parseString(raw.llmModelFast, fallback.llmModelFast),
    llmModelReasoning: parseString(raw.llmModelReasoning, fallback.llmModelReasoning),
    llmModelExtract: parseString(raw.llmModelExtract, fallback.llmModelExtract),
    llmModelValidate: parseString(raw.llmModelValidate, fallback.llmModelValidate),
    llmModelWrite: parseString(raw.llmModelWrite, fallback.llmModelWrite),
    llmPlanFallbackModel: parseString(raw.llmPlanFallbackModel, fallback.llmPlanFallbackModel, true),
    llmExtractFallbackModel: parseString(raw.llmExtractFallbackModel, fallback.llmExtractFallbackModel, true),
    llmValidateFallbackModel: parseString(raw.llmValidateFallbackModel, fallback.llmValidateFallbackModel, true),
    llmWriteFallbackModel: parseString(raw.llmWriteFallbackModel, fallback.llmWriteFallbackModel, true),
    outputMode: parseString(raw.outputMode, fallback.outputMode, true),
    localInputRoot: parseString(raw.localInputRoot, fallback.localInputRoot, true),
    localOutputRoot: parseString(raw.localOutputRoot, fallback.localOutputRoot, true),
    runtimeEventsKey: parseString(raw.runtimeEventsKey, fallback.runtimeEventsKey, true),
    awsRegion: parseString(raw.awsRegion, fallback.awsRegion, true),
    s3Bucket: parseString(raw.s3Bucket, fallback.s3Bucket, true),
    s3InputPrefix: parseString(raw.s3InputPrefix, fallback.s3InputPrefix, true),
    s3OutputPrefix: parseString(raw.s3OutputPrefix, fallback.s3OutputPrefix, true),
    eloSupabaseAnonKey: parseString(raw.eloSupabaseAnonKey, fallback.eloSupabaseAnonKey, true),
    eloSupabaseEndpoint: parseString(raw.eloSupabaseEndpoint, fallback.eloSupabaseEndpoint, true),
    llmProvider: parseString(raw.llmProvider, fallback.llmProvider, true),
    llmBaseUrl: parseString(raw.llmBaseUrl, fallback.llmBaseUrl, true),
    openaiApiKey: parseString(raw.openaiApiKey, fallback.openaiApiKey, true),
    anthropicApiKey: parseString(raw.anthropicApiKey, fallback.anthropicApiKey, true),
    llmPlanProvider: parseString(raw.llmPlanProvider, fallback.llmPlanProvider, true),
    llmPlanBaseUrl: parseString(raw.llmPlanBaseUrl, fallback.llmPlanBaseUrl, true),
    importsRoot: parseString(raw.importsRoot, fallback.importsRoot, true),
    llmExtractionCacheDir: parseString(raw.llmExtractionCacheDir, fallback.llmExtractionCacheDir, true),
    resumeMode: parseEnum(raw.resumeMode, RESUME_MODE_OPTIONS, fallback.resumeMode),
    scannedPdfOcrBackend: parseEnum(raw.scannedPdfOcrBackend, OCR_BACKEND_OPTIONS, fallback.scannedPdfOcrBackend),
    fetchBudgetMs: parseBoundedNumber(
      raw.fetchBudgetMs,
      fallback.fetchBudgetMs,
      RUNTIME_NUMBER_BOUNDS.fetchBudgetMs,
    ),
    fetchConcurrency: parseBoundedNumber(
      raw.fetchConcurrency,
      fallback.fetchConcurrency,
      RUNTIME_NUMBER_BOUNDS.fetchConcurrency,
    ),
    perHostMinDelayMs: parseBoundedNumber(
      raw.perHostMinDelayMs,
      fallback.perHostMinDelayMs,
      RUNTIME_NUMBER_BOUNDS.perHostMinDelayMs,
    ),
    searchGlobalRps: parseBoundedNumber(
      raw.searchGlobalRps,
      fallback.searchGlobalRps,
      RUNTIME_NUMBER_BOUNDS.searchGlobalRps,
    ),
    searchGlobalBurst: parseBoundedNumber(
      raw.searchGlobalBurst,
      fallback.searchGlobalBurst,
      RUNTIME_NUMBER_BOUNDS.searchGlobalBurst,
    ),
    searchPerHostRps: parseBoundedNumber(
      raw.searchPerHostRps,
      fallback.searchPerHostRps,
      RUNTIME_NUMBER_BOUNDS.searchPerHostRps,
    ),
    searchPerHostBurst: parseBoundedNumber(
      raw.searchPerHostBurst,
      fallback.searchPerHostBurst,
      RUNTIME_NUMBER_BOUNDS.searchPerHostBurst,
    ),
    domainRequestRps: parseBoundedNumber(
      raw.domainRequestRps,
      fallback.domainRequestRps,
      RUNTIME_NUMBER_BOUNDS.domainRequestRps,
    ),
    domainRequestBurst: parseBoundedNumber(
      raw.domainRequestBurst,
      fallback.domainRequestBurst,
      RUNTIME_NUMBER_BOUNDS.domainRequestBurst,
    ),
    globalRequestRps: parseBoundedNumber(
      raw.globalRequestRps,
      fallback.globalRequestRps,
      RUNTIME_NUMBER_BOUNDS.globalRequestRps,
    ),
    globalRequestBurst: parseBoundedNumber(
      raw.globalRequestBurst,
      fallback.globalRequestBurst,
      RUNTIME_NUMBER_BOUNDS.globalRequestBurst,
    ),
    fetchPerHostConcurrencyCap: parseBoundedNumber(
      raw.fetchPerHostConcurrencyCap,
      fallback.fetchPerHostConcurrencyCap,
      RUNTIME_NUMBER_BOUNDS.fetchPerHostConcurrencyCap,
    ),
    llmMaxOutputTokensPlan: parseRuntimeLlmTokenCap(raw.llmMaxOutputTokensPlan ?? raw.llmTokensPlan) || fallback.llmMaxOutputTokensPlan,
    llmTokensPlan: parseRuntimeLlmTokenCap(raw.llmTokensPlan ?? raw.llmMaxOutputTokensPlan) || fallback.llmTokensPlan,
    llmMaxOutputTokensTriage: parseRuntimeLlmTokenCap(raw.llmMaxOutputTokensTriage ?? raw.llmTokensTriage) || fallback.llmMaxOutputTokensTriage,
    llmTokensTriage: parseRuntimeLlmTokenCap(raw.llmTokensTriage ?? raw.llmMaxOutputTokensTriage) || fallback.llmTokensTriage,
    llmMaxOutputTokensFast: parseRuntimeLlmTokenCap(raw.llmMaxOutputTokensFast ?? raw.llmTokensFast) || fallback.llmMaxOutputTokensFast,
    llmTokensFast: parseRuntimeLlmTokenCap(raw.llmTokensFast ?? raw.llmMaxOutputTokensFast) || fallback.llmTokensFast,
    llmMaxOutputTokensReasoning: parseRuntimeLlmTokenCap(raw.llmMaxOutputTokensReasoning ?? raw.llmTokensReasoning) || fallback.llmMaxOutputTokensReasoning,
    llmTokensReasoning: parseRuntimeLlmTokenCap(raw.llmTokensReasoning ?? raw.llmMaxOutputTokensReasoning) || fallback.llmTokensReasoning,
    llmMaxOutputTokensExtract: parseRuntimeLlmTokenCap(raw.llmMaxOutputTokensExtract ?? raw.llmTokensExtract) || fallback.llmMaxOutputTokensExtract,
    llmTokensExtract: parseRuntimeLlmTokenCap(raw.llmTokensExtract ?? raw.llmMaxOutputTokensExtract) || fallback.llmTokensExtract,
    llmMaxOutputTokensValidate: parseRuntimeLlmTokenCap(raw.llmMaxOutputTokensValidate ?? raw.llmTokensValidate) || fallback.llmMaxOutputTokensValidate,
    llmTokensValidate: parseRuntimeLlmTokenCap(raw.llmTokensValidate ?? raw.llmMaxOutputTokensValidate) || fallback.llmTokensValidate,
    llmMaxOutputTokensWrite: parseRuntimeLlmTokenCap(raw.llmMaxOutputTokensWrite ?? raw.llmTokensWrite) || fallback.llmMaxOutputTokensWrite,
    llmTokensWrite: parseRuntimeLlmTokenCap(raw.llmTokensWrite ?? raw.llmMaxOutputTokensWrite) || fallback.llmTokensWrite,
    llmMaxOutputTokensPlanFallback: parseRuntimeLlmTokenCap(raw.llmMaxOutputTokensPlanFallback ?? raw.llmTokensPlanFallback) || fallback.llmMaxOutputTokensPlanFallback,
    llmTokensPlanFallback: parseRuntimeLlmTokenCap(raw.llmTokensPlanFallback ?? raw.llmMaxOutputTokensPlanFallback) || fallback.llmTokensPlanFallback,
    llmMaxOutputTokensExtractFallback: parseRuntimeLlmTokenCap(raw.llmMaxOutputTokensExtractFallback ?? raw.llmTokensExtractFallback) || fallback.llmMaxOutputTokensExtractFallback,
    llmTokensExtractFallback: parseRuntimeLlmTokenCap(raw.llmTokensExtractFallback ?? raw.llmMaxOutputTokensExtractFallback) || fallback.llmTokensExtractFallback,
    llmMaxOutputTokensValidateFallback: parseRuntimeLlmTokenCap(raw.llmMaxOutputTokensValidateFallback ?? raw.llmTokensValidateFallback) || fallback.llmMaxOutputTokensValidateFallback,
    llmTokensValidateFallback: parseRuntimeLlmTokenCap(raw.llmTokensValidateFallback ?? raw.llmMaxOutputTokensValidateFallback) || fallback.llmTokensValidateFallback,
    llmMaxOutputTokensWriteFallback: parseRuntimeLlmTokenCap(raw.llmMaxOutputTokensWriteFallback ?? raw.llmTokensWriteFallback) || fallback.llmMaxOutputTokensWriteFallback,
    llmTokensWriteFallback: parseRuntimeLlmTokenCap(raw.llmTokensWriteFallback ?? raw.llmMaxOutputTokensWriteFallback) || fallback.llmTokensWriteFallback,
    resumeWindowHours: parseBoundedNumber(
      raw.resumeWindowHours,
      fallback.resumeWindowHours,
      RUNTIME_NUMBER_BOUNDS.resumeWindowHours,
    ),
    indexingResumeSeedLimit: parseBoundedNumber(
      raw.indexingResumeSeedLimit,
      fallback.indexingResumeSeedLimit,
      RUNTIME_NUMBER_BOUNDS.indexingResumeSeedLimit,
    ),
    indexingResumePersistLimit: parseBoundedNumber(
      raw.indexingResumePersistLimit,
      fallback.indexingResumePersistLimit,
      RUNTIME_NUMBER_BOUNDS.indexingResumePersistLimit,
    ),
    reextractAfterHours: parseBoundedNumber(
      raw.reextractAfterHours,
      fallback.reextractAfterHours,
      RUNTIME_NUMBER_BOUNDS.reextractAfterHours,
    ),
    scannedPdfOcrMaxPages: parseBoundedNumber(
      raw.scannedPdfOcrMaxPages,
      fallback.scannedPdfOcrMaxPages,
      RUNTIME_NUMBER_BOUNDS.scannedPdfOcrMaxPages,
    ),
    scannedPdfOcrMaxPairs: parseBoundedNumber(
      raw.scannedPdfOcrMaxPairs,
      fallback.scannedPdfOcrMaxPairs,
      RUNTIME_NUMBER_BOUNDS.scannedPdfOcrMaxPairs,
    ),
    scannedPdfOcrMinCharsPerPage: parseBoundedNumber(
      raw.scannedPdfOcrMinCharsPerPage,
      fallback.scannedPdfOcrMinCharsPerPage,
      RUNTIME_NUMBER_BOUNDS.scannedPdfOcrMinCharsPerPage,
    ),
    scannedPdfOcrMinLinesPerPage: parseBoundedNumber(
      raw.scannedPdfOcrMinLinesPerPage,
      fallback.scannedPdfOcrMinLinesPerPage,
      RUNTIME_NUMBER_BOUNDS.scannedPdfOcrMinLinesPerPage,
    ),
    scannedPdfOcrMinConfidence: parseBoundedNumber(
      raw.scannedPdfOcrMinConfidence,
      fallback.scannedPdfOcrMinConfidence,
      RUNTIME_NUMBER_BOUNDS.scannedPdfOcrMinConfidence,
    ),
    crawleeRequestHandlerTimeoutSecs: parseBoundedNumber(
      raw.crawleeRequestHandlerTimeoutSecs,
      fallback.crawleeRequestHandlerTimeoutSecs,
      RUNTIME_NUMBER_BOUNDS.crawleeRequestHandlerTimeoutSecs,
    ),
    dynamicFetchRetryBudget: parseBoundedNumber(
      raw.dynamicFetchRetryBudget,
      fallback.dynamicFetchRetryBudget,
      RUNTIME_NUMBER_BOUNDS.dynamicFetchRetryBudget,
    ),
    dynamicFetchRetryBackoffMs: parseBoundedNumber(
      raw.dynamicFetchRetryBackoffMs,
      fallback.dynamicFetchRetryBackoffMs,
      RUNTIME_NUMBER_BOUNDS.dynamicFetchRetryBackoffMs,
    ),
    fetchSchedulerMaxRetries: parseBoundedNumber(
      raw.fetchSchedulerMaxRetries,
      fallback.fetchSchedulerMaxRetries,
      RUNTIME_NUMBER_BOUNDS.fetchSchedulerMaxRetries,
    ),
    fetchSchedulerFallbackWaitMs: parseBoundedNumber(
      raw.fetchSchedulerFallbackWaitMs,
      fallback.fetchSchedulerFallbackWaitMs,
      RUNTIME_NUMBER_BOUNDS.fetchSchedulerFallbackWaitMs,
    ),
    pageGotoTimeoutMs: parseBoundedNumber(
      raw.pageGotoTimeoutMs,
      fallback.pageGotoTimeoutMs,
      RUNTIME_NUMBER_BOUNDS.pageGotoTimeoutMs,
    ),
    pageNetworkIdleTimeoutMs: parseBoundedNumber(
      raw.pageNetworkIdleTimeoutMs,
      fallback.pageNetworkIdleTimeoutMs,
      RUNTIME_NUMBER_BOUNDS.pageNetworkIdleTimeoutMs,
    ),
    postLoadWaitMs: parseBoundedNumber(
      raw.postLoadWaitMs,
      fallback.postLoadWaitMs,
      RUNTIME_NUMBER_BOUNDS.postLoadWaitMs,
    ),
    frontierDbPath: parseString(raw.frontierDbPath, fallback.frontierDbPath, true),
    frontierQueryCooldownSeconds: parseBoundedNumber(
      raw.frontierQueryCooldownSeconds,
      fallback.frontierQueryCooldownSeconds,
      RUNTIME_NUMBER_BOUNDS.frontierQueryCooldownSeconds,
    ),
    frontierCooldown404Seconds: parseBoundedNumber(
      raw.frontierCooldown404Seconds,
      fallback.frontierCooldown404Seconds,
      RUNTIME_NUMBER_BOUNDS.frontierCooldown404Seconds,
    ),
    frontierCooldown404RepeatSeconds: parseBoundedNumber(
      raw.frontierCooldown404RepeatSeconds,
      fallback.frontierCooldown404RepeatSeconds,
      RUNTIME_NUMBER_BOUNDS.frontierCooldown404RepeatSeconds,
    ),
    frontierCooldown410Seconds: parseBoundedNumber(
      raw.frontierCooldown410Seconds,
      fallback.frontierCooldown410Seconds,
      RUNTIME_NUMBER_BOUNDS.frontierCooldown410Seconds,
    ),
    frontierCooldownTimeoutSeconds: parseBoundedNumber(
      raw.frontierCooldownTimeoutSeconds,
      fallback.frontierCooldownTimeoutSeconds,
      RUNTIME_NUMBER_BOUNDS.frontierCooldownTimeoutSeconds,
    ),
    frontierCooldown403BaseSeconds: parseBoundedNumber(
      raw.frontierCooldown403BaseSeconds,
      fallback.frontierCooldown403BaseSeconds,
      RUNTIME_NUMBER_BOUNDS.frontierCooldown403BaseSeconds,
    ),
    frontierCooldown429BaseSeconds: parseBoundedNumber(
      raw.frontierCooldown429BaseSeconds,
      fallback.frontierCooldown429BaseSeconds,
      RUNTIME_NUMBER_BOUNDS.frontierCooldown429BaseSeconds,
    ),
    frontierBackoffMaxExponent: parseBoundedNumber(
      raw.frontierBackoffMaxExponent,
      fallback.frontierBackoffMaxExponent,
      RUNTIME_NUMBER_BOUNDS.frontierBackoffMaxExponent,
    ),
    frontierPathPenaltyNotfoundThreshold: parseBoundedNumber(
      raw.frontierPathPenaltyNotfoundThreshold,
      fallback.frontierPathPenaltyNotfoundThreshold,
      RUNTIME_NUMBER_BOUNDS.frontierPathPenaltyNotfoundThreshold,
    ),
    frontierBlockedDomainThreshold: parseBoundedNumber(
      raw.frontierBlockedDomainThreshold,
      fallback.frontierBlockedDomainThreshold,
      RUNTIME_NUMBER_BOUNDS.frontierBlockedDomainThreshold,
    ),
    autoScrollPasses: parseBoundedNumber(
      raw.autoScrollPasses,
      fallback.autoScrollPasses,
      RUNTIME_NUMBER_BOUNDS.autoScrollPasses,
    ),
    autoScrollDelayMs: parseBoundedNumber(
      raw.autoScrollDelayMs,
      fallback.autoScrollDelayMs,
      RUNTIME_NUMBER_BOUNDS.autoScrollDelayMs,
    ),
    maxGraphqlReplays: parseBoundedNumber(
      raw.maxGraphqlReplays,
      fallback.maxGraphqlReplays,
      RUNTIME_NUMBER_BOUNDS.maxGraphqlReplays,
    ),
    maxNetworkResponsesPerPage: parseBoundedNumber(
      raw.maxNetworkResponsesPerPage,
      fallback.maxNetworkResponsesPerPage,
      RUNTIME_NUMBER_BOUNDS.maxNetworkResponsesPerPage,
    ),
    robotsTxtTimeoutMs: parseBoundedNumber(
      raw.robotsTxtTimeoutMs,
      fallback.robotsTxtTimeoutMs,
      RUNTIME_NUMBER_BOUNDS.robotsTxtTimeoutMs,
    ),
    endpointSignalLimit: parseBoundedNumber(
      raw.endpointSignalLimit,
      fallback.endpointSignalLimit,
      RUNTIME_NUMBER_BOUNDS.endpointSignalLimit,
    ),
    endpointSuggestionLimit: parseBoundedNumber(
      raw.endpointSuggestionLimit,
      fallback.endpointSuggestionLimit,
      RUNTIME_NUMBER_BOUNDS.endpointSuggestionLimit,
    ),
    endpointNetworkScanLimit: parseBoundedNumber(
      raw.endpointNetworkScanLimit,
      fallback.endpointNetworkScanLimit,
      RUNTIME_NUMBER_BOUNDS.endpointNetworkScanLimit,
    ),
    discoveryMaxQueries: parseBoundedNumber(
      raw.discoveryMaxQueries,
      fallback.discoveryMaxQueries,
      RUNTIME_NUMBER_BOUNDS.discoveryMaxQueries,
    ),
    discoveryMaxDiscovered: parseBoundedNumber(
      raw.discoveryMaxDiscovered,
      fallback.discoveryMaxDiscovered,
      RUNTIME_NUMBER_BOUNDS.discoveryMaxDiscovered,
    ),
    maxUrlsPerProduct: parseBoundedNumber(
      raw.maxUrlsPerProduct,
      fallback.maxUrlsPerProduct,
      RUNTIME_NUMBER_BOUNDS.maxUrlsPerProduct,
    ),
    maxCandidateUrls: parseBoundedNumber(
      raw.maxCandidateUrls,
      fallback.maxCandidateUrls,
      RUNTIME_NUMBER_BOUNDS.maxCandidateUrls,
    ),
    serpTriageMaxUrls: parseBoundedNumber(
      raw.serpTriageMaxUrls,
      fallback.serpTriageMaxUrls,
      RUNTIME_NUMBER_BOUNDS.serpTriageMaxUrls,
    ),
    maxPagesPerDomain: parseBoundedNumber(
      raw.maxPagesPerDomain,
      fallback.maxPagesPerDomain,
      RUNTIME_NUMBER_BOUNDS.maxPagesPerDomain,
    ),
    maxRunSeconds: parseBoundedNumber(
      raw.maxRunSeconds,
      fallback.maxRunSeconds,
      RUNTIME_NUMBER_BOUNDS.maxRunSeconds,
    ),
    maxJsonBytes: parseBoundedNumber(
      raw.maxJsonBytes,
      fallback.maxJsonBytes,
      RUNTIME_NUMBER_BOUNDS.maxJsonBytes,
    ),
    maxPdfBytes: parseBoundedNumber(
      raw.maxPdfBytes,
      fallback.maxPdfBytes,
      RUNTIME_NUMBER_BOUNDS.maxPdfBytes,
    ),
    pdfBackendRouterTimeoutMs: parseBoundedNumber(
      raw.pdfBackendRouterTimeoutMs,
      fallback.pdfBackendRouterTimeoutMs,
      RUNTIME_NUMBER_BOUNDS.pdfBackendRouterTimeoutMs,
    ),
    pdfBackendRouterMaxPages: parseBoundedNumber(
      raw.pdfBackendRouterMaxPages,
      fallback.pdfBackendRouterMaxPages,
      RUNTIME_NUMBER_BOUNDS.pdfBackendRouterMaxPages,
    ),
    pdfBackendRouterMaxPairs: parseBoundedNumber(
      raw.pdfBackendRouterMaxPairs,
      fallback.pdfBackendRouterMaxPairs,
      RUNTIME_NUMBER_BOUNDS.pdfBackendRouterMaxPairs,
    ),
    pdfBackendRouterMaxTextPreviewChars: parseBoundedNumber(
      raw.pdfBackendRouterMaxTextPreviewChars,
      fallback.pdfBackendRouterMaxTextPreviewChars,
      RUNTIME_NUMBER_BOUNDS.pdfBackendRouterMaxTextPreviewChars,
    ),
    capturePageScreenshotQuality: parseBoundedNumber(
      raw.capturePageScreenshotQuality,
      fallback.capturePageScreenshotQuality,
      RUNTIME_NUMBER_BOUNDS.capturePageScreenshotQuality,
    ),
    capturePageScreenshotMaxBytes: parseBoundedNumber(
      raw.capturePageScreenshotMaxBytes,
      fallback.capturePageScreenshotMaxBytes,
      RUNTIME_NUMBER_BOUNDS.capturePageScreenshotMaxBytes,
    ),
    articleExtractorMinChars: parseBoundedNumber(
      raw.articleExtractorMinChars,
      fallback.articleExtractorMinChars,
      RUNTIME_NUMBER_BOUNDS.articleExtractorMinChars,
    ),
    articleExtractorMinScore: parseBoundedNumber(
      raw.articleExtractorMinScore,
      fallback.articleExtractorMinScore,
      RUNTIME_NUMBER_BOUNDS.articleExtractorMinScore,
    ),
    articleExtractorMaxChars: parseBoundedNumber(
      raw.articleExtractorMaxChars,
      fallback.articleExtractorMaxChars,
      RUNTIME_NUMBER_BOUNDS.articleExtractorMaxChars,
    ),
    staticDomTargetMatchThreshold: parseBoundedNumber(
      raw.staticDomTargetMatchThreshold,
      fallback.staticDomTargetMatchThreshold,
      RUNTIME_NUMBER_BOUNDS.staticDomTargetMatchThreshold,
    ),
    staticDomMaxEvidenceSnippets: parseBoundedNumber(
      raw.staticDomMaxEvidenceSnippets,
      fallback.staticDomMaxEvidenceSnippets,
      RUNTIME_NUMBER_BOUNDS.staticDomMaxEvidenceSnippets,
    ),
    structuredMetadataExtructTimeoutMs: parseBoundedNumber(
      raw.structuredMetadataExtructTimeoutMs,
      fallback.structuredMetadataExtructTimeoutMs,
      RUNTIME_NUMBER_BOUNDS.structuredMetadataExtructTimeoutMs,
    ),
    structuredMetadataExtructMaxItemsPerSurface: parseBoundedNumber(
      raw.structuredMetadataExtructMaxItemsPerSurface,
      fallback.structuredMetadataExtructMaxItemsPerSurface,
      RUNTIME_NUMBER_BOUNDS.structuredMetadataExtructMaxItemsPerSurface,
    ),
    structuredMetadataExtructCacheLimit: parseBoundedNumber(
      raw.structuredMetadataExtructCacheLimit,
      fallback.structuredMetadataExtructCacheLimit,
      RUNTIME_NUMBER_BOUNDS.structuredMetadataExtructCacheLimit,
    ),
    domSnippetMaxChars: parseBoundedNumber(
      raw.domSnippetMaxChars,
      fallback.domSnippetMaxChars,
      RUNTIME_NUMBER_BOUNDS.domSnippetMaxChars,
    ),
    llmExtractionCacheTtlMs: parseBoundedNumber(
      raw.llmExtractionCacheTtlMs,
      fallback.llmExtractionCacheTtlMs,
      RUNTIME_NUMBER_BOUNDS.llmExtractionCacheTtlMs,
    ),
    llmMaxCallsPerProductTotal: parseBoundedNumber(
      raw.llmMaxCallsPerProductTotal,
      fallback.llmMaxCallsPerProductTotal,
      RUNTIME_NUMBER_BOUNDS.llmMaxCallsPerProductTotal,
    ),
    llmMaxCallsPerProductFast: parseBoundedNumber(
      raw.llmMaxCallsPerProductFast,
      fallback.llmMaxCallsPerProductFast,
      RUNTIME_NUMBER_BOUNDS.llmMaxCallsPerProductFast,
    ),
    consensusMethodWeightNetworkJson: parseBoundedNumber(
      raw.consensusMethodWeightNetworkJson,
      fallback.consensusMethodWeightNetworkJson,
      RUNTIME_NUMBER_BOUNDS.consensusMethodWeightNetworkJson,
    ),
    consensusMethodWeightAdapterApi: parseBoundedNumber(
      raw.consensusMethodWeightAdapterApi,
      fallback.consensusMethodWeightAdapterApi,
      RUNTIME_NUMBER_BOUNDS.consensusMethodWeightAdapterApi,
    ),
    consensusMethodWeightStructuredMeta: parseBoundedNumber(
      raw.consensusMethodWeightStructuredMeta,
      fallback.consensusMethodWeightStructuredMeta,
      RUNTIME_NUMBER_BOUNDS.consensusMethodWeightStructuredMeta,
    ),
    consensusMethodWeightPdf: parseBoundedNumber(
      raw.consensusMethodWeightPdf,
      fallback.consensusMethodWeightPdf,
      RUNTIME_NUMBER_BOUNDS.consensusMethodWeightPdf,
    ),
    consensusMethodWeightTableKv: parseBoundedNumber(
      raw.consensusMethodWeightTableKv,
      fallback.consensusMethodWeightTableKv,
      RUNTIME_NUMBER_BOUNDS.consensusMethodWeightTableKv,
    ),
    consensusMethodWeightDom: parseBoundedNumber(
      raw.consensusMethodWeightDom,
      fallback.consensusMethodWeightDom,
      RUNTIME_NUMBER_BOUNDS.consensusMethodWeightDom,
    ),
    consensusMethodWeightLlmExtractBase: parseBoundedNumber(
      raw.consensusMethodWeightLlmExtractBase,
      fallback.consensusMethodWeightLlmExtractBase,
      RUNTIME_NUMBER_BOUNDS.consensusMethodWeightLlmExtractBase,
    ),
    consensusPolicyBonus: parseBoundedNumber(
      raw.consensusPolicyBonus,
      fallback.consensusPolicyBonus,
      RUNTIME_NUMBER_BOUNDS.consensusPolicyBonus,
    ),
    consensusWeightedMajorityThreshold: parseBoundedNumber(
      raw.consensusWeightedMajorityThreshold,
      fallback.consensusWeightedMajorityThreshold,
      RUNTIME_NUMBER_BOUNDS.consensusWeightedMajorityThreshold,
    ),
    consensusStrictAcceptanceDomainCount: parseBoundedNumber(
      raw.consensusStrictAcceptanceDomainCount,
      fallback.consensusStrictAcceptanceDomainCount,
      RUNTIME_NUMBER_BOUNDS.consensusStrictAcceptanceDomainCount,
    ),
    consensusRelaxedAcceptanceDomainCount: parseBoundedNumber(
      raw.consensusRelaxedAcceptanceDomainCount,
      fallback.consensusRelaxedAcceptanceDomainCount,
      RUNTIME_NUMBER_BOUNDS.consensusRelaxedAcceptanceDomainCount,
    ),
    consensusInstrumentedFieldThreshold: parseBoundedNumber(
      raw.consensusInstrumentedFieldThreshold,
      fallback.consensusInstrumentedFieldThreshold,
      RUNTIME_NUMBER_BOUNDS.consensusInstrumentedFieldThreshold,
    ),
    consensusConfidenceScoringBase: parseBoundedNumber(
      raw.consensusConfidenceScoringBase,
      fallback.consensusConfidenceScoringBase,
      RUNTIME_NUMBER_BOUNDS.consensusConfidenceScoringBase,
    ),
    consensusPassTargetIdentityStrong: parseBoundedNumber(
      raw.consensusPassTargetIdentityStrong,
      fallback.consensusPassTargetIdentityStrong,
      RUNTIME_NUMBER_BOUNDS.consensusPassTargetIdentityStrong,
    ),
    consensusPassTargetNormal: parseBoundedNumber(
      raw.consensusPassTargetNormal,
      fallback.consensusPassTargetNormal,
      RUNTIME_NUMBER_BOUNDS.consensusPassTargetNormal,
    ),
    retrievalTierWeightTier1: parseBoundedNumber(
      raw.retrievalTierWeightTier1,
      fallback.retrievalTierWeightTier1,
      RUNTIME_NUMBER_BOUNDS.retrievalTierWeightTier1,
    ),
    retrievalTierWeightTier2: parseBoundedNumber(
      raw.retrievalTierWeightTier2,
      fallback.retrievalTierWeightTier2,
      RUNTIME_NUMBER_BOUNDS.retrievalTierWeightTier2,
    ),
    retrievalTierWeightTier3: parseBoundedNumber(
      raw.retrievalTierWeightTier3,
      fallback.retrievalTierWeightTier3,
      RUNTIME_NUMBER_BOUNDS.retrievalTierWeightTier3,
    ),
    retrievalTierWeightTier4: parseBoundedNumber(
      raw.retrievalTierWeightTier4,
      fallback.retrievalTierWeightTier4,
      RUNTIME_NUMBER_BOUNDS.retrievalTierWeightTier4,
    ),
    retrievalTierWeightTier5: parseBoundedNumber(
      raw.retrievalTierWeightTier5,
      fallback.retrievalTierWeightTier5,
      RUNTIME_NUMBER_BOUNDS.retrievalTierWeightTier5,
    ),
    retrievalDocKindWeightManualPdf: parseBoundedNumber(
      raw.retrievalDocKindWeightManualPdf,
      fallback.retrievalDocKindWeightManualPdf,
      RUNTIME_NUMBER_BOUNDS.retrievalDocKindWeightManualPdf,
    ),
    retrievalDocKindWeightSpecPdf: parseBoundedNumber(
      raw.retrievalDocKindWeightSpecPdf,
      fallback.retrievalDocKindWeightSpecPdf,
      RUNTIME_NUMBER_BOUNDS.retrievalDocKindWeightSpecPdf,
    ),
    retrievalDocKindWeightSupport: parseBoundedNumber(
      raw.retrievalDocKindWeightSupport,
      fallback.retrievalDocKindWeightSupport,
      RUNTIME_NUMBER_BOUNDS.retrievalDocKindWeightSupport,
    ),
    retrievalDocKindWeightLabReview: parseBoundedNumber(
      raw.retrievalDocKindWeightLabReview,
      fallback.retrievalDocKindWeightLabReview,
      RUNTIME_NUMBER_BOUNDS.retrievalDocKindWeightLabReview,
    ),
    retrievalDocKindWeightProductPage: parseBoundedNumber(
      raw.retrievalDocKindWeightProductPage,
      fallback.retrievalDocKindWeightProductPage,
      RUNTIME_NUMBER_BOUNDS.retrievalDocKindWeightProductPage,
    ),
    retrievalDocKindWeightOther: parseBoundedNumber(
      raw.retrievalDocKindWeightOther,
      fallback.retrievalDocKindWeightOther,
      RUNTIME_NUMBER_BOUNDS.retrievalDocKindWeightOther,
    ),
    retrievalMethodWeightTable: parseBoundedNumber(
      raw.retrievalMethodWeightTable,
      fallback.retrievalMethodWeightTable,
      RUNTIME_NUMBER_BOUNDS.retrievalMethodWeightTable,
    ),
    retrievalMethodWeightKv: parseBoundedNumber(
      raw.retrievalMethodWeightKv,
      fallback.retrievalMethodWeightKv,
      RUNTIME_NUMBER_BOUNDS.retrievalMethodWeightKv,
    ),
    retrievalMethodWeightJsonLd: parseBoundedNumber(
      raw.retrievalMethodWeightJsonLd,
      fallback.retrievalMethodWeightJsonLd,
      RUNTIME_NUMBER_BOUNDS.retrievalMethodWeightJsonLd,
    ),
    retrievalMethodWeightLlmExtract: parseBoundedNumber(
      raw.retrievalMethodWeightLlmExtract,
      fallback.retrievalMethodWeightLlmExtract,
      RUNTIME_NUMBER_BOUNDS.retrievalMethodWeightLlmExtract,
    ),
    retrievalMethodWeightHelperSupportive: parseBoundedNumber(
      raw.retrievalMethodWeightHelperSupportive,
      fallback.retrievalMethodWeightHelperSupportive,
      RUNTIME_NUMBER_BOUNDS.retrievalMethodWeightHelperSupportive,
    ),
    retrievalAnchorScorePerMatch: parseBoundedNumber(
      raw.retrievalAnchorScorePerMatch,
      fallback.retrievalAnchorScorePerMatch,
      RUNTIME_NUMBER_BOUNDS.retrievalAnchorScorePerMatch,
    ),
    retrievalIdentityScorePerMatch: parseBoundedNumber(
      raw.retrievalIdentityScorePerMatch,
      fallback.retrievalIdentityScorePerMatch,
      RUNTIME_NUMBER_BOUNDS.retrievalIdentityScorePerMatch,
    ),
    retrievalUnitMatchBonus: parseBoundedNumber(
      raw.retrievalUnitMatchBonus,
      fallback.retrievalUnitMatchBonus,
      RUNTIME_NUMBER_BOUNDS.retrievalUnitMatchBonus,
    ),
    retrievalDirectFieldMatchBonus: parseBoundedNumber(
      raw.retrievalDirectFieldMatchBonus,
      fallback.retrievalDirectFieldMatchBonus,
      RUNTIME_NUMBER_BOUNDS.retrievalDirectFieldMatchBonus,
    ),
    llmExtractMaxTokens: parseBoundedNumber(
      raw.llmExtractMaxTokens,
      fallback.llmExtractMaxTokens,
      RUNTIME_NUMBER_BOUNDS.llmExtractMaxTokens,
    ),
    llmExtractMaxSnippetsPerBatch: parseBoundedNumber(
      raw.llmExtractMaxSnippetsPerBatch,
      fallback.llmExtractMaxSnippetsPerBatch,
      RUNTIME_NUMBER_BOUNDS.llmExtractMaxSnippetsPerBatch,
    ),
    llmExtractMaxSnippetChars: parseBoundedNumber(
      raw.llmExtractMaxSnippetChars,
      fallback.llmExtractMaxSnippetChars,
      RUNTIME_NUMBER_BOUNDS.llmExtractMaxSnippetChars,
    ),
    llmExtractReasoningBudget: parseBoundedNumber(
      raw.llmExtractReasoningBudget,
      fallback.llmExtractReasoningBudget,
      RUNTIME_NUMBER_BOUNDS.llmExtractReasoningBudget,
    ),
    llmReasoningBudget: parseBoundedNumber(
      raw.llmReasoningBudget,
      fallback.llmReasoningBudget,
      RUNTIME_NUMBER_BOUNDS.llmReasoningBudget,
    ),
    llmMonthlyBudgetUsd: parseBoundedNumber(
      raw.llmMonthlyBudgetUsd,
      fallback.llmMonthlyBudgetUsd,
      RUNTIME_NUMBER_BOUNDS.llmMonthlyBudgetUsd,
    ),
    llmPerProductBudgetUsd: parseBoundedNumber(
      raw.llmPerProductBudgetUsd,
      fallback.llmPerProductBudgetUsd,
      RUNTIME_NUMBER_BOUNDS.llmPerProductBudgetUsd,
    ),
    llmMaxCallsPerRound: parseBoundedNumber(
      raw.llmMaxCallsPerRound,
      fallback.llmMaxCallsPerRound,
      RUNTIME_NUMBER_BOUNDS.llmMaxCallsPerRound,
    ),
    llmMaxOutputTokens: parseBoundedNumber(
      raw.llmMaxOutputTokens,
      fallback.llmMaxOutputTokens,
      RUNTIME_NUMBER_BOUNDS.llmMaxOutputTokens,
    ),
    llmVerifySampleRate: parseBoundedNumber(
      raw.llmVerifySampleRate,
      fallback.llmVerifySampleRate,
      RUNTIME_NUMBER_BOUNDS.llmVerifySampleRate,
    ),
    llmMaxBatchesPerProduct: parseBoundedNumber(
      raw.llmMaxBatchesPerProduct,
      fallback.llmMaxBatchesPerProduct,
      RUNTIME_NUMBER_BOUNDS.llmMaxBatchesPerProduct,
    ),
    llmMaxEvidenceChars: parseBoundedNumber(
      raw.llmMaxEvidenceChars,
      fallback.llmMaxEvidenceChars,
      RUNTIME_NUMBER_BOUNDS.llmMaxEvidenceChars,
    ),
    llmMaxTokens: parseBoundedNumber(
      raw.llmMaxTokens,
      fallback.llmMaxTokens,
      RUNTIME_NUMBER_BOUNDS.llmMaxTokens,
    ),
    llmTimeoutMs: parseBoundedNumber(
      raw.llmTimeoutMs,
      fallback.llmTimeoutMs,
      RUNTIME_NUMBER_BOUNDS.llmTimeoutMs,
    ),
    llmCostInputPer1M: parseBoundedNumber(
      raw.llmCostInputPer1M,
      fallback.llmCostInputPer1M,
      RUNTIME_NUMBER_BOUNDS.llmCostInputPer1M,
    ),
    llmCostOutputPer1M: parseBoundedNumber(
      raw.llmCostOutputPer1M,
      fallback.llmCostOutputPer1M,
      RUNTIME_NUMBER_BOUNDS.llmCostOutputPer1M,
    ),
    llmCostCachedInputPer1M: parseBoundedNumber(
      raw.llmCostCachedInputPer1M,
      fallback.llmCostCachedInputPer1M,
      RUNTIME_NUMBER_BOUNDS.llmCostCachedInputPer1M,
    ),
    maxManufacturerUrlsPerProduct: parseBoundedNumber(
      raw.maxManufacturerUrlsPerProduct,
      fallback.maxManufacturerUrlsPerProduct,
      RUNTIME_NUMBER_BOUNDS.maxManufacturerUrlsPerProduct,
    ),
    maxManufacturerPagesPerDomain: parseBoundedNumber(
      raw.maxManufacturerPagesPerDomain,
      fallback.maxManufacturerPagesPerDomain,
      RUNTIME_NUMBER_BOUNDS.maxManufacturerPagesPerDomain,
    ),
    manufacturerReserveUrls: parseBoundedNumber(
      raw.manufacturerReserveUrls,
      fallback.manufacturerReserveUrls,
      RUNTIME_NUMBER_BOUNDS.manufacturerReserveUrls,
    ),
    maxHypothesisItems: parseBoundedNumber(
      raw.maxHypothesisItems,
      fallback.maxHypothesisItems,
      RUNTIME_NUMBER_BOUNDS.maxHypothesisItems,
    ),
    hypothesisAutoFollowupRounds: parseBoundedNumber(
      raw.hypothesisAutoFollowupRounds,
      fallback.hypothesisAutoFollowupRounds,
      RUNTIME_NUMBER_BOUNDS.hypothesisAutoFollowupRounds,
    ),
    hypothesisFollowupUrlsPerRound: parseBoundedNumber(
      raw.hypothesisFollowupUrlsPerRound,
      fallback.hypothesisFollowupUrlsPerRound,
      RUNTIME_NUMBER_BOUNDS.hypothesisFollowupUrlsPerRound,
    ),
    runtimeScreencastFps: parseBoundedNumber(
      raw.runtimeScreencastFps,
      fallback.runtimeScreencastFps,
      RUNTIME_NUMBER_BOUNDS.runtimeScreencastFps,
    ),
    runtimeScreencastQuality: parseBoundedNumber(
      raw.runtimeScreencastQuality,
      fallback.runtimeScreencastQuality,
      RUNTIME_NUMBER_BOUNDS.runtimeScreencastQuality,
    ),
    runtimeScreencastMaxWidth: parseBoundedNumber(
      raw.runtimeScreencastMaxWidth,
      fallback.runtimeScreencastMaxWidth,
      RUNTIME_NUMBER_BOUNDS.runtimeScreencastMaxWidth,
    ),
    runtimeScreencastMaxHeight: parseBoundedNumber(
      raw.runtimeScreencastMaxHeight,
      fallback.runtimeScreencastMaxHeight,
      RUNTIME_NUMBER_BOUNDS.runtimeScreencastMaxHeight,
    ),
    runtimeTraceFetchRing: parseBoundedNumber(
      raw.runtimeTraceFetchRing,
      fallback.runtimeTraceFetchRing,
      RUNTIME_NUMBER_BOUNDS.runtimeTraceFetchRing,
    ),
    runtimeTraceLlmRing: parseBoundedNumber(
      raw.runtimeTraceLlmRing,
      fallback.runtimeTraceLlmRing,
      RUNTIME_NUMBER_BOUNDS.runtimeTraceLlmRing,
    ),
    daemonConcurrency: parseBoundedNumber(
      raw.daemonConcurrency,
      fallback.daemonConcurrency,
      RUNTIME_NUMBER_BOUNDS.daemonConcurrency,
    ),
    daemonGracefulShutdownTimeoutMs: parseBoundedNumber(
      raw.daemonGracefulShutdownTimeoutMs,
      fallback.daemonGracefulShutdownTimeoutMs,
      RUNTIME_NUMBER_BOUNDS.daemonGracefulShutdownTimeoutMs,
    ),
    importsPollSeconds: parseBoundedNumber(
      raw.importsPollSeconds,
      fallback.importsPollSeconds,
      RUNTIME_NUMBER_BOUNDS.importsPollSeconds,
    ),
    identityGatePublishThreshold: parseBoundedNumber(
      raw.identityGatePublishThreshold,
      fallback.identityGatePublishThreshold,
      RUNTIME_NUMBER_BOUNDS.identityGatePublishThreshold,
    ),
    identityGateBaseMatchThreshold: parseBoundedNumber(
      raw.identityGateBaseMatchThreshold,
      fallback.identityGateBaseMatchThreshold,
      RUNTIME_NUMBER_BOUNDS.identityGateBaseMatchThreshold,
    ),
    qualityGateIdentityThreshold: parseBoundedNumber(
      raw.qualityGateIdentityThreshold,
      fallback.qualityGateIdentityThreshold,
      RUNTIME_NUMBER_BOUNDS.qualityGateIdentityThreshold,
    ),
    evidenceTextMaxChars: parseBoundedNumber(
      raw.evidenceTextMaxChars,
      fallback.evidenceTextMaxChars,
      RUNTIME_NUMBER_BOUNDS.evidenceTextMaxChars,
    ),
    helperSupportiveMaxSources: parseBoundedNumber(
      raw.helperSupportiveMaxSources,
      fallback.helperSupportiveMaxSources,
      RUNTIME_NUMBER_BOUNDS.helperSupportiveMaxSources,
    ),
    helperActiveSyncLimit: parseBoundedNumber(
      raw.helperActiveSyncLimit,
      fallback.helperActiveSyncLimit,
      RUNTIME_NUMBER_BOUNDS.helperActiveSyncLimit,
    ),
    fieldRewardHalfLifeDays: parseBoundedNumber(
      raw.fieldRewardHalfLifeDays,
      fallback.fieldRewardHalfLifeDays,
      RUNTIME_NUMBER_BOUNDS.fieldRewardHalfLifeDays,
    ),
    driftPollSeconds: parseBoundedNumber(
      raw.driftPollSeconds,
      fallback.driftPollSeconds,
      RUNTIME_NUMBER_BOUNDS.driftPollSeconds,
    ),
    driftScanMaxProducts: parseBoundedNumber(
      raw.driftScanMaxProducts,
      fallback.driftScanMaxProducts,
      RUNTIME_NUMBER_BOUNDS.driftScanMaxProducts,
    ),
    reCrawlStaleAfterDays: parseBoundedNumber(
      raw.reCrawlStaleAfterDays,
      fallback.reCrawlStaleAfterDays,
      RUNTIME_NUMBER_BOUNDS.reCrawlStaleAfterDays,
    ),
    cortexSyncTimeoutMs: parseBoundedNumber(
      raw.cortexSyncTimeoutMs,
      fallback.cortexSyncTimeoutMs,
      RUNTIME_NUMBER_BOUNDS.cortexSyncTimeoutMs,
    ),
    cortexAsyncPollIntervalMs: parseBoundedNumber(
      raw.cortexAsyncPollIntervalMs,
      fallback.cortexAsyncPollIntervalMs,
      RUNTIME_NUMBER_BOUNDS.cortexAsyncPollIntervalMs,
    ),
    cortexAsyncMaxWaitMs: parseBoundedNumber(
      raw.cortexAsyncMaxWaitMs,
      fallback.cortexAsyncMaxWaitMs,
      RUNTIME_NUMBER_BOUNDS.cortexAsyncMaxWaitMs,
    ),
    cortexEnsureReadyTimeoutMs: parseBoundedNumber(
      raw.cortexEnsureReadyTimeoutMs,
      fallback.cortexEnsureReadyTimeoutMs,
      RUNTIME_NUMBER_BOUNDS.cortexEnsureReadyTimeoutMs,
    ),
    cortexStartReadyTimeoutMs: parseBoundedNumber(
      raw.cortexStartReadyTimeoutMs,
      fallback.cortexStartReadyTimeoutMs,
      RUNTIME_NUMBER_BOUNDS.cortexStartReadyTimeoutMs,
    ),
    cortexFailureThreshold: parseBoundedNumber(
      raw.cortexFailureThreshold,
      fallback.cortexFailureThreshold,
      RUNTIME_NUMBER_BOUNDS.cortexFailureThreshold,
    ),
    cortexCircuitOpenMs: parseBoundedNumber(
      raw.cortexCircuitOpenMs,
      fallback.cortexCircuitOpenMs,
      RUNTIME_NUMBER_BOUNDS.cortexCircuitOpenMs,
    ),
    cortexEscalateConfidenceLt: parseBoundedNumber(
      raw.cortexEscalateConfidenceLt,
      fallback.cortexEscalateConfidenceLt,
      RUNTIME_NUMBER_BOUNDS.cortexEscalateConfidenceLt,
    ),
    cortexMaxDeepFieldsPerProduct: parseBoundedNumber(
      raw.cortexMaxDeepFieldsPerProduct,
      fallback.cortexMaxDeepFieldsPerProduct,
      RUNTIME_NUMBER_BOUNDS.cortexMaxDeepFieldsPerProduct,
    ),
    userAgent: parseString(raw.userAgent, fallback.userAgent, true),
    pdfPreferredBackend: parseString(raw.pdfPreferredBackend, fallback.pdfPreferredBackend, true),
    capturePageScreenshotFormat: parseString(raw.capturePageScreenshotFormat, fallback.capturePageScreenshotFormat, true),
    capturePageScreenshotSelectors: parseString(raw.capturePageScreenshotSelectors, fallback.capturePageScreenshotSelectors, true),
    runtimeScreenshotMode: parseString(raw.runtimeScreenshotMode, fallback.runtimeScreenshotMode, true),
    runtimeControlFile: parseString(raw.runtimeControlFile, fallback.runtimeControlFile, true),
    staticDomMode: parseString(raw.staticDomMode, fallback.staticDomMode, true),
    specDbDir: parseString(raw.specDbDir, fallback.specDbDir, true),
    articleExtractorDomainPolicyMapJson: parseString(raw.articleExtractorDomainPolicyMapJson, fallback.articleExtractorDomainPolicyMapJson, true),
    structuredMetadataExtructUrl: parseString(raw.structuredMetadataExtructUrl, fallback.structuredMetadataExtructUrl, true),
    cortexBaseUrl: parseString(raw.cortexBaseUrl, fallback.cortexBaseUrl, true),
    cortexApiKey: parseString(raw.cortexApiKey, fallback.cortexApiKey, true),
    cortexAsyncBaseUrl: parseString(raw.cortexAsyncBaseUrl, fallback.cortexAsyncBaseUrl, true),
    cortexAsyncSubmitPath: parseString(raw.cortexAsyncSubmitPath, fallback.cortexAsyncSubmitPath, true),
    cortexAsyncStatusPath: parseString(raw.cortexAsyncStatusPath, fallback.cortexAsyncStatusPath, true),
    cortexModelFast: parseString(raw.cortexModelFast, fallback.cortexModelFast, true),
    cortexModelDom: parseString(raw.cortexModelDom, fallback.cortexModelDom, true),
    cortexModelReasoningDeep: parseString(raw.cortexModelReasoningDeep, fallback.cortexModelReasoningDeep, true),
    cortexModelVision: parseString(raw.cortexModelVision, fallback.cortexModelVision, true),
    cortexModelSearchFast: parseString(raw.cortexModelSearchFast, fallback.cortexModelSearchFast, true),
    cortexModelRerankFast: parseString(raw.cortexModelRerankFast, fallback.cortexModelRerankFast, true),
    categoryAuthorityRoot: parseString(
      raw.categoryAuthorityRoot ?? raw.helperFilesRoot,
      fallback.categoryAuthorityRoot,
      true,
    ),
    helperFilesRoot: parseString(
      raw.helperFilesRoot ?? raw.categoryAuthorityRoot,
      fallback.helperFilesRoot,
      true,
    ),
    batchStrategy: parseString(raw.batchStrategy, fallback.batchStrategy, true),
    dynamicFetchPolicyMapJson: parseString(raw.dynamicFetchPolicyMapJson, fallback.dynamicFetchPolicyMapJson, true),
    searchProfileCapMapJson: parseString(raw.searchProfileCapMapJson, fallback.searchProfileCapMapJson, true),
    serpRerankerWeightMapJson: parseString(raw.serpRerankerWeightMapJson, fallback.serpRerankerWeightMapJson, true),
    fetchSchedulerInternalsMapJson: parseString(raw.fetchSchedulerInternalsMapJson, fallback.fetchSchedulerInternalsMapJson, true),
    retrievalInternalsMapJson: parseString(raw.retrievalInternalsMapJson, fallback.retrievalInternalsMapJson, true),
    evidencePackLimitsMapJson: parseString(raw.evidencePackLimitsMapJson, fallback.evidencePackLimitsMapJson, true),
    parsingConfidenceBaseMapJson: parseString(raw.parsingConfidenceBaseMapJson, fallback.parsingConfidenceBaseMapJson, true),
    repairDedupeRule: parseString(raw.repairDedupeRule, fallback.repairDedupeRule, true) as RuntimeRepairDedupeRule,
    automationQueueStorageEngine: parseString(
      raw.automationQueueStorageEngine,
      fallback.automationQueueStorageEngine,
      true,
    ) as RuntimeAutomationQueueStorageEngine,
    scannedPdfOcrEnabled: parseBoolean(raw.scannedPdfOcrEnabled, fallback.scannedPdfOcrEnabled),
    scannedPdfOcrPromoteCandidates: parseBoolean(raw.scannedPdfOcrPromoteCandidates, fallback.scannedPdfOcrPromoteCandidates),
    llmExtractionCacheEnabled: parseBoolean(raw.llmExtractionCacheEnabled, fallback.llmExtractionCacheEnabled),
    llmExtractSkipLowSignal: parseBoolean(raw.llmExtractSkipLowSignal, fallback.llmExtractSkipLowSignal),
    llmReasoningMode: parseBoolean(raw.llmReasoningMode, fallback.llmReasoningMode),
    llmDisableBudgetGuards: parseBoolean(raw.llmDisableBudgetGuards, fallback.llmDisableBudgetGuards),
    llmVerifyMode: parseBoolean(raw.llmVerifyMode, fallback.llmVerifyMode),
    localMode: parseBoolean(raw.localMode, fallback.localMode),
    dryRun: parseBoolean(raw.dryRun, fallback.dryRun),
    mirrorToS3: parseBoolean(raw.mirrorToS3, fallback.mirrorToS3),
    mirrorToS3Input: parseBoolean(raw.mirrorToS3Input, fallback.mirrorToS3Input),
    writeMarkdownSummary: parseBoolean(raw.writeMarkdownSummary, fallback.writeMarkdownSummary),
    llmWriteSummary: parseBoolean(raw.llmWriteSummary, fallback.llmWriteSummary),
    reextractIndexed: parseBoolean(raw.reextractIndexed, fallback.reextractIndexed),
    fetchCandidateSources: parseBoolean(raw.fetchCandidateSources, fallback.fetchCandidateSources),
    manufacturerBroadDiscovery: parseBoolean(raw.manufacturerBroadDiscovery, fallback.manufacturerBroadDiscovery),
    manufacturerSeedSearchUrls: parseBoolean(raw.manufacturerSeedSearchUrls, fallback.manufacturerSeedSearchUrls),
    manufacturerDeepResearchEnabled: parseBoolean(raw.manufacturerDeepResearchEnabled, fallback.manufacturerDeepResearchEnabled),
    pdfBackendRouterEnabled: parseBoolean(raw.pdfBackendRouterEnabled, fallback.pdfBackendRouterEnabled),
    capturePageScreenshotEnabled: parseBoolean(raw.capturePageScreenshotEnabled, fallback.capturePageScreenshotEnabled),
    runtimeCaptureScreenshots: parseBoolean(raw.runtimeCaptureScreenshots, fallback.runtimeCaptureScreenshots),
    chartExtractionEnabled: parseBoolean(raw.chartExtractionEnabled, fallback.chartExtractionEnabled),
    articleExtractorV2Enabled: parseBoolean(raw.articleExtractorV2Enabled, fallback.articleExtractorV2Enabled),
    staticDomExtractorEnabled: parseBoolean(raw.staticDomExtractorEnabled, fallback.staticDomExtractorEnabled),
    htmlTableExtractorV2: parseBoolean(raw.htmlTableExtractorV2, fallback.htmlTableExtractorV2),
    structuredMetadataExtructEnabled: parseBoolean(raw.structuredMetadataExtructEnabled, fallback.structuredMetadataExtructEnabled),
    structuredMetadataExtructCacheEnabled: parseBoolean(raw.structuredMetadataExtructCacheEnabled, fallback.structuredMetadataExtructCacheEnabled),
    categoryAuthorityEnabled: parseBoolean(
      raw.categoryAuthorityEnabled ?? raw.helperFilesEnabled,
      fallback.categoryAuthorityEnabled,
    ),
    helperSupportiveEnabled: parseBoolean(raw.helperSupportiveEnabled, fallback.helperSupportiveEnabled),
    helperSupportiveFillMissing: parseBoolean(raw.helperSupportiveFillMissing, fallback.helperSupportiveFillMissing),
    helperAutoSeedTargets: parseBoolean(raw.helperAutoSeedTargets, fallback.helperAutoSeedTargets),
    driftDetectionEnabled: parseBoolean(raw.driftDetectionEnabled, fallback.driftDetectionEnabled),
    driftAutoRepublish: parseBoolean(raw.driftAutoRepublish, fallback.driftAutoRepublish),
    cortexEnabled: parseBoolean(raw.cortexEnabled, fallback.cortexEnabled),
    cortexAsyncEnabled: parseBoolean(raw.cortexAsyncEnabled, fallback.cortexAsyncEnabled),
    cortexAutoStart: parseBoolean(raw.cortexAutoStart, fallback.cortexAutoStart),
    cortexEscalateIfConflict: parseBoolean(raw.cortexEscalateIfConflict, fallback.cortexEscalateIfConflict),
    cortexEscalateCriticalOnly: parseBoolean(raw.cortexEscalateCriticalOnly, fallback.cortexEscalateCriticalOnly),
    allowBelowPassTargetFill: parseBoolean(raw.allowBelowPassTargetFill, fallback.allowBelowPassTargetFill),
    indexingCategoryAuthorityEnabled: parseBoolean(
      raw.indexingCategoryAuthorityEnabled ?? raw.indexingHelperFilesEnabled,
      fallback.indexingCategoryAuthorityEnabled,
    ),
    discoveryEnabled: parseBoolean(raw.discoveryEnabled, fallback.discoveryEnabled),
    enableSourceRegistry: parseBoolean(raw.enableSourceRegistry, fallback.enableSourceRegistry),
    enableDomainHintResolverV2: parseBoolean(raw.enableDomainHintResolverV2, fallback.enableDomainHintResolverV2),
    enableQueryCompiler: parseBoolean(raw.enableQueryCompiler, fallback.enableQueryCompiler),
    enableCoreDeepGates: parseBoolean(raw.enableCoreDeepGates, fallback.enableCoreDeepGates),
    enableQueryIndex: parseBoolean(raw.enableQueryIndex, fallback.enableQueryIndex),
    enableUrlIndex: parseBoolean(raw.enableUrlIndex, fallback.enableUrlIndex),
    manufacturerAutoPromote: parseBoolean(raw.manufacturerAutoPromote, fallback.manufacturerAutoPromote),
    helperFilesEnabled: parseBoolean(
      raw.helperFilesEnabled ?? raw.categoryAuthorityEnabled,
      fallback.helperFilesEnabled,
    ),
    indexingHelperFilesEnabled: parseBoolean(
      raw.indexingHelperFilesEnabled ?? raw.indexingCategoryAuthorityEnabled,
      fallback.indexingHelperFilesEnabled,
    ),
    dynamicCrawleeEnabled: parseBoolean(raw.dynamicCrawleeEnabled, fallback.dynamicCrawleeEnabled),
    crawleeHeadless: parseBoolean(raw.crawleeHeadless, fallback.crawleeHeadless),
    fetchSchedulerEnabled: parseBoolean(raw.fetchSchedulerEnabled, fallback.fetchSchedulerEnabled),
    preferHttpFetcher: parseBoolean(raw.preferHttpFetcher, fallback.preferHttpFetcher),
    frontierEnableSqlite: parseBoolean(raw.frontierEnableSqlite, fallback.frontierEnableSqlite),
    frontierStripTrackingParams: parseBoolean(raw.frontierStripTrackingParams, fallback.frontierStripTrackingParams),
    frontierRepairSearchEnabled: parseBoolean(raw.frontierRepairSearchEnabled, fallback.frontierRepairSearchEnabled),
    autoScrollEnabled: parseBoolean(raw.autoScrollEnabled, fallback.autoScrollEnabled),
    graphqlReplayEnabled: parseBoolean(raw.graphqlReplayEnabled, fallback.graphqlReplayEnabled),
    robotsTxtCompliant: parseBoolean(raw.robotsTxtCompliant, fallback.robotsTxtCompliant),
    runtimeScreencastEnabled: parseBoolean(raw.runtimeScreencastEnabled, fallback.runtimeScreencastEnabled),
    runtimeTraceEnabled: parseBoolean(raw.runtimeTraceEnabled, fallback.runtimeTraceEnabled),
    runtimeTraceLlmPayloads: parseBoolean(raw.runtimeTraceLlmPayloads, fallback.runtimeTraceLlmPayloads),
    eventsJsonWrite: parseBoolean(raw.eventsJsonWrite, fallback.eventsJsonWrite),
    indexingSchemaPacketsValidationEnabled: parseBoolean(raw.indexingSchemaPacketsValidationEnabled, fallback.indexingSchemaPacketsValidationEnabled),
    indexingSchemaPacketsValidationStrict: parseBoolean(raw.indexingSchemaPacketsValidationStrict, fallback.indexingSchemaPacketsValidationStrict),
    queueJsonWrite: parseBoolean(raw.queueJsonWrite, fallback.queueJsonWrite),
    billingJsonWrite: parseBoolean(raw.billingJsonWrite, fallback.billingJsonWrite),
    intelJsonWrite: parseBoolean(raw.intelJsonWrite, fallback.intelJsonWrite),
    corpusJsonWrite: parseBoolean(raw.corpusJsonWrite, fallback.corpusJsonWrite),
    learningJsonWrite: parseBoolean(raw.learningJsonWrite, fallback.learningJsonWrite),
    cacheJsonWrite: parseBoolean(raw.cacheJsonWrite, fallback.cacheJsonWrite),
    authoritySnapshotEnabled: parseBoolean(raw.authoritySnapshotEnabled, fallback.authoritySnapshotEnabled),
    selfImproveEnabled: parseBoolean(raw.selfImproveEnabled, fallback.selfImproveEnabled),
  };
}



