import type { RuntimeStepId } from '../components/RuntimeFlowStepIcon';

export type { RuntimeStepId } from '../components/RuntimeFlowStepIcon';

export interface RuntimeStepEntry {
  id: RuntimeStepId;
  phase: string;
  label: string;
  tip: string;
  options: readonly string[];
}

export interface RuntimeSubStepEntry {
  id: string;
  label: string;
  tip: string;
}

export const RUNTIME_STEP_IDS: readonly RuntimeStepId[] = [
  'run-setup',
  'run-output',
  'scoring-evidence',
  'automation',
  'observability-trace',
  'fetch-network',
  'browser-rendering',
  'parsing',
  'ocr',
  'planner-triage',
  'llm-cortex',
] as const;

export const RUNTIME_STEPS: RuntimeStepEntry[] = [
  {
    id: 'run-setup',
    phase: '01',
    label: 'Run Setup',
    tip: 'Pipeline bootstrap profile, discovery, and resume policy.',
    options: [
      'Discovery Enabled',
      'Source Registry',
      'Domain Hint Resolver v2',
      'Query Compiler',
      'Core / Deep Gates',
      'Search Route',
      'SearXNG Base URL',
      'Fetch Candidate Sources',
      'Discovery Max Queries',
      'Discovery Results / Query',
      'Discovery Max Discovered',
      'Discovery Query Concurrency',
      'Search Profile Caps Map (JSON)',
      'Manufacturer Broad Discovery',
      'Manufacturer Seed Search URLs',
      'Manufacturer Deep Research Enabled',
      'Max URLs / Product',
      'Max Candidate URLs',
      'Max Pages / Domain',
      'Max Run Seconds',
      'Max JSON Bytes',
      'Max Manufacturer URLs / Product',
      'Max Manufacturer Pages / Domain',
      'Manufacturer Reserve URLs',
      'User Agent',
      'Resume Mode',
      'Resume Window (hours)',
      'Re-extract Indexed',
      'Re-extract Age (hours)',
      'Convergence Identity Fail-Fast Rounds',
    ],
  },
  {
    id: 'run-output',
    phase: '01B',
    label: 'Runtime Outputs',
    tip: 'Output destinations, provider credentials, and planner/runtime endpoint overrides.',
    options: [
      'Output Mode',
      'Local Mode',
      'Dry Run',
      'Mirror To S3',
      'Mirror To S3 Input',
      'Local Input Root',
      'Local Output Root',
      'Runtime Events Key',
      'Write Markdown Summary',
      'AWS Region',
      'S3 Bucket',
      'S3 Input Prefix',
      'S3 Output Prefix',
      'ELO Supabase Anon Key',
      'ELO Supabase Endpoint',
      'LLM Enabled',
      'LLM Write Summary',
      'LLM Provider',
      'LLM Base URL',
      'OpenAI API Key',
      'Anthropic API Key',
      'Runtime Control File',
      'LLM Plan Provider',
      'LLM Plan Base URL',
    ],
  },
  {
    id: 'scoring-evidence',
    phase: '02',
    label: 'Scoring and Evidence',
    tip: 'NeedSet scoring, identity gate, consensus engine, and retrieval weights.',
    options: [
      'NeedSet Required Weight (Identity)',
      'NeedSet Required Weight (Critical)',
      'NeedSet Missing Multiplier',
      'NeedSet Identity Lock Threshold',
      'Identity Gate Publish Threshold',
      'Identity Gate Base Match Threshold',
      'Quality Gate Identity Threshold',
      'Consensus Weighted Majority Threshold',
      'Consensus Strict Acceptance Domain Count',
      'Consensus Confidence Scoring Base',
      'Consensus Pass Target (Identity/Strong)',
      'Allow Below Pass-Target Fill',
      'Retrieval Tier Weight (Tier 1)',
      'Evidence Text Max Chars',
    ],
  },
  {
    id: 'automation',
    phase: '02B',
    label: 'Automation',
    tip: 'Drift detection, self-improvement, and helper runtime.',
    options: [
      'Drift Detection Enabled',
      'Drift Poll Seconds',
      'Drift Scan Max Products',
      'Self Improve Enabled',
      'Batch Strategy',
      'Helper Files Enabled',
      'Helper Supportive Enabled',
    ],
  },
  {
    id: 'observability-trace',
    phase: '02',
    label: 'Observability and Trace',
    tip: 'Runtime trace, event stream, and screencast diagnostics.',
    options: [
      'Runtime Trace Enabled',
      'Fetch Trace Ring Size',
      'LLM Trace Ring Size',
      'Trace LLM Payloads',
      'Events NDJSON Write',
      'Indexing Resume Seed Limit',
      'Indexing Resume Persist Limit',
      'Indexing Schema Validation Enabled',
      'Indexing Schema Validation Strict',
      'Re-Crawl Stale After (days)',
      'Daemon Concurrency',
      'Daemon Graceful Shutdown Timeout (ms)',
      'Imports Root',
      'Imports Poll Seconds',
      'Queue JSON Write',
      'Billing JSON Write',
      'Intel JSON Write',
      'Corpus JSON Write',
      'Learning JSON Write',
      'Cache JSON Write',
      'Authority Snapshot Enabled',
      'Runtime Screencast Enabled',
      'Runtime Screencast FPS',
      'Runtime Screencast Quality',
      'Runtime Screencast Max Width',
      'Runtime Screencast Max Height',
    ],
  },
  {
    id: 'fetch-network',
    phase: '03',
    label: 'Fetch and Network',
    tip: 'Fetch throughput, scheduler pacing, frontier cooldown, and repair controls.',
    options: [
      'Fetch Scheduler Enabled',
      'Fetch Concurrency',
      'Per Host Min Delay (ms)',
      'Fetch Per-Host Concurrency Cap',
      'Prefer HTTP Fetcher',
      'Frontier Repair Search Enabled',
      'Frontier Query Cooldown (sec)',
      'Frontier SQLite Enabled',
      'Repair Dedupe Rule',
      'Automation Queue Storage Engine',
    ],
  },
  {
    id: 'browser-rendering',
    phase: '03B',
    label: 'Browser and Rendering',
    tip: 'Dynamic browser rendering, scroll/replay, screenshots, and visual asset capture.',
    options: [
      'Dynamic Crawlee Enabled',
      'Crawlee Headless',
      'Page Goto Timeout (ms)',
      'Page Network Idle Timeout (ms)',
      'Post Load Wait (ms)',
      'Auto Scroll Enabled',
      'GraphQL Replay Enabled',
      'Robots.txt Compliant',
      'Capture Page Screenshot Enabled',
      'Runtime Capture Screenshots',
    ],
  },
  {
    id: 'parsing',
    phase: '03C',
    label: 'Parsing',
    tip: 'PDF processing, article extraction, DOM parsing, and structured metadata.',
    options: [
      'PDF Router Enabled',
      'PDF Preferred Backend',
      'Max PDF Bytes',
      'Article Extractor V2 Enabled',
      'Static DOM Extractor Enabled',
      'Structured Metadata Extruct Enabled',
      'HTML Table Extractor V2',
      'Chart Extraction Enabled',
    ],
  },
  {
    id: 'ocr',
    phase: '04',
    label: 'OCR',
    tip: 'Scanned PDF OCR activation and evidence promotion rules.',
    options: [
      'OCR Enabled',
      'Promote OCR Candidates',
      'OCR Backend',
      'OCR Max Pages',
      'OCR Max Pairs',
      'OCR Min Chars / Page',
      'OCR Min Lines / Page',
      'OCR Min Confidence',
    ],
  },
  {
    id: 'planner-triage',
    phase: '05',
    label: 'Search & Reranker',
    tip: 'Search planner, LLM discovery queries, and SERP reranker scoring policy.',
    options: [
      'Planner Enabled',
      'LLM Discovery Queries',
      'Search Profile Caps Map (JSON)',
      'SERP Reranker Weight Map (JSON)',
    ],
  },
  {
    id: 'llm-cortex',
    phase: '06',
    label: 'LLM & Cortex',
    tip: 'Unified LLM model routing, token caps, fallbacks, budgets, verification, cache, and Cortex sidecar configuration.',
    options: [
      'Plan Model',
      'Plan Token Cap',
      'Triage Model',
      'Triage Token Cap',
      'Fast Model',
      'Fast Token Cap',
      'Reasoning Model',
      'Reasoning Token Cap',
      'Extract Model',
      'Extract Token Cap',
      'Validate Model',
      'Validate Token Cap',
      'Write Model',
      'Write Token Cap',
      'Plan Fallback Token Cap',
      'LLM Plan API Key',
      'Extract Fallback Token Cap',
      'Validate Fallback Token Cap',
      'Write Fallback Token Cap',
      'LLM Max Calls / Product Total',
      'LLM Max Calls / Product Fast',
      'LLM Monthly Budget (USD)',
      'LLM Per-Product Budget (USD)',
      'LLM Max Calls / Round',
      'LLM Max Output Tokens',
      'LLM Timeout (ms)',
      'CORTEX Enabled',
      'CORTEX Base URL',
      'CORTEX API Key',
      'CORTEX Model Fast',
    ],
  },
];

export const RUNTIME_SUB_STEPS: Record<RuntimeStepId, RuntimeSubStepEntry[]> = {
  'run-setup': [
    {
      id: 'run-setup-discovery',
      label: 'Discovery',
      tip: 'Search routing and discovery caps.',
    },
    {
      id: 'run-setup-budgets',
      label: 'URL Budgets',
      tip: 'URL budget caps, runtime timeout, and user agent controls.',
    },
    {
      id: 'run-setup-manufacturer',
      label: 'Manufacturer Discovery',
      tip: 'Manufacturer-specific deep research and URL reserve controls.',
    },
    {
      id: 'run-setup-results',
      label: 'Discovery Results',
      tip: 'Discovery query counts and result caps.',
    },
    {
      id: 'run-setup-resume',
      label: 'Resume and Re-extract',
      tip: 'Resume strategy plus stale indexed-source re-extraction controls.',
    },
  ],
  'run-output': [
    {
      id: 'run-output-destinations',
      label: 'Output Destinations',
      tip: 'Output mode, local/S3 paths, and artifact destination controls.',
    },
    {
      id: 'run-output-providers',
      label: 'Provider and Runtime Keys',
      tip: 'Runtime provider endpoints, API keys, and planner endpoint overrides.',
    },
  ],
  'scoring-evidence': [
    {
      id: 'scoring-evidence-needset',
      label: 'NeedSet Scoring',
      tip: 'NeedSet weight multipliers, identity lock, and evidence decay controls.',
    },
    {
      id: 'scoring-evidence-identity',
      label: 'Identity Gate',
      tip: 'Identity gate thresholds and quality gate controls for source matching and publish gating.',
    },
    {
      id: 'scoring-evidence-consensus',
      label: 'Consensus Engine',
      tip: 'Consensus method weights, majority threshold, and pass-target controls.',
    },
    {
      id: 'scoring-evidence-retrieval',
      label: 'Retrieval and Evidence',
      tip: 'Retrieval tier/doc/method weights, anchor scoring, and evidence pack controls.',
    },
  ],
  'automation': [
    {
      id: 'automation-drift',
      label: 'Drift Detection',
      tip: 'Drift scanning cadence and auto-republish controls.',
    },
    {
      id: 'automation-learning',
      label: 'Self-Improvement',
      tip: 'Learning confidence, hypothesis queue, and endpoint signal controls.',
    },
    {
      id: 'automation-helper',
      label: 'Helper Runtime',
      tip: 'Helper-file runtime sourcing and supportive-fill policy.',
    },
  ],
  'observability-trace': [
    {
      id: 'observability-trace-core',
      label: 'Trace Core',
      tip: 'Runtime trace capture and event ring configuration.',
    },
    {
      id: 'observability-trace-daemon',
      label: 'Daemon and Imports',
      tip: 'Daemon runtime limits and import watcher controls.',
    },
    {
      id: 'observability-trace-outputs',
      label: 'Diagnostic Outputs',
      tip: 'Dual-write diagnostics, snapshots, and screencast stream controls.',
    },
  ],
  'fetch-network': [
    {
      id: 'fetch-network-throughput',
      label: 'Core Throughput',
      tip: 'Fetch concurrency, scheduler pacing, and RPS/burst controls.',
    },
    {
      id: 'fetch-network-frontier',
      label: 'Frontier and Repair',
      tip: 'Frontier cooldown, dedupe, queue engine, and repair controls.',
    },
  ],
  'browser-rendering': [
    {
      id: 'browser-rendering-core',
      label: 'Browser Core',
      tip: 'Dynamic crawlee, headless mode, and page timeout controls.',
    },
    {
      id: 'browser-rendering-scroll',
      label: 'Scroll and Replay',
      tip: 'Auto-scroll, GraphQL replay, and robots compliance controls.',
    },
    {
      id: 'browser-rendering-screenshots',
      label: 'Screenshots',
      tip: 'Page screenshot capture format, quality, and selector controls.',
    },
  ],
  'parsing': [
    {
      id: 'parsing-pdf',
      label: 'PDF Processing',
      tip: 'PDF backend routing, page limits, and text preview controls.',
    },
    {
      id: 'parsing-article',
      label: 'Article Extraction',
      tip: 'Article extractor enablement, score, and char limit controls.',
    },
    {
      id: 'parsing-dom',
      label: 'Static DOM',
      tip: 'Static DOM extraction mode, threshold, and snippet controls.',
    },
    {
      id: 'parsing-metadata',
      label: 'Structured Metadata',
      tip: 'Extruct URL, timeout, caching, and item limit controls.',
    },
  ],
  ocr: [
    {
      id: 'ocr-activation',
      label: 'Activation',
      tip: 'OCR enablement, promotion policy, and backend selection controls.',
    },
    {
      id: 'ocr-thresholds',
      label: 'Sampling Thresholds',
      tip: 'OCR page/pair/quality thresholds for evidence promotion.',
    },
  ],
  'planner-triage': [
    { id: 'planner-triage-reranker', label: 'Reranker Policy', tip: 'SERP reranker weight map and deterministic scoring policy controls.' },
  ],
  'llm-cortex': [
    { id: 'llm-cortex-models', label: 'Primary Models', tip: 'Per-lane model and token cap routing.' },
    { id: 'llm-cortex-fallback', label: 'Fallback Routing', tip: 'Fallback models, tokens, and call caps.' },
    { id: 'llm-cortex-budgets', label: 'Budgets & Cost', tip: 'LLM spend limits and cost tracking.' },
    { id: 'llm-cortex-extraction', label: 'Extraction & Reasoning', tip: 'Extract limits, reasoning mode.' },
    { id: 'llm-cortex-verification', label: 'Verification', tip: 'Verification mode and sampling.' },
    { id: 'llm-cortex-cache', label: 'Cache', tip: 'Extraction cache settings.' },
    { id: 'llm-cortex-cortex', label: 'Cortex Sidecar', tip: 'Cortex connection, models, escalation.' },
    { id: 'llm-cortex-limits', label: 'Global Limits', tip: 'Global token and batch limits.' },
  ],
};
