import type {
  RuntimeOcrBackend,
  RuntimeProfile,
  RuntimeRepairDedupeRule,
  RuntimeResumeMode,
} from '../../../stores/settingsManifest';
import type { RuntimeSettingsNumericBaseline } from './runtimeSettingsAuthority';

type RuntimeStringHydrationBinding = {
  key: string;
  allowEmpty?: boolean;
  apply: (value: string) => void;
};

type RuntimeNumberHydrationBinding = {
  key: string;
  apply: (value: number) => void;
};

type RuntimeBooleanHydrationBinding = {
  key: string;
  apply: (value: boolean) => void;
};

export interface RuntimeHydrationBindings {
  stringBindings: RuntimeStringHydrationBinding[];
  numberBindings: RuntimeNumberHydrationBinding[];
  booleanBindings: RuntimeBooleanHydrationBinding[];
}

export interface RuntimeHydrationBindingSetters {
  setProfile: (value: RuntimeProfile) => void;
  setSearchEngines: (value: string) => void;
  setSearchEnginesFallback: (value: string) => void;
  setSearxngBaseUrl: (value: string) => void;
  setLlmPlanApiKey: (value: string) => void;
  setLlmModelPlan: (value: string) => void;
  setLlmModelReasoning: (value: string) => void;
  setLlmPlanFallbackModel: (value: string) => void;
  setLlmReasoningFallbackModel: (value: string) => void;
  setLlmExtractMaxTokens: (value: string) => void;
  setLlmExtractMaxSnippetsPerBatch: (value: string) => void;
  setLlmExtractMaxSnippetChars: (value: string) => void;
  setLlmExtractReasoningBudget: (value: string) => void;
  setLlmReasoningBudget: (value: string) => void;
  setLlmMonthlyBudgetUsd: (value: string) => void;
  setLlmPerProductBudgetUsd: (value: string) => void;
  setLlmMaxCallsPerRound: (value: string) => void;
  setLlmMaxOutputTokens: (value: string) => void;
  setLlmVerifySampleRate: (value: string) => void;
  setLlmMaxBatchesPerProduct: (value: string) => void;
  setLlmMaxEvidenceChars: (value: string) => void;
  setLlmMaxTokens: (value: string) => void;
  setLlmTimeoutMs: (value: string) => void;
  setLlmCostInputPer1M: (value: string) => void;
  setLlmCostOutputPer1M: (value: string) => void;
  setLlmCostCachedInputPer1M: (value: string) => void;
  setLocalInputRoot: (value: string) => void;
  setLocalOutputRoot: (value: string) => void;
  setRuntimeEventsKey: (value: string) => void;
  setAwsRegion: (value: string) => void;
  setS3Bucket: (value: string) => void;
  setS3InputPrefix: (value: string) => void;
  setS3OutputPrefix: (value: string) => void;
  setEloSupabaseAnonKey: (value: string) => void;
  setEloSupabaseEndpoint: (value: string) => void;
  setLlmProvider: (value: string) => void;
  setLlmBaseUrl: (value: string) => void;
  setOpenaiApiKey: (value: string) => void;
  setAnthropicApiKey: (value: string) => void;
  setGeminiApiKey: (value: string) => void;
  setDeepseekApiKey: (value: string) => void;
  setResumeMode: (value: RuntimeResumeMode) => void;
  setImportsRoot: (value: string) => void;
  setScannedPdfOcrBackend: (value: RuntimeOcrBackend) => void;
  setDynamicFetchPolicyMapJson: (value: string) => void;
  setSearchProfileCapMapJson: (value: string) => void;
  setSerpRerankerWeightMapJson: (value: string) => void;
  setLlmProviderRegistryJson?: (value: string) => void;
  setLlmPhaseOverridesJson?: (value: string) => void;
  setFetchSchedulerInternalsMapJson?: (value: string) => void;
  setParsingConfidenceBaseMapJson?: (value: string) => void;
  setRepairDedupeRule?: (value: RuntimeRepairDedupeRule) => void;
  setFetchConcurrency: (value: string) => void;
  setFetchBudgetMs?: (value: string) => void;
  setPerHostMinDelayMs: (value: string) => void;
  setSearxngMinQueryIntervalMs: (value: string) => void;
  setGoogleSearchProxyUrlsJson: (value: string) => void;
  setGoogleSearchTimeoutMs: (value: string) => void;
  setGoogleSearchMinQueryIntervalMs: (value: string) => void;
  setGoogleSearchMaxRetries: (value: string) => void;
  setGoogleSearchScreenshotsEnabled: (value: boolean) => void;
  setSerperApiKey: (value: string) => void;
  setSerperResultCount: (value: string) => void;
  setSearchMaxRetries: (value: string) => void;
  setDomainRequestRps: (value: string) => void;
  setDomainRequestBurst: (value: string) => void;
  setGlobalRequestRps: (value: string) => void;
  setGlobalRequestBurst: (value: string) => void;
  setFetchPerHostConcurrencyCap: (value: string) => void;
  setLlmMaxOutputTokensPlan: (value: number) => void;
  setLlmMaxOutputTokensReasoning: (value: number) => void;
  setLlmMaxOutputTokensPlanFallback: (value: number) => void;
  setLlmMaxOutputTokensReasoningFallback: (value: number) => void;
  setResumeWindowHours: (value: string) => void;
  setReextractAfterHours: (value: string) => void;
  setScannedPdfOcrMaxPages: (value: string) => void;
  setScannedPdfOcrMaxPairs: (value: string) => void;
  setScannedPdfOcrMinCharsPerPage: (value: string) => void;
  setScannedPdfOcrMinLinesPerPage: (value: string) => void;
  setScannedPdfOcrMinConfidence: (value: string) => void;
  setCrawleeRequestHandlerTimeoutSecs: (value: string) => void;
  setDynamicFetchRetryBudget: (value: string) => void;
  setDynamicFetchRetryBackoffMs: (value: string) => void;
  setFetchSchedulerMaxRetries: (value: string) => void;
  setPageGotoTimeoutMs: (value: string) => void;
  setPageNetworkIdleTimeoutMs: (value: string) => void;
  setPostLoadWaitMs: (value: string) => void;
  setFrontierDbPath: (value: string) => void;
  setFrontierQueryCooldownSeconds: (value: string) => void;
  setFrontierCooldown404Seconds: (value: string) => void;
  setFrontierCooldown404RepeatSeconds: (value: string) => void;
  setFrontierCooldown410Seconds: (value: string) => void;
  setFrontierCooldownTimeoutSeconds: (value: string) => void;
  setFrontierCooldown403BaseSeconds: (value: string) => void;
  setFrontierCooldown429BaseSeconds: (value: string) => void;
  setFrontierBackoffMaxExponent: (value: string) => void;
  setFrontierPathPenaltyNotfoundThreshold: (value: string) => void;
  setFrontierBlockedDomainThreshold: (value: string) => void;
  setAutoScrollPasses: (value: string) => void;
  setAutoScrollDelayMs: (value: string) => void;
  setMaxGraphqlReplays: (value: string) => void;
  setMaxNetworkResponsesPerPage: (value: string) => void;
  setRobotsTxtTimeoutMs: (value: string) => void;
  setEndpointSignalLimit: (value: string) => void;
  setEndpointSuggestionLimit: (value: string) => void;
  setEndpointNetworkScanLimit: (value: string) => void;
  setDiscoveryMaxQueries: (value: string) => void;
  setDiscoveryMaxDiscovered: (value: string) => void;
  setMaxUrlsPerProduct: (value: string) => void;
  setMaxCandidateUrls: (value: string) => void;
  setSerpTriageMaxUrls?: (value: string) => void;
  setMaxPagesPerDomain: (value: string) => void;
  setMaxRunSeconds: (value: string) => void;
  setMaxJsonBytes: (value: string) => void;
  setMaxPdfBytes: (value: string) => void;
  setPdfBackendRouterTimeoutMs: (value: string) => void;
  setPdfBackendRouterMaxPages: (value: string) => void;
  setPdfBackendRouterMaxPairs: (value: string) => void;
  setPdfBackendRouterMaxTextPreviewChars: (value: string) => void;
  setCapturePageScreenshotQuality: (value: string) => void;
  setCapturePageScreenshotMaxBytes: (value: string) => void;
  setArticleExtractorMinChars: (value: string) => void;
  setArticleExtractorMinScore: (value: string) => void;
  setArticleExtractorMaxChars: (value: string) => void;
  setStaticDomTargetMatchThreshold: (value: string) => void;
  setStaticDomMaxEvidenceSnippets: (value: string) => void;
  setDomSnippetMaxChars: (value: string) => void;
  setLlmExtractionCacheTtlMs: (value: string) => void;
  setLlmMaxCallsPerProductTotal: (value: string) => void;
  setMaxHypothesisItems: (value: string) => void;
  setHypothesisAutoFollowupRounds: (value: string) => void;
  setHypothesisFollowupUrlsPerRound: (value: string) => void;
  setUserAgent: (value: string) => void;
  setPdfPreferredBackend: (value: string) => void;
  setCapturePageScreenshotFormat: (value: string) => void;
  setCapturePageScreenshotSelectors: (value: string) => void;
  setStaticDomMode: (value: string) => void;
  setSpecDbDir: (value: string) => void;
  setArticleExtractorDomainPolicyMapJson: (value: string) => void;
  setLlmExtractionCacheDir: (value: string) => void;
  setRuntimeScreencastFps: (value: string) => void;
  setRuntimeScreencastQuality: (value: string) => void;
  setRuntimeScreencastMaxWidth: (value: string) => void;
  setRuntimeScreencastMaxHeight: (value: string) => void;
  setRuntimeTraceFetchRing: (value: string) => void;
  setRuntimeTraceLlmRing: (value: string) => void;
  setDaemonConcurrency: (value: string) => void;
  setImportsPollSeconds: (value: string) => void;
  setIndexingResumeSeedLimit: (value: string) => void;
  setIndexingResumePersistLimit: (value: string) => void;
  setFieldRewardHalfLifeDays: (value: string) => void;
  setDriftPollSeconds: (value: string) => void;
  setDriftScanMaxProducts: (value: string) => void;
  setReCrawlStaleAfterDays: (value: string) => void;
  setDiscoveryEnabled: (value: boolean) => void;

  setReextractIndexed: (value: boolean) => void;
  setFetchCandidateSources: (value: boolean) => void;
  setManufacturerAutoPromote?: (value: boolean) => void;
  setPdfBackendRouterEnabled: (value: boolean) => void;
  setCapturePageScreenshotEnabled: (value: boolean) => void;



  setCategoryAuthorityEnabled: (value: boolean) => void;
  setIndexingCategoryAuthorityEnabled: (value: boolean) => void;
  setHelperSupportiveFillMissing: (value: boolean) => void;
  setDriftDetectionEnabled: (value: boolean) => void;
  setDriftAutoRepublish: (value: boolean) => void;
  setScannedPdfOcrEnabled: (value: boolean) => void;

  setDynamicCrawleeEnabled: (value: boolean) => void;
  setCrawleeHeadless: (value: boolean) => void;
  setLlmExtractSkipLowSignal: (value: boolean) => void;
  setLlmReasoningMode: (value: boolean) => void;
  setLlmPlanUseReasoning: (value: boolean) => void;
  setLlmVerifyMode: (value: boolean) => void;
  setLocalMode: (value: boolean) => void;
  setDryRun: (value: boolean) => void;
  setMirrorToS3: (value: boolean) => void;
  setMirrorToS3Input: (value: boolean) => void;
  setWriteMarkdownSummary: (value: boolean) => void;
  setLlmWriteSummary: (value: boolean) => void;

  setPreferHttpFetcher: (value: boolean) => void;

  setFrontierStripTrackingParams: (value: boolean) => void;

  setAutoScrollEnabled: (value: boolean) => void;
  setGraphqlReplayEnabled: (value: boolean) => void;
  setRobotsTxtCompliant: (value: boolean) => void;
  setRuntimeScreencastEnabled: (value: boolean) => void;
  setRuntimeTraceEnabled: (value: boolean) => void;
  setRuntimeTraceLlmPayloads: (value: boolean) => void;
  setEventsJsonWrite: (value: boolean) => void;
  setIndexingSchemaPacketsValidationEnabled: (value: boolean) => void;
  setIndexingSchemaPacketsValidationStrict: (value: boolean) => void;

  setSelfImproveEnabled: (value: boolean) => void;
  setOutputMode: (value: string) => void;
  setLlmPlanProvider: (value: string) => void;
  setLlmPlanBaseUrl: (value: string) => void;
  setRuntimeControlFile: (value: string) => void;
  setHelperFilesRoot: (value: string) => void;
  setBatchStrategy: (value: string) => void;
}

export interface RuntimeModelTokenDefaults {
  default_output_tokens: number;
  max_output_tokens: number;
}

export type RuntimeModelTokenDefaultsResolver = (
  model: string,
) => RuntimeModelTokenDefaults;

export interface RuntimeSettingsPayloadSerializerInput {
  searchEngines: string;
  searchEnginesFallback: string;
  searxngBaseUrl: string;
  llmPlanApiKey: string;
  llmModelPlan: string;
  llmModelReasoning: string;
  llmExtractMaxSnippetsPerBatch: number | string;
  llmExtractMaxSnippetChars: number | string;
  llmReasoningBudget: number | string;
  llmMonthlyBudgetUsd: number | string;
  llmPerProductBudgetUsd: number | string;
  llmMaxCallsPerRound: number | string;
  llmMaxOutputTokens: number | string;
  llmVerifySampleRate: number | string;
  llmMaxBatchesPerProduct: number | string;
  llmMaxEvidenceChars: number | string;
  llmMaxTokens: number | string;
  llmTimeoutMs: number | string;
  llmCostInputPer1M: number | string;
  llmCostOutputPer1M: number | string;
  llmCostCachedInputPer1M: number | string;
  llmPlanFallbackModel?: string;
  llmReasoningFallbackModel?: string;
  outputMode: string;
  localInputRoot: string;
  localOutputRoot: string;
  runtimeEventsKey: string;
  awsRegion?: string;
  s3Bucket?: string;
  s3InputPrefix: string;
  s3OutputPrefix: string;
  eloSupabaseAnonKey: string;
  eloSupabaseEndpoint: string;
  llmProvider: string;
  llmBaseUrl: string;
  openaiApiKey: string;
  anthropicApiKey: string;
  geminiApiKey: string;
  deepseekApiKey: string;
  llmPlanProvider: string;
  llmPlanBaseUrl: string;
  importsRoot: string;
  resumeMode: RuntimeResumeMode | string;
  scannedPdfOcrBackend: RuntimeOcrBackend | string;
  fetchBudgetMs?: number | string;
  fetchConcurrency: number | string;
  perHostMinDelayMs: number | string;
  searxngMinQueryIntervalMs: number | string;
  googleSearchProxyUrlsJson: string;
  googleSearchTimeoutMs: number | string;
  googleSearchMinQueryIntervalMs: number | string;
  googleSearchMaxRetries: number | string;
  googleSearchScreenshotsEnabled: boolean;
  serperApiKey: string;
  serperResultCount: number | string;
  searchMaxRetries: number | string;
  domainRequestRps: number | string;
  domainRequestBurst: number | string;
  globalRequestRps: number | string;
  globalRequestBurst: number | string;
  fetchPerHostConcurrencyCap: number | string;
  llmMaxOutputTokensPlan: number | string;
  llmMaxOutputTokensReasoning: number | string;
  llmMaxOutputTokensPlanFallback: number | string;
  llmMaxOutputTokensReasoningFallback: number | string;
  llmExtractionCacheTtlMs: number | string;
  llmMaxCallsPerProductTotal: number | string;
  resumeWindowHours: number | string;
  reextractAfterHours: number | string;
  scannedPdfOcrMaxPages: number | string;
  scannedPdfOcrMaxPairs: number | string;
  scannedPdfOcrMinCharsPerPage: number | string;
  scannedPdfOcrMinLinesPerPage: number | string;
  scannedPdfOcrMinConfidence: number | string;
  crawleeRequestHandlerTimeoutSecs: number | string;
  dynamicFetchRetryBudget: number | string;
  dynamicFetchRetryBackoffMs: number | string;
  fetchSchedulerMaxRetries: number | string;
  pageGotoTimeoutMs: number | string;
  pageNetworkIdleTimeoutMs: number | string;
  postLoadWaitMs: number | string;
  frontierDbPath: string;
  frontierQueryCooldownSeconds: number | string;
  frontierCooldown404Seconds: number | string;
  frontierCooldown404RepeatSeconds: number | string;
  frontierCooldown410Seconds: number | string;
  frontierCooldownTimeoutSeconds: number | string;
  frontierCooldown403BaseSeconds: number | string;
  frontierCooldown429BaseSeconds: number | string;
  frontierBackoffMaxExponent: number | string;
  frontierPathPenaltyNotfoundThreshold: number | string;
  frontierBlockedDomainThreshold: number | string;
  autoScrollPasses: number | string;
  autoScrollDelayMs: number | string;
  maxGraphqlReplays: number | string;
  maxNetworkResponsesPerPage: number | string;
  robotsTxtTimeoutMs: number | string;
  endpointSignalLimit: number | string;
  endpointSuggestionLimit: number | string;
  endpointNetworkScanLimit: number | string;
  discoveryMaxQueries: number | string;
  discoveryMaxDiscovered: number | string;
  maxUrlsPerProduct: number | string;
  maxCandidateUrls: number | string;
  maxPagesPerDomain: number | string;
  maxRunSeconds: number | string;
  maxJsonBytes: number | string;
  maxPdfBytes: number | string;
  pdfBackendRouterTimeoutMs: number | string;
  pdfBackendRouterMaxPages: number | string;
  pdfBackendRouterMaxPairs: number | string;
  pdfBackendRouterMaxTextPreviewChars: number | string;
  capturePageScreenshotQuality: number | string;
  capturePageScreenshotMaxBytes: number | string;
  articleExtractorMinChars: number | string;
  articleExtractorMinScore: number | string;
  articleExtractorMaxChars: number | string;
  staticDomTargetMatchThreshold: number | string;
  staticDomMaxEvidenceSnippets: number | string;
  domSnippetMaxChars: number | string;
  maxHypothesisItems: number | string;
  hypothesisAutoFollowupRounds: number | string;
  hypothesisFollowupUrlsPerRound: number | string;
  runtimeScreencastFps: number | string;
  runtimeScreencastQuality: number | string;
  runtimeScreencastMaxWidth: number | string;
  runtimeScreencastMaxHeight: number | string;
  runtimeTraceFetchRing: number | string;
  runtimeTraceLlmRing: number | string;
  daemonConcurrency: number | string;
  importsPollSeconds: number | string;
  indexingResumeSeedLimit: number | string;
  indexingResumePersistLimit: number | string;
  fieldRewardHalfLifeDays: number | string;
  driftPollSeconds: number | string;
  driftScanMaxProducts: number | string;
  reCrawlStaleAfterDays: number | string;
  dynamicFetchPolicyMapJson: string;
  searchProfileCapMapJson: string;
  serpRerankerWeightMapJson: string;
  llmProviderRegistryJson?: string;
  llmPhaseOverridesJson?: string;
  fetchSchedulerInternalsMapJson?: string;
  parsingConfidenceBaseMapJson?: string;
  repairDedupeRule?: RuntimeRepairDedupeRule;
  userAgent: string;
  pdfPreferredBackend: string;
  capturePageScreenshotFormat: string;
  capturePageScreenshotSelectors: string;
  runtimeControlFile: string;
  staticDomMode: string;
  specDbDir: string;
  articleExtractorDomainPolicyMapJson: string;
  llmExtractionCacheDir: string;
  categoryAuthorityRoot: string;
  helperFilesRoot?: string;
  batchStrategy: string;
  reextractIndexed: boolean;
  fetchCandidateSources: boolean;
  manufacturerAutoPromote?: boolean;
  pdfBackendRouterEnabled: boolean;
  capturePageScreenshotEnabled: boolean;
  categoryAuthorityEnabled: boolean;
  helperSupportiveFillMissing: boolean;
  driftDetectionEnabled: boolean;
  driftAutoRepublish: boolean;
  indexingCategoryAuthorityEnabled: boolean;
  scannedPdfOcrEnabled: boolean;
  dynamicCrawleeEnabled: boolean;
  crawleeHeadless: boolean;
  llmExtractSkipLowSignal: boolean;
  llmReasoningMode: boolean;
  llmPlanUseReasoning: boolean;
  llmVerifyMode: boolean;
  localMode: boolean;
  dryRun: boolean;
  mirrorToS3: boolean;
  mirrorToS3Input: boolean;
  writeMarkdownSummary: boolean;
  llmWriteSummary: boolean;
  preferHttpFetcher: boolean;
  frontierStripTrackingParams: boolean;
  autoScrollEnabled: boolean;
  graphqlReplayEnabled: boolean;
  robotsTxtCompliant: boolean;
  runtimeScreencastEnabled: boolean;
  runtimeTraceEnabled: boolean;
  runtimeTraceLlmPayloads: boolean;
  eventsJsonWrite: boolean;
  indexingSchemaPacketsValidationEnabled: boolean;
  indexingSchemaPacketsValidationStrict: boolean;
  selfImproveEnabled: boolean;
  runtimeSettingsFallbackBaseline: RuntimeSettingsNumericBaseline;
  resolveModelTokenDefaults: RuntimeModelTokenDefaultsResolver;
}
