import type {
  RuntimeAutomationQueueStorageEngine,
  RuntimeOcrBackend,
  RuntimeProfile,
  RuntimeRepairDedupeRule,
  RuntimeResumeMode,
  RuntimeSearchProvider,
} from '../../../stores/settingsManifest';
import type { RuntimeSettingsNumericBaseline } from './runtimeSettingsAuthority';

type RuntimeStringHydrationBinding = {
  key: string;
  allowEmpty?: boolean;
  apply: (value: string) => void;
};

type RuntimeNumberHydrationBinding = {
  key: string;
  apply: (value: number) => void;
};

type RuntimeBooleanHydrationBinding = {
  key: string;
  apply: (value: boolean) => void;
};

export interface RuntimeHydrationBindings {
  stringBindings: RuntimeStringHydrationBinding[];
  numberBindings: RuntimeNumberHydrationBinding[];
  booleanBindings: RuntimeBooleanHydrationBinding[];
}

export interface RuntimeHydrationBindingSetters {
  setProfile: (value: RuntimeProfile) => void;
  setSearchProvider: (value: RuntimeSearchProvider) => void;
  setSearxngBaseUrl: (value: string) => void;
  setLlmPlanApiKey: (value: string) => void;
  setPhase2LlmModel: (value: string) => void;
  setPhase3LlmModel: (value: string) => void;
  setLlmModelFast: (value: string) => void;
  setLlmModelReasoning: (value: string) => void;
  setLlmModelExtract: (value: string) => void;
  setLlmModelValidate: (value: string) => void;
  setLlmModelWrite: (value: string) => void;
  setLlmPlanFallbackModel: (value: string) => void;
  setLlmExtractFallbackModel: (value: string) => void;
  setLlmValidateFallbackModel: (value: string) => void;
  setLlmWriteFallbackModel: (value: string) => void;
  setConsensusMethodWeightNetworkJson: (value: string) => void;
  setConsensusMethodWeightAdapterApi: (value: string) => void;
  setConsensusMethodWeightStructuredMeta: (value: string) => void;
  setConsensusMethodWeightPdf: (value: string) => void;
  setConsensusMethodWeightTableKv: (value: string) => void;
  setConsensusMethodWeightDom: (value: string) => void;
  setConsensusPolicyBonus: (value: string) => void;
  setConsensusWeightedMajorityThreshold: (value: string) => void;
  setConsensusStrictAcceptanceDomainCount: (value: string) => void;
  setConsensusRelaxedAcceptanceDomainCount: (value: string) => void;
  setConsensusInstrumentedFieldThreshold: (value: string) => void;
  setConsensusConfidenceScoringBase: (value: string) => void;
  setConsensusPassTargetIdentityStrong: (value: string) => void;
  setConsensusPassTargetNormal: (value: string) => void;
  setRetrievalTierWeightTier1: (value: string) => void;
  setRetrievalTierWeightTier2: (value: string) => void;
  setRetrievalTierWeightTier3: (value: string) => void;
  setRetrievalTierWeightTier4: (value: string) => void;
  setRetrievalTierWeightTier5: (value: string) => void;
  setRetrievalDocKindWeightManualPdf: (value: string) => void;
  setRetrievalDocKindWeightSpecPdf: (value: string) => void;
  setRetrievalDocKindWeightSupport: (value: string) => void;
  setRetrievalDocKindWeightLabReview: (value: string) => void;
  setRetrievalDocKindWeightProductPage: (value: string) => void;
  setRetrievalDocKindWeightOther: (value: string) => void;
  setRetrievalMethodWeightTable: (value: string) => void;
  setRetrievalMethodWeightKv: (value: string) => void;
  setRetrievalMethodWeightJsonLd: (value: string) => void;
  setRetrievalMethodWeightLlmExtract: (value: string) => void;
  setRetrievalMethodWeightHelperSupportive: (value: string) => void;
  setRetrievalAnchorScorePerMatch: (value: string) => void;
  setRetrievalIdentityScorePerMatch: (value: string) => void;
  setRetrievalUnitMatchBonus: (value: string) => void;
  setRetrievalDirectFieldMatchBonus: (value: string) => void;
  setIdentityGatePublishThreshold: (value: string) => void;
  setIdentityGateBaseMatchThreshold: (value: string) => void;
  setQualityGateIdentityThreshold: (value: string) => void;
  setEvidenceTextMaxChars: (value: string) => void;
  setLlmExtractMaxTokens: (value: string) => void;
  setLlmExtractMaxSnippetsPerBatch: (value: string) => void;
  setLlmExtractMaxSnippetChars: (value: string) => void;
  setLlmExtractReasoningBudget: (value: string) => void;
  setLlmReasoningBudget: (value: string) => void;
  setLlmMonthlyBudgetUsd: (value: string) => void;
  setLlmPerProductBudgetUsd: (value: string) => void;
  setLlmMaxCallsPerRound: (value: string) => void;
  setLlmMaxOutputTokens: (value: string) => void;
  setLlmVerifySampleRate: (value: string) => void;
  setLlmMaxBatchesPerProduct: (value: string) => void;
  setLlmMaxEvidenceChars: (value: string) => void;
  setLlmMaxTokens: (value: string) => void;
  setLlmTimeoutMs: (value: string) => void;
  setLlmCostInputPer1M: (value: string) => void;
  setLlmCostOutputPer1M: (value: string) => void;
  setLlmCostCachedInputPer1M: (value: string) => void;
  setLocalInputRoot: (value: string) => void;
  setLocalOutputRoot: (value: string) => void;
  setRuntimeEventsKey: (value: string) => void;
  setAwsRegion: (value: string) => void;
  setS3Bucket: (value: string) => void;
  setS3InputPrefix: (value: string) => void;
  setS3OutputPrefix: (value: string) => void;
  setEloSupabaseAnonKey: (value: string) => void;
  setEloSupabaseEndpoint: (value: string) => void;
  setLlmProvider: (value: string) => void;
  setLlmBaseUrl: (value: string) => void;
  setOpenaiApiKey: (value: string) => void;
  setAnthropicApiKey: (value: string) => void;
  setResumeMode: (value: RuntimeResumeMode) => void;
  setImportsRoot: (value: string) => void;
  setScannedPdfOcrBackend: (value: RuntimeOcrBackend) => void;
  setDynamicFetchPolicyMapJson: (value: string) => void;
  setSearchProfileCapMapJson: (value: string) => void;
  setSerpRerankerWeightMapJson: (value: string) => void;
  setFetchSchedulerInternalsMapJson?: (value: string) => void;
  setRetrievalInternalsMapJson?: (value: string) => void;
  setEvidencePackLimitsMapJson?: (value: string) => void;
  setParsingConfidenceBaseMapJson?: (value: string) => void;
  setRepairDedupeRule?: (value: RuntimeRepairDedupeRule) => void;
  setAutomationQueueStorageEngine?: (value: RuntimeAutomationQueueStorageEngine) => void;
  setConsensusMethodWeightLlmExtractBase?: (value: string) => void;
  setFetchConcurrency: (value: string) => void;
  setFetchBudgetMs?: (value: string) => void;
  setPerHostMinDelayMs: (value: string) => void;
  setSearchGlobalRps: (value: string) => void;
  setSearchGlobalBurst: (value: string) => void;
  setSearchPerHostRps: (value: string) => void;
  setSearchPerHostBurst: (value: string) => void;
  setDomainRequestRps: (value: string) => void;
  setDomainRequestBurst: (value: string) => void;
  setGlobalRequestRps: (value: string) => void;
  setGlobalRequestBurst: (value: string) => void;
  setFetchPerHostConcurrencyCap: (value: string) => void;
  setLlmTokensPlan: (value: number) => void;
  setLlmTokensTriage: (value: number) => void;
  setLlmTokensFast: (value: number) => void;
  setLlmTokensReasoning: (value: number) => void;
  setLlmTokensExtract: (value: number) => void;
  setLlmTokensValidate: (value: number) => void;
  setLlmTokensWrite: (value: number) => void;
  setLlmTokensPlanFallback: (value: number) => void;
  setLlmTokensExtractFallback: (value: number) => void;
  setLlmTokensValidateFallback: (value: number) => void;
  setLlmTokensWriteFallback: (value: number) => void;
  setResumeWindowHours: (value: string) => void;
  setReextractAfterHours: (value: string) => void;
  setScannedPdfOcrMaxPages: (value: string) => void;
  setScannedPdfOcrMaxPairs: (value: string) => void;
  setScannedPdfOcrMinCharsPerPage: (value: string) => void;
  setScannedPdfOcrMinLinesPerPage: (value: string) => void;
  setScannedPdfOcrMinConfidence: (value: string) => void;
  setCrawleeRequestHandlerTimeoutSecs: (value: string) => void;
  setDynamicFetchRetryBudget: (value: string) => void;
  setDynamicFetchRetryBackoffMs: (value: string) => void;
  setFetchSchedulerMaxRetries: (value: string) => void;
  setFetchSchedulerFallbackWaitMs: (value: string) => void;
  setPageGotoTimeoutMs: (value: string) => void;
  setPageNetworkIdleTimeoutMs: (value: string) => void;
  setPostLoadWaitMs: (value: string) => void;
  setFrontierDbPath: (value: string) => void;
  setFrontierQueryCooldownSeconds: (value: string) => void;
  setFrontierCooldown404Seconds: (value: string) => void;
  setFrontierCooldown404RepeatSeconds: (value: string) => void;
  setFrontierCooldown410Seconds: (value: string) => void;
  setFrontierCooldownTimeoutSeconds: (value: string) => void;
  setFrontierCooldown403BaseSeconds: (value: string) => void;
  setFrontierCooldown429BaseSeconds: (value: string) => void;
  setFrontierBackoffMaxExponent: (value: string) => void;
  setFrontierPathPenaltyNotfoundThreshold: (value: string) => void;
  setFrontierBlockedDomainThreshold: (value: string) => void;
  setAutoScrollPasses: (value: string) => void;
  setAutoScrollDelayMs: (value: string) => void;
  setMaxGraphqlReplays: (value: string) => void;
  setMaxNetworkResponsesPerPage: (value: string) => void;
  setRobotsTxtTimeoutMs: (value: string) => void;
  setEndpointSignalLimit: (value: string) => void;
  setEndpointSuggestionLimit: (value: string) => void;
  setEndpointNetworkScanLimit: (value: string) => void;
  setDiscoveryMaxQueries: (value: string) => void;
  setDiscoveryMaxDiscovered: (value: string) => void;
  setMaxUrlsPerProduct: (value: string) => void;
  setMaxCandidateUrls: (value: string) => void;
  setSerpTriageMaxUrls?: (value: string) => void;
  setMaxPagesPerDomain: (value: string) => void;
  setMaxRunSeconds: (value: string) => void;
  setMaxJsonBytes: (value: string) => void;
  setMaxPdfBytes: (value: string) => void;
  setPdfBackendRouterTimeoutMs: (value: string) => void;
  setPdfBackendRouterMaxPages: (value: string) => void;
  setPdfBackendRouterMaxPairs: (value: string) => void;
  setPdfBackendRouterMaxTextPreviewChars: (value: string) => void;
  setCapturePageScreenshotQuality: (value: string) => void;
  setCapturePageScreenshotMaxBytes: (value: string) => void;
  setArticleExtractorMinChars: (value: string) => void;
  setArticleExtractorMinScore: (value: string) => void;
  setArticleExtractorMaxChars: (value: string) => void;
  setStaticDomTargetMatchThreshold: (value: string) => void;
  setStaticDomMaxEvidenceSnippets: (value: string) => void;
  setStructuredMetadataExtructTimeoutMs: (value: string) => void;
  setStructuredMetadataExtructMaxItemsPerSurface: (value: string) => void;
  setStructuredMetadataExtructCacheLimit: (value: string) => void;
  setDomSnippetMaxChars: (value: string) => void;
  setLlmExtractionCacheTtlMs: (value: string) => void;
  setLlmMaxCallsPerProductTotal: (value: string) => void;
  setLlmMaxCallsPerProductFast: (value: string) => void;
  setMaxManufacturerUrlsPerProduct: (value: string) => void;
  setMaxManufacturerPagesPerDomain: (value: string) => void;
  setManufacturerReserveUrls: (value: string) => void;
  setMaxHypothesisItems: (value: string) => void;
  setHypothesisAutoFollowupRounds: (value: string) => void;
  setHypothesisFollowupUrlsPerRound: (value: string) => void;
  setUserAgent: (value: string) => void;
  setPdfPreferredBackend: (value: string) => void;
  setCapturePageScreenshotFormat: (value: string) => void;
  setCapturePageScreenshotSelectors: (value: string) => void;
  setRuntimeScreenshotMode: (value: string) => void;
  setStaticDomMode: (value: string) => void;
  setSpecDbDir: (value: string) => void;
  setArticleExtractorDomainPolicyMapJson: (value: string) => void;
  setStructuredMetadataExtructUrl: (value: string) => void;
  setLlmExtractionCacheDir: (value: string) => void;
  setCortexBaseUrl: (value: string) => void;
  setCortexApiKey: (value: string) => void;
  setCortexAsyncBaseUrl: (value: string) => void;
  setCortexAsyncSubmitPath: (value: string) => void;
  setCortexAsyncStatusPath: (value: string) => void;
  setCortexModelFast: (value: string) => void;
  setCortexModelDom: (value: string) => void;
  setCortexModelReasoningDeep: (value: string) => void;
  setCortexModelVision: (value: string) => void;
  setCortexModelSearchFast: (value: string) => void;
  setCortexModelRerankFast: (value: string) => void;
  setRuntimeScreencastFps: (value: string) => void;
  setRuntimeScreencastQuality: (value: string) => void;
  setRuntimeScreencastMaxWidth: (value: string) => void;
  setRuntimeScreencastMaxHeight: (value: string) => void;
  setRuntimeTraceFetchRing: (value: string) => void;
  setRuntimeTraceLlmRing: (value: string) => void;
  setDaemonConcurrency: (value: string) => void;
  setDaemonGracefulShutdownTimeoutMs: (value: string) => void;
  setImportsPollSeconds: (value: string) => void;
  setIndexingResumeSeedLimit: (value: string) => void;
  setIndexingResumePersistLimit: (value: string) => void;
  setHelperSupportiveMaxSources: (value: string) => void;
  setHelperActiveSyncLimit: (value: string) => void;
  setFieldRewardHalfLifeDays: (value: string) => void;
  setDriftPollSeconds: (value: string) => void;
  setDriftScanMaxProducts: (value: string) => void;
  setReCrawlStaleAfterDays: (value: string) => void;
  setCortexSyncTimeoutMs: (value: string) => void;
  setCortexAsyncPollIntervalMs: (value: string) => void;
  setCortexAsyncMaxWaitMs: (value: string) => void;
  setCortexEnsureReadyTimeoutMs: (value: string) => void;
  setCortexStartReadyTimeoutMs: (value: string) => void;
  setCortexFailureThreshold: (value: string) => void;
  setCortexCircuitOpenMs: (value: string) => void;
  setCortexEscalateConfidenceLt: (value: string) => void;
  setCortexMaxDeepFieldsPerProduct: (value: string) => void;
  setDiscoveryEnabled: (value: boolean) => void;
  setEnableSourceRegistry: (value: boolean) => void;
  setEnableDomainHintResolverV2: (value: boolean) => void;
  setEnableQueryCompiler: (value: boolean) => void;
  setEnableCoreDeepGates: (value: boolean) => void;
  setEnableQueryIndex?: (value: boolean) => void;
  setEnableUrlIndex?: (value: boolean) => void;
  setPhase2LlmEnabled: (value: boolean) => void;
  setLlmExtractionCacheEnabled: (value: boolean) => void;
  setReextractIndexed: (value: boolean) => void;
  setFetchCandidateSources: (value: boolean) => void;
  setManufacturerBroadDiscovery: (value: boolean) => void;
  setManufacturerSeedSearchUrls: (value: boolean) => void;
  setManufacturerAutoPromote?: (value: boolean) => void;
  setManufacturerDeepResearchEnabled: (value: boolean) => void;
  setPdfBackendRouterEnabled: (value: boolean) => void;
  setCapturePageScreenshotEnabled: (value: boolean) => void;
  setRuntimeCaptureScreenshots: (value: boolean) => void;
  setChartExtractionEnabled: (value: boolean) => void;
  setArticleExtractorV2Enabled: (value: boolean) => void;
  setStaticDomExtractorEnabled: (value: boolean) => void;
  setHtmlTableExtractorV2: (value: boolean) => void;
  setStructuredMetadataExtructEnabled: (value: boolean) => void;
  setStructuredMetadataExtructCacheEnabled: (value: boolean) => void;
  setHelperFilesEnabled: (value: boolean) => void;
  setHelperSupportiveEnabled: (value: boolean) => void;
  setHelperSupportiveFillMissing: (value: boolean) => void;
  setHelperAutoSeedTargets: (value: boolean) => void;
  setDriftDetectionEnabled: (value: boolean) => void;
  setDriftAutoRepublish: (value: boolean) => void;
  setCortexEnabled: (value: boolean) => void;
  setCortexAsyncEnabled: (value: boolean) => void;
  setCortexAutoStart: (value: boolean) => void;
  setCortexEscalateIfConflict: (value: boolean) => void;
  setCortexEscalateCriticalOnly: (value: boolean) => void;
  setAllowBelowPassTargetFill: (value: boolean) => void;
  setIndexingHelperFilesEnabled: (value: boolean) => void;
  setScannedPdfOcrEnabled: (value: boolean) => void;
  setScannedPdfOcrPromoteCandidates: (value: boolean) => void;
  setDynamicCrawleeEnabled: (value: boolean) => void;
  setCrawleeHeadless: (value: boolean) => void;
  setLlmExtractSkipLowSignal: (value: boolean) => void;
  setLlmReasoningMode: (value: boolean) => void;
  setLlmDisableBudgetGuards: (value: boolean) => void;
  setLlmVerifyMode: (value: boolean) => void;
  setLocalMode: (value: boolean) => void;
  setDryRun: (value: boolean) => void;
  setMirrorToS3: (value: boolean) => void;
  setMirrorToS3Input: (value: boolean) => void;
  setWriteMarkdownSummary: (value: boolean) => void;
  setLlmEnabled: (value: boolean) => void;
  setLlmWriteSummary: (value: boolean) => void;
  setFetchSchedulerEnabled: (value: boolean) => void;
  setPreferHttpFetcher: (value: boolean) => void;
  setFrontierEnableSqlite: (value: boolean) => void;
  setFrontierStripTrackingParams: (value: boolean) => void;
  setFrontierRepairSearchEnabled: (value: boolean) => void;
  setAutoScrollEnabled: (value: boolean) => void;
  setGraphqlReplayEnabled: (value: boolean) => void;
  setRobotsTxtCompliant: (value: boolean) => void;
  setRuntimeScreencastEnabled: (value: boolean) => void;
  setRuntimeTraceEnabled: (value: boolean) => void;
  setRuntimeTraceLlmPayloads: (value: boolean) => void;
  setEventsJsonWrite: (value: boolean) => void;
  setIndexingSchemaPacketsValidationEnabled: (value: boolean) => void;
  setIndexingSchemaPacketsValidationStrict: (value: boolean) => void;
  setQueueJsonWrite: (value: boolean) => void;
  setBillingJsonWrite: (value: boolean) => void;
  setIntelJsonWrite: (value: boolean) => void;
  setCorpusJsonWrite: (value: boolean) => void;
  setLearningJsonWrite: (value: boolean) => void;
  setCacheJsonWrite: (value: boolean) => void;
  setAuthoritySnapshotEnabled: (value: boolean) => void;
  setSelfImproveEnabled: (value: boolean) => void;
  setOutputMode: (value: string) => void;
  setLlmPlanProvider: (value: string) => void;
  setLlmPlanBaseUrl: (value: string) => void;
  setRuntimeControlFile: (value: string) => void;
  setHelperFilesRoot: (value: string) => void;
  setBatchStrategy: (value: string) => void;
}

export interface RuntimeModelTokenDefaults {
  default_output_tokens: number;
  max_output_tokens: number;
}

export type RuntimeModelTokenDefaultsResolver = (
  model: string,
) => RuntimeModelTokenDefaults;

export interface RuntimeSettingsPayloadSerializerInput {
  profile?: RuntimeProfile | string;
  searchProvider: RuntimeSearchProvider | string;
  searxngBaseUrl: string;
  llmPlanApiKey: string;
  llmModelPlan?: string;
  phase2LlmModel: string;
  llmModelTriage?: string;
  phase3LlmModel: string;
  llmModelFast: string;
  llmModelReasoning: string;
  llmModelExtract: string;
  llmModelValidate: string;
  llmModelWrite: string;
  consensusMethodWeightNetworkJson: number | string;
  consensusMethodWeightAdapterApi: number | string;
  consensusMethodWeightStructuredMeta: number | string;
  consensusMethodWeightPdf: number | string;
  consensusMethodWeightTableKv: number | string;
  consensusMethodWeightDom: number | string;
  consensusMethodWeightLlmExtractBase?: number | string;
  consensusPolicyBonus: number | string;
  consensusWeightedMajorityThreshold: number | string;
  consensusStrictAcceptanceDomainCount: number | string;
  consensusRelaxedAcceptanceDomainCount: number | string;
  consensusInstrumentedFieldThreshold: number | string;
  consensusConfidenceScoringBase: number | string;
  consensusPassTargetIdentityStrong: number | string;
  consensusPassTargetNormal: number | string;
  retrievalTierWeightTier1: number | string;
  retrievalTierWeightTier2: number | string;
  retrievalTierWeightTier3: number | string;
  retrievalTierWeightTier4: number | string;
  retrievalTierWeightTier5: number | string;
  retrievalDocKindWeightManualPdf: number | string;
  retrievalDocKindWeightSpecPdf: number | string;
  retrievalDocKindWeightSupport: number | string;
  retrievalDocKindWeightLabReview: number | string;
  retrievalDocKindWeightProductPage: number | string;
  retrievalDocKindWeightOther: number | string;
  retrievalMethodWeightTable: number | string;
  retrievalMethodWeightKv: number | string;
  retrievalMethodWeightJsonLd: number | string;
  retrievalMethodWeightLlmExtract: number | string;
  retrievalMethodWeightHelperSupportive: number | string;
  retrievalAnchorScorePerMatch: number | string;
  retrievalIdentityScorePerMatch: number | string;
  retrievalUnitMatchBonus: number | string;
  retrievalDirectFieldMatchBonus: number | string;
  identityGatePublishThreshold: number | string;
  identityGateBaseMatchThreshold: number | string;
  qualityGateIdentityThreshold: number | string;
  evidenceTextMaxChars: number | string;
  llmExtractMaxTokens: number | string;
  llmExtractMaxSnippetsPerBatch: number | string;
  llmExtractMaxSnippetChars: number | string;
  llmExtractReasoningBudget: number | string;
  llmReasoningBudget: number | string;
  llmMonthlyBudgetUsd: number | string;
  llmPerProductBudgetUsd: number | string;
  llmMaxCallsPerRound: number | string;
  llmMaxOutputTokens: number | string;
  llmVerifySampleRate: number | string;
  llmMaxBatchesPerProduct: number | string;
  llmMaxEvidenceChars: number | string;
  llmMaxTokens: number | string;
  llmTimeoutMs: number | string;
  llmCostInputPer1M: number | string;
  llmCostOutputPer1M: number | string;
  llmCostCachedInputPer1M: number | string;
  llmPlanFallbackModel?: string;
  llmExtractFallbackModel?: string;
  llmValidateFallbackModel?: string;
  llmWriteFallbackModel?: string;
  outputMode: string;
  localInputRoot: string;
  localOutputRoot: string;
  runtimeEventsKey: string;
  awsRegion?: string;
  s3Bucket?: string;
  s3InputPrefix: string;
  s3OutputPrefix: string;
  eloSupabaseAnonKey: string;
  eloSupabaseEndpoint: string;
  llmProvider: string;
  llmBaseUrl: string;
  openaiApiKey: string;
  anthropicApiKey: string;
  llmPlanProvider: string;
  llmPlanBaseUrl: string;
  importsRoot: string;
  resumeMode: RuntimeResumeMode | string;
  scannedPdfOcrBackend: RuntimeOcrBackend | string;
  fetchBudgetMs?: number | string;
  fetchConcurrency: number | string;
  perHostMinDelayMs: number | string;
  searchGlobalRps: number | string;
  searchGlobalBurst: number | string;
  searchPerHostRps: number | string;
  searchPerHostBurst: number | string;
  domainRequestRps: number | string;
  domainRequestBurst: number | string;
  globalRequestRps: number | string;
  globalRequestBurst: number | string;
  fetchPerHostConcurrencyCap: number | string;
  llmMaxOutputTokensPlan?: number | string;
  llmTokensPlan: number | string;
  llmMaxOutputTokensTriage?: number | string;
  llmTokensTriage: number | string;
  llmMaxOutputTokensFast?: number | string;
  llmTokensFast: number | string;
  llmMaxOutputTokensReasoning?: number | string;
  llmTokensReasoning: number | string;
  llmMaxOutputTokensExtract?: number | string;
  llmTokensExtract: number | string;
  llmMaxOutputTokensValidate?: number | string;
  llmTokensValidate: number | string;
  llmMaxOutputTokensWrite?: number | string;
  llmTokensWrite: number | string;
  llmMaxOutputTokensPlanFallback?: number | string;
  llmTokensPlanFallback: number | string;
  llmMaxOutputTokensExtractFallback?: number | string;
  llmTokensExtractFallback: number | string;
  llmMaxOutputTokensValidateFallback?: number | string;
  llmTokensValidateFallback: number | string;
  llmMaxOutputTokensWriteFallback?: number | string;
  llmTokensWriteFallback: number | string;
  llmExtractionCacheTtlMs: number | string;
  llmMaxCallsPerProductTotal: number | string;
  llmMaxCallsPerProductFast: number | string;
  resumeWindowHours: number | string;
  reextractAfterHours: number | string;
  scannedPdfOcrMaxPages: number | string;
  scannedPdfOcrMaxPairs: number | string;
  scannedPdfOcrMinCharsPerPage: number | string;
  scannedPdfOcrMinLinesPerPage: number | string;
  scannedPdfOcrMinConfidence: number | string;
  crawleeRequestHandlerTimeoutSecs: number | string;
  dynamicFetchRetryBudget: number | string;
  dynamicFetchRetryBackoffMs: number | string;
  fetchSchedulerMaxRetries: number | string;
  fetchSchedulerFallbackWaitMs: number | string;
  pageGotoTimeoutMs: number | string;
  pageNetworkIdleTimeoutMs: number | string;
  postLoadWaitMs: number | string;
  frontierDbPath: string;
  frontierQueryCooldownSeconds: number | string;
  frontierCooldown404Seconds: number | string;
  frontierCooldown404RepeatSeconds: number | string;
  frontierCooldown410Seconds: number | string;
  frontierCooldownTimeoutSeconds: number | string;
  frontierCooldown403BaseSeconds: number | string;
  frontierCooldown429BaseSeconds: number | string;
  frontierBackoffMaxExponent: number | string;
  frontierPathPenaltyNotfoundThreshold: number | string;
  frontierBlockedDomainThreshold: number | string;
  autoScrollPasses: number | string;
  autoScrollDelayMs: number | string;
  maxGraphqlReplays: number | string;
  maxNetworkResponsesPerPage: number | string;
  robotsTxtTimeoutMs: number | string;
  endpointSignalLimit: number | string;
  endpointSuggestionLimit: number | string;
  endpointNetworkScanLimit: number | string;
  discoveryMaxQueries: number | string;
  discoveryMaxDiscovered: number | string;
  maxUrlsPerProduct: number | string;
  maxCandidateUrls: number | string;
  serpTriageMaxUrls: number | string;
  maxPagesPerDomain: number | string;
  maxRunSeconds: number | string;
  maxJsonBytes: number | string;
  maxPdfBytes: number | string;
  pdfBackendRouterTimeoutMs: number | string;
  pdfBackendRouterMaxPages: number | string;
  pdfBackendRouterMaxPairs: number | string;
  pdfBackendRouterMaxTextPreviewChars: number | string;
  capturePageScreenshotQuality: number | string;
  capturePageScreenshotMaxBytes: number | string;
  articleExtractorMinChars: number | string;
  articleExtractorMinScore: number | string;
  articleExtractorMaxChars: number | string;
  staticDomTargetMatchThreshold: number | string;
  staticDomMaxEvidenceSnippets: number | string;
  structuredMetadataExtructTimeoutMs: number | string;
  structuredMetadataExtructMaxItemsPerSurface: number | string;
  structuredMetadataExtructCacheLimit: number | string;
  domSnippetMaxChars: number | string;
  maxManufacturerUrlsPerProduct: number | string;
  maxManufacturerPagesPerDomain: number | string;
  manufacturerReserveUrls: number | string;
  maxHypothesisItems: number | string;
  hypothesisAutoFollowupRounds: number | string;
  hypothesisFollowupUrlsPerRound: number | string;
  runtimeScreencastFps: number | string;
  runtimeScreencastQuality: number | string;
  runtimeScreencastMaxWidth: number | string;
  runtimeScreencastMaxHeight: number | string;
  runtimeTraceFetchRing: number | string;
  runtimeTraceLlmRing: number | string;
  daemonConcurrency: number | string;
  daemonGracefulShutdownTimeoutMs: number | string;
  importsPollSeconds: number | string;
  indexingResumeSeedLimit: number | string;
  indexingResumePersistLimit: number | string;
  helperSupportiveMaxSources: number | string;
  helperActiveSyncLimit: number | string;
  fieldRewardHalfLifeDays: number | string;
  driftPollSeconds: number | string;
  driftScanMaxProducts: number | string;
  reCrawlStaleAfterDays: number | string;
  cortexSyncTimeoutMs: number | string;
  cortexAsyncPollIntervalMs: number | string;
  cortexAsyncMaxWaitMs: number | string;
  cortexEnsureReadyTimeoutMs: number | string;
  cortexStartReadyTimeoutMs: number | string;
  cortexFailureThreshold: number | string;
  cortexCircuitOpenMs: number | string;
  cortexEscalateConfidenceLt: number | string;
  cortexMaxDeepFieldsPerProduct: number | string;
  dynamicFetchPolicyMapJson: string;
  searchProfileCapMapJson: string;
  serpRerankerWeightMapJson: string;
  fetchSchedulerInternalsMapJson?: string;
  retrievalInternalsMapJson?: string;
  evidencePackLimitsMapJson?: string;
  parsingConfidenceBaseMapJson?: string;
  repairDedupeRule?: RuntimeRepairDedupeRule;
  automationQueueStorageEngine?: RuntimeAutomationQueueStorageEngine;
  userAgent: string;
  pdfPreferredBackend: string;
  capturePageScreenshotFormat: string;
  capturePageScreenshotSelectors: string;
  runtimeScreenshotMode: string;
  runtimeControlFile: string;
  staticDomMode: string;
  specDbDir: string;
  articleExtractorDomainPolicyMapJson: string;
  structuredMetadataExtructUrl: string;
  llmExtractionCacheDir: string;
  cortexBaseUrl: string;
  cortexApiKey: string;
  cortexAsyncBaseUrl: string;
  cortexAsyncSubmitPath: string;
  cortexAsyncStatusPath: string;
  cortexModelFast: string;
  cortexModelDom: string;
  cortexModelReasoningDeep: string;
  cortexModelVision: string;
  cortexModelSearchFast: string;
  cortexModelRerankFast: string;
  categoryAuthorityRoot: string;
  batchStrategy: string;
  discoveryEnabled: boolean;
  enableSourceRegistry: boolean;
  enableDomainHintResolverV2: boolean;
  enableQueryCompiler: boolean;
  enableCoreDeepGates: boolean;
  enableQueryIndex?: boolean;
  enableUrlIndex?: boolean;
  llmPlanDiscoveryQueries?: boolean;
  phase2LlmEnabled: boolean;
  llmExtractionCacheEnabled: boolean;
  reextractIndexed: boolean;
  fetchCandidateSources: boolean;
  manufacturerBroadDiscovery: boolean;
  manufacturerSeedSearchUrls: boolean;
  manufacturerAutoPromote?: boolean;
  manufacturerDeepResearchEnabled: boolean;
  pdfBackendRouterEnabled: boolean;
  capturePageScreenshotEnabled: boolean;
  runtimeCaptureScreenshots: boolean;
  chartExtractionEnabled: boolean;
  articleExtractorV2Enabled: boolean;
  staticDomExtractorEnabled: boolean;
  htmlTableExtractorV2: boolean;
  structuredMetadataExtructEnabled: boolean;
  structuredMetadataExtructCacheEnabled: boolean;
  categoryAuthorityEnabled: boolean;
  helperFilesEnabled?: boolean;
  helperFilesRoot?: string;
  indexingHelperFilesEnabled?: boolean;
  helperSupportiveEnabled: boolean;
  helperSupportiveFillMissing: boolean;
  helperAutoSeedTargets: boolean;
  driftDetectionEnabled: boolean;
  driftAutoRepublish: boolean;
  cortexEnabled: boolean;
  cortexAsyncEnabled: boolean;
  cortexAutoStart: boolean;
  cortexEscalateIfConflict: boolean;
  cortexEscalateCriticalOnly: boolean;
  allowBelowPassTargetFill: boolean;
  indexingCategoryAuthorityEnabled: boolean;
  scannedPdfOcrEnabled: boolean;
  scannedPdfOcrPromoteCandidates: boolean;
  dynamicCrawleeEnabled: boolean;
  crawleeHeadless: boolean;
  llmExtractSkipLowSignal: boolean;
  llmReasoningMode: boolean;
  llmDisableBudgetGuards: boolean;
  llmVerifyMode: boolean;
  localMode: boolean;
  dryRun: boolean;
  mirrorToS3: boolean;
  mirrorToS3Input: boolean;
  writeMarkdownSummary: boolean;
  llmEnabled: boolean;
  llmWriteSummary: boolean;
  fetchSchedulerEnabled: boolean;
  preferHttpFetcher: boolean;
  frontierEnableSqlite: boolean;
  frontierStripTrackingParams: boolean;
  frontierRepairSearchEnabled: boolean;
  autoScrollEnabled: boolean;
  graphqlReplayEnabled: boolean;
  robotsTxtCompliant: boolean;
  runtimeScreencastEnabled: boolean;
  runtimeTraceEnabled: boolean;
  runtimeTraceLlmPayloads: boolean;
  eventsJsonWrite: boolean;
  indexingSchemaPacketsValidationEnabled: boolean;
  indexingSchemaPacketsValidationStrict: boolean;
  queueJsonWrite: boolean;
  billingJsonWrite: boolean;
  intelJsonWrite: boolean;
  corpusJsonWrite: boolean;
  learningJsonWrite: boolean;
  cacheJsonWrite: boolean;
  authoritySnapshotEnabled: boolean;
  selfImproveEnabled: boolean;
  runtimeSettingsFallbackBaseline: RuntimeSettingsNumericBaseline;
  resolveModelTokenDefaults: RuntimeModelTokenDefaultsResolver;
}
