import {
  type RuntimeRepairDedupeRule,
} from '../../../stores/settingsManifest';
import {
  collectRuntimeSettingsPayload,
  type RuntimeModelTokenDefaultsResolver,
} from './runtimeSettingsDomain';
import {
  RUNTIME_NUMBER_BOUNDS,
  parseBoundedNumber,
  type RuntimeDraft,
} from './RuntimeFlowDraftContracts';

interface CollectRuntimeFlowDraftPayloadParams {
  nextRuntimeDraft: RuntimeDraft;
  runtimeManifestDefaults: RuntimeDraft;
  resolveModelTokenDefaults: RuntimeModelTokenDefaultsResolver;
}

export function collectRuntimeFlowDraftPayload({
  nextRuntimeDraft,
  runtimeManifestDefaults,
  resolveModelTokenDefaults,
}: CollectRuntimeFlowDraftPayloadParams) {
  return collectRuntimeSettingsPayload({
    searchEngines: nextRuntimeDraft.searchEngines,
    searchEnginesFallback: nextRuntimeDraft.searchEnginesFallback,
    searxngBaseUrl: String(nextRuntimeDraft.searxngBaseUrl || '').trim(),
    llmPlanApiKey: String(nextRuntimeDraft.llmPlanApiKey || '').trim(),
    llmModelPlan: nextRuntimeDraft.llmModelPlan,
    llmModelReasoning: nextRuntimeDraft.llmModelReasoning,
    llmPlanFallbackModel: nextRuntimeDraft.llmPlanFallbackModel,
    llmReasoningFallbackModel: nextRuntimeDraft.llmReasoningFallbackModel,
    outputMode: String(nextRuntimeDraft.outputMode || '').trim(),
    localInputRoot: String(nextRuntimeDraft.localInputRoot || '').trim(),
    localOutputRoot: String(nextRuntimeDraft.localOutputRoot || '').trim(),
    runtimeEventsKey: String(nextRuntimeDraft.runtimeEventsKey || '').trim(),
    s3InputPrefix: String(nextRuntimeDraft.s3InputPrefix || '').trim(),
    s3OutputPrefix: String(nextRuntimeDraft.s3OutputPrefix || '').trim(),
    eloSupabaseAnonKey: String(nextRuntimeDraft.eloSupabaseAnonKey || '').trim(),
    eloSupabaseEndpoint: String(nextRuntimeDraft.eloSupabaseEndpoint || '').trim(),
    llmProvider: String(nextRuntimeDraft.llmProvider || '').trim(),
    llmBaseUrl: String(nextRuntimeDraft.llmBaseUrl || '').trim(),
    openaiApiKey: String(nextRuntimeDraft.openaiApiKey || '').trim(),
    anthropicApiKey: String(nextRuntimeDraft.anthropicApiKey || '').trim(),
    geminiApiKey: String(nextRuntimeDraft.geminiApiKey || '').trim(),
    deepseekApiKey: String(nextRuntimeDraft.deepseekApiKey || '').trim(),
    llmPlanProvider: String(nextRuntimeDraft.llmPlanProvider || '').trim(),
    llmPlanBaseUrl: String(nextRuntimeDraft.llmPlanBaseUrl || '').trim(),
    importsRoot: String(nextRuntimeDraft.importsRoot || '').trim(),
    llmExtractionCacheDir: String(nextRuntimeDraft.llmExtractionCacheDir || '').trim(),
    resumeMode: nextRuntimeDraft.resumeMode,
    scannedPdfOcrBackend: nextRuntimeDraft.scannedPdfOcrBackend,
    fetchBudgetMs: parseBoundedNumber(
      nextRuntimeDraft.fetchBudgetMs,
      runtimeManifestDefaults.fetchBudgetMs,
      RUNTIME_NUMBER_BOUNDS.fetchBudgetMs,
    ),
    fetchConcurrency: parseBoundedNumber(
      nextRuntimeDraft.fetchConcurrency,
      runtimeManifestDefaults.fetchConcurrency,
      RUNTIME_NUMBER_BOUNDS.fetchConcurrency,
    ),
    perHostMinDelayMs: parseBoundedNumber(
      nextRuntimeDraft.perHostMinDelayMs,
      runtimeManifestDefaults.perHostMinDelayMs,
      RUNTIME_NUMBER_BOUNDS.perHostMinDelayMs,
    ),
    searxngMinQueryIntervalMs: parseBoundedNumber(
      nextRuntimeDraft.searxngMinQueryIntervalMs,
      runtimeManifestDefaults.searxngMinQueryIntervalMs,
      RUNTIME_NUMBER_BOUNDS.searxngMinQueryIntervalMs,
    ),
    googleSearchProxyUrlsJson: String(nextRuntimeDraft.googleSearchProxyUrlsJson || '[]').trim(),
    googleSearchTimeoutMs: parseBoundedNumber(
      nextRuntimeDraft.googleSearchTimeoutMs,
      runtimeManifestDefaults.googleSearchTimeoutMs,
      RUNTIME_NUMBER_BOUNDS.googleSearchTimeoutMs,
    ),
    googleSearchMinQueryIntervalMs: parseBoundedNumber(
      nextRuntimeDraft.googleSearchMinQueryIntervalMs,
      runtimeManifestDefaults.googleSearchMinQueryIntervalMs,
      RUNTIME_NUMBER_BOUNDS.googleSearchMinQueryIntervalMs,
    ),
    googleSearchMaxRetries: parseBoundedNumber(
      nextRuntimeDraft.googleSearchMaxRetries,
      runtimeManifestDefaults.googleSearchMaxRetries,
      RUNTIME_NUMBER_BOUNDS.googleSearchMaxRetries,
    ),
    googleSearchScreenshotsEnabled: nextRuntimeDraft.googleSearchScreenshotsEnabled,
    domainRequestRps: parseBoundedNumber(
      nextRuntimeDraft.domainRequestRps,
      runtimeManifestDefaults.domainRequestRps,
      RUNTIME_NUMBER_BOUNDS.domainRequestRps,
    ),
    domainRequestBurst: parseBoundedNumber(
      nextRuntimeDraft.domainRequestBurst,
      runtimeManifestDefaults.domainRequestBurst,
      RUNTIME_NUMBER_BOUNDS.domainRequestBurst,
    ),
    globalRequestRps: parseBoundedNumber(
      nextRuntimeDraft.globalRequestRps,
      runtimeManifestDefaults.globalRequestRps,
      RUNTIME_NUMBER_BOUNDS.globalRequestRps,
    ),
    globalRequestBurst: parseBoundedNumber(
      nextRuntimeDraft.globalRequestBurst,
      runtimeManifestDefaults.globalRequestBurst,
      RUNTIME_NUMBER_BOUNDS.globalRequestBurst,
    ),
    fetchPerHostConcurrencyCap: parseBoundedNumber(
      nextRuntimeDraft.fetchPerHostConcurrencyCap,
      runtimeManifestDefaults.fetchPerHostConcurrencyCap,
      RUNTIME_NUMBER_BOUNDS.fetchPerHostConcurrencyCap,
    ),
    llmMaxOutputTokensPlan: nextRuntimeDraft.llmMaxOutputTokensPlan,
    llmMaxOutputTokensReasoning: nextRuntimeDraft.llmMaxOutputTokensReasoning,
    llmMaxOutputTokensPlanFallback: nextRuntimeDraft.llmMaxOutputTokensPlanFallback,
    llmMaxOutputTokensReasoningFallback: nextRuntimeDraft.llmMaxOutputTokensReasoningFallback,
    resumeWindowHours: parseBoundedNumber(
      nextRuntimeDraft.resumeWindowHours,
      runtimeManifestDefaults.resumeWindowHours,
      RUNTIME_NUMBER_BOUNDS.resumeWindowHours,
    ),
    indexingResumeSeedLimit: parseBoundedNumber(
      nextRuntimeDraft.indexingResumeSeedLimit,
      runtimeManifestDefaults.indexingResumeSeedLimit,
      RUNTIME_NUMBER_BOUNDS.indexingResumeSeedLimit,
    ),
    indexingResumePersistLimit: parseBoundedNumber(
      nextRuntimeDraft.indexingResumePersistLimit,
      runtimeManifestDefaults.indexingResumePersistLimit,
      RUNTIME_NUMBER_BOUNDS.indexingResumePersistLimit,
    ),
    reextractAfterHours: parseBoundedNumber(
      nextRuntimeDraft.reextractAfterHours,
      runtimeManifestDefaults.reextractAfterHours,
      RUNTIME_NUMBER_BOUNDS.reextractAfterHours,
    ),
    scannedPdfOcrMaxPages: parseBoundedNumber(
      nextRuntimeDraft.scannedPdfOcrMaxPages,
      runtimeManifestDefaults.scannedPdfOcrMaxPages,
      RUNTIME_NUMBER_BOUNDS.scannedPdfOcrMaxPages,
    ),
    scannedPdfOcrMaxPairs: parseBoundedNumber(
      nextRuntimeDraft.scannedPdfOcrMaxPairs,
      runtimeManifestDefaults.scannedPdfOcrMaxPairs,
      RUNTIME_NUMBER_BOUNDS.scannedPdfOcrMaxPairs,
    ),
    scannedPdfOcrMinCharsPerPage: parseBoundedNumber(
      nextRuntimeDraft.scannedPdfOcrMinCharsPerPage,
      runtimeManifestDefaults.scannedPdfOcrMinCharsPerPage,
      RUNTIME_NUMBER_BOUNDS.scannedPdfOcrMinCharsPerPage,
    ),
    scannedPdfOcrMinLinesPerPage: parseBoundedNumber(
      nextRuntimeDraft.scannedPdfOcrMinLinesPerPage,
      runtimeManifestDefaults.scannedPdfOcrMinLinesPerPage,
      RUNTIME_NUMBER_BOUNDS.scannedPdfOcrMinLinesPerPage,
    ),
    scannedPdfOcrMinConfidence: parseBoundedNumber(
      nextRuntimeDraft.scannedPdfOcrMinConfidence,
      runtimeManifestDefaults.scannedPdfOcrMinConfidence,
      RUNTIME_NUMBER_BOUNDS.scannedPdfOcrMinConfidence,
    ),
    crawleeRequestHandlerTimeoutSecs: parseBoundedNumber(
      nextRuntimeDraft.crawleeRequestHandlerTimeoutSecs,
      runtimeManifestDefaults.crawleeRequestHandlerTimeoutSecs,
      RUNTIME_NUMBER_BOUNDS.crawleeRequestHandlerTimeoutSecs,
    ),
    dynamicFetchRetryBudget: parseBoundedNumber(
      nextRuntimeDraft.dynamicFetchRetryBudget,
      runtimeManifestDefaults.dynamicFetchRetryBudget,
      RUNTIME_NUMBER_BOUNDS.dynamicFetchRetryBudget,
    ),
    dynamicFetchRetryBackoffMs: parseBoundedNumber(
      nextRuntimeDraft.dynamicFetchRetryBackoffMs,
      runtimeManifestDefaults.dynamicFetchRetryBackoffMs,
      RUNTIME_NUMBER_BOUNDS.dynamicFetchRetryBackoffMs,
    ),
    fetchSchedulerMaxRetries: parseBoundedNumber(
      nextRuntimeDraft.fetchSchedulerMaxRetries,
      runtimeManifestDefaults.fetchSchedulerMaxRetries,
      RUNTIME_NUMBER_BOUNDS.fetchSchedulerMaxRetries,
    ),
    fetchSchedulerFallbackWaitMs: parseBoundedNumber(
      nextRuntimeDraft.fetchSchedulerFallbackWaitMs,
      runtimeManifestDefaults.fetchSchedulerFallbackWaitMs,
      RUNTIME_NUMBER_BOUNDS.fetchSchedulerFallbackWaitMs,
    ),
    pageGotoTimeoutMs: parseBoundedNumber(
      nextRuntimeDraft.pageGotoTimeoutMs,
      runtimeManifestDefaults.pageGotoTimeoutMs,
      RUNTIME_NUMBER_BOUNDS.pageGotoTimeoutMs,
    ),
    pageNetworkIdleTimeoutMs: parseBoundedNumber(
      nextRuntimeDraft.pageNetworkIdleTimeoutMs,
      runtimeManifestDefaults.pageNetworkIdleTimeoutMs,
      RUNTIME_NUMBER_BOUNDS.pageNetworkIdleTimeoutMs,
    ),
    postLoadWaitMs: parseBoundedNumber(
      nextRuntimeDraft.postLoadWaitMs,
      runtimeManifestDefaults.postLoadWaitMs,
      RUNTIME_NUMBER_BOUNDS.postLoadWaitMs,
    ),
    frontierDbPath: String(nextRuntimeDraft.frontierDbPath || '').trim(),
    frontierQueryCooldownSeconds: parseBoundedNumber(
      nextRuntimeDraft.frontierQueryCooldownSeconds,
      runtimeManifestDefaults.frontierQueryCooldownSeconds,
      RUNTIME_NUMBER_BOUNDS.frontierQueryCooldownSeconds,
    ),
    frontierCooldown404Seconds: parseBoundedNumber(
      nextRuntimeDraft.frontierCooldown404Seconds,
      runtimeManifestDefaults.frontierCooldown404Seconds,
      RUNTIME_NUMBER_BOUNDS.frontierCooldown404Seconds,
    ),
    frontierCooldown404RepeatSeconds: parseBoundedNumber(
      nextRuntimeDraft.frontierCooldown404RepeatSeconds,
      runtimeManifestDefaults.frontierCooldown404RepeatSeconds,
      RUNTIME_NUMBER_BOUNDS.frontierCooldown404RepeatSeconds,
    ),
    frontierCooldown410Seconds: parseBoundedNumber(
      nextRuntimeDraft.frontierCooldown410Seconds,
      runtimeManifestDefaults.frontierCooldown410Seconds,
      RUNTIME_NUMBER_BOUNDS.frontierCooldown410Seconds,
    ),
    frontierCooldownTimeoutSeconds: parseBoundedNumber(
      nextRuntimeDraft.frontierCooldownTimeoutSeconds,
      runtimeManifestDefaults.frontierCooldownTimeoutSeconds,
      RUNTIME_NUMBER_BOUNDS.frontierCooldownTimeoutSeconds,
    ),
    frontierCooldown403BaseSeconds: parseBoundedNumber(
      nextRuntimeDraft.frontierCooldown403BaseSeconds,
      runtimeManifestDefaults.frontierCooldown403BaseSeconds,
      RUNTIME_NUMBER_BOUNDS.frontierCooldown403BaseSeconds,
    ),
    frontierCooldown429BaseSeconds: parseBoundedNumber(
      nextRuntimeDraft.frontierCooldown429BaseSeconds,
      runtimeManifestDefaults.frontierCooldown429BaseSeconds,
      RUNTIME_NUMBER_BOUNDS.frontierCooldown429BaseSeconds,
    ),
    frontierBackoffMaxExponent: parseBoundedNumber(
      nextRuntimeDraft.frontierBackoffMaxExponent,
      runtimeManifestDefaults.frontierBackoffMaxExponent,
      RUNTIME_NUMBER_BOUNDS.frontierBackoffMaxExponent,
    ),
    frontierPathPenaltyNotfoundThreshold: parseBoundedNumber(
      nextRuntimeDraft.frontierPathPenaltyNotfoundThreshold,
      runtimeManifestDefaults.frontierPathPenaltyNotfoundThreshold,
      RUNTIME_NUMBER_BOUNDS.frontierPathPenaltyNotfoundThreshold,
    ),
    frontierBlockedDomainThreshold: parseBoundedNumber(
      nextRuntimeDraft.frontierBlockedDomainThreshold,
      runtimeManifestDefaults.frontierBlockedDomainThreshold,
      RUNTIME_NUMBER_BOUNDS.frontierBlockedDomainThreshold,
    ),
    autoScrollPasses: parseBoundedNumber(
      nextRuntimeDraft.autoScrollPasses,
      runtimeManifestDefaults.autoScrollPasses,
      RUNTIME_NUMBER_BOUNDS.autoScrollPasses,
    ),
    autoScrollDelayMs: parseBoundedNumber(
      nextRuntimeDraft.autoScrollDelayMs,
      runtimeManifestDefaults.autoScrollDelayMs,
      RUNTIME_NUMBER_BOUNDS.autoScrollDelayMs,
    ),
    maxGraphqlReplays: parseBoundedNumber(
      nextRuntimeDraft.maxGraphqlReplays,
      runtimeManifestDefaults.maxGraphqlReplays,
      RUNTIME_NUMBER_BOUNDS.maxGraphqlReplays,
    ),
    maxNetworkResponsesPerPage: parseBoundedNumber(
      nextRuntimeDraft.maxNetworkResponsesPerPage,
      runtimeManifestDefaults.maxNetworkResponsesPerPage,
      RUNTIME_NUMBER_BOUNDS.maxNetworkResponsesPerPage,
    ),
    robotsTxtTimeoutMs: parseBoundedNumber(
      nextRuntimeDraft.robotsTxtTimeoutMs,
      runtimeManifestDefaults.robotsTxtTimeoutMs,
      RUNTIME_NUMBER_BOUNDS.robotsTxtTimeoutMs,
    ),
    endpointSignalLimit: parseBoundedNumber(
      nextRuntimeDraft.endpointSignalLimit,
      runtimeManifestDefaults.endpointSignalLimit,
      RUNTIME_NUMBER_BOUNDS.endpointSignalLimit,
    ),
    endpointSuggestionLimit: parseBoundedNumber(
      nextRuntimeDraft.endpointSuggestionLimit,
      runtimeManifestDefaults.endpointSuggestionLimit,
      RUNTIME_NUMBER_BOUNDS.endpointSuggestionLimit,
    ),
    endpointNetworkScanLimit: parseBoundedNumber(
      nextRuntimeDraft.endpointNetworkScanLimit,
      runtimeManifestDefaults.endpointNetworkScanLimit,
      RUNTIME_NUMBER_BOUNDS.endpointNetworkScanLimit,
    ),
    discoveryMaxQueries: parseBoundedNumber(
      nextRuntimeDraft.discoveryMaxQueries,
      runtimeManifestDefaults.discoveryMaxQueries,
      RUNTIME_NUMBER_BOUNDS.discoveryMaxQueries,
    ),
    discoveryMaxDiscovered: parseBoundedNumber(
      nextRuntimeDraft.discoveryMaxDiscovered,
      runtimeManifestDefaults.discoveryMaxDiscovered,
      RUNTIME_NUMBER_BOUNDS.discoveryMaxDiscovered,
    ),
    maxUrlsPerProduct: parseBoundedNumber(
      nextRuntimeDraft.maxUrlsPerProduct,
      runtimeManifestDefaults.maxUrlsPerProduct,
      RUNTIME_NUMBER_BOUNDS.maxUrlsPerProduct,
    ),
    maxCandidateUrls: parseBoundedNumber(
      nextRuntimeDraft.maxCandidateUrls,
      runtimeManifestDefaults.maxCandidateUrls,
      RUNTIME_NUMBER_BOUNDS.maxCandidateUrls,
    ),
    maxPagesPerDomain: parseBoundedNumber(
      nextRuntimeDraft.maxPagesPerDomain,
      runtimeManifestDefaults.maxPagesPerDomain,
      RUNTIME_NUMBER_BOUNDS.maxPagesPerDomain,
    ),
    maxRunSeconds: parseBoundedNumber(
      nextRuntimeDraft.maxRunSeconds,
      runtimeManifestDefaults.maxRunSeconds,
      RUNTIME_NUMBER_BOUNDS.maxRunSeconds,
    ),
    maxJsonBytes: parseBoundedNumber(
      nextRuntimeDraft.maxJsonBytes,
      runtimeManifestDefaults.maxJsonBytes,
      RUNTIME_NUMBER_BOUNDS.maxJsonBytes,
    ),
    maxPdfBytes: parseBoundedNumber(
      nextRuntimeDraft.maxPdfBytes,
      runtimeManifestDefaults.maxPdfBytes,
      RUNTIME_NUMBER_BOUNDS.maxPdfBytes,
    ),
    pdfBackendRouterTimeoutMs: parseBoundedNumber(
      nextRuntimeDraft.pdfBackendRouterTimeoutMs,
      runtimeManifestDefaults.pdfBackendRouterTimeoutMs,
      RUNTIME_NUMBER_BOUNDS.pdfBackendRouterTimeoutMs,
    ),
    pdfBackendRouterMaxPages: parseBoundedNumber(
      nextRuntimeDraft.pdfBackendRouterMaxPages,
      runtimeManifestDefaults.pdfBackendRouterMaxPages,
      RUNTIME_NUMBER_BOUNDS.pdfBackendRouterMaxPages,
    ),
    pdfBackendRouterMaxPairs: parseBoundedNumber(
      nextRuntimeDraft.pdfBackendRouterMaxPairs,
      runtimeManifestDefaults.pdfBackendRouterMaxPairs,
      RUNTIME_NUMBER_BOUNDS.pdfBackendRouterMaxPairs,
    ),
    pdfBackendRouterMaxTextPreviewChars: parseBoundedNumber(
      nextRuntimeDraft.pdfBackendRouterMaxTextPreviewChars,
      runtimeManifestDefaults.pdfBackendRouterMaxTextPreviewChars,
      RUNTIME_NUMBER_BOUNDS.pdfBackendRouterMaxTextPreviewChars,
    ),
    capturePageScreenshotQuality: parseBoundedNumber(
      nextRuntimeDraft.capturePageScreenshotQuality,
      runtimeManifestDefaults.capturePageScreenshotQuality,
      RUNTIME_NUMBER_BOUNDS.capturePageScreenshotQuality,
    ),
    capturePageScreenshotMaxBytes: parseBoundedNumber(
      nextRuntimeDraft.capturePageScreenshotMaxBytes,
      runtimeManifestDefaults.capturePageScreenshotMaxBytes,
      RUNTIME_NUMBER_BOUNDS.capturePageScreenshotMaxBytes,
    ),
    articleExtractorMinChars: parseBoundedNumber(
      nextRuntimeDraft.articleExtractorMinChars,
      runtimeManifestDefaults.articleExtractorMinChars,
      RUNTIME_NUMBER_BOUNDS.articleExtractorMinChars,
    ),
    articleExtractorMinScore: parseBoundedNumber(
      nextRuntimeDraft.articleExtractorMinScore,
      runtimeManifestDefaults.articleExtractorMinScore,
      RUNTIME_NUMBER_BOUNDS.articleExtractorMinScore,
    ),
    articleExtractorMaxChars: parseBoundedNumber(
      nextRuntimeDraft.articleExtractorMaxChars,
      runtimeManifestDefaults.articleExtractorMaxChars,
      RUNTIME_NUMBER_BOUNDS.articleExtractorMaxChars,
    ),
    staticDomTargetMatchThreshold: parseBoundedNumber(
      nextRuntimeDraft.staticDomTargetMatchThreshold,
      runtimeManifestDefaults.staticDomTargetMatchThreshold,
      RUNTIME_NUMBER_BOUNDS.staticDomTargetMatchThreshold,
    ),
    staticDomMaxEvidenceSnippets: parseBoundedNumber(
      nextRuntimeDraft.staticDomMaxEvidenceSnippets,
      runtimeManifestDefaults.staticDomMaxEvidenceSnippets,
      RUNTIME_NUMBER_BOUNDS.staticDomMaxEvidenceSnippets,
    ),
    domSnippetMaxChars: parseBoundedNumber(
      nextRuntimeDraft.domSnippetMaxChars,
      runtimeManifestDefaults.domSnippetMaxChars,
      RUNTIME_NUMBER_BOUNDS.domSnippetMaxChars,
    ),
    llmExtractionCacheTtlMs: parseBoundedNumber(
      nextRuntimeDraft.llmExtractionCacheTtlMs,
      runtimeManifestDefaults.llmExtractionCacheTtlMs,
      RUNTIME_NUMBER_BOUNDS.llmExtractionCacheTtlMs,
    ),
    llmMaxCallsPerProductTotal: parseBoundedNumber(
      nextRuntimeDraft.llmMaxCallsPerProductTotal,
      runtimeManifestDefaults.llmMaxCallsPerProductTotal,
      RUNTIME_NUMBER_BOUNDS.llmMaxCallsPerProductTotal,
    ),
    llmExtractMaxSnippetsPerBatch: parseBoundedNumber(
      nextRuntimeDraft.llmExtractMaxSnippetsPerBatch,
      runtimeManifestDefaults.llmExtractMaxSnippetsPerBatch,
      RUNTIME_NUMBER_BOUNDS.llmExtractMaxSnippetsPerBatch,
    ),
    llmExtractMaxSnippetChars: parseBoundedNumber(
      nextRuntimeDraft.llmExtractMaxSnippetChars,
      runtimeManifestDefaults.llmExtractMaxSnippetChars,
      RUNTIME_NUMBER_BOUNDS.llmExtractMaxSnippetChars,
    ),
    llmReasoningBudget: parseBoundedNumber(
      nextRuntimeDraft.llmReasoningBudget,
      runtimeManifestDefaults.llmReasoningBudget,
      RUNTIME_NUMBER_BOUNDS.llmReasoningBudget,
    ),
    llmMonthlyBudgetUsd: parseBoundedNumber(
      nextRuntimeDraft.llmMonthlyBudgetUsd,
      runtimeManifestDefaults.llmMonthlyBudgetUsd,
      RUNTIME_NUMBER_BOUNDS.llmMonthlyBudgetUsd,
    ),
    llmPerProductBudgetUsd: parseBoundedNumber(
      nextRuntimeDraft.llmPerProductBudgetUsd,
      runtimeManifestDefaults.llmPerProductBudgetUsd,
      RUNTIME_NUMBER_BOUNDS.llmPerProductBudgetUsd,
    ),
    llmMaxCallsPerRound: parseBoundedNumber(
      nextRuntimeDraft.llmMaxCallsPerRound,
      runtimeManifestDefaults.llmMaxCallsPerRound,
      RUNTIME_NUMBER_BOUNDS.llmMaxCallsPerRound,
    ),
    llmMaxOutputTokens: parseBoundedNumber(
      nextRuntimeDraft.llmMaxOutputTokens,
      runtimeManifestDefaults.llmMaxOutputTokens,
      RUNTIME_NUMBER_BOUNDS.llmMaxOutputTokens,
    ),
    llmVerifySampleRate: parseBoundedNumber(
      nextRuntimeDraft.llmVerifySampleRate,
      runtimeManifestDefaults.llmVerifySampleRate,
      RUNTIME_NUMBER_BOUNDS.llmVerifySampleRate,
    ),
    llmMaxBatchesPerProduct: parseBoundedNumber(
      nextRuntimeDraft.llmMaxBatchesPerProduct,
      runtimeManifestDefaults.llmMaxBatchesPerProduct,
      RUNTIME_NUMBER_BOUNDS.llmMaxBatchesPerProduct,
    ),
    llmMaxEvidenceChars: parseBoundedNumber(
      nextRuntimeDraft.llmMaxEvidenceChars,
      runtimeManifestDefaults.llmMaxEvidenceChars,
      RUNTIME_NUMBER_BOUNDS.llmMaxEvidenceChars,
    ),
    llmMaxTokens: parseBoundedNumber(
      nextRuntimeDraft.llmMaxTokens,
      runtimeManifestDefaults.llmMaxTokens,
      RUNTIME_NUMBER_BOUNDS.llmMaxTokens,
    ),
    llmTimeoutMs: parseBoundedNumber(
      nextRuntimeDraft.llmTimeoutMs,
      runtimeManifestDefaults.llmTimeoutMs,
      RUNTIME_NUMBER_BOUNDS.llmTimeoutMs,
    ),
    llmCostInputPer1M: parseBoundedNumber(
      nextRuntimeDraft.llmCostInputPer1M,
      runtimeManifestDefaults.llmCostInputPer1M,
      RUNTIME_NUMBER_BOUNDS.llmCostInputPer1M,
    ),
    llmCostOutputPer1M: parseBoundedNumber(
      nextRuntimeDraft.llmCostOutputPer1M,
      runtimeManifestDefaults.llmCostOutputPer1M,
      RUNTIME_NUMBER_BOUNDS.llmCostOutputPer1M,
    ),
    llmCostCachedInputPer1M: parseBoundedNumber(
      nextRuntimeDraft.llmCostCachedInputPer1M,
      runtimeManifestDefaults.llmCostCachedInputPer1M,
      RUNTIME_NUMBER_BOUNDS.llmCostCachedInputPer1M,
    ),
    maxHypothesisItems: parseBoundedNumber(
      nextRuntimeDraft.maxHypothesisItems,
      runtimeManifestDefaults.maxHypothesisItems,
      RUNTIME_NUMBER_BOUNDS.maxHypothesisItems,
    ),
    hypothesisAutoFollowupRounds: parseBoundedNumber(
      nextRuntimeDraft.hypothesisAutoFollowupRounds,
      runtimeManifestDefaults.hypothesisAutoFollowupRounds,
      RUNTIME_NUMBER_BOUNDS.hypothesisAutoFollowupRounds,
    ),
    hypothesisFollowupUrlsPerRound: parseBoundedNumber(
      nextRuntimeDraft.hypothesisFollowupUrlsPerRound,
      runtimeManifestDefaults.hypothesisFollowupUrlsPerRound,
      RUNTIME_NUMBER_BOUNDS.hypothesisFollowupUrlsPerRound,
    ),
    runtimeScreencastFps: parseBoundedNumber(
      nextRuntimeDraft.runtimeScreencastFps,
      runtimeManifestDefaults.runtimeScreencastFps,
      RUNTIME_NUMBER_BOUNDS.runtimeScreencastFps,
    ),
    runtimeScreencastQuality: parseBoundedNumber(
      nextRuntimeDraft.runtimeScreencastQuality,
      runtimeManifestDefaults.runtimeScreencastQuality,
      RUNTIME_NUMBER_BOUNDS.runtimeScreencastQuality,
    ),
    runtimeScreencastMaxWidth: parseBoundedNumber(
      nextRuntimeDraft.runtimeScreencastMaxWidth,
      runtimeManifestDefaults.runtimeScreencastMaxWidth,
      RUNTIME_NUMBER_BOUNDS.runtimeScreencastMaxWidth,
    ),
    runtimeScreencastMaxHeight: parseBoundedNumber(
      nextRuntimeDraft.runtimeScreencastMaxHeight,
      runtimeManifestDefaults.runtimeScreencastMaxHeight,
      RUNTIME_NUMBER_BOUNDS.runtimeScreencastMaxHeight,
    ),
    runtimeTraceFetchRing: parseBoundedNumber(
      nextRuntimeDraft.runtimeTraceFetchRing,
      runtimeManifestDefaults.runtimeTraceFetchRing,
      RUNTIME_NUMBER_BOUNDS.runtimeTraceFetchRing,
    ),
    runtimeTraceLlmRing: parseBoundedNumber(
      nextRuntimeDraft.runtimeTraceLlmRing,
      runtimeManifestDefaults.runtimeTraceLlmRing,
      RUNTIME_NUMBER_BOUNDS.runtimeTraceLlmRing,
    ),
    daemonConcurrency: parseBoundedNumber(
      nextRuntimeDraft.daemonConcurrency,
      runtimeManifestDefaults.daemonConcurrency,
      RUNTIME_NUMBER_BOUNDS.daemonConcurrency,
    ),
    importsPollSeconds: parseBoundedNumber(
      nextRuntimeDraft.importsPollSeconds,
      runtimeManifestDefaults.importsPollSeconds,
      RUNTIME_NUMBER_BOUNDS.importsPollSeconds,
    ),
    fieldRewardHalfLifeDays: parseBoundedNumber(
      nextRuntimeDraft.fieldRewardHalfLifeDays,
      runtimeManifestDefaults.fieldRewardHalfLifeDays,
      RUNTIME_NUMBER_BOUNDS.fieldRewardHalfLifeDays,
    ),
    driftPollSeconds: parseBoundedNumber(
      nextRuntimeDraft.driftPollSeconds,
      runtimeManifestDefaults.driftPollSeconds,
      RUNTIME_NUMBER_BOUNDS.driftPollSeconds,
    ),
    driftScanMaxProducts: parseBoundedNumber(
      nextRuntimeDraft.driftScanMaxProducts,
      runtimeManifestDefaults.driftScanMaxProducts,
      RUNTIME_NUMBER_BOUNDS.driftScanMaxProducts,
    ),
    reCrawlStaleAfterDays: parseBoundedNumber(
      nextRuntimeDraft.reCrawlStaleAfterDays,
      runtimeManifestDefaults.reCrawlStaleAfterDays,
      RUNTIME_NUMBER_BOUNDS.reCrawlStaleAfterDays,
    ),
    userAgent: String(nextRuntimeDraft.userAgent || '').trim(),
    pdfPreferredBackend: String(nextRuntimeDraft.pdfPreferredBackend || '').trim(),
    capturePageScreenshotFormat: String(nextRuntimeDraft.capturePageScreenshotFormat || '').trim(),
    capturePageScreenshotSelectors: String(nextRuntimeDraft.capturePageScreenshotSelectors || '').trim(),
    runtimeControlFile: String(nextRuntimeDraft.runtimeControlFile || '').trim(),
    staticDomMode: String(nextRuntimeDraft.staticDomMode || '').trim(),
    specDbDir: String(nextRuntimeDraft.specDbDir || '').trim(),
    articleExtractorDomainPolicyMapJson: String(nextRuntimeDraft.articleExtractorDomainPolicyMapJson || '').trim(),
    categoryAuthorityRoot: String(nextRuntimeDraft.categoryAuthorityRoot || '').trim(),
    helperFilesRoot: String(nextRuntimeDraft.helperFilesRoot || '').trim(),
    batchStrategy: String(nextRuntimeDraft.batchStrategy || '').trim(),
    dynamicFetchPolicyMapJson: String(nextRuntimeDraft.dynamicFetchPolicyMapJson || '').trim(),
    searchProfileCapMapJson: String(nextRuntimeDraft.searchProfileCapMapJson || '').trim(),
    serpRerankerWeightMapJson: String(nextRuntimeDraft.serpRerankerWeightMapJson || '').trim(),
    llmProviderRegistryJson: String(nextRuntimeDraft.llmProviderRegistryJson || '').trim(),
    llmPhaseOverridesJson: String(nextRuntimeDraft.llmPhaseOverridesJson || '').trim(),
    fetchSchedulerInternalsMapJson: String(nextRuntimeDraft.fetchSchedulerInternalsMapJson || '').trim(),
    parsingConfidenceBaseMapJson: String(nextRuntimeDraft.parsingConfidenceBaseMapJson || '').trim(),
    repairDedupeRule: (String(nextRuntimeDraft.repairDedupeRule || '').trim() || runtimeManifestDefaults.repairDedupeRule) as RuntimeRepairDedupeRule,
    scannedPdfOcrEnabled: nextRuntimeDraft.scannedPdfOcrEnabled,
    localMode: nextRuntimeDraft.localMode,
    dryRun: nextRuntimeDraft.dryRun,
    mirrorToS3: nextRuntimeDraft.mirrorToS3,
    mirrorToS3Input: nextRuntimeDraft.mirrorToS3Input,
    writeMarkdownSummary: nextRuntimeDraft.writeMarkdownSummary,
    llmWriteSummary: nextRuntimeDraft.llmWriteSummary,
    llmExtractSkipLowSignal: nextRuntimeDraft.llmExtractSkipLowSignal,
    llmReasoningMode: nextRuntimeDraft.llmReasoningMode,
    llmPlanUseReasoning: nextRuntimeDraft.llmPlanUseReasoning,
    llmVerifyMode: nextRuntimeDraft.llmVerifyMode,
    reextractIndexed: nextRuntimeDraft.reextractIndexed,
    fetchCandidateSources: nextRuntimeDraft.fetchCandidateSources,
    pdfBackendRouterEnabled: nextRuntimeDraft.pdfBackendRouterEnabled,
    capturePageScreenshotEnabled: nextRuntimeDraft.capturePageScreenshotEnabled,
    categoryAuthorityEnabled: nextRuntimeDraft.categoryAuthorityEnabled,
    helperSupportiveFillMissing: nextRuntimeDraft.helperSupportiveFillMissing,
    driftDetectionEnabled: nextRuntimeDraft.driftDetectionEnabled,
    driftAutoRepublish: nextRuntimeDraft.driftAutoRepublish,
    indexingCategoryAuthorityEnabled: nextRuntimeDraft.indexingCategoryAuthorityEnabled,
    manufacturerAutoPromote: nextRuntimeDraft.manufacturerAutoPromote,
    dynamicCrawleeEnabled: nextRuntimeDraft.dynamicCrawleeEnabled,
    crawleeHeadless: nextRuntimeDraft.crawleeHeadless,
    preferHttpFetcher: nextRuntimeDraft.preferHttpFetcher,
    frontierStripTrackingParams: nextRuntimeDraft.frontierStripTrackingParams,
    autoScrollEnabled: nextRuntimeDraft.autoScrollEnabled,
    graphqlReplayEnabled: nextRuntimeDraft.graphqlReplayEnabled,
    robotsTxtCompliant: nextRuntimeDraft.robotsTxtCompliant,
    runtimeScreencastEnabled: nextRuntimeDraft.runtimeScreencastEnabled,
    runtimeTraceEnabled: nextRuntimeDraft.runtimeTraceEnabled,
    runtimeTraceLlmPayloads: nextRuntimeDraft.runtimeTraceLlmPayloads,
    eventsJsonWrite: nextRuntimeDraft.eventsJsonWrite,
    indexingSchemaPacketsValidationEnabled: nextRuntimeDraft.indexingSchemaPacketsValidationEnabled,
    indexingSchemaPacketsValidationStrict: nextRuntimeDraft.indexingSchemaPacketsValidationStrict,
    selfImproveEnabled: nextRuntimeDraft.selfImproveEnabled,
    runtimeSettingsFallbackBaseline: runtimeManifestDefaults,
    resolveModelTokenDefaults,
  });
}

