import { SETTINGS_OPTION_VALUES } from '../../shared/settingsDefaults.js';
import {
  CATEGORY_AUTHORITY_ROOT_KEY,
  CATEGORY_AUTHORITY_ENABLED_KEY,
  INDEXING_CATEGORY_AUTHORITY_ENABLED_KEY,
} from './runtimeSettingsRouteGet.js';

export const RUNTIME_SETTINGS_ROUTE_PUT = Object.freeze({
  dynamicFetchPolicyMapJsonKey: 'dynamicFetchPolicyMapJson',
  stringEnumMap: Object.freeze({
    resumeMode: Object.freeze({ cfgKey: 'indexingResumeMode', allowed: SETTINGS_OPTION_VALUES.runtime.resumeMode }),
    scannedPdfOcrBackend: Object.freeze({ cfgKey: 'scannedPdfOcrBackend', allowed: SETTINGS_OPTION_VALUES.runtime.scannedPdfOcrBackend }),
    searchProvider: Object.freeze({ cfgKey: 'searchProvider', allowed: SETTINGS_OPTION_VALUES.runtime.searchProvider }),
    repairDedupeRule: Object.freeze({ cfgKey: 'repairDedupeRule', allowed: SETTINGS_OPTION_VALUES.runtime.repairDedupeRule }),
    automationQueueStorageEngine: Object.freeze({ cfgKey: 'automationQueueStorageEngine', allowed: SETTINGS_OPTION_VALUES.runtime.automationQueueStorageEngine }),
    outputMode: Object.freeze({ cfgKey: 'outputMode', allowed: SETTINGS_OPTION_VALUES.runtime.outputMode }),
  }),
  stringFreeMap: Object.freeze({
    searxngBaseUrl: 'searxngBaseUrl',
    llmPlanApiKey: 'llmPlanApiKey',
    llmPlanProvider: 'llmPlanProvider',
    llmPlanBaseUrl: 'llmPlanBaseUrl',
    pdfPreferredBackend: 'pdfPreferredBackend',
    capturePageScreenshotFormat: 'capturePageScreenshotFormat',
    capturePageScreenshotSelectors: 'capturePageScreenshotSelectors',
    runtimeScreenshotMode: 'runtimeScreenshotMode',
    runtimeControlFile: 'runtimeControlFile',
    staticDomMode: 'staticDomMode',
    [CATEGORY_AUTHORITY_ROOT_KEY]: CATEGORY_AUTHORITY_ROOT_KEY,
    batchStrategy: 'batchStrategy',
    specDbDir: 'specDbDir',
    articleExtractorDomainPolicyMapJson: 'articleExtractorDomainPolicyMapJson',
    structuredMetadataExtructUrl: 'structuredMetadataExtructUrl',
    llmExtractionCacheDir: 'llmExtractionCacheDir',
    userAgent: 'userAgent',
    frontierDbPath: 'frontierDbPath',
    searchProfileCapMapJson: 'searchProfileCapMapJson',
    serpRerankerWeightMapJson: 'serpRerankerWeightMapJson',
    fetchSchedulerInternalsMapJson: 'fetchSchedulerInternalsMapJson',
    retrievalInternalsMapJson: 'retrievalInternalsMapJson',
    evidencePackLimitsMapJson: 'evidencePackLimitsMapJson',
    parsingConfidenceBaseMapJson: 'parsingConfidenceBaseMapJson',
    phase2LlmModel: 'llmModelPlan',
    phase3LlmModel: 'llmModelTriage',
    llmModelFast: 'llmModelFast',
    llmModelReasoning: 'llmModelReasoning',
    llmModelExtract: 'llmModelExtract',
    llmModelValidate: 'llmModelValidate',
    llmModelWrite: 'llmModelWrite',
    importsRoot: 'importsRoot',
    localInputRoot: 'localInputRoot',
    localOutputRoot: 'localOutputRoot',
    runtimeEventsKey: 'runtimeEventsKey',
    s3InputPrefix: 's3InputPrefix',
    s3OutputPrefix: 's3OutputPrefix',
    eloSupabaseAnonKey: 'eloSupabaseAnonKey',
    eloSupabaseEndpoint: 'eloSupabaseEndpoint',
    llmProvider: 'llmProvider',
    llmBaseUrl: 'llmBaseUrl',
    openaiApiKey: 'openaiApiKey',
    anthropicApiKey: 'anthropicApiKey',
    cortexBaseUrl: 'cortexBaseUrl',
    cortexApiKey: 'cortexApiKey',
    cortexAsyncBaseUrl: 'cortexAsyncBaseUrl',
    cortexAsyncSubmitPath: 'cortexAsyncSubmitPath',
    cortexAsyncStatusPath: 'cortexAsyncStatusPath',
    cortexModelFast: 'cortexModelFast',
    cortexModelDom: 'cortexModelDom',
    cortexModelReasoningDeep: 'cortexModelReasoningDeep',
    cortexModelVision: 'cortexModelVision',
    cortexModelSearchFast: 'cortexModelSearchFast',
    cortexModelRerankFast: 'cortexModelRerankFast',
    helperFilesRoot: 'helperFilesRoot',
  }),
  stringTrimMap: Object.freeze({
    fetchSchedulerInternalsMapJson: 'fetchSchedulerInternalsMapJson',
    retrievalInternalsMapJson: 'retrievalInternalsMapJson',
    evidencePackLimitsMapJson: 'evidencePackLimitsMapJson',
    parsingConfidenceBaseMapJson: 'parsingConfidenceBaseMapJson',
  }),
  intRangeMap: Object.freeze({
    fetchConcurrency: Object.freeze({ cfgKey: 'concurrency', min: 1, max: 64 }),
    perHostMinDelayMs: Object.freeze({ cfgKey: 'perHostMinDelayMs', min: 0, max: 120000 }),
    searchGlobalRps: Object.freeze({ cfgKey: 'searchGlobalRps', min: 0, max: 100 }),
    searchGlobalBurst: Object.freeze({ cfgKey: 'searchGlobalBurst', min: 0, max: 1000 }),
    searchPerHostRps: Object.freeze({ cfgKey: 'searchPerHostRps', min: 0, max: 100 }),
    searchPerHostBurst: Object.freeze({ cfgKey: 'searchPerHostBurst', min: 0, max: 1000 }),
    domainRequestRps: Object.freeze({ cfgKey: 'domainRequestRps', min: 0, max: 100 }),
    domainRequestBurst: Object.freeze({ cfgKey: 'domainRequestBurst', min: 0, max: 1000 }),
    globalRequestRps: Object.freeze({ cfgKey: 'globalRequestRps', min: 0, max: 100 }),
    globalRequestBurst: Object.freeze({ cfgKey: 'globalRequestBurst', min: 0, max: 1000 }),
    fetchPerHostConcurrencyCap: Object.freeze({ cfgKey: 'fetchPerHostConcurrencyCap', min: 1, max: 64 }),
    discoveryMaxQueries: Object.freeze({ cfgKey: 'discoveryMaxQueries', min: 1, max: 100 }),
    discoveryMaxDiscovered: Object.freeze({ cfgKey: 'discoveryMaxDiscovered', min: 1, max: 2000 }),
    maxUrlsPerProduct: Object.freeze({ cfgKey: 'maxUrlsPerProduct', min: 1, max: 1000 }),
    maxCandidateUrls: Object.freeze({ cfgKey: 'maxCandidateUrls', min: 1, max: 5000 }),
    serpTriageMaxUrls: Object.freeze({ cfgKey: 'serpTriageMaxUrls', min: 5, max: 30 }),
    maxPagesPerDomain: Object.freeze({ cfgKey: 'maxPagesPerDomain', min: 1, max: 100 }),
    maxRunSeconds: Object.freeze({ cfgKey: 'maxRunSeconds', min: 30, max: 86400 }),
    maxJsonBytes: Object.freeze({ cfgKey: 'maxJsonBytes', min: 1024, max: 100000000 }),
    maxPdfBytes: Object.freeze({ cfgKey: 'maxPdfBytes', min: 1024, max: 100000000 }),
    pdfBackendRouterTimeoutMs: Object.freeze({ cfgKey: 'pdfBackendRouterTimeoutMs', min: 10000, max: 300000 }),
    pdfBackendRouterMaxPages: Object.freeze({ cfgKey: 'pdfBackendRouterMaxPages', min: 1, max: 300 }),
    pdfBackendRouterMaxPairs: Object.freeze({ cfgKey: 'pdfBackendRouterMaxPairs', min: 100, max: 20000 }),
    pdfBackendRouterMaxTextPreviewChars: Object.freeze({ cfgKey: 'pdfBackendRouterMaxTextPreviewChars', min: 1000, max: 100000 }),
    capturePageScreenshotQuality: Object.freeze({ cfgKey: 'capturePageScreenshotQuality', min: 1, max: 100 }),
    capturePageScreenshotMaxBytes: Object.freeze({ cfgKey: 'capturePageScreenshotMaxBytes', min: 1024, max: 100000000 }),
    articleExtractorMinChars: Object.freeze({ cfgKey: 'articleExtractorMinChars', min: 50, max: 200000 }),
    articleExtractorMinScore: Object.freeze({ cfgKey: 'articleExtractorMinScore', min: 1, max: 100 }),
    articleExtractorMaxChars: Object.freeze({ cfgKey: 'articleExtractorMaxChars', min: 256, max: 500000 }),
    staticDomMaxEvidenceSnippets: Object.freeze({ cfgKey: 'staticDomMaxEvidenceSnippets', min: 10, max: 500 }),
    structuredMetadataExtructTimeoutMs: Object.freeze({ cfgKey: 'structuredMetadataExtructTimeoutMs', min: 250, max: 15000 }),
    structuredMetadataExtructMaxItemsPerSurface: Object.freeze({ cfgKey: 'structuredMetadataExtructMaxItemsPerSurface', min: 1, max: 1000 }),
    structuredMetadataExtructCacheLimit: Object.freeze({ cfgKey: 'structuredMetadataExtructCacheLimit', min: 32, max: 5000 }),
    domSnippetMaxChars: Object.freeze({ cfgKey: 'domSnippetMaxChars', min: 600, max: 20000 }),
    llmExtractionCacheTtlMs: Object.freeze({ cfgKey: 'llmExtractionCacheTtlMs', min: 60000, max: 31536000000 }),
    llmMaxCallsPerProductTotal: Object.freeze({ cfgKey: 'llmMaxCallsPerProductTotal', min: 1, max: 100 }),
    llmMaxCallsPerProductFast: Object.freeze({ cfgKey: 'llmMaxCallsPerProductFast', min: 0, max: 100 }),
    helperSupportiveMaxSources: Object.freeze({ cfgKey: 'helperSupportiveMaxSources', min: 0, max: 100 }),
    helperActiveSyncLimit: Object.freeze({ cfgKey: 'helperActiveSyncLimit', min: 0, max: 5000 }),
    fieldRewardHalfLifeDays: Object.freeze({ cfgKey: 'fieldRewardHalfLifeDays', min: 1, max: 365 }),
    driftPollSeconds: Object.freeze({ cfgKey: 'driftPollSeconds', min: 60, max: 604800 }),
    driftScanMaxProducts: Object.freeze({ cfgKey: 'driftScanMaxProducts', min: 1, max: 10000 }),
    cortexSyncTimeoutMs: Object.freeze({ cfgKey: 'cortexSyncTimeoutMs', min: 1000, max: 600000 }),
    cortexAsyncPollIntervalMs: Object.freeze({ cfgKey: 'cortexAsyncPollIntervalMs', min: 250, max: 120000 }),
    cortexAsyncMaxWaitMs: Object.freeze({ cfgKey: 'cortexAsyncMaxWaitMs', min: 1000, max: 3600000 }),
    cortexEnsureReadyTimeoutMs: Object.freeze({ cfgKey: 'cortexEnsureReadyTimeoutMs', min: 1000, max: 300000 }),
    cortexStartReadyTimeoutMs: Object.freeze({ cfgKey: 'cortexStartReadyTimeoutMs', min: 1000, max: 300000 }),
    cortexFailureThreshold: Object.freeze({ cfgKey: 'cortexFailureThreshold', min: 1, max: 20 }),
    cortexCircuitOpenMs: Object.freeze({ cfgKey: 'cortexCircuitOpenMs', min: 1000, max: 600000 }),
    cortexMaxDeepFieldsPerProduct: Object.freeze({ cfgKey: 'cortexMaxDeepFieldsPerProduct', min: 1, max: 200 }),
    maxManufacturerUrlsPerProduct: Object.freeze({ cfgKey: 'maxManufacturerUrlsPerProduct', min: 1, max: 1000 }),
    maxManufacturerPagesPerDomain: Object.freeze({ cfgKey: 'maxManufacturerPagesPerDomain', min: 1, max: 200 }),
    manufacturerReserveUrls: Object.freeze({ cfgKey: 'manufacturerReserveUrls', min: 0, max: 1000 }),
    maxHypothesisItems: Object.freeze({ cfgKey: 'maxHypothesisItems', min: 1, max: 1000 }),
    hypothesisAutoFollowupRounds: Object.freeze({ cfgKey: 'hypothesisAutoFollowupRounds', min: 0, max: 10 }),
    hypothesisFollowupUrlsPerRound: Object.freeze({ cfgKey: 'hypothesisFollowupUrlsPerRound', min: 1, max: 200 }),
    llmTokensPlan: Object.freeze({ cfgKey: 'llmMaxOutputTokensPlan', min: 128, max: 262144 }),
    llmTokensTriage: Object.freeze({ cfgKey: 'llmMaxOutputTokensTriage', min: 128, max: 262144 }),
    llmTokensFast: Object.freeze({ cfgKey: 'llmMaxOutputTokensFast', min: 128, max: 262144 }),
    llmTokensReasoning: Object.freeze({ cfgKey: 'llmMaxOutputTokensReasoning', min: 128, max: 262144 }),
    llmTokensExtract: Object.freeze({ cfgKey: 'llmMaxOutputTokensExtract', min: 128, max: 262144 }),
    llmTokensValidate: Object.freeze({ cfgKey: 'llmMaxOutputTokensValidate', min: 128, max: 262144 }),
    llmTokensWrite: Object.freeze({ cfgKey: 'llmMaxOutputTokensWrite', min: 128, max: 262144 }),
    llmTokensPlanFallback: Object.freeze({ cfgKey: 'llmMaxOutputTokensPlanFallback', min: 128, max: 262144 }),
    llmTokensExtractFallback: Object.freeze({ cfgKey: 'llmMaxOutputTokensExtractFallback', min: 128, max: 262144 }),
    llmTokensValidateFallback: Object.freeze({ cfgKey: 'llmMaxOutputTokensValidateFallback', min: 128, max: 262144 }),
    llmTokensWriteFallback: Object.freeze({ cfgKey: 'llmMaxOutputTokensWriteFallback', min: 128, max: 262144 }),
    consensusStrictAcceptanceDomainCount: Object.freeze({ cfgKey: 'consensusStrictAcceptanceDomainCount', min: 1, max: 50 }),
    consensusRelaxedAcceptanceDomainCount: Object.freeze({ cfgKey: 'consensusRelaxedAcceptanceDomainCount', min: 1, max: 50 }),
    consensusInstrumentedFieldThreshold: Object.freeze({ cfgKey: 'consensusInstrumentedFieldThreshold', min: 1, max: 50 }),
    consensusPassTargetIdentityStrong: Object.freeze({ cfgKey: 'consensusPassTargetIdentityStrong', min: 1, max: 50 }),
    consensusPassTargetNormal: Object.freeze({ cfgKey: 'consensusPassTargetNormal', min: 1, max: 50 }),
    evidenceTextMaxChars: Object.freeze({ cfgKey: 'evidenceTextMaxChars', min: 200, max: 200000 }),
    llmExtractMaxTokens: Object.freeze({ cfgKey: 'llmExtractMaxTokens', min: 128, max: 262144 }),
    llmExtractMaxSnippetsPerBatch: Object.freeze({ cfgKey: 'llmExtractMaxSnippetsPerBatch', min: 1, max: 50 }),
    llmExtractMaxSnippetChars: Object.freeze({ cfgKey: 'llmExtractMaxSnippetChars', min: 100, max: 200000 }),
    llmExtractReasoningBudget: Object.freeze({ cfgKey: 'llmExtractReasoningBudget', min: 128, max: 262144 }),
    llmReasoningBudget: Object.freeze({ cfgKey: 'llmReasoningBudget', min: 128, max: 262144 }),
    llmMaxCallsPerRound: Object.freeze({ cfgKey: 'llmMaxCallsPerRound', min: 1, max: 200 }),
    llmMaxOutputTokens: Object.freeze({ cfgKey: 'llmMaxOutputTokens', min: 128, max: 262144 }),
    llmVerifySampleRate: Object.freeze({ cfgKey: 'llmVerifySampleRate', min: 1, max: 1000 }),
    llmMaxBatchesPerProduct: Object.freeze({ cfgKey: 'llmMaxBatchesPerProduct', min: 1, max: 100 }),
    llmMaxEvidenceChars: Object.freeze({ cfgKey: 'llmMaxEvidenceChars', min: 1000, max: 500000 }),
    llmMaxTokens: Object.freeze({ cfgKey: 'llmMaxTokens', min: 128, max: 262144 }),
    llmTimeoutMs: Object.freeze({ cfgKey: 'llmTimeoutMs', min: 1000, max: 600000 }),
    resumeWindowHours: Object.freeze({ cfgKey: 'indexingResumeMaxAgeHours', min: 1, max: 8760 }),
    indexingResumeSeedLimit: Object.freeze({ cfgKey: 'indexingResumeSeedLimit', min: 1, max: 10000 }),
    indexingResumePersistLimit: Object.freeze({ cfgKey: 'indexingResumePersistLimit', min: 1, max: 100000 }),
    reextractAfterHours: Object.freeze({ cfgKey: 'indexingReextractAfterHours', min: 1, max: 8760 }),
    reCrawlStaleAfterDays: Object.freeze({ cfgKey: 'reCrawlStaleAfterDays', min: 1, max: 3650 }),
    scannedPdfOcrMaxPages: Object.freeze({ cfgKey: 'scannedPdfOcrMaxPages', min: 1, max: 100 }),
    scannedPdfOcrMaxPairs: Object.freeze({ cfgKey: 'scannedPdfOcrMaxPairs', min: 50, max: 20000 }),
    scannedPdfOcrMinCharsPerPage: Object.freeze({ cfgKey: 'scannedPdfOcrMinCharsPerPage', min: 1, max: 500 }),
    scannedPdfOcrMinLinesPerPage: Object.freeze({ cfgKey: 'scannedPdfOcrMinLinesPerPage', min: 1, max: 100 }),
    crawleeRequestHandlerTimeoutSecs: Object.freeze({ cfgKey: 'crawleeRequestHandlerTimeoutSecs', min: 0, max: 300 }),
    dynamicFetchRetryBudget: Object.freeze({ cfgKey: 'dynamicFetchRetryBudget', min: 0, max: 5 }),
    dynamicFetchRetryBackoffMs: Object.freeze({ cfgKey: 'dynamicFetchRetryBackoffMs', min: 0, max: 30000 }),
    fetchSchedulerMaxRetries: Object.freeze({ cfgKey: 'fetchSchedulerMaxRetries', min: 0, max: 20 }),
    fetchSchedulerFallbackWaitMs: Object.freeze({ cfgKey: 'fetchSchedulerFallbackWaitMs', min: 0, max: 600000 }),
    pageGotoTimeoutMs: Object.freeze({ cfgKey: 'pageGotoTimeoutMs', min: 0, max: 120000 }),
    pageNetworkIdleTimeoutMs: Object.freeze({ cfgKey: 'pageNetworkIdleTimeoutMs', min: 0, max: 60000 }),
    postLoadWaitMs: Object.freeze({ cfgKey: 'postLoadWaitMs', min: 0, max: 60000 }),
    frontierQueryCooldownSeconds: Object.freeze({ cfgKey: 'frontierQueryCooldownSeconds', min: 0, max: 31536000 }),
    frontierCooldown404Seconds: Object.freeze({ cfgKey: 'frontierCooldown404Seconds', min: 0, max: 31536000 }),
    frontierCooldown404RepeatSeconds: Object.freeze({ cfgKey: 'frontierCooldown404RepeatSeconds', min: 0, max: 31536000 }),
    frontierCooldown410Seconds: Object.freeze({ cfgKey: 'frontierCooldown410Seconds', min: 0, max: 31536000 }),
    frontierCooldownTimeoutSeconds: Object.freeze({ cfgKey: 'frontierCooldownTimeoutSeconds', min: 0, max: 31536000 }),
    frontierCooldown403BaseSeconds: Object.freeze({ cfgKey: 'frontierCooldown403BaseSeconds', min: 0, max: 86400 }),
    frontierCooldown429BaseSeconds: Object.freeze({ cfgKey: 'frontierCooldown429BaseSeconds', min: 0, max: 86400 }),
    frontierBackoffMaxExponent: Object.freeze({ cfgKey: 'frontierBackoffMaxExponent', min: 1, max: 12 }),
    frontierPathPenaltyNotfoundThreshold: Object.freeze({ cfgKey: 'frontierPathPenaltyNotfoundThreshold', min: 1, max: 50 }),
    frontierBlockedDomainThreshold: Object.freeze({ cfgKey: 'frontierBlockedDomainThreshold', min: 1, max: 50 }),
    autoScrollPasses: Object.freeze({ cfgKey: 'autoScrollPasses', min: 0, max: 20 }),
    autoScrollDelayMs: Object.freeze({ cfgKey: 'autoScrollDelayMs', min: 0, max: 10000 }),
    maxGraphqlReplays: Object.freeze({ cfgKey: 'maxGraphqlReplays', min: 0, max: 20 }),
    maxNetworkResponsesPerPage: Object.freeze({ cfgKey: 'maxNetworkResponsesPerPage', min: 100, max: 10000 }),
    robotsTxtTimeoutMs: Object.freeze({ cfgKey: 'robotsTxtTimeoutMs', min: 100, max: 120000 }),
    endpointSignalLimit: Object.freeze({ cfgKey: 'endpointSignalLimit', min: 1, max: 500 }),
    endpointSuggestionLimit: Object.freeze({ cfgKey: 'endpointSuggestionLimit', min: 1, max: 200 }),
    endpointNetworkScanLimit: Object.freeze({ cfgKey: 'endpointNetworkScanLimit', min: 50, max: 10000 }),
    runtimeTraceFetchRing: Object.freeze({ cfgKey: 'runtimeTraceFetchRing', min: 10, max: 2000 }),
    runtimeTraceLlmRing: Object.freeze({ cfgKey: 'runtimeTraceLlmRing', min: 10, max: 2000 }),
    daemonConcurrency: Object.freeze({ cfgKey: 'daemonConcurrency', min: 1, max: 128 }),
    daemonGracefulShutdownTimeoutMs: Object.freeze({ cfgKey: 'daemonGracefulShutdownTimeoutMs', min: 1000, max: 600000 }),
    importsPollSeconds: Object.freeze({ cfgKey: 'importsPollSeconds', min: 1, max: 3600 }),
    runtimeScreencastFps: Object.freeze({ cfgKey: 'runtimeScreencastFps', min: 1, max: 60 }),
    runtimeScreencastQuality: Object.freeze({ cfgKey: 'runtimeScreencastQuality', min: 10, max: 100 }),
    runtimeScreencastMaxWidth: Object.freeze({ cfgKey: 'runtimeScreencastMaxWidth', min: 320, max: 3840 }),
    runtimeScreencastMaxHeight: Object.freeze({ cfgKey: 'runtimeScreencastMaxHeight', min: 240, max: 2160 }),
    fetchBudgetMs: Object.freeze({ cfgKey: 'fetchBudgetMs', min: 5000, max: 300000 }),
  }),
  floatRangeMap: Object.freeze({
    scannedPdfOcrMinConfidence: Object.freeze({ cfgKey: 'scannedPdfOcrMinConfidence', min: 0, max: 1 }),
    staticDomTargetMatchThreshold: Object.freeze({ cfgKey: 'staticDomTargetMatchThreshold', min: 0, max: 1 }),
    cortexEscalateConfidenceLt: Object.freeze({ cfgKey: 'cortexEscalateConfidenceLt', min: 0, max: 1 }),
    identityGatePublishThreshold: Object.freeze({ cfgKey: 'identityGatePublishThreshold', min: 0, max: 1 }),
    identityGateBaseMatchThreshold: Object.freeze({ cfgKey: 'identityGateBaseMatchThreshold', min: 0, max: 1 }),
    consensusMethodWeightNetworkJson: Object.freeze({ cfgKey: 'consensusMethodWeightNetworkJson', min: 0, max: 2 }),
    consensusMethodWeightAdapterApi: Object.freeze({ cfgKey: 'consensusMethodWeightAdapterApi', min: 0, max: 2 }),
    consensusMethodWeightStructuredMeta: Object.freeze({ cfgKey: 'consensusMethodWeightStructuredMeta', min: 0, max: 2 }),
    consensusMethodWeightPdf: Object.freeze({ cfgKey: 'consensusMethodWeightPdf', min: 0, max: 2 }),
    consensusMethodWeightTableKv: Object.freeze({ cfgKey: 'consensusMethodWeightTableKv', min: 0, max: 2 }),
    consensusMethodWeightDom: Object.freeze({ cfgKey: 'consensusMethodWeightDom', min: 0, max: 2 }),
    consensusMethodWeightLlmExtractBase: Object.freeze({ cfgKey: 'consensusMethodWeightLlmExtractBase', min: 0, max: 2 }),
    consensusPolicyBonus: Object.freeze({ cfgKey: 'consensusPolicyBonus', min: -5, max: 5 }),
    consensusWeightedMajorityThreshold: Object.freeze({ cfgKey: 'consensusWeightedMajorityThreshold', min: 1, max: 10 }),
    consensusConfidenceScoringBase: Object.freeze({ cfgKey: 'consensusConfidenceScoringBase', min: 0, max: 1 }),
    retrievalTierWeightTier1: Object.freeze({ cfgKey: 'retrievalTierWeightTier1', min: 0, max: 10 }),
    retrievalTierWeightTier2: Object.freeze({ cfgKey: 'retrievalTierWeightTier2', min: 0, max: 10 }),
    retrievalTierWeightTier3: Object.freeze({ cfgKey: 'retrievalTierWeightTier3', min: 0, max: 10 }),
    retrievalTierWeightTier4: Object.freeze({ cfgKey: 'retrievalTierWeightTier4', min: 0, max: 10 }),
    retrievalTierWeightTier5: Object.freeze({ cfgKey: 'retrievalTierWeightTier5', min: 0, max: 10 }),
    retrievalDocKindWeightManualPdf: Object.freeze({ cfgKey: 'retrievalDocKindWeightManualPdf', min: 0, max: 10 }),
    retrievalDocKindWeightSpecPdf: Object.freeze({ cfgKey: 'retrievalDocKindWeightSpecPdf', min: 0, max: 10 }),
    retrievalDocKindWeightSupport: Object.freeze({ cfgKey: 'retrievalDocKindWeightSupport', min: 0, max: 10 }),
    retrievalDocKindWeightLabReview: Object.freeze({ cfgKey: 'retrievalDocKindWeightLabReview', min: 0, max: 10 }),
    retrievalDocKindWeightProductPage: Object.freeze({ cfgKey: 'retrievalDocKindWeightProductPage', min: 0, max: 10 }),
    retrievalDocKindWeightOther: Object.freeze({ cfgKey: 'retrievalDocKindWeightOther', min: 0, max: 10 }),
    retrievalMethodWeightTable: Object.freeze({ cfgKey: 'retrievalMethodWeightTable', min: 0, max: 10 }),
    retrievalMethodWeightKv: Object.freeze({ cfgKey: 'retrievalMethodWeightKv', min: 0, max: 10 }),
    retrievalMethodWeightJsonLd: Object.freeze({ cfgKey: 'retrievalMethodWeightJsonLd', min: 0, max: 10 }),
    retrievalMethodWeightLlmExtract: Object.freeze({ cfgKey: 'retrievalMethodWeightLlmExtract', min: 0, max: 10 }),
    retrievalMethodWeightHelperSupportive: Object.freeze({ cfgKey: 'retrievalMethodWeightHelperSupportive', min: 0, max: 10 }),
    retrievalAnchorScorePerMatch: Object.freeze({ cfgKey: 'retrievalAnchorScorePerMatch', min: 0, max: 2 }),
    retrievalIdentityScorePerMatch: Object.freeze({ cfgKey: 'retrievalIdentityScorePerMatch', min: 0, max: 2 }),
    retrievalUnitMatchBonus: Object.freeze({ cfgKey: 'retrievalUnitMatchBonus', min: 0, max: 2 }),
    retrievalDirectFieldMatchBonus: Object.freeze({ cfgKey: 'retrievalDirectFieldMatchBonus', min: 0, max: 2 }),
    qualityGateIdentityThreshold: Object.freeze({ cfgKey: 'qualityGateIdentityThreshold', min: 0, max: 1 }),
    llmMonthlyBudgetUsd: Object.freeze({ cfgKey: 'llmMonthlyBudgetUsd', min: 0, max: 100000 }),
    llmPerProductBudgetUsd: Object.freeze({ cfgKey: 'llmPerProductBudgetUsd', min: 0, max: 1000 }),
    llmCostInputPer1M: Object.freeze({ cfgKey: 'llmCostInputPer1M', min: 0, max: 1000 }),
    llmCostOutputPer1M: Object.freeze({ cfgKey: 'llmCostOutputPer1M', min: 0, max: 1000 }),
    llmCostCachedInputPer1M: Object.freeze({ cfgKey: 'llmCostCachedInputPer1M', min: 0, max: 1000 }),
  }),
  boolMap: Object.freeze({
    // discoveryEnabled removed — hardcoded invariant, no GUI toggle
    enableSourceRegistry: 'enableSourceRegistry',
    enableDomainHintResolverV2: 'enableDomainHintResolverV2',
    enableQueryCompiler: 'enableQueryCompiler',
    enableCoreDeepGates: 'enableCoreDeepGates',
    fetchCandidateSources: 'fetchCandidateSources',
    manufacturerBroadDiscovery: 'manufacturerBroadDiscovery',
    manufacturerSeedSearchUrls: 'manufacturerSeedSearchUrls',
    manufacturerDeepResearchEnabled: 'manufacturerDeepResearchEnabled',
    pdfBackendRouterEnabled: 'pdfBackendRouterEnabled',
    capturePageScreenshotEnabled: 'capturePageScreenshotEnabled',
    runtimeCaptureScreenshots: 'runtimeCaptureScreenshots',
    chartExtractionEnabled: 'chartExtractionEnabled',
    articleExtractorV2Enabled: 'articleExtractorV2Enabled',
    staticDomExtractorEnabled: 'staticDomExtractorEnabled',
    htmlTableExtractorV2: 'htmlTableExtractorV2',
    structuredMetadataExtructEnabled: 'structuredMetadataExtructEnabled',
    structuredMetadataExtructCacheEnabled: 'structuredMetadataExtructCacheEnabled',
    [CATEGORY_AUTHORITY_ENABLED_KEY]: CATEGORY_AUTHORITY_ENABLED_KEY,
    helperSupportiveEnabled: 'helperSupportiveEnabled',
    helperSupportiveFillMissing: 'helperSupportiveFillMissing',
    helperAutoSeedTargets: 'helperAutoSeedTargets',
    driftDetectionEnabled: 'driftDetectionEnabled',
    driftAutoRepublish: 'driftAutoRepublish',
    cortexEnabled: 'cortexEnabled',
    cortexAsyncEnabled: 'cortexAsyncEnabled',
    cortexAutoStart: 'cortexAutoStart',
    cortexEscalateIfConflict: 'cortexEscalateIfConflict',
    cortexEscalateCriticalOnly: 'cortexEscalateCriticalOnly',
    allowBelowPassTargetFill: 'allowBelowPassTargetFill',
    [INDEXING_CATEGORY_AUTHORITY_ENABLED_KEY]: INDEXING_CATEGORY_AUTHORITY_ENABLED_KEY,
    selfImproveEnabled: 'selfImproveEnabled',
    llmExtractionCacheEnabled: 'llmExtractionCacheEnabled',
    reextractIndexed: 'indexingReextractEnabled',
    scannedPdfOcrEnabled: 'scannedPdfOcrEnabled',
    scannedPdfOcrPromoteCandidates: 'scannedPdfOcrPromoteCandidates',
    dynamicCrawleeEnabled: 'dynamicCrawleeEnabled',
    crawleeHeadless: 'crawleeHeadless',
    llmExtractSkipLowSignal: 'llmExtractSkipLowSignal',
    llmReasoningMode: 'llmReasoningMode',
    llmDisableBudgetGuards: 'llmDisableBudgetGuards',
    llmVerifyMode: 'llmVerifyMode',
    localMode: 'localMode',
    dryRun: 'dryRun',
    mirrorToS3: 'mirrorToS3',
    mirrorToS3Input: 'mirrorToS3Input',
    writeMarkdownSummary: 'writeMarkdownSummary',
    llmWriteSummary: 'llmWriteSummary',
    fetchSchedulerEnabled: 'fetchSchedulerEnabled',
    preferHttpFetcher: 'preferHttpFetcher',
    frontierEnableSqlite: 'frontierEnableSqlite',
    frontierStripTrackingParams: 'frontierStripTrackingParams',
    frontierRepairSearchEnabled: 'frontierRepairSearchEnabled',
    autoScrollEnabled: 'autoScrollEnabled',
    graphqlReplayEnabled: 'graphqlReplayEnabled',
    robotsTxtCompliant: 'robotsTxtCompliant',
    runtimeTraceEnabled: 'runtimeTraceEnabled',
    runtimeTraceLlmPayloads: 'runtimeTraceLlmPayloads',
    eventsJsonWrite: 'eventsJsonWrite',
    indexingSchemaPacketsValidationEnabled: 'indexingSchemaPacketsValidationEnabled',
    indexingSchemaPacketsValidationStrict: 'indexingSchemaPacketsValidationStrict',
    queueJsonWrite: 'queueJsonWrite',
    billingJsonWrite: 'billingJsonWrite',
    intelJsonWrite: 'intelJsonWrite',
    corpusJsonWrite: 'corpusJsonWrite',
    learningJsonWrite: 'learningJsonWrite',
    cacheJsonWrite: 'cacheJsonWrite',
    authoritySnapshotEnabled: 'authoritySnapshotEnabled',
    runtimeScreencastEnabled: 'runtimeScreencastEnabled',
    enableQueryIndex: 'enableQueryIndex',
    enableUrlIndex: 'enableUrlIndex',
    manufacturerAutoPromote: 'manufacturerAutoPromote',
    helperFilesEnabled: 'helperFilesEnabled',
    indexingHelperFilesEnabled: 'indexingHelperFilesEnabled',
  }),
});
