import {
  SETTINGS_CLAMPING_INT_RANGE_MAP,
  SETTINGS_CLAMPING_FLOAT_RANGE_MAP,
  SETTINGS_CLAMPING_STRING_ENUM_MAP,
} from '../../shared/settingsClampingRanges.js';
import {
  CATEGORY_AUTHORITY_ROOT_KEY,
  CATEGORY_AUTHORITY_ENABLED_KEY,
  INDEXING_CATEGORY_AUTHORITY_ENABLED_KEY,
} from './runtimeSettingsRouteGet.js';

export const RUNTIME_SETTINGS_ROUTE_PUT = Object.freeze({
  dynamicFetchPolicyMapJsonKey: 'dynamicFetchPolicyMapJson',
  stringEnumMap: SETTINGS_CLAMPING_STRING_ENUM_MAP,
  stringFreeMap: Object.freeze({
    searxngBaseUrl: 'searxngBaseUrl',
    llmPlanApiKey: 'llmPlanApiKey',
    llmPlanProvider: 'llmPlanProvider',
    llmPlanBaseUrl: 'llmPlanBaseUrl',
    llmExtractProvider: 'llmExtractProvider',
    llmExtractBaseUrl: 'llmExtractBaseUrl',
    llmExtractApiKey: 'llmExtractApiKey',
    llmValidateProvider: 'llmValidateProvider',
    llmValidateBaseUrl: 'llmValidateBaseUrl',
    llmValidateApiKey: 'llmValidateApiKey',
    llmWriteProvider: 'llmWriteProvider',
    llmWriteBaseUrl: 'llmWriteBaseUrl',
    llmWriteApiKey: 'llmWriteApiKey',
    pdfPreferredBackend: 'pdfPreferredBackend',
    capturePageScreenshotFormat: 'capturePageScreenshotFormat',
    capturePageScreenshotSelectors: 'capturePageScreenshotSelectors',
    runtimeControlFile: 'runtimeControlFile',
    staticDomMode: 'staticDomMode',
    [CATEGORY_AUTHORITY_ROOT_KEY]: CATEGORY_AUTHORITY_ROOT_KEY,
    batchStrategy: 'batchStrategy',
    specDbDir: 'specDbDir',
    articleExtractorDomainPolicyMapJson: 'articleExtractorDomainPolicyMapJson',
    llmExtractionCacheDir: 'llmExtractionCacheDir',
    userAgent: 'userAgent',
    frontierDbPath: 'frontierDbPath',
    searchProfileCapMapJson: 'searchProfileCapMapJson',
    serpRerankerWeightMapJson: 'serpRerankerWeightMapJson',
    llmProviderRegistryJson: 'llmProviderRegistryJson',
    llmPhaseOverridesJson: 'llmPhaseOverridesJson',
    fetchSchedulerInternalsMapJson: 'fetchSchedulerInternalsMapJson',
    llmModelPlan: 'llmModelPlan',
    llmModelTriage: 'llmModelTriage',
    llmModelFast: 'llmModelFast',
    llmModelReasoning: 'llmModelReasoning',
    llmModelExtract: 'llmModelExtract',
    llmModelValidate: 'llmModelValidate',
    llmModelWrite: 'llmModelWrite',
    importsRoot: 'importsRoot',
    localInputRoot: 'localInputRoot',
    localOutputRoot: 'localOutputRoot',
    runtimeEventsKey: 'runtimeEventsKey',
    s3InputPrefix: 's3InputPrefix',
    s3OutputPrefix: 's3OutputPrefix',
    eloSupabaseAnonKey: 'eloSupabaseAnonKey',
    eloSupabaseEndpoint: 'eloSupabaseEndpoint',
    llmProvider: 'llmProvider',
    llmBaseUrl: 'llmBaseUrl',
    openaiApiKey: 'openaiApiKey',
    anthropicApiKey: 'anthropicApiKey',
    geminiApiKey: 'geminiApiKey',
    deepseekApiKey: 'deepseekApiKey',
    cortexBaseUrl: 'cortexBaseUrl',
    cortexApiKey: 'cortexApiKey',
    cortexAsyncBaseUrl: 'cortexAsyncBaseUrl',
    cortexAsyncSubmitPath: 'cortexAsyncSubmitPath',
    cortexAsyncStatusPath: 'cortexAsyncStatusPath',
    cortexModelFast: 'cortexModelFast',
    cortexModelDom: 'cortexModelDom',
    cortexModelReasoningDeep: 'cortexModelReasoningDeep',
    cortexModelVision: 'cortexModelVision',
    cortexModelSearchFast: 'cortexModelSearchFast',
    cortexModelRerankFast: 'cortexModelRerankFast',
    helperFilesRoot: 'helperFilesRoot',
  }),
  stringTrimMap: Object.freeze({
    fetchSchedulerInternalsMapJson: 'fetchSchedulerInternalsMapJson',
  }),
  intRangeMap: SETTINGS_CLAMPING_INT_RANGE_MAP,
  floatRangeMap: SETTINGS_CLAMPING_FLOAT_RANGE_MAP,
  boolMap: Object.freeze({
    // discoveryEnabled removed — hardcoded invariant, no GUI toggle
    fetchCandidateSources: 'fetchCandidateSources',
    pdfBackendRouterEnabled: 'pdfBackendRouterEnabled',
    capturePageScreenshotEnabled: 'capturePageScreenshotEnabled',
    articleExtractorV2Enabled: 'articleExtractorV2Enabled',
    staticDomExtractorEnabled: 'staticDomExtractorEnabled',
    htmlTableExtractorV2: 'htmlTableExtractorV2',
    [CATEGORY_AUTHORITY_ENABLED_KEY]: CATEGORY_AUTHORITY_ENABLED_KEY,
    helperSupportiveFillMissing: 'helperSupportiveFillMissing',
    driftDetectionEnabled: 'driftDetectionEnabled',
    driftAutoRepublish: 'driftAutoRepublish',
    cortexEnabled: 'cortexEnabled',
    cortexAsyncEnabled: 'cortexAsyncEnabled',
    cortexAutoStart: 'cortexAutoStart',
    cortexEscalateIfConflict: 'cortexEscalateIfConflict',
    cortexEscalateCriticalOnly: 'cortexEscalateCriticalOnly',
    [INDEXING_CATEGORY_AUTHORITY_ENABLED_KEY]: INDEXING_CATEGORY_AUTHORITY_ENABLED_KEY,
    selfImproveEnabled: 'selfImproveEnabled',
    llmExtractionCacheEnabled: 'llmExtractionCacheEnabled',
    reextractIndexed: 'indexingReextractEnabled',
    scannedPdfOcrEnabled: 'scannedPdfOcrEnabled',
    scannedPdfOcrPromoteCandidates: 'scannedPdfOcrPromoteCandidates',
    dynamicCrawleeEnabled: 'dynamicCrawleeEnabled',
    crawleeHeadless: 'crawleeHeadless',
    llmExtractSkipLowSignal: 'llmExtractSkipLowSignal',
    llmReasoningMode: 'llmReasoningMode',
    llmPlanUseReasoning: 'llmPlanUseReasoning',
    llmTriageUseReasoning: 'llmTriageUseReasoning',
    llmDisableBudgetGuards: 'llmDisableBudgetGuards',
    llmVerifyMode: 'llmVerifyMode',
    localMode: 'localMode',
    dryRun: 'dryRun',
    mirrorToS3: 'mirrorToS3',
    mirrorToS3Input: 'mirrorToS3Input',
    writeMarkdownSummary: 'writeMarkdownSummary',
    llmWriteSummary: 'llmWriteSummary',
    fetchSchedulerEnabled: 'fetchSchedulerEnabled',
    preferHttpFetcher: 'preferHttpFetcher',
    frontierEnableSqlite: 'frontierEnableSqlite',
    frontierStripTrackingParams: 'frontierStripTrackingParams',
    frontierRepairSearchEnabled: 'frontierRepairSearchEnabled',
    autoScrollEnabled: 'autoScrollEnabled',
    graphqlReplayEnabled: 'graphqlReplayEnabled',
    robotsTxtCompliant: 'robotsTxtCompliant',
    runtimeTraceEnabled: 'runtimeTraceEnabled',
    runtimeTraceLlmPayloads: 'runtimeTraceLlmPayloads',
    eventsJsonWrite: 'eventsJsonWrite',
    indexingSchemaPacketsValidationEnabled: 'indexingSchemaPacketsValidationEnabled',
    indexingSchemaPacketsValidationStrict: 'indexingSchemaPacketsValidationStrict',
    queueJsonWrite: 'queueJsonWrite',
    billingJsonWrite: 'billingJsonWrite',
    intelJsonWrite: 'intelJsonWrite',
    corpusJsonWrite: 'corpusJsonWrite',
    learningJsonWrite: 'learningJsonWrite',
    cacheJsonWrite: 'cacheJsonWrite',
    authoritySnapshotEnabled: 'authoritySnapshotEnabled',
    runtimeScreencastEnabled: 'runtimeScreencastEnabled',
    manufacturerAutoPromote: 'manufacturerAutoPromote',
  }),
});
