import type { Config } from 'tailwindcss';

export default {
  content: ['./index.html', './src/**/*.{ts,tsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        surface: {
          DEFAULT: 'rgb(var(--sf-color-surface-rgb) / <alpha-value>)',
          dark: 'rgb(var(--sf-color-surface-dark-rgb) / <alpha-value>)',
        },
        panel: {
          DEFAULT: 'rgb(var(--sf-color-panel-rgb) / <alpha-value>)',
          dark: 'rgb(var(--sf-color-panel-dark-rgb) / <alpha-value>)',
        },
        accent: {
          DEFAULT: 'rgb(var(--sf-color-accent-rgb) / <alpha-value>)',
          dark: 'rgb(var(--sf-color-accent-dark-rgb) / <alpha-value>)',
        },
        sf: {
          surface: 'rgb(var(--sf-color-surface-rgb) / <alpha-value>)',
          'surface-elevated': 'rgb(var(--sf-color-surface-elevated-rgb) / <alpha-value>)',
          panel: 'rgb(var(--sf-color-panel-rgb) / <alpha-value>)',
          'text-primary': 'rgb(var(--sf-color-text-primary-rgb) / <alpha-value>)',
          'text-muted': 'rgb(var(--sf-color-text-muted-rgb) / <alpha-value>)',
          'border-default': 'rgb(var(--sf-color-border-default-rgb) / <alpha-value>)',
          'border-subtle': 'rgb(var(--sf-color-border-subtle-rgb) / <alpha-value>)',
          accent: 'rgb(var(--sf-color-accent-rgb) / <alpha-value>)',
          'state-warning': 'var(--sf-state-warning-fg)',
          'state-info': 'var(--sf-state-info-fg)',
          'state-error': 'var(--sf-state-error-fg)',
        },
        gray: {
          50: '#f8fafc',
          100: '#eef2f9',
          200: '#dce3f3',
          300: '#c1ccdf',
          400: '#94a3b8',
          500: '#64748b',
          600: '#4b5f7f',
          700: '#334155',
          750: '#27374f',
          800: '#1f2f49',
          900: '#111f35',
          950: '#0a1224',
        },
      },
      spacing: {
        0: 'var(--sf-space-0)',
        '0.5': 'var(--sf-space-0-5)',
        1: 'var(--sf-space-1)',
        '1.5': 'var(--sf-space-1-5)',
        2: 'var(--sf-space-2)',
        '2.5': 'var(--sf-space-2-5)',
        3: 'var(--sf-space-3)',
        4: 'var(--sf-space-4)',
        6: 'var(--sf-space-6)',
        8: 'var(--sf-space-8)',
        12: 'var(--sf-space-12)',
      },
      borderRadius: {
        none: 'var(--sf-radius-none)',
        sm: 'var(--sf-radius-sm)',
        DEFAULT: 'var(--sf-radius-sm)',
        md: 'var(--sf-radius-md)',
        lg: 'var(--sf-radius-lg)',
        full: 'var(--sf-radius-pill)',
      },
      fontFamily: {
        'sf-sans': ['var(--sf-font-family-ui)'],
        'sf-mono': ['var(--sf-font-family-mono)'],
      },
      fontSize: {
        micro: 'var(--sf-token-font-size-micro)',
        nano: 'var(--sf-token-font-size-nano)',
        caption: 'var(--sf-token-font-size-caption)',
        label: 'var(--sf-token-font-size-label)',
        'body-xs': 'var(--sf-token-font-size-body-xs)',
        'body-sm': 'var(--sf-token-font-size-body-sm)',
        body: 'var(--sf-token-font-size-body)',
        'title-sm': 'var(--sf-token-font-size-title-sm)',
        title: 'var(--sf-token-font-size-title)',
        'title-lg': 'var(--sf-token-font-size-title-lg)',
        'display-sm': 'var(--sf-token-font-size-display-sm)',
        display: 'var(--sf-token-font-size-display)',
      },
    },
  },
  plugins: [],
} satisfies Config;
