// AUTO-GENERATED from RUNTIME_SETTINGS_REGISTRY — do not edit manually.
// Run: node tools/gui-react/scripts/generateManifestTypes.js

export type RuntimeRepairDedupeRule = 'domain_once' | 'domain_and_status' | 'none';
export type RuntimeResumeMode = 'auto' | 'force_resume' | 'start_over';

export interface RuntimeSettingDefaults {
  anthropicApiKey: string;
  autoScrollDelayMs: number;
  autoScrollEnabled: boolean;
  autoScrollPasses: number;
  capturePageScreenshotEnabled: boolean;
  capturePageScreenshotFormat: string;
  capturePageScreenshotMaxBytes: number;
  capturePageScreenshotQuality: number;
  capturePageScreenshotSelectors: string;
  categoryAuthorityEnabled: boolean;
  categoryAuthorityRoot: string;
  crawleeHeadless: boolean;
  crawleeRequestHandlerTimeoutSecs: number;
  fetcherAdapter: string;
  fetcherPlugins: string;
  deepseekApiKey: string;
  searchProfileQueryCap: number;
  domainClassifierUrlCap: number;
  dryRun: boolean;
  eventsJsonWrite: boolean;
  geminiApiKey: string;
  googleSearchMaxRetries: number;
  googleSearchMinQueryIntervalMs: number;
  googleSearchProxyUrlsJson: string;
  googleSearchScreenshotsEnabled: boolean;
  googleSearchTimeoutMs: number;
  serperApiKey: string;
  serperEnabled: boolean;
  indexingResumePersistLimit: number;
  indexingResumeSeedLimit: number;
  llmEnhancerMaxRetries: number;
  llmBaseUrl: string;
  llmCostCachedInputPer1M: number;
  llmCostInputPer1M: number;
  llmCostOutputPer1M: number;
  llmMaxCallsPerProductTotal: number;
  llmMaxCallsPerRound: number;
  llmMaxOutputTokens: number;
  llmMaxOutputTokensPlan: number;
  llmMaxOutputTokensPlanFallback: number;
  llmMaxOutputTokensTriage: number;
  llmMaxOutputTokensReasoning: number;
  llmMaxOutputTokensReasoningFallback: number;
  llmMaxTokens: number;
  llmModelPlan: string;
  llmModelReasoning: string;
  llmMonthlyBudgetUsd: number;
  llmPerProductBudgetUsd: number;
  llmPhaseOverridesJson: string;
  llmPlanApiKey: string;
  llmPlanBaseUrl: string;
  llmPlanFallbackModel: string;
  llmPlanProvider: string;
  llmPlanUseReasoning: boolean;
  llmProvider: string;
  llmProviderRegistryJson: string;
  llmReasoningBudget: number;
  llmReasoningFallbackModel: string;
  llmReasoningMode: boolean;
  llmTimeoutMs: number;
  localInputRoot: string;
  localMode: boolean;
  localOutputRoot: string;
  maxPagesPerDomain: number;
  maxRunSeconds: number;
  openaiApiKey: string;
  pipelineSchemaEnforcementMode: string;
  repairDedupeRule: RuntimeRepairDedupeRule;
  indexingResumeMode: RuntimeResumeMode;
  resumeMode: RuntimeResumeMode;
  indexingResumeMaxAgeHours: number;
  resumeWindowHours: number;
  robotsTxtCompliant: boolean;
  robotsTxtTimeoutMs: number;
  runtimeControlFile: string;
  runtimeEventsKey: string;
  runtimeScreencastEnabled: boolean;
  runtimeScreencastFps: number;
  runtimeScreencastMaxHeight: number;
  runtimeScreencastMaxWidth: number;
  runtimeScreencastQuality: number;
  runtimeTraceEnabled: boolean;
  runtimeTraceFetchRing: number;
  runtimeTraceLlmPayloads: boolean;
  runtimeTraceLlmRing: number;
  searchEngines: string;
  searchEnginesFallback: string;
  searchMaxRetries: number;
  serpSelectorUrlCap: number;
  searxngBaseUrl: string;
  searxngMinQueryIntervalMs: number;
  specDbDir: string;
  writeMarkdownSummary: boolean;
  discoveryEnabled: boolean;
}

export type RuntimeProfile = 'standard';
export type SearxngEngine = 'google' | 'bing' | 'google-proxy' | 'duckduckgo' | 'brave';
