export function buildHypothesisFollowupsContext({
  config,
  startMs,
  logger,
  planner,
  processPlannerQueue,
  sourceResults,
  categoryConfig,
  fieldOrder,
  anchors,
  job,
  productId,
  category,
  requiredFields,
  sourceIntel,
  hypothesisFollowupRoundsExecuted,
  hypothesisFollowupSeededUrls,
  isHelperSyntheticSourceFn,
} = {}) {
  return {
    config,
    startMs,
    logger,
    planner,
    processPlannerQueueFn: processPlannerQueue,
    sourceResults,
    categoryConfig,
    fieldOrder,
    anchors,
    job,
    productId,
    category,
    requiredFields,
    sourceIntel,
    hypothesisFollowupRoundsExecuted,
    hypothesisFollowupSeededUrls,
    isHelperSyntheticSourceFn,
  };
}
