export function buildSourceProcessedPayload({
  source = {},
  sourceUrl = '',
  fetcherKind = '',
  fetchDurationMs = 0,
  parseDurationMs = 0,
  pageData = {},
  sourceFetchOutcome = '',
  fetchContentType = '',
  pageContentHash = '',
  pageBytes = 0,
  identity = {},
  anchorStatus = '',
  mergedFieldCandidatesWithEvidence = [],
  llmFieldCandidates = [],
  articleExtractionMeta = {},
  staticDomMeta = {},
  structuredMeta = {},
  pdfExtractionMeta = {},
  screenshotUri = '',
  domSnippetUri = '',
  hostBudgetAfterSource = {
    score: 0,
    state: 'open'
  }
} = {}) {
  return {
    url: source.url,
    final_url: sourceUrl,
    host: source.host,
    fetcher_kind: fetcherKind,
    fetch_ms: fetchDurationMs,
    parse_ms: parseDurationMs,
    status: pageData.status,
    outcome: sourceFetchOutcome,
    content_type: fetchContentType,
    content_hash: pageContentHash,
    bytes: pageBytes,
    identity_match: identity.match,
    identity_score: identity.score,
    anchor_status: anchorStatus,
    candidate_count: mergedFieldCandidatesWithEvidence.length,
    candidate_source: source.candidateSource,
    llm_candidate_count: llmFieldCandidates.length,
    candidates: mergedFieldCandidatesWithEvidence.slice(0, 200).map((c) => ({
      field: String(c.field || '').trim(),
      value: c.value != null ? String(c.value).slice(0, 200) : null,
      confidence: Number(c.confidence || 0),
      method: String(c.method || '').trim(),
    })),
    fetch_attempts: Number(pageData?.fetchTelemetry?.attempts || 0),
    fetch_retry_count: Number(pageData?.fetchTelemetry?.retry_count || 0),
    fetch_policy_matched_host: String(pageData?.fetchTelemetry?.policy?.matched_host || '').trim(),
    fetch_policy_override_applied: Boolean(pageData?.fetchTelemetry?.policy?.override_applied),
    article_title: String(articleExtractionMeta.title || ''),
    article_excerpt: String(articleExtractionMeta.excerpt || ''),
    article_preview: String(articleExtractionMeta.preview || ''),
    article_extraction_method: String(articleExtractionMeta.method || ''),
    article_quality_score: Number(articleExtractionMeta.quality_score || 0),
    article_char_count: Number(articleExtractionMeta.char_count || 0),
    article_heading_count: Number(articleExtractionMeta.heading_count || 0),
    article_duplicate_sentence_ratio: Number(articleExtractionMeta.duplicate_sentence_ratio || 0),
    article_low_quality: Boolean(articleExtractionMeta.low_quality),
    article_fallback_reason: String(articleExtractionMeta.fallback_reason || ''),
    article_policy_mode: String(articleExtractionMeta.policy_mode || ''),
    article_policy_matched_host: String(articleExtractionMeta.policy_matched_host || ''),
    article_policy_override_applied: Boolean(articleExtractionMeta.policy_override_applied),
    static_dom_mode: String(staticDomMeta.mode || ''),
    static_dom_accepted_field_candidates: Number(staticDomMeta.accepted_field_candidates || 0),
    static_dom_rejected_field_candidates: Number(staticDomMeta.rejected_field_candidates || 0),
    static_dom_parse_error_count: Number(staticDomMeta.parse_error_count || 0),
    static_dom_rejected_field_candidates_audit_count: Number(staticDomMeta.rejected_field_candidates_audit_count || 0),
    structured_json_ld_count: Number(structuredMeta.json_ld_count || 0),
    structured_microdata_count: Number(structuredMeta.microdata_count || 0),
    structured_opengraph_count: Number(structuredMeta.opengraph_count || 0),
    structured_candidates: Number(structuredMeta.structured_candidates || 0),
    structured_rejected_candidates: Number(structuredMeta.structured_rejected_candidates || 0),
    structured_error_count: Number(structuredMeta.error_count || 0),
    structured_snippet_rows: Array.isArray(structuredMeta.snippet_rows)
      ? structuredMeta.snippet_rows.slice(0, 20)
      : [],
    pdf_docs_parsed: Number(pdfExtractionMeta.docs_parsed || 0),
    pdf_pairs_total: Number(pdfExtractionMeta.pair_count || 0),
    pdf_kv_pairs: Number(pdfExtractionMeta.kv_pair_count || 0),
    pdf_table_pairs: Number(pdfExtractionMeta.table_pair_count || 0),
    pdf_pages_scanned: Number(pdfExtractionMeta.pages_scanned || 0),
    pdf_error_count: Number(pdfExtractionMeta.error_count || 0),
    pdf_backend_selected: String(pdfExtractionMeta.backend_selected || ''),
    scanned_pdf_docs_detected: Number(pdfExtractionMeta.scanned_docs_detected || 0),
    scanned_pdf_ocr_docs_attempted: Number(pdfExtractionMeta.scanned_docs_ocr_attempted || 0),
    scanned_pdf_ocr_docs_succeeded: Number(pdfExtractionMeta.scanned_docs_ocr_succeeded || 0),
    scanned_pdf_ocr_pairs: Number(pdfExtractionMeta.scanned_ocr_pair_count || 0),
    scanned_pdf_ocr_kv_pairs: Number(pdfExtractionMeta.scanned_ocr_kv_pair_count || 0),
    scanned_pdf_ocr_table_pairs: Number(pdfExtractionMeta.scanned_ocr_table_pair_count || 0),
    scanned_pdf_ocr_low_conf_pairs: Number(pdfExtractionMeta.scanned_ocr_low_confidence_pairs || 0),
    scanned_pdf_ocr_error_count: Number(pdfExtractionMeta.scanned_ocr_error_count || 0),
    scanned_pdf_ocr_backend_selected: String(pdfExtractionMeta.scanned_ocr_backend_selected || ''),
    scanned_pdf_ocr_confidence_avg: Number(pdfExtractionMeta.scanned_ocr_confidence_avg || 0),
    screenshot_uri: screenshotUri || '',
    dom_snippet_uri: domSnippetUri || '',
    host_budget_score: hostBudgetAfterSource.score,
    host_budget_state: hostBudgetAfterSource.state
  };
}
