export function buildSourcePreflightPhaseContext({
  syncRuntimeOverridesFn,
  applyRuntimeOverridesToPlannerFn,
  planner,
  llmContext,
  logger,
  runtimeControlKey,
  waitFn,
  nowMsFn,
  startMs,
  maxRunSeconds,
  normalizeHostTokenFn,
  hostFromHttpUrlFn,
  ensureHostBudgetRowFn,
  hostBudgetByHost,
  attemptedSourceUrls,
} = {}) {
  return {
    syncRuntimeOverridesFn,
    applyRuntimeOverridesToPlannerFn,
    planner,
    llmContext,
    logger,
    runtimeControlKey,
    waitFn,
    nowMsFn,
    startMs,
    maxRunSeconds,
    normalizeHostTokenFn,
    hostFromHttpUrlFn,
    ensureHostBudgetRowFn,
    hostBudgetByHost,
    attemptedSourceUrls,
  };
}
