export function runSourceResultsAppendPhase({
  sourceResults = [],
  source = {},
  pageData = {},
  discoveryOnlySource = false,
  identity = {},
  mergedIdentityCandidates = [],
  mergedFieldCandidatesWithEvidence = [],
  anchorCheck = {},
  anchorStatus = '',
  endpointIntel = {},
  temporalSignals = [],
  evidencePack = null,
  artifactHostKey = '',
  artifactRefs = {},
  fingerprint = {},
  parserHealth = {},
  nowIsoFn = () => new Date().toISOString(),
} = {}) {
  sourceResults.push({
    ...source,
    ts: nowIsoFn(),
    status: pageData.status,
    finalUrl: pageData.finalUrl,
    discoveryOnly: discoveryOnlySource,
    title: pageData.title,
    identity,
    identityCandidates: mergedIdentityCandidates,
    fieldCandidates: mergedFieldCandidatesWithEvidence,
    anchorCheck,
    anchorStatus,
    endpointSignals: endpointIntel.endpointSignals,
    endpointSuggestions: endpointIntel.nextBestUrls,
    temporalSignals,
    llmEvidencePack: evidencePack,
    artifact_host_key: artifactHostKey,
    artifact_refs: artifactRefs,
    fingerprint,
    parserHealth
  });
}
