export function buildDiscoverySeedPlanContext({
  config,
  storage,
  category,
  categoryConfig,
  job,
  runId,
  logger,
  roundContext,
  requiredFields,
  llmContext,
  frontierDb,
  learningStoreHints,
  planner,
  normalizeFieldList,
} = {}) {
  return {
    config,
    storage,
    category,
    categoryConfig,
    job,
    runId,
    logger,
    roundContext,
    requiredFields,
    llmContext,
    frontierDb,
    learningStoreHints,
    planner,
    normalizeFieldListFn: normalizeFieldList,
  };
}
