export const SETTINGS_DEFAULTS = Object.freeze({
  convergence: Object.freeze({
    convergenceMaxRounds: 3,
    convergenceNoProgressLimit: 2,
    convergenceMaxLowQualityRounds: 1,
    convergenceLowQualityConfidence: 0.2,
    convergenceMaxDispatchQueries: 20,
    convergenceMaxTargetFields: 30,
    needsetEvidenceDecayDays: 14,
    needsetEvidenceDecayFloor: 0.3,
    needsetCapIdentityLocked: 1.0,
    needsetCapIdentityProvisional: 0.74,
    needsetCapIdentityConflict: 0.39,
    needsetCapIdentityUnlocked: 0.59,
    consensusLlmWeightTier1: 0.6,
    consensusLlmWeightTier2: 0.4,
    consensusLlmWeightTier3: 0.2,
    consensusLlmWeightTier4: 0.15,
    consensusTier1Weight: 1.0,
    consensusTier2Weight: 0.8,
    consensusTier3Weight: 0.45,
    consensusTier4Weight: 0.25,
    serpTriageMinScore: 5,
    serpTriageMaxUrls: 12,
    serpTriageEnabled: true,
    retrievalMaxHitsPerField: 24,
    retrievalMaxPrimeSources: 8,
    retrievalIdentityFilterEnabled: true,
    laneConcurrencySearch: 2,
    laneConcurrencyFetch: 4,
    laneConcurrencyParse: 4,
    laneConcurrencyLlm: 2,
  }),
  runtime: Object.freeze({
    profile: 'fast',
    searchProvider: 'duckduckgo',
    phase2LlmModel: 'gpt-5.1-low',
    phase3LlmModel: 'gemini-2.5-flash',
    llmModelFast: 'gpt-5-low',
    llmModelReasoning: 'gpt-5.2-high',
    llmModelExtract: 'gpt-5.1-high',
    llmModelValidate: 'gpt-5.1-high',
    llmModelWrite: 'gemini-2.5-flash-lite',
    llmFallbackPlanModel: '',
    llmFallbackExtractModel: '',
    llmFallbackValidateModel: '',
    llmFallbackWriteModel: '',
    resumeMode: 'auto',
    scannedPdfOcrBackend: 'auto',
    fetchConcurrency: 2,
    perHostMinDelayMs: 900,
    llmTokensPlan: 2048,
    llmTokensTriage: 2048,
    llmTokensFast: 2048,
    llmTokensReasoning: 4096,
    llmTokensExtract: 2048,
    llmTokensValidate: 2048,
    llmTokensWrite: 2048,
    llmTokensPlanFallback: 2048,
    llmTokensExtractFallback: 2048,
    llmTokensValidateFallback: 2048,
    llmTokensWriteFallback: 2048,
    resumeWindowHours: 48,
    reextractAfterHours: 24,
    scannedPdfOcrMaxPages: 4,
    scannedPdfOcrMaxPairs: 800,
    scannedPdfOcrMinCharsPerPage: 30,
    scannedPdfOcrMinLinesPerPage: 2,
    scannedPdfOcrMinConfidence: 0.5,
    crawleeRequestHandlerTimeoutSecs: 45,
    dynamicFetchRetryBudget: 1,
    dynamicFetchRetryBackoffMs: 500,
    dynamicFetchPolicyMapJson: '',
    scannedPdfOcrEnabled: true,
    scannedPdfOcrPromoteCandidates: true,
    phase2LlmEnabled: true,
    phase3LlmTriageEnabled: true,
    llmFallbackEnabled: true,
    reextractIndexed: true,
    discoveryEnabled: true,
    dynamicCrawleeEnabled: true,
    crawleeHeadless: true,
    runtimeAutoSaveEnabled: true,
  }),
  storage: Object.freeze({
    enabled: false,
    destinationType: 'local',
    localDirectory: '',
    s3Region: 'us-east-2',
    s3Bucket: '',
    s3Prefix: 'spec-factory-runs',
    s3AccessKeyId: '',
  }),
  ui: Object.freeze({
    studioAutoSaveAllEnabled: false,
    studioAutoSaveEnabled: true,
    studioAutoSaveMapEnabled: true,
    runtimeAutoSaveEnabled: true,
    storageAutoSaveEnabled: false,
    llmSettingsAutoSaveEnabled: true,
  }),
  autosave: Object.freeze({
    debounceMs: Object.freeze({
      runtime: 1500,
      storage: 700,
      llmRoutes: 700,
      uiSettings: 250,
      studioDocs: 1500,
      studioMap: 1500,
    }),
    statusMs: Object.freeze({
      studioSavedIndicatorReset: 2000,
    }),
  }),
});

export const SETTINGS_OPTION_VALUES = Object.freeze({
  runtime: Object.freeze({
    profile: Object.freeze(['fast', 'standard', 'thorough']),
    searchProvider: Object.freeze(['none', 'google', 'bing', 'searxng', 'duckduckgo', 'dual']),
    resumeMode: Object.freeze(['auto', 'force_resume', 'start_over']),
    scannedPdfOcrBackend: Object.freeze(['auto', 'tesseract', 'none']),
  }),
  storage: Object.freeze({
    destinationType: Object.freeze(['local', 's3']),
  }),
});
