// WHY: Single source of truth for all runtime settings. Every other layer
// (defaults, clamping ranges, route contracts, TS types, hydration, payload)
// derives from this registry. Adding a new setting = add one entry here.

// WHY: Inlined here to break circular dependency with settingsDefaults.js
// which imports from this registry. This is the canonical list.
export const SEARXNG_AVAILABLE_ENGINES = Object.freeze(['google', 'bing', 'google-proxy', 'duckduckgo', 'brave']);

const DEFAULT_FETCH_SCHEDULER_INTERNALS_MAP_JSON = "{\"defaultDelayMs\":300,\"defaultConcurrency\":3,\"defaultMaxRetries\":1,\"retryWaitMs\":15000}";
const DEFAULT_LLM_PROVIDER_REGISTRY_JSON = "[{\"id\":\"default-gemini\",\"name\":\"Gemini\",\"type\":\"openai-compatible\",\"baseUrl\":\"https://generativelanguage.googleapis.com/v1beta/openai\",\"apiKey\":\"\",\"enabled\":true,\"models\":[{\"id\":\"default-gemini-flash\",\"modelId\":\"gemini-2.5-flash\",\"role\":\"primary\",\"costInputPer1M\":0.3,\"costOutputPer1M\":2.5,\"costCachedPer1M\":0.03,\"maxContextTokens\":1048576,\"maxOutputTokens\":65536},{\"id\":\"default-gemini-flash-lite\",\"modelId\":\"gemini-2.5-flash-lite\",\"role\":\"primary\",\"costInputPer1M\":0.1,\"costOutputPer1M\":0.4,\"costCachedPer1M\":0.01,\"maxContextTokens\":1048576,\"maxOutputTokens\":65536},{\"id\":\"default-gemini-pro\",\"modelId\":\"gemini-2.5-pro\",\"role\":\"reasoning\",\"costInputPer1M\":1.25,\"costOutputPer1M\":10,\"costCachedPer1M\":0.125,\"maxContextTokens\":1048576,\"maxOutputTokens\":65536}]},{\"id\":\"default-deepseek\",\"name\":\"DeepSeek\",\"type\":\"openai-compatible\",\"baseUrl\":\"https://api.deepseek.com\",\"apiKey\":\"\",\"enabled\":true,\"models\":[{\"id\":\"default-deepseek-chat\",\"modelId\":\"deepseek-chat\",\"role\":\"primary\",\"costInputPer1M\":0.28,\"costOutputPer1M\":0.42,\"costCachedPer1M\":0.028,\"maxContextTokens\":128000,\"maxOutputTokens\":8192},{\"id\":\"default-deepseek-reasoner\",\"modelId\":\"deepseek-reasoner\",\"role\":\"reasoning\",\"costInputPer1M\":0.28,\"costOutputPer1M\":0.42,\"costCachedPer1M\":0.028,\"maxContextTokens\":128000,\"maxOutputTokens\":64000}]},{\"id\":\"default-anthropic\",\"name\":\"Anthropic\",\"type\":\"anthropic\",\"baseUrl\":\"https://api.anthropic.com\",\"apiKey\":\"\",\"enabled\":false,\"models\":[{\"id\":\"default-anthropic-sonnet\",\"modelId\":\"claude-sonnet-4-20250514\",\"role\":\"reasoning\",\"costInputPer1M\":3,\"costOutputPer1M\":15,\"costCachedPer1M\":0.3,\"maxContextTokens\":200000,\"maxOutputTokens\":64000}]},{\"id\":\"default-openai\",\"name\":\"OpenAI\",\"type\":\"openai-compatible\",\"baseUrl\":\"https://api.openai.com/v1\",\"apiKey\":\"\",\"enabled\":false,\"models\":[{\"id\":\"default-openai-gpt-4-1\",\"modelId\":\"gpt-4.1\",\"role\":\"primary\",\"costInputPer1M\":2,\"costOutputPer1M\":8,\"costCachedPer1M\":0.5,\"maxContextTokens\":1047576,\"maxOutputTokens\":32768},{\"id\":\"default-openai-gpt-4-1-mini\",\"modelId\":\"gpt-4.1-mini\",\"role\":\"primary\",\"costInputPer1M\":0.4,\"costOutputPer1M\":1.6,\"costCachedPer1M\":0.1,\"maxContextTokens\":1047576,\"maxOutputTokens\":32768},{\"id\":\"default-openai-gpt-4-1-nano\",\"modelId\":\"gpt-4.1-nano\",\"role\":\"primary\",\"costInputPer1M\":0.1,\"costOutputPer1M\":0.4,\"costCachedPer1M\":0.025,\"maxContextTokens\":1047576,\"maxOutputTokens\":32768},{\"id\":\"default-openai-gpt-4o\",\"modelId\":\"gpt-4o\",\"role\":\"primary\",\"costInputPer1M\":2.5,\"costOutputPer1M\":10,\"costCachedPer1M\":1.25,\"maxContextTokens\":128000,\"maxOutputTokens\":16384},{\"id\":\"default-openai-gpt-4o-mini\",\"modelId\":\"gpt-4o-mini\",\"role\":\"primary\",\"costInputPer1M\":0.15,\"costOutputPer1M\":0.6,\"costCachedPer1M\":0.075,\"maxContextTokens\":128000,\"maxOutputTokens\":16384},{\"id\":\"default-openai-gpt-5\",\"modelId\":\"gpt-5\",\"role\":\"primary\",\"costInputPer1M\":1.25,\"costOutputPer1M\":10,\"costCachedPer1M\":0.125,\"maxContextTokens\":400000,\"maxOutputTokens\":128000},{\"id\":\"default-openai-gpt-5-mini\",\"modelId\":\"gpt-5-mini\",\"role\":\"primary\",\"costInputPer1M\":0.25,\"costOutputPer1M\":2,\"costCachedPer1M\":0.025,\"maxContextTokens\":400000,\"maxOutputTokens\":128000},{\"id\":\"default-openai-gpt-5-1\",\"modelId\":\"gpt-5.1\",\"role\":\"primary\",\"costInputPer1M\":1.25,\"costOutputPer1M\":10,\"costCachedPer1M\":0.125,\"maxContextTokens\":400000,\"maxOutputTokens\":128000},{\"id\":\"default-openai-gpt-5-2\",\"modelId\":\"gpt-5.2\",\"role\":\"primary\",\"costInputPer1M\":1.75,\"costOutputPer1M\":14,\"costCachedPer1M\":0.175,\"maxContextTokens\":400000,\"maxOutputTokens\":128000},{\"id\":\"default-openai-gpt-5-2-pro\",\"modelId\":\"gpt-5.2-pro\",\"role\":\"reasoning\",\"costInputPer1M\":21,\"costOutputPer1M\":168,\"costCachedPer1M\":2.1,\"maxContextTokens\":400000,\"maxOutputTokens\":128000}]}]";
const DEFAULT_SEARCH_PROFILE_CAP_MAP_JSON = "{\"deterministicAliasCap\":6,\"llmAliasValidationCap\":12,\"llmDocHintQueriesCap\":3,\"llmFieldTargetQueriesCap\":3,\"dedupeQueriesCap\":24}";
const DEFAULT_USER_AGENT = "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/125.0.0.0 Safari/537.36";

export const RUNTIME_SETTINGS_REGISTRY = Object.freeze([
  { key: "anthropicApiKey", type: "string", default: "", secret: true, allowEmpty: true, policyGroup: "apiKeys", policyField: "anthropic", configKey: "anthropicApiKey", envKey: "ANTHROPIC_API_KEY" },
  { key: "articleExtractorDomainPolicyMapJson", type: "string", default: "", allowEmpty: true, configKey: "articleExtractorDomainPolicyMapJson", envKey: "ARTICLE_EXTRACTOR_DOMAIN_POLICY_MAP_JSON" },
  { key: "articleExtractorMaxChars", type: "int", default: 24000, min: 256, max: 500000, configKey: "articleExtractorMaxChars", envKey: "ARTICLE_EXTRACTOR_MAX_CHARS" },
  { key: "articleExtractorMinChars", type: "int", default: 700, min: 50, max: 200000, configKey: "articleExtractorMinChars", envKey: "ARTICLE_EXTRACTOR_MIN_CHARS" },
  { key: "articleExtractorMinScore", type: "int", default: 45, min: 1, max: 100, configKey: "articleExtractorMinScore", envKey: "ARTICLE_EXTRACTOR_MIN_SCORE" },
  { key: "autoScrollDelayMs", type: "int", default: 1200, min: 0, max: 10000, configKey: "autoScrollDelayMs", envKey: "AUTO_SCROLL_DELAY_MS" },
  { key: "autoScrollEnabled", type: "bool", default: true, configKey: "autoScrollEnabled", envKey: "AUTO_SCROLL_ENABLED" },
  { key: "autoScrollPasses", type: "int", default: 2, min: 0, max: 20, configKey: "autoScrollPasses", envKey: "AUTO_SCROLL_PASSES" },
  { key: "awsRegion", type: "string", default: "us-east-2", readOnly: true, configKey: "awsRegion", envKey: "AWS_REGION" },
  { key: "batchStrategy", type: "string", default: "bandit", configKey: "batchStrategy", envKey: "BATCH_STRATEGY" },
  { key: "capturePageScreenshotEnabled", type: "bool", default: true, configKey: "capturePageScreenshotEnabled", envKey: "CAPTURE_PAGE_SCREENSHOT_ENABLED" },
  { key: "capturePageScreenshotFormat", type: "string", default: "jpeg", configKey: "capturePageScreenshotFormat", envKey: "CAPTURE_PAGE_SCREENSHOT_FORMAT" },
  { key: "capturePageScreenshotMaxBytes", type: "int", default: 5000000, min: 1024, max: 100000000, configKey: "capturePageScreenshotMaxBytes", envKey: "CAPTURE_PAGE_SCREENSHOT_MAX_BYTES" },
  { key: "capturePageScreenshotQuality", type: "int", default: 50, min: 1, max: 100, configKey: "capturePageScreenshotQuality", envKey: "CAPTURE_PAGE_SCREENSHOT_QUALITY" },
  { key: "capturePageScreenshotSelectors", type: "string", default: "table,[data-spec-table],.specs-table,.spec-table,.specifications", configKey: "capturePageScreenshotSelectors", envKey: "CAPTURE_PAGE_SCREENSHOT_SELECTORS" },
  { key: "categoryAuthorityEnabled", type: "bool", default: true, aliases: ["helperFilesEnabled"], configKey: "categoryAuthorityEnabled", envKey: "HELPER_FILES_ENABLED" },
  { key: "categoryAuthorityRoot", type: "string", default: "category_authority", allowEmpty: true, aliases: ["helperFilesRoot"], configKey: "categoryAuthorityRoot", envKey: "CATEGORY_AUTHORITY_ROOT" },
  { key: "crawleeHeadless", type: "bool", default: true, configKey: "crawleeHeadless", envKey: "CRAWLEE_HEADLESS" },
  { key: "crawleeRequestHandlerTimeoutSecs", type: "int", default: 75, min: 0, max: 300, configKey: "crawleeRequestHandlerTimeoutSecs", envKey: "CRAWLEE_REQUEST_HANDLER_TIMEOUT_SECS" },
  { key: "daemonConcurrency", type: "int", default: 1, min: 1, max: 128, configKey: "daemonConcurrency", envKey: "DAEMON_CONCURRENCY" },
  { key: "deepseekApiKey", type: "string", default: "", secret: true, allowEmpty: true, policyGroup: "apiKeys", policyField: "deepseek", configKey: "deepseekApiKey", envKey: "DEEPSEEK_API_KEY" },
  { key: "searchProfileQueryCap", type: "int", default: 10, min: 1, max: 100, configKey: "searchProfileQueryCap", envKey: "SEARCH_PROFILE_QUERY_CAP" },
  { key: "searchPlannerQueryCap", type: "int", default: 30, min: 1, max: 200, configKey: "searchPlannerQueryCap", envKey: "SEARCH_PLANNER_QUERY_CAP" },
  { key: "discoveryQueryConcurrency", type: "int", default: 2, min: 1, max: 16, configKey: "discoveryQueryConcurrency", envKey: "DISCOVERY_QUERY_CONCURRENCY" },
  { key: "discoveryResultsPerQuery", type: "int", default: 10, min: 1, max: 100, configKey: "discoveryResultsPerQuery", envKey: "DISCOVERY_RESULTS_PER_QUERY" },
  { key: "domainClassifierUrlCap", type: "int", default: 50, min: 1, max: 500, configKey: "domainClassifierUrlCap", envKey: "DOMAIN_CLASSIFIER_URL_CAP" },
  { key: "domSnippetMaxChars", type: "int", default: 3600, min: 600, max: 20000, configKey: "domSnippetMaxChars", envKey: "DOM_SNIPPET_MAX_CHARS" },
  { key: "domainRequestBurst", type: "int", default: 0, min: 0, max: 1000, configKey: "domainRequestBurst", envKey: "DOMAIN_REQUEST_BURST" },
  { key: "domainRequestRps", type: "int", default: 0, min: 0, max: 100, configKey: "domainRequestRps", envKey: "DOMAIN_REQUEST_RPS" },
  { key: "driftAutoRepublish", type: "bool", default: true, configKey: "driftAutoRepublish", envKey: "DRIFT_AUTO_REPUBLISH" },
  { key: "driftDetectionEnabled", type: "bool", default: true, configKey: "driftDetectionEnabled", envKey: "DRIFT_DETECTION_ENABLED" },
  { key: "driftPollSeconds", type: "int", default: 86400, min: 60, max: 604800, configKey: "driftPollSeconds", envKey: "DRIFT_POLL_SECONDS" },
  { key: "driftScanMaxProducts", type: "int", default: 250, min: 1, max: 10000, configKey: "driftScanMaxProducts", envKey: "DRIFT_SCAN_MAX_PRODUCTS" },
  { key: "dryRun", type: "bool", default: false, configKey: "dryRun", envKey: "DRY_RUN" },
  { key: "dynamicCrawleeEnabled", type: "bool", default: true, configKey: "dynamicCrawleeEnabled", envKey: "DYNAMIC_CRAWLEE_ENABLED" },
  { key: "dynamicFetchPolicyMapJson", type: "string", default: "", allowEmpty: true, configKey: "dynamicFetchPolicyMapJson", envKey: "DYNAMIC_FETCH_POLICY_MAP_JSON" },
  { key: "dynamicFetchRetryBackoffMs", type: "int", default: 2500, min: 0, max: 30000, configKey: "dynamicFetchRetryBackoffMs", envKey: "DYNAMIC_FETCH_RETRY_BACKOFF_MS" },
  { key: "dynamicFetchRetryBudget", type: "int", default: 1, min: 0, max: 5, configKey: "dynamicFetchRetryBudget", envKey: "DYNAMIC_FETCH_RETRY_BUDGET" },
  { key: "endpointNetworkScanLimit", type: "int", default: 1800, min: 50, max: 10000, configKey: "endpointNetworkScanLimit", envKey: "ENDPOINT_NETWORK_SCAN_LIMIT" },
  { key: "endpointSignalLimit", type: "int", default: 120, min: 1, max: 500, configKey: "endpointSignalLimit", envKey: "ENDPOINT_SIGNAL_LIMIT" },
  { key: "endpointSuggestionLimit", type: "int", default: 36, min: 1, max: 200, configKey: "endpointSuggestionLimit", envKey: "ENDPOINT_SUGGESTION_LIMIT" },
  { key: "eventsJsonWrite", type: "bool", default: true, configKey: "eventsJsonWrite", envKey: "EVENTS_JSON_WRITE" },
  { key: "fetchBudgetMs", type: "int", default: 45000, min: 5000, max: 300000, configKey: "fetchBudgetMs", envKey: "FETCH_BUDGET_MS" },
  // WHY: fetchCandidateSources retired — always true. Kept as defaultsOnly for backward compat.
  { key: "fetchCandidateSources", type: "bool", default: true, deprecated: true, configKey: "fetchCandidateSources", envKey: "", defaultsOnly: true },
  { key: "fetchConcurrency", type: "int", default: 4, min: 1, max: 64, configKey: "concurrency", envKey: "CONCURRENCY" },
  { key: "fetchPerHostConcurrencyCap", type: "int", default: 1, min: 1, max: 64, configKey: "fetchPerHostConcurrencyCap", envKey: "FETCH_PER_HOST_CONCURRENCY_CAP" },
  { key: "fetchSchedulerInternalsMapJson", type: "string", default: DEFAULT_FETCH_SCHEDULER_INTERNALS_MAP_JSON, allowEmpty: true, configKey: "fetchSchedulerInternalsMapJson", envKey: "FETCH_SCHEDULER_INTERNALS_MAP_JSON" },
  { key: "fetchDrainTimeoutMs", type: "int", default: 120000, min: 10000, max: 600000, configKey: "fetchDrainTimeoutMs", envKey: "FETCH_DRAIN_TIMEOUT_MS" },
  { key: "fetchSchedulerMaxRetries", type: "int", default: 1, min: 0, max: 20, configKey: "fetchSchedulerMaxRetries", envKey: "FETCH_SCHEDULER_MAX_RETRIES" },
  { key: "fieldRewardHalfLifeDays", type: "int", default: 45, min: 1, max: 365, configKey: "fieldRewardHalfLifeDays", envKey: "FIELD_REWARD_HALF_LIFE_DAYS" },
  { key: "frontierBackoffMaxExponent", type: "int", default: 4, min: 1, max: 12, configKey: "frontierBackoffMaxExponent", envKey: "FRONTIER_BACKOFF_MAX_EXPONENT" },
  { key: "frontierBlockedDomainThreshold", type: "int", default: 1, min: 1, max: 50, configKey: "frontierBlockedDomainThreshold", envKey: "FRONTIER_BLOCKED_DOMAIN_THRESHOLD" },
  { key: "frontierCooldown403BaseSeconds", type: "int", default: 1800, min: 0, max: 86400, configKey: "frontierCooldown403BaseSeconds", envKey: "FRONTIER_COOLDOWN_403_BASE" },
  { key: "frontierCooldown404RepeatSeconds", type: "int", default: 1209600, min: 0, max: 31536000, configKey: "frontierCooldown404RepeatSeconds", envKey: "FRONTIER_COOLDOWN_404_REPEAT" },
  { key: "frontierCooldown404Seconds", type: "int", default: 259200, min: 0, max: 31536000, configKey: "frontierCooldown404Seconds", envKey: "FRONTIER_COOLDOWN_404" },
  { key: "frontierCooldown410Seconds", type: "int", default: 7776000, min: 0, max: 31536000, configKey: "frontierCooldown410Seconds", envKey: "FRONTIER_COOLDOWN_410" },
  { key: "frontierCooldown429BaseSeconds", type: "int", default: 600, min: 0, max: 86400, configKey: "frontierCooldown429BaseSeconds", envKey: "FRONTIER_COOLDOWN_429_BASE" },
  { key: "frontierCooldownTimeoutSeconds", type: "int", default: 21600, min: 0, max: 31536000, configKey: "frontierCooldownTimeoutSeconds", envKey: "FRONTIER_COOLDOWN_TIMEOUT" },
  { key: "frontierDbPath", type: "string", default: "_intel/frontier/frontier.json", allowEmpty: true, configKey: "frontierDbPath", envKey: "FRONTIER_DB_PATH" },
  { key: "frontierPathPenaltyNotfoundThreshold", type: "int", default: 3, min: 1, max: 50, configKey: "frontierPathPenaltyNotfoundThreshold", envKey: "FRONTIER_PATH_PENALTY_NOTFOUND_THRESHOLD" },
  { key: "frontierQueryCooldownSeconds", type: "int", default: 21600, min: 0, max: 31536000, configKey: "frontierQueryCooldownSeconds", envKey: "FRONTIER_QUERY_COOLDOWN_SECONDS" },
  { key: "frontierStripTrackingParams", type: "bool", default: true, configKey: "frontierStripTrackingParams", envKey: "FRONTIER_STRIP_TRACKING_PARAMS" },
  { key: "geminiApiKey", type: "string", default: "", secret: true, allowEmpty: true, policyGroup: "apiKeys", policyField: "gemini", configKey: "geminiApiKey", envKey: "GEMINI_API_KEY" },
  { key: "globalRequestBurst", type: "int", default: 0, min: 0, max: 1000, configKey: "globalRequestBurst", envKey: "GLOBAL_REQUEST_BURST" },
  { key: "globalRequestRps", type: "int", default: 0, min: 0, max: 100, configKey: "globalRequestRps", envKey: "GLOBAL_REQUEST_RPS" },
  { key: "googleSearchMaxRetries", type: "int", default: 1, min: 0, max: 3, configKey: "googleSearchMaxRetries", envKey: "GOOGLE_SEARCH_MAX_RETRIES" },
  { key: "googleSearchMinQueryIntervalMs", type: "int", default: 1000, min: 0, max: 60000, configKey: "googleSearchMinQueryIntervalMs", envKey: "GOOGLE_SEARCH_MIN_QUERY_INTERVAL_MS" },
  { key: "googleSearchProxyUrlsJson", type: "string", default: "[\"http://zruyrjpq-rotate:dfm4udpzx5p0@p.webshare.io:80\"]", allowEmpty: true, configKey: "googleSearchProxyUrlsJson", envKey: "" },
  { key: "googleSearchScreenshotsEnabled", type: "bool", default: true, configKey: "googleSearchScreenshotsEnabled", envKey: "GOOGLE_SEARCH_SCREENSHOTS_ENABLED" },
  { key: "googleSearchTimeoutMs", type: "int", default: 30000, min: 30000, max: 120000, configKey: "googleSearchTimeoutMs", envKey: "GOOGLE_SEARCH_TIMEOUT_MS" },
  { key: "serperApiKey", type: "string", default: "", allowEmpty: true, configKey: "serperApiKey", envKey: "SERPER_API_KEY" },
  { key: "serperEnabled", type: "bool", default: true, configKey: "serperEnabled", envKey: "SERPER_ENABLED" },
  { key: "graphqlReplayEnabled", type: "bool", default: true, configKey: "graphqlReplayEnabled", envKey: "GRAPHQL_REPLAY_ENABLED" },
  // WHY: helperFilesRoot removed — canonical key is categoryAuthorityRoot (line 31). HELPER_FILES_ROOT env var still read by configBuilder.
  { key: "helperSupportiveFillMissing", type: "bool", default: true, configKey: "helperSupportiveFillMissing", envKey: "HELPER_SUPPORTIVE_FILL_MISSING" },
  { key: "hypothesisAutoFollowupRounds", type: "int", default: 2, min: 0, max: 10, configKey: "hypothesisAutoFollowupRounds", envKey: "HYPOTHESIS_AUTO_FOLLOWUP_ROUNDS" },
  { key: "hypothesisFollowupUrlsPerRound", type: "int", default: 24, min: 1, max: 200, configKey: "hypothesisFollowupUrlsPerRound", envKey: "HYPOTHESIS_FOLLOWUP_URLS_PER_ROUND" },
  { key: "importsPollSeconds", type: "int", default: 10, min: 1, max: 3600, configKey: "importsPollSeconds", envKey: "IMPORTS_POLL_SECONDS" },
  { key: "importsRoot", type: "string", default: "imports", allowEmpty: true, configKey: "importsRoot", envKey: "IMPORTS_ROOT" },
  { key: "indexingCategoryAuthorityEnabled", type: "bool", default: false, aliases: ["indexingHelperFilesEnabled"], configKey: "indexingCategoryAuthorityEnabled", envKey: "INDEXING_HELPER_FILES_ENABLED" },
  { key: "indexingResumePersistLimit", type: "int", default: 160, min: 1, max: 100000, configKey: "indexingResumePersistLimit", envKey: "INDEXING_RESUME_PERSIST_LIMIT" },
  { key: "indexingResumeSeedLimit", type: "int", default: 24, min: 1, max: 10000, configKey: "indexingResumeSeedLimit", envKey: "INDEXING_RESUME_SEED_LIMIT" },
  { key: "indexingSchemaPacketsValidationEnabled", type: "bool", default: true, configKey: "indexingSchemaPacketsValidationEnabled", envKey: "INDEXING_SCHEMA_PACKETS_VALIDATION_ENABLED" },
  { key: "indexingSchemaPacketsValidationStrict", type: "bool", default: true, configKey: "indexingSchemaPacketsValidationStrict", envKey: "INDEXING_SCHEMA_PACKETS_VALIDATION_STRICT" },
  { key: "llmEnhancerMaxRetries", type: "int", default: 2, min: 1, max: 5, configKey: "llmEnhancerMaxRetries", envKey: "LLM_ENHANCER_MAX_RETRIES" },
  { key: "llmBaseUrl", type: "string", default: "https://generativelanguage.googleapis.com/v1beta/openai", allowEmpty: true, policyGroup: "provider", policyField: "baseUrl", configKey: "llmBaseUrl", envKey: "LLM_BASE_URL" },
  { key: "llmCostCachedInputPer1M", type: "float", default: 0.125, min: 0, max: 1000, policyGroup: "budget", policyField: "costCachedInputPer1M", configKey: "llmCostCachedInputPer1M", envKey: "LLM_COST_CACHED_INPUT_PER_1M" },
  { key: "llmCostInputPer1M", type: "float", default: 1.25, min: 0, max: 1000, policyGroup: "budget", policyField: "costInputPer1M", configKey: "llmCostInputPer1M", envKey: "LLM_COST_INPUT_PER_1M" },
  { key: "llmCostOutputPer1M", type: "float", default: 10, min: 0, max: 1000, policyGroup: "budget", policyField: "costOutputPer1M", configKey: "llmCostOutputPer1M", envKey: "LLM_COST_OUTPUT_PER_1M" },
  { key: "llmExtractMaxSnippetChars", type: "int", default: 700, min: 100, max: 200000, policyGroup: "extraction", policyField: "maxSnippetChars", configKey: "llmExtractMaxSnippetChars", envKey: "LLM_EXTRACT_MAX_SNIPPET_CHARS" },
  { key: "llmExtractMaxSnippetsPerBatch", type: "int", default: 4, min: 1, max: 50, policyGroup: "extraction", policyField: "maxSnippetsPerBatch", configKey: "llmExtractMaxSnippetsPerBatch", envKey: "LLM_EXTRACT_MAX_SNIPPETS_PER_BATCH" },
  { key: "llmExtractSkipLowSignal", type: "bool", default: true, policyGroup: "extraction", policyField: "skipLowSignal", configKey: "llmExtractSkipLowSignal", envKey: "LLM_EXTRACT_SKIP_LOW_SIGNAL" },
  { key: "llmExtractionCacheDir", type: "string", default: ".specfactory_tmp/llm_cache", allowEmpty: true, policyGroup: "extraction", policyField: "cacheDir", configKey: "llmExtractionCacheDir", envKey: "LLM_EXTRACTION_CACHE_DIR" },
  { key: "llmExtractionCacheTtlMs", type: "int", default: 604800000, min: 60000, max: 31536000000, policyGroup: "extraction", policyField: "cacheTtlMs", configKey: "llmExtractionCacheTtlMs", envKey: "LLM_EXTRACTION_CACHE_TTL_MS" },
  { key: "llmMaxBatchesPerProduct", type: "int", default: 4, min: 1, max: 100, policyGroup: "extraction", policyField: "maxBatchesPerProduct", configKey: "llmMaxBatchesPerProduct", envKey: "LLM_MAX_BATCHES_PER_PRODUCT" },
  { key: "llmMaxCallsPerProductTotal", type: "int", default: 14, min: 1, max: 100, policyGroup: "extraction", policyField: "maxCallsPerProductTotal", configKey: "llmMaxCallsPerProductTotal", envKey: "LLM_MAX_CALLS_PER_PRODUCT_TOTAL" },
  { key: "llmMaxCallsPerRound", type: "int", default: 5, min: 1, max: 200, policyGroup: "extraction", policyField: "maxCallsPerRound", configKey: "llmMaxCallsPerRound", envKey: "LLM_MAX_CALLS_PER_ROUND" },
  { key: "llmMaxEvidenceChars", type: "int", default: 60000, min: 1000, max: 500000, policyGroup: "extraction", policyField: "maxEvidenceChars", configKey: "llmMaxEvidenceChars", envKey: "LLM_MAX_EVIDENCE_CHARS" },
  { key: "llmMaxOutputTokens", type: "int", default: 1400, min: 128, max: 262144, policyGroup: "tokens", policyField: "maxOutput", configKey: "llmMaxOutputTokens", envKey: "LLM_MAX_OUTPUT_TOKENS" },
  { key: "llmMaxOutputTokensPlan", type: "int", default: 4096, min: 128, max: 262144, tokenClamped: true, clampModelKey: "llmModelPlan", aliases: ["llmTokensPlan"], policyGroup: "tokens", policyField: "plan", configKey: "llmMaxOutputTokensPlan", envKey: "LLM_MAX_OUTPUT_TOKENS_PLAN" },
  { key: "llmMaxOutputTokensPlanFallback", type: "int", default: 2048, min: 128, max: 262144, tokenClamped: true, clampModelKey: "llmPlanFallbackModel", clampModelFallbackKey: "llmModelPlan", aliases: ["llmTokensPlanFallback"], policyGroup: "tokens", policyField: "planFallback", configKey: "llmMaxOutputTokensPlanFallback", envKey: "LLM_MAX_OUTPUT_TOKENS_PLAN_FALLBACK" },
  { key: "llmMaxOutputTokensTriage", type: "int", default: 20000, min: 20000, max: 262144, tokenClamped: true, clampModelKey: "llmModelPlan", aliases: ["llmTokensTriage"], configKey: "llmMaxOutputTokensTriage", envKey: "LLM_MAX_OUTPUT_TOKENS_TRIAGE" },
  { key: "llmMaxOutputTokensReasoning", type: "int", default: 4096, min: 128, max: 262144, tokenClamped: true, clampModelKey: "llmModelReasoning", aliases: ["llmTokensReasoning"], policyGroup: "tokens", policyField: "reasoning", configKey: "llmMaxOutputTokensReasoning", envKey: "LLM_MAX_OUTPUT_TOKENS_REASONING" },
  { key: "llmMaxOutputTokensReasoningFallback", type: "int", default: 2048, min: 128, max: 262144, tokenClamped: true, clampModelKey: "llmReasoningFallbackModel", clampModelFallbackKey: "llmModelReasoning", aliases: ["llmTokensReasoningFallback"], policyGroup: "tokens", policyField: "reasoningFallback", configKey: "llmMaxOutputTokensReasoningFallback", envKey: "LLM_MAX_OUTPUT_TOKENS_REASONING_FALLBACK" },
  { key: "llmMaxTokens", type: "int", default: 16384, min: 128, max: 262144, policyGroup: "tokens", policyField: "maxTokens", configKey: "llmMaxTokens", envKey: "LLM_MAX_TOKENS" },
  { key: "llmModelPlan", type: "string", default: "gemini-2.5-flash", aliases: ["phase2LlmModel"], policyGroup: "models", policyField: "plan", configKey: "llmModelPlan", envKey: "LLM_MODEL_PLAN" },
  { key: "llmModelReasoning", type: "string", default: "deepseek-reasoner", policyGroup: "models", policyField: "reasoning", configKey: "llmModelReasoning", envKey: "LLM_MODEL_REASONING" },
  { key: "llmMonthlyBudgetUsd", type: "float", default: 300, min: 0, max: 100000, policyGroup: "budget", policyField: "monthlyUsd", configKey: "llmMonthlyBudgetUsd", envKey: "LLM_MONTHLY_BUDGET_USD" },
  { key: "llmPerProductBudgetUsd", type: "float", default: 0.35, min: 0, max: 1000, policyGroup: "budget", policyField: "perProductUsd", configKey: "llmPerProductBudgetUsd", envKey: "LLM_PER_PRODUCT_BUDGET_USD" },
  { key: "llmPhaseOverridesJson", type: "string", default: "{}", allowEmpty: true, policyGroup: "_json", policyField: "phaseOverrides", configKey: "llmPhaseOverridesJson", envKey: "" },
  { key: "llmPlanApiKey", type: "string", default: "", secret: true, allowEmpty: true, policyGroup: "apiKeys", policyField: "plan", configKey: "llmPlanApiKey", envKey: "LLM_PLAN_API_KEY" },
  { key: "llmPlanBaseUrl", type: "string", default: "https://generativelanguage.googleapis.com/v1beta/openai", allowEmpty: true, policyGroup: "provider", policyField: "planBaseUrl", configKey: "llmPlanBaseUrl", envKey: "LLM_PLAN_BASE_URL" },
  { key: "llmPlanFallbackModel", type: "string", default: "deepseek-chat", policyGroup: "models", policyField: "planFallback", configKey: "llmPlanFallbackModel", envKey: "LLM_PLAN_FALLBACK_MODEL" },
  { key: "llmPlanProvider", type: "string", default: "gemini", policyGroup: "provider", policyField: "planProvider", configKey: "llmPlanProvider", envKey: "LLM_PLAN_PROVIDER" },
  { key: "llmPlanUseReasoning", type: "bool", default: false, policyGroup: "reasoning", policyField: "enabled", configKey: "llmPlanUseReasoning", envKey: "LLM_PLAN_USE_REASONING" },
  { key: "llmProvider", type: "string", default: "gemini", policyGroup: "provider", policyField: "id", configKey: "llmProvider", envKey: "LLM_PROVIDER" },
  { key: "llmProviderRegistryJson", type: "string", default: DEFAULT_LLM_PROVIDER_REGISTRY_JSON, allowEmpty: true, policyGroup: "_json", policyField: "providerRegistry", configKey: "llmProviderRegistryJson", envKey: "" },
  { key: "llmReasoningBudget", type: "int", default: 32768, min: 128, max: 262144, policyGroup: "reasoning", policyField: "budget", configKey: "llmReasoningBudget", envKey: "LLM_REASONING_BUDGET" },
  { key: "llmReasoningFallbackModel", type: "string", default: "gemini-2.5-pro", policyGroup: "models", policyField: "reasoningFallback", configKey: "llmReasoningFallbackModel", envKey: "LLM_REASONING_FALLBACK_MODEL" },
  { key: "llmReasoningMode", type: "bool", default: true, policyGroup: "reasoning", policyField: "mode", configKey: "llmReasoningMode", envKey: "LLM_REASONING_MODE" },
  { key: "llmTimeoutMs", type: "int", default: 30000, min: 1000, max: 600000, policyGroup: "_topLevel", policyField: "timeoutMs", configKey: "llmTimeoutMs", envKey: "LLM_TIMEOUT_MS" },
  { key: "llmVerifyMode", type: "bool", default: true, policyGroup: "verify", policyField: "mode", configKey: "llmVerifyMode", envKey: "LLM_VERIFY_MODE" },
  { key: "llmVerifySampleRate", type: "int", default: 25, min: 1, max: 1000, policyGroup: "verify", policyField: "sampleRate", configKey: "llmVerifySampleRate", envKey: "LLM_VERIFY_SAMPLE_RATE" },
  { key: "llmWriteSummary", type: "bool", default: false, policyGroup: "_topLevel", policyField: "writeSummary", configKey: "llmWriteSummary", envKey: "LLM_WRITE_SUMMARY" },
  { key: "localInputRoot", type: "string", default: "fixtures/s3", allowEmpty: true, configKey: "localInputRoot", envKey: "LOCAL_INPUT_ROOT" },
  { key: "localMode", type: "bool", default: true, configKey: "localMode", envKey: "LOCAL_MODE" },
  // WHY: LOCAL_OUTPUT_ROOT is owned by pathsGroup.js (calls defaultLocalOutputRoot() dynamically).
  // No envKey here — prevents miscGroup from creating a duplicate manifest entry with a stale default.
  { key: "localOutputRoot", type: "string", default: "", allowEmpty: true, configKey: "localOutputRoot", envKey: "" },
  { key: "maxCandidateUrls", type: "int", default: 80, min: 1, max: 5000, configKey: "maxCandidateUrls", envKey: "MAX_CANDIDATE_URLS" },
  { key: "maxGraphqlReplays", type: "int", default: 20, min: 0, max: 20, configKey: "maxGraphqlReplays", envKey: "MAX_GRAPHQL_REPLAYS" },
  { key: "maxHypothesisItems", type: "int", default: 120, min: 1, max: 1000, configKey: "maxHypothesisItems", envKey: "MAX_HYPOTHESIS_ITEMS" },
  { key: "maxJsonBytes", type: "int", default: 6000000, min: 1024, max: 100000000, configKey: "maxJsonBytes", envKey: "MAX_JSON_BYTES" },
  { key: "maxNetworkResponsesPerPage", type: "int", default: 2500, min: 100, max: 10000, configKey: "maxNetworkResponsesPerPage", envKey: "MAX_NETWORK_RESPONSES_PER_PAGE" },
  { key: "maxPagesPerDomain", type: "int", default: 5, min: 1, max: 100, configKey: "maxPagesPerDomain", envKey: "MAX_PAGES_PER_DOMAIN" },
  { key: "maxPdfBytes", type: "int", default: 30000000, min: 1024, max: 100000000, configKey: "maxPdfBytes", envKey: "MAX_PDF_BYTES" },
  { key: "maxRunSeconds", type: "int", default: 480, min: 30, max: 86400, configKey: "maxRunSeconds", envKey: "MAX_RUN_SECONDS" },
  { key: "maxUrlsPerProduct", type: "int", default: 50, min: 1, max: 1000, configKey: "maxUrlsPerProduct", envKey: "MAX_URLS_PER_PRODUCT" },
  { key: "manufacturerCrawlRateLimitMs", type: "int", default: 2000, min: 100, max: 30000, configKey: "manufacturerCrawlRateLimitMs", envKey: "MANUFACTURER_CRAWL_RATE_LIMIT_MS" },
  { key: "manufacturerCrawlTimeoutMs", type: "int", default: 12000, min: 1000, max: 120000, configKey: "manufacturerCrawlTimeoutMs", envKey: "MANUFACTURER_CRAWL_TIMEOUT_MS" },
  { key: "mirrorToS3", type: "bool", default: false, configKey: "mirrorToS3", envKey: "MIRROR_TO_S3" },
  { key: "mirrorToS3Input", type: "bool", default: false, configKey: "mirrorToS3Input", envKey: "MIRROR_TO_S3_INPUT" },
  { key: "openaiApiKey", type: "string", default: "", secret: true, allowEmpty: true, policyGroup: "apiKeys", policyField: "openai", configKey: "openaiApiKey", envKey: "OPENAI_API_KEY" },
  { key: "outputMode", type: "enum", default: "local", allowed: ["local","dual","s3"], configKey: "outputMode", envKey: "OUTPUT_MODE" },
  { key: "pageGotoTimeoutMs", type: "int", default: 12000, min: 0, max: 120000, configKey: "pageGotoTimeoutMs", envKey: "PAGE_GOTO_TIMEOUT_MS" },
  { key: "pageNetworkIdleTimeoutMs", type: "int", default: 2000, min: 0, max: 60000, configKey: "pageNetworkIdleTimeoutMs", envKey: "PAGE_NETWORK_IDLE_TIMEOUT_MS" },
  { key: "parsingConfidenceBaseMapJson", type: "string", default: "", allowEmpty: true, routeOnly: true, configKey: "parsingConfidenceBaseMapJson", envKey: "" },
  { key: "pdfBackendRouterEnabled", type: "bool", default: true, configKey: "pdfBackendRouterEnabled", envKey: "PDF_BACKEND_ROUTER_ENABLED" },
  { key: "pdfBackendRouterMaxPages", type: "int", default: 60, min: 1, max: 300, configKey: "pdfBackendRouterMaxPages", envKey: "PDF_BACKEND_ROUTER_MAX_PAGES" },
  { key: "pdfBackendRouterMaxPairs", type: "int", default: 5000, min: 100, max: 20000, configKey: "pdfBackendRouterMaxPairs", envKey: "PDF_BACKEND_ROUTER_MAX_PAIRS" },
  { key: "pdfBackendRouterMaxTextPreviewChars", type: "int", default: 20000, min: 1000, max: 100000, configKey: "pdfBackendRouterMaxTextPreviewChars", envKey: "PDF_BACKEND_ROUTER_MAX_TEXT_PREVIEW_CHARS" },
  { key: "pdfBackendRouterTimeoutMs", type: "int", default: 120000, min: 10000, max: 300000, configKey: "pdfBackendRouterTimeoutMs", envKey: "PDF_BACKEND_ROUTER_TIMEOUT_MS" },
  { key: "pdfPreferredBackend", type: "string", default: "auto", configKey: "pdfPreferredBackend", envKey: "PDF_PREFERRED_BACKEND" },
  { key: "perHostMinDelayMs", type: "int", default: 1500, min: 0, max: 120000, configKey: "perHostMinDelayMs", envKey: "PER_HOST_MIN_DELAY_MS" },
  { key: "pipelineSchemaEnforcementMode", type: "enum", default: "warn", allowed: ["off", "warn", "enforce"], configKey: "pipelineSchemaEnforcementMode", envKey: "PIPELINE_SCHEMA_ENFORCEMENT_MODE" },
  { key: "postLoadWaitMs", type: "int", default: 200, min: 0, max: 60000, configKey: "postLoadWaitMs", envKey: "POST_LOAD_WAIT_MS" },
  { key: "preferHttpFetcher", type: "bool", default: true, configKey: "preferHttpFetcher", envKey: "PREFER_HTTP_FETCHER" },
  { key: "reCrawlStaleAfterDays", type: "int", default: 30, min: 1, max: 3650, configKey: "reCrawlStaleAfterDays", envKey: "RECRAWL_STALE_AFTER_DAYS" },
  { key: "reextractAfterHours", type: "int", default: 24, min: 1, max: 8760, configKey: "indexingReextractAfterHours", envKey: "INDEXING_REEXTRACT_AFTER_HOURS" },
  { key: "reextractIndexed", type: "bool", default: true, configKey: "indexingReextractEnabled", envKey: "INDEXING_REEXTRACT_ENABLED" },
  { key: "repairDedupeRule", type: "enum", default: "domain_once", allowed: ["domain_once","domain_and_status","none"], configKey: "repairDedupeRule", envKey: "REPAIR_DEDUPE_RULE" },
  { key: "resumeMode", type: "enum", default: "auto", allowed: ["auto","force_resume","start_over"], configKey: "indexingResumeMode", envKey: "INDEXING_RESUME_MODE" },
  { key: "resumeWindowHours", type: "int", default: 48, min: 1, max: 8760, configKey: "indexingResumeMaxAgeHours", envKey: "INDEXING_RESUME_MAX_AGE_HOURS" },
  { key: "robotsTxtCompliant", type: "bool", default: true, configKey: "robotsTxtCompliant", envKey: "ROBOTS_TXT_COMPLIANT" },
  { key: "robotsTxtTimeoutMs", type: "int", default: 6000, min: 100, max: 120000, configKey: "robotsTxtTimeoutMs", envKey: "ROBOTS_TXT_TIMEOUT_MS" },
  { key: "runtimeControlFile", type: "string", default: "_runtime/control/runtime_overrides.json", configKey: "runtimeControlFile", envKey: "RUNTIME_CONTROL_FILE" },
  { key: "runtimeEventsKey", type: "string", default: "_runtime/events.jsonl", configKey: "runtimeEventsKey", envKey: "RUNTIME_EVENTS_KEY" },
  { key: "runtimeScreencastEnabled", type: "bool", default: true, configKey: "runtimeScreencastEnabled", envKey: "RUNTIME_SCREENCAST_ENABLED" },
  { key: "runtimeScreencastFps", type: "int", default: 10, min: 1, max: 60, configKey: "runtimeScreencastFps", envKey: "RUNTIME_SCREENCAST_FPS" },
  { key: "runtimeScreencastMaxHeight", type: "int", default: 720, min: 240, max: 2160, configKey: "runtimeScreencastMaxHeight", envKey: "RUNTIME_SCREENCAST_MAX_HEIGHT" },
  { key: "runtimeScreencastMaxWidth", type: "int", default: 1280, min: 320, max: 3840, configKey: "runtimeScreencastMaxWidth", envKey: "RUNTIME_SCREENCAST_MAX_WIDTH" },
  { key: "runtimeScreencastQuality", type: "int", default: 50, min: 10, max: 100, configKey: "runtimeScreencastQuality", envKey: "RUNTIME_SCREENCAST_QUALITY" },
  { key: "runtimeTraceEnabled", type: "bool", default: true, configKey: "runtimeTraceEnabled", envKey: "RUNTIME_TRACE_ENABLED" },
  { key: "runtimeTraceFetchRing", type: "int", default: 30, min: 10, max: 2000, configKey: "runtimeTraceFetchRing", envKey: "RUNTIME_TRACE_FETCH_RING" },
  { key: "runtimeTraceLlmPayloads", type: "bool", default: true, configKey: "runtimeTraceLlmPayloads", envKey: "RUNTIME_TRACE_LLM_PAYLOADS" },
  { key: "runtimeTraceLlmRing", type: "int", default: 50, min: 10, max: 2000, configKey: "runtimeTraceLlmRing", envKey: "RUNTIME_TRACE_LLM_RING" },
  { key: "s3Bucket", type: "string", default: "my-spec-harvester-data", readOnly: true, configKey: "s3Bucket", envKey: "S3_BUCKET" },
  { key: "s3InputPrefix", type: "string", default: "specs/inputs", allowEmpty: true, configKey: "s3InputPrefix", envKey: "S3_INPUT_PREFIX" },
  { key: "s3OutputPrefix", type: "string", default: "specs/outputs", allowEmpty: true, configKey: "s3OutputPrefix", envKey: "S3_OUTPUT_PREFIX" },
  { key: "scannedPdfOcrBackend", type: "enum", default: "auto", allowed: ["auto","tesseract","none"], configKey: "scannedPdfOcrBackend", envKey: "SCANNED_PDF_OCR_BACKEND" },
  { key: "scannedPdfOcrEnabled", type: "bool", default: true, configKey: "scannedPdfOcrEnabled", envKey: "SCANNED_PDF_OCR_ENABLED" },
  { key: "scannedPdfOcrMaxPages", type: "int", default: 4, min: 1, max: 100, configKey: "scannedPdfOcrMaxPages", envKey: "SCANNED_PDF_OCR_MAX_PAGES" },
  { key: "scannedPdfOcrMaxPairs", type: "int", default: 800, min: 50, max: 20000, configKey: "scannedPdfOcrMaxPairs", envKey: "SCANNED_PDF_OCR_MAX_PAIRS" },
  { key: "scannedPdfOcrMinCharsPerPage", type: "int", default: 30, min: 1, max: 500, configKey: "scannedPdfOcrMinCharsPerPage", envKey: "SCANNED_PDF_OCR_MIN_CHARS_PER_PAGE" },
  { key: "scannedPdfOcrMinConfidence", type: "float", default: 0.5, min: 0, max: 1, configKey: "scannedPdfOcrMinConfidence", envKey: "SCANNED_PDF_OCR_MIN_CONFIDENCE" },
  { key: "scannedPdfOcrMinLinesPerPage", type: "int", default: 2, min: 1, max: 100, configKey: "scannedPdfOcrMinLinesPerPage", envKey: "SCANNED_PDF_OCR_MIN_LINES_PER_PAGE" },
  { key: "searchEngines", type: "csv_enum", default: "google", allowed: SEARXNG_AVAILABLE_ENGINES, aliases: ["searchProvider"], configKey: "searchEngines", envKey: "SEARCH_ENGINES" },
  { key: "searchEnginesFallback", type: "csv_enum", default: "bing", allowed: SEARXNG_AVAILABLE_ENGINES, configKey: "searchEnginesFallback", envKey: "SEARCH_ENGINES_FALLBACK" },
  { key: "searchMaxRetries", type: "int", default: 3, min: 0, max: 5, configKey: "searchMaxRetries", envKey: "SEARCH_MAX_RETRIES" },
  { key: "searchProfileCapMapJson", type: "string", default: DEFAULT_SEARCH_PROFILE_CAP_MAP_JSON, allowEmpty: true, configKey: "searchProfileCapMapJson", envKey: "SEARCH_PROFILE_CAP_MAP_JSON" },
  { key: "serpSelectorUrlCap", type: "int", default: 50, min: 1, max: 500, configKey: "serpSelectorUrlCap", envKey: "SERP_SELECTOR_URL_CAP" },
  { key: "searxngBaseUrl", type: "string", default: "http://127.0.0.1:8080", allowEmpty: true, configKey: "searxngBaseUrl", envKey: "SEARXNG_BASE_URL" },
  { key: "searxngMinQueryIntervalMs", type: "int", default: 3000, min: 0, max: 30000, configKey: "searxngMinQueryIntervalMs", envKey: "SEARXNG_MIN_QUERY_INTERVAL_MS" },
  { key: "selfImproveEnabled", type: "bool", default: true, configKey: "selfImproveEnabled", envKey: "SELF_IMPROVE_ENABLED" },
  { key: "specDbDir", type: "string", default: ".specfactory_tmp", allowEmpty: true, configKey: "specDbDir", envKey: "SPEC_DB_DIR" },
  { key: "staticDomMaxEvidenceSnippets", type: "int", default: 120, min: 10, max: 500, configKey: "staticDomMaxEvidenceSnippets", envKey: "STATIC_DOM_MAX_EVIDENCE_SNIPPETS" },
  { key: "staticDomMode", type: "string", default: "cheerio", configKey: "staticDomMode", envKey: "STATIC_DOM_MODE" },
  { key: "staticDomTargetMatchThreshold", type: "float", default: 0.55, min: 0, max: 1, configKey: "staticDomTargetMatchThreshold", envKey: "STATIC_DOM_TARGET_MATCH_THRESHOLD" },
  { key: "userAgent", type: "string", default: DEFAULT_USER_AGENT, configKey: "userAgent", envKey: "USER_AGENT" },
  { key: "writeMarkdownSummary", type: "bool", default: true, configKey: "writeMarkdownSummary", envKey: "WRITE_MARKDOWN_SUMMARY" },

  // --- Non-route keys: exist in SETTINGS_DEFAULTS.runtime but not in route maps ---
  // WHY: These are config-only keys used internally, not exposed via the settings API.
  { key: "authoritySnapshotEnabled", type: "bool", default: true, defaultsOnly: true, configKey: "authoritySnapshotEnabled", envKey: "" },
  { key: "billingJsonWrite", type: "bool", default: false, defaultsOnly: true, configKey: "billingJsonWrite", envKey: "" },
  { key: "cacheJsonWrite", type: "bool", default: false, defaultsOnly: true, configKey: "cacheJsonWrite", envKey: "" },
  { key: "corpusJsonWrite", type: "bool", default: false, defaultsOnly: true, configKey: "corpusJsonWrite", envKey: "" },
  { key: "discoveryEnabled", type: "bool", default: true, defaultsOnly: true, configKey: "discoveryEnabled", envKey: "DISCOVERY_ENABLED" },
  { key: "daemonGracefulShutdownTimeoutMs", type: "int", default: 30000, defaultsOnly: true, configKey: "daemonGracefulShutdownTimeoutMs", envKey: "" },
  { key: "frontierRepairSearchEnabled", type: "bool", default: true, defaultsOnly: true, configKey: "frontierRepairSearchEnabled", envKey: "" },
  { key: "htmlTableExtractorV2", type: "bool", default: true, defaultsOnly: true, configKey: "htmlTableExtractorV2", envKey: "" },
  { key: "intelJsonWrite", type: "bool", default: false, defaultsOnly: true, configKey: "intelJsonWrite", envKey: "" },
  { key: "learningJsonWrite", type: "bool", default: false, defaultsOnly: true, configKey: "learningJsonWrite", envKey: "" },
  { key: "llmExtractionCacheEnabled", type: "bool", default: true, defaultsOnly: true, configKey: "llmExtractionCacheEnabled", envKey: "" },
  { key: "queueJsonWrite", type: "bool", default: false, defaultsOnly: true, configKey: "queueJsonWrite", envKey: "" },
  // WHY: runtimeAutoSaveEnabled removed from RUNTIME — canonical home is UI_SETTINGS_REGISTRY (line 252).
  { key: "scannedPdfOcrPromoteCandidates", type: "bool", default: true, defaultsOnly: true, configKey: "scannedPdfOcrPromoteCandidates", envKey: "" },
  { key: "staticDomExtractorEnabled", type: "bool", default: true, defaultsOnly: true, configKey: "staticDomExtractorEnabled", envKey: "" },
]);

// WHY: Single source of truth for convergence settings. Same derivation pattern
// as RUNTIME_SETTINGS_REGISTRY — add one entry, all downstream layers derive.
export const CONVERGENCE_SETTINGS_REGISTRY = Object.freeze([
  { key: "serpTriageMinScore", type: "int", default: 3, min: 1, max: 10 },
]);

// WHY: Single source of truth for UI settings. All are simple booleans
// controlling auto-save behavior. Derivation functions produce the defaults,
// value-type map, and mutable key allowlist the handler needs.
export const UI_SETTINGS_REGISTRY = Object.freeze([
  { key: "studioAutoSaveAllEnabled", type: "bool", default: false, mutable: true },
  { key: "studioAutoSaveEnabled", type: "bool", default: true, mutable: true },
  { key: "studioAutoSaveMapEnabled", type: "bool", default: true, mutable: true },
  { key: "runtimeAutoSaveEnabled", type: "bool", default: true, mutable: true },
  { key: "storageAutoSaveEnabled", type: "bool", default: false, mutable: true },
]);

// WHY: Single source of truth for storage settings. Secret fields use
// `secret: true` and `clearFlag` metadata so derivation functions can
// exclude secrets from defaults and include clear flags in the mutable key allowlist.
export const STORAGE_SETTINGS_REGISTRY = Object.freeze([
  { key: "enabled", type: "bool", default: false, mutable: true },
  { key: "destinationType", type: "enum", default: "local", allowed: ["local", "s3"], mutable: true },
  { key: "localDirectory", type: "string", default: "", mutable: true },
  { key: "awsRegion", type: "string", default: "us-east-2", mutable: true },
  { key: "s3Bucket", type: "string", default: "", mutable: true },
  { key: "s3Prefix", type: "string", default: "spec-factory-runs", mutable: true },
  { key: "s3AccessKeyId", type: "string", default: "", mutable: true },
  { key: "s3SecretAccessKey", type: "string", default: "", secret: true, mutable: true, clearFlag: "clearS3SecretAccessKey" },
  { key: "s3SessionToken", type: "string", default: "", secret: true, mutable: true, clearFlag: "clearS3SessionToken" },
  { key: "updatedAt", type: "string_or_null", default: null, computed: true },
]);
