// WHY: SSOT clamping ranges for runtime settings — consumed by both
// core/config (post-merge normalization) and features/settings-authority
// (route validation). Lives in shared/ so core/ never imports features/.

import { SETTINGS_OPTION_VALUES } from './settingsDefaults.js';

export const SETTINGS_CLAMPING_INT_RANGE_MAP = Object.freeze({
  fetchConcurrency: Object.freeze({ cfgKey: 'concurrency', min: 1, max: 64 }),
  perHostMinDelayMs: Object.freeze({ cfgKey: 'perHostMinDelayMs', min: 0, max: 120000 }),
  searxngMinQueryIntervalMs: Object.freeze({ cfgKey: 'searxngMinQueryIntervalMs', min: 0, max: 30000 }),
  domainRequestRps: Object.freeze({ cfgKey: 'domainRequestRps', min: 0, max: 100 }),
  domainRequestBurst: Object.freeze({ cfgKey: 'domainRequestBurst', min: 0, max: 1000 }),
  globalRequestRps: Object.freeze({ cfgKey: 'globalRequestRps', min: 0, max: 100 }),
  globalRequestBurst: Object.freeze({ cfgKey: 'globalRequestBurst', min: 0, max: 1000 }),
  fetchPerHostConcurrencyCap: Object.freeze({ cfgKey: 'fetchPerHostConcurrencyCap', min: 1, max: 64 }),
  discoveryMaxQueries: Object.freeze({ cfgKey: 'discoveryMaxQueries', min: 1, max: 100 }),
  discoveryMaxDiscovered: Object.freeze({ cfgKey: 'discoveryMaxDiscovered', min: 1, max: 2000 }),
  maxUrlsPerProduct: Object.freeze({ cfgKey: 'maxUrlsPerProduct', min: 1, max: 1000 }),
  maxCandidateUrls: Object.freeze({ cfgKey: 'maxCandidateUrls', min: 1, max: 5000 }),
  serpTriageMaxUrls: Object.freeze({ cfgKey: 'serpTriageMaxUrls', min: 5, max: 30 }),
  maxPagesPerDomain: Object.freeze({ cfgKey: 'maxPagesPerDomain', min: 1, max: 100 }),
  maxRunSeconds: Object.freeze({ cfgKey: 'maxRunSeconds', min: 30, max: 86400 }),
  maxJsonBytes: Object.freeze({ cfgKey: 'maxJsonBytes', min: 1024, max: 100000000 }),
  maxPdfBytes: Object.freeze({ cfgKey: 'maxPdfBytes', min: 1024, max: 100000000 }),
  pdfBackendRouterTimeoutMs: Object.freeze({ cfgKey: 'pdfBackendRouterTimeoutMs', min: 10000, max: 300000 }),
  pdfBackendRouterMaxPages: Object.freeze({ cfgKey: 'pdfBackendRouterMaxPages', min: 1, max: 300 }),
  pdfBackendRouterMaxPairs: Object.freeze({ cfgKey: 'pdfBackendRouterMaxPairs', min: 100, max: 20000 }),
  pdfBackendRouterMaxTextPreviewChars: Object.freeze({ cfgKey: 'pdfBackendRouterMaxTextPreviewChars', min: 1000, max: 100000 }),
  capturePageScreenshotQuality: Object.freeze({ cfgKey: 'capturePageScreenshotQuality', min: 1, max: 100 }),
  capturePageScreenshotMaxBytes: Object.freeze({ cfgKey: 'capturePageScreenshotMaxBytes', min: 1024, max: 100000000 }),
  articleExtractorMinChars: Object.freeze({ cfgKey: 'articleExtractorMinChars', min: 50, max: 200000 }),
  articleExtractorMinScore: Object.freeze({ cfgKey: 'articleExtractorMinScore', min: 1, max: 100 }),
  articleExtractorMaxChars: Object.freeze({ cfgKey: 'articleExtractorMaxChars', min: 256, max: 500000 }),
  staticDomMaxEvidenceSnippets: Object.freeze({ cfgKey: 'staticDomMaxEvidenceSnippets', min: 10, max: 500 }),
  domSnippetMaxChars: Object.freeze({ cfgKey: 'domSnippetMaxChars', min: 600, max: 20000 }),
  llmExtractionCacheTtlMs: Object.freeze({ cfgKey: 'llmExtractionCacheTtlMs', min: 60000, max: 31536000000 }),
  llmMaxCallsPerProductTotal: Object.freeze({ cfgKey: 'llmMaxCallsPerProductTotal', min: 1, max: 100 }),

  fieldRewardHalfLifeDays: Object.freeze({ cfgKey: 'fieldRewardHalfLifeDays', min: 1, max: 365 }),
  driftPollSeconds: Object.freeze({ cfgKey: 'driftPollSeconds', min: 60, max: 604800 }),
  driftScanMaxProducts: Object.freeze({ cfgKey: 'driftScanMaxProducts', min: 1, max: 10000 }),
  maxHypothesisItems: Object.freeze({ cfgKey: 'maxHypothesisItems', min: 1, max: 1000 }),
  hypothesisAutoFollowupRounds: Object.freeze({ cfgKey: 'hypothesisAutoFollowupRounds', min: 0, max: 10 }),
  hypothesisFollowupUrlsPerRound: Object.freeze({ cfgKey: 'hypothesisFollowupUrlsPerRound', min: 1, max: 200 }),
  llmMaxOutputTokensPlan: Object.freeze({ cfgKey: 'llmMaxOutputTokensPlan', min: 128, max: 262144 }),
  llmMaxOutputTokensReasoning: Object.freeze({ cfgKey: 'llmMaxOutputTokensReasoning', min: 128, max: 262144 }),
  llmMaxOutputTokensPlanFallback: Object.freeze({ cfgKey: 'llmMaxOutputTokensPlanFallback', min: 128, max: 262144 }),
  llmMaxOutputTokensReasoningFallback: Object.freeze({ cfgKey: 'llmMaxOutputTokensReasoningFallback', min: 128, max: 262144 }),
  llmExtractMaxTokens: Object.freeze({ cfgKey: 'llmExtractMaxTokens', min: 128, max: 262144 }),
  llmExtractMaxSnippetsPerBatch: Object.freeze({ cfgKey: 'llmExtractMaxSnippetsPerBatch', min: 1, max: 50 }),
  llmExtractMaxSnippetChars: Object.freeze({ cfgKey: 'llmExtractMaxSnippetChars', min: 100, max: 200000 }),
  llmExtractReasoningBudget: Object.freeze({ cfgKey: 'llmExtractReasoningBudget', min: 128, max: 262144 }),
  llmReasoningBudget: Object.freeze({ cfgKey: 'llmReasoningBudget', min: 128, max: 262144 }),
  llmMaxCallsPerRound: Object.freeze({ cfgKey: 'llmMaxCallsPerRound', min: 1, max: 200 }),
  llmMaxOutputTokens: Object.freeze({ cfgKey: 'llmMaxOutputTokens', min: 128, max: 262144 }),
  llmVerifySampleRate: Object.freeze({ cfgKey: 'llmVerifySampleRate', min: 1, max: 1000 }),
  llmMaxBatchesPerProduct: Object.freeze({ cfgKey: 'llmMaxBatchesPerProduct', min: 1, max: 100 }),
  llmMaxEvidenceChars: Object.freeze({ cfgKey: 'llmMaxEvidenceChars', min: 1000, max: 500000 }),
  llmMaxTokens: Object.freeze({ cfgKey: 'llmMaxTokens', min: 128, max: 262144 }),
  llmTimeoutMs: Object.freeze({ cfgKey: 'llmTimeoutMs', min: 1000, max: 600000 }),
  resumeWindowHours: Object.freeze({ cfgKey: 'indexingResumeMaxAgeHours', min: 1, max: 8760 }),
  indexingResumeSeedLimit: Object.freeze({ cfgKey: 'indexingResumeSeedLimit', min: 1, max: 10000 }),
  indexingResumePersistLimit: Object.freeze({ cfgKey: 'indexingResumePersistLimit', min: 1, max: 100000 }),
  reextractAfterHours: Object.freeze({ cfgKey: 'indexingReextractAfterHours', min: 1, max: 8760 }),
  reCrawlStaleAfterDays: Object.freeze({ cfgKey: 'reCrawlStaleAfterDays', min: 1, max: 3650 }),
  scannedPdfOcrMaxPages: Object.freeze({ cfgKey: 'scannedPdfOcrMaxPages', min: 1, max: 100 }),
  scannedPdfOcrMaxPairs: Object.freeze({ cfgKey: 'scannedPdfOcrMaxPairs', min: 50, max: 20000 }),
  scannedPdfOcrMinCharsPerPage: Object.freeze({ cfgKey: 'scannedPdfOcrMinCharsPerPage', min: 1, max: 500 }),
  scannedPdfOcrMinLinesPerPage: Object.freeze({ cfgKey: 'scannedPdfOcrMinLinesPerPage', min: 1, max: 100 }),
  crawleeRequestHandlerTimeoutSecs: Object.freeze({ cfgKey: 'crawleeRequestHandlerTimeoutSecs', min: 0, max: 300 }),
  dynamicFetchRetryBudget: Object.freeze({ cfgKey: 'dynamicFetchRetryBudget', min: 0, max: 5 }),
  dynamicFetchRetryBackoffMs: Object.freeze({ cfgKey: 'dynamicFetchRetryBackoffMs', min: 0, max: 30000 }),
  fetchSchedulerMaxRetries: Object.freeze({ cfgKey: 'fetchSchedulerMaxRetries', min: 0, max: 20 }),
  fetchSchedulerFallbackWaitMs: Object.freeze({ cfgKey: 'fetchSchedulerFallbackWaitMs', min: 0, max: 600000 }),
  pageGotoTimeoutMs: Object.freeze({ cfgKey: 'pageGotoTimeoutMs', min: 0, max: 120000 }),
  pageNetworkIdleTimeoutMs: Object.freeze({ cfgKey: 'pageNetworkIdleTimeoutMs', min: 0, max: 60000 }),
  postLoadWaitMs: Object.freeze({ cfgKey: 'postLoadWaitMs', min: 0, max: 60000 }),
  frontierQueryCooldownSeconds: Object.freeze({ cfgKey: 'frontierQueryCooldownSeconds', min: 0, max: 31536000 }),
  frontierCooldown404Seconds: Object.freeze({ cfgKey: 'frontierCooldown404Seconds', min: 0, max: 31536000 }),
  frontierCooldown404RepeatSeconds: Object.freeze({ cfgKey: 'frontierCooldown404RepeatSeconds', min: 0, max: 31536000 }),
  frontierCooldown410Seconds: Object.freeze({ cfgKey: 'frontierCooldown410Seconds', min: 0, max: 31536000 }),
  frontierCooldownTimeoutSeconds: Object.freeze({ cfgKey: 'frontierCooldownTimeoutSeconds', min: 0, max: 31536000 }),
  frontierCooldown403BaseSeconds: Object.freeze({ cfgKey: 'frontierCooldown403BaseSeconds', min: 0, max: 86400 }),
  frontierCooldown429BaseSeconds: Object.freeze({ cfgKey: 'frontierCooldown429BaseSeconds', min: 0, max: 86400 }),
  frontierBackoffMaxExponent: Object.freeze({ cfgKey: 'frontierBackoffMaxExponent', min: 1, max: 12 }),
  frontierPathPenaltyNotfoundThreshold: Object.freeze({ cfgKey: 'frontierPathPenaltyNotfoundThreshold', min: 1, max: 50 }),
  frontierBlockedDomainThreshold: Object.freeze({ cfgKey: 'frontierBlockedDomainThreshold', min: 1, max: 50 }),
  autoScrollPasses: Object.freeze({ cfgKey: 'autoScrollPasses', min: 0, max: 20 }),
  autoScrollDelayMs: Object.freeze({ cfgKey: 'autoScrollDelayMs', min: 0, max: 10000 }),
  maxGraphqlReplays: Object.freeze({ cfgKey: 'maxGraphqlReplays', min: 0, max: 20 }),
  maxNetworkResponsesPerPage: Object.freeze({ cfgKey: 'maxNetworkResponsesPerPage', min: 100, max: 10000 }),
  robotsTxtTimeoutMs: Object.freeze({ cfgKey: 'robotsTxtTimeoutMs', min: 100, max: 120000 }),
  endpointSignalLimit: Object.freeze({ cfgKey: 'endpointSignalLimit', min: 1, max: 500 }),
  endpointSuggestionLimit: Object.freeze({ cfgKey: 'endpointSuggestionLimit', min: 1, max: 200 }),
  endpointNetworkScanLimit: Object.freeze({ cfgKey: 'endpointNetworkScanLimit', min: 50, max: 10000 }),
  runtimeTraceFetchRing: Object.freeze({ cfgKey: 'runtimeTraceFetchRing', min: 10, max: 2000 }),
  runtimeTraceLlmRing: Object.freeze({ cfgKey: 'runtimeTraceLlmRing', min: 10, max: 2000 }),
  daemonConcurrency: Object.freeze({ cfgKey: 'daemonConcurrency', min: 1, max: 128 }),
  importsPollSeconds: Object.freeze({ cfgKey: 'importsPollSeconds', min: 1, max: 3600 }),
  runtimeScreencastFps: Object.freeze({ cfgKey: 'runtimeScreencastFps', min: 1, max: 60 }),
  runtimeScreencastQuality: Object.freeze({ cfgKey: 'runtimeScreencastQuality', min: 10, max: 100 }),
  runtimeScreencastMaxWidth: Object.freeze({ cfgKey: 'runtimeScreencastMaxWidth', min: 320, max: 3840 }),
  runtimeScreencastMaxHeight: Object.freeze({ cfgKey: 'runtimeScreencastMaxHeight', min: 240, max: 2160 }),
  fetchBudgetMs: Object.freeze({ cfgKey: 'fetchBudgetMs', min: 5000, max: 300000 }),
});

export const SETTINGS_CLAMPING_FLOAT_RANGE_MAP = Object.freeze({
  scannedPdfOcrMinConfidence: Object.freeze({ cfgKey: 'scannedPdfOcrMinConfidence', min: 0, max: 1 }),
  staticDomTargetMatchThreshold: Object.freeze({ cfgKey: 'staticDomTargetMatchThreshold', min: 0, max: 1 }),
  llmMonthlyBudgetUsd: Object.freeze({ cfgKey: 'llmMonthlyBudgetUsd', min: 0, max: 100000 }),
  llmPerProductBudgetUsd: Object.freeze({ cfgKey: 'llmPerProductBudgetUsd', min: 0, max: 1000 }),
  llmCostInputPer1M: Object.freeze({ cfgKey: 'llmCostInputPer1M', min: 0, max: 1000 }),
  llmCostOutputPer1M: Object.freeze({ cfgKey: 'llmCostOutputPer1M', min: 0, max: 1000 }),
  llmCostCachedInputPer1M: Object.freeze({ cfgKey: 'llmCostCachedInputPer1M', min: 0, max: 1000 }),
});

export const SETTINGS_CLAMPING_STRING_ENUM_MAP = Object.freeze({
  resumeMode: Object.freeze({ cfgKey: 'indexingResumeMode', allowed: SETTINGS_OPTION_VALUES.runtime.resumeMode }),
  scannedPdfOcrBackend: Object.freeze({ cfgKey: 'scannedPdfOcrBackend', allowed: SETTINGS_OPTION_VALUES.runtime.scannedPdfOcrBackend }),
  searchProvider: Object.freeze({ cfgKey: 'searchProvider', allowed: SETTINGS_OPTION_VALUES.runtime.searchProvider }),
  repairDedupeRule: Object.freeze({ cfgKey: 'repairDedupeRule', allowed: SETTINGS_OPTION_VALUES.runtime.repairDedupeRule }),
  outputMode: Object.freeze({ cfgKey: 'outputMode', allowed: SETTINGS_OPTION_VALUES.runtime.outputMode }),
});
