// Canonical shared settings defaults.
// Tune runtime/convergence/UI defaults here.

export const SETTINGS_DEFAULTS = Object.freeze({
  convergence: Object.freeze({
    serpTriageMinScore: 3,
    serpTriageMaxUrls: 20,
  }),
  // Canonical runtime settings. GUI aliases retired — use canonical names only.
  runtime: Object.freeze({
    searchProvider: 'dual',
    searxngBaseUrl: 'http://127.0.0.1:8080',
    llmPlanApiKey: '',
    llmExtractProvider: '',
    llmExtractBaseUrl: '',
    llmExtractApiKey: '',
    llmValidateProvider: '',
    llmValidateBaseUrl: '',
    llmValidateApiKey: '',
    llmWriteProvider: '',
    llmWriteBaseUrl: '',
    llmWriteApiKey: '',
    llmModelPlan: 'gemini-2.5-flash',
    llmModelTriage: '',      // retired — aliases to llmModelPlan
    llmModelFast: '',        // retired — aliases to llmModelPlan
    llmModelReasoning: 'deepseek-reasoner',
    llmModelExtract: '',     // retired — aliases to llmModelPlan
    llmModelValidate: '',    // retired — aliases to llmModelPlan
    llmModelWrite: '',       // retired — aliases to llmModelPlan
    llmExtractMaxTokens: 1200,
    llmExtractMaxSnippetsPerBatch: 4,
    llmExtractMaxSnippetChars: 700,
    llmExtractSkipLowSignal: true,
    llmExtractReasoningBudget: 2048,
    llmReasoningMode: true,
    llmReasoningBudget: 32768,
    llmMonthlyBudgetUsd: 300,
    llmPerProductBudgetUsd: 0.35,
    llmDisableBudgetGuards: false,
    llmMaxCallsPerRound: 5,
    llmMaxOutputTokens: 1400,
    llmVerifySampleRate: 25,
    llmMaxBatchesPerProduct: 4,
    llmMaxEvidenceChars: 60000,
    llmMaxTokens: 16384,
    llmTimeoutMs: 30000,
    llmCostInputPer1M: 1.25,
    llmCostOutputPer1M: 10,
    llmCostCachedInputPer1M: 0.125,
    llmVerifyMode: true,
    llmPlanFallbackModel: 'deepseek-chat',
    llmReasoningFallbackModel: 'gemini-2.5-pro',
    llmExtractFallbackModel: '',   // retired — aliases to llmPlanFallbackModel
    llmValidateFallbackModel: '',  // retired — aliases to llmPlanFallbackModel
    llmWriteFallbackModel: '',     // retired — aliases to llmPlanFallbackModel
    llmPlanUseReasoning: false,
    llmTriageUseReasoning: false,  // retired — use llmPlanUseReasoning
    resumeMode: 'auto',
    indexingResumeSeedLimit: 24,
    indexingResumePersistLimit: 160,
    indexingSchemaPacketsValidationEnabled: true,
    indexingSchemaPacketsValidationStrict: true,
    scannedPdfOcrBackend: 'auto',
    fetchConcurrency: 4,
    perHostMinDelayMs: 1500,
    searxngMinQueryIntervalMs: 2000,
    domainRequestRps: 0,
    domainRequestBurst: 0,
    globalRequestRps: 0,
    globalRequestBurst: 0,
    fetchPerHostConcurrencyCap: 1,
    llmMaxOutputTokensPlan: 4096,
    llmMaxOutputTokensTriage: 2048,
    llmMaxOutputTokensFast: 1536,
    llmMaxOutputTokensReasoning: 4096,
    llmMaxOutputTokensExtract: 900,
    llmMaxOutputTokensValidate: 900,
    llmMaxOutputTokensWrite: 800,
    llmMaxOutputTokensPlanFallback: 2048,
    llmMaxOutputTokensReasoningFallback: 2048,
    llmMaxOutputTokensExtractFallback: 4096,
    llmMaxOutputTokensValidateFallback: 4096,
    llmMaxOutputTokensWriteFallback: 2048,
    llmExtractionCacheEnabled: true,
    llmExtractionCacheDir: '.specfactory_tmp/llm_cache',
    llmExtractionCacheTtlMs: 604800000,
    llmMaxCallsPerProductTotal: 14,
    llmMaxCallsPerProductFast: 6,
    resumeWindowHours: 48,
    reextractAfterHours: 24,
    scannedPdfOcrMaxPages: 4,
    scannedPdfOcrMaxPairs: 800,
    scannedPdfOcrMinCharsPerPage: 30,
    scannedPdfOcrMinLinesPerPage: 2,
    scannedPdfOcrMinConfidence: 0.5,
    crawleeRequestHandlerTimeoutSecs: 75,
    dynamicFetchRetryBudget: 1,
    dynamicFetchRetryBackoffMs: 2500,
    dynamicFetchPolicyMapJson: '',
    searchProfileCapMapJson: '{"deterministicAliasCap":6,"llmAliasValidationCap":12,"llmDocHintQueriesCap":3,"llmFieldTargetQueriesCap":3,"dedupeQueriesCap":24}',
    serpRerankerWeightMapJson: '{"identityStrongBonus":1.4,"identityPartialBonus":0.7,"identityWeakBonus":0,"identityNoneBonus":-1.4,"brandPresenceBonus":1.6,"modelPresenceBonus":2.1,"specManualKeywordBonus":0.7,"reviewBenchmarkBonus":0.6,"forumRedditPenalty":-1.2,"brandInHostnameBonus":0.8,"wikipediaPenalty":-1,"variantGuardPenalty":-4,"multiModelHintPenalty":-1.6,"tier1Bonus":1.1,"tier2Bonus":0.1,"hostHealthDownrankPenalty":-0.4,"hostHealthExcludePenalty":-2,"operatorRiskPenalty":-0.5,"fieldAffinityBonus":0.5,"diversityPenaltyPerDupe":-0.3,"needsetCoverageBonus":0.2}',
    llmProviderRegistryJson: JSON.stringify([
      {
        id: 'default-gemini',
        name: 'Gemini',
        type: 'openai-compatible',
        baseUrl: 'https://generativelanguage.googleapis.com/v1beta/openai',
        apiKey: '',
        enabled: true,
        models: [
          {
            id: 'default-gemini-flash',
            modelId: 'gemini-2.5-flash',
            role: 'primary',
            costInputPer1M: 0.3,
            costOutputPer1M: 2.5,
            costCachedPer1M: 0.03,
            maxContextTokens: 1048576,
            maxOutputTokens: 65536,
          },
          {
            id: 'default-gemini-flash-lite',
            modelId: 'gemini-2.5-flash-lite',
            role: 'fast',
            costInputPer1M: 0.1,
            costOutputPer1M: 0.4,
            costCachedPer1M: 0.01,
            maxContextTokens: 1048576,
            maxOutputTokens: 65536,
          },
          {
            id: 'default-gemini-pro',
            modelId: 'gemini-2.5-pro',
            role: 'reasoning',
            costInputPer1M: 1.25,
            costOutputPer1M: 10,
            costCachedPer1M: 0.125,
            maxContextTokens: 1048576,
            maxOutputTokens: 65536,
          },
        ],
      },
      {
        id: 'default-deepseek',
        name: 'DeepSeek',
        type: 'openai-compatible',
        baseUrl: 'https://api.deepseek.com',
        apiKey: '',
        enabled: true,
        models: [
          {
            id: 'default-deepseek-chat',
            modelId: 'deepseek-chat',
            role: 'primary',
            costInputPer1M: 0.28,
            costOutputPer1M: 0.42,
            costCachedPer1M: 0.028,
            maxContextTokens: 128000,
            maxOutputTokens: 8192,
          },
          {
            id: 'default-deepseek-reasoner',
            modelId: 'deepseek-reasoner',
            role: 'reasoning',
            costInputPer1M: 0.28,
            costOutputPer1M: 0.42,
            costCachedPer1M: 0.028,
            maxContextTokens: 128000,
            maxOutputTokens: 64000,
          },
        ],
      },
      {
        id: 'default-anthropic',
        name: 'Anthropic',
        type: 'anthropic',
        baseUrl: 'https://api.anthropic.com',
        apiKey: '',
        enabled: false,
        models: [
          {
            id: 'default-anthropic-sonnet',
            modelId: 'claude-sonnet-4-20250514',
            role: 'reasoning',
            costInputPer1M: 3,
            costOutputPer1M: 15,
            costCachedPer1M: 0.3,
            maxContextTokens: 200000,
            maxOutputTokens: 64000,
          },
        ],
      },
      {
        id: 'default-openai',
        name: 'OpenAI',
        type: 'openai-compatible',
        baseUrl: 'https://api.openai.com/v1',
        apiKey: '',
        enabled: false,
        models: [
          {
            id: 'default-openai-gpt-4-1',
            modelId: 'gpt-4.1',
            role: 'primary',
            costInputPer1M: 2,
            costOutputPer1M: 8,
            costCachedPer1M: 0.5,
            maxContextTokens: 1047576,
            maxOutputTokens: 32768,
          },
          {
            id: 'default-openai-gpt-4-1-mini',
            modelId: 'gpt-4.1-mini',
            role: 'fast',
            costInputPer1M: 0.4,
            costOutputPer1M: 1.6,
            costCachedPer1M: 0.1,
            maxContextTokens: 1047576,
            maxOutputTokens: 32768,
          },
          {
            id: 'default-openai-gpt-4-1-nano',
            modelId: 'gpt-4.1-nano',
            role: 'fast',
            costInputPer1M: 0.1,
            costOutputPer1M: 0.4,
            costCachedPer1M: 0.025,
            maxContextTokens: 1047576,
            maxOutputTokens: 32768,
          },
          {
            id: 'default-openai-gpt-4o',
            modelId: 'gpt-4o',
            role: 'primary',
            costInputPer1M: 2.5,
            costOutputPer1M: 10,
            costCachedPer1M: 1.25,
            maxContextTokens: 128000,
            maxOutputTokens: 16384,
          },
          {
            id: 'default-openai-gpt-4o-mini',
            modelId: 'gpt-4o-mini',
            role: 'fast',
            costInputPer1M: 0.15,
            costOutputPer1M: 0.6,
            costCachedPer1M: 0.075,
            maxContextTokens: 128000,
            maxOutputTokens: 16384,
          },
          {
            id: 'default-openai-gpt-5',
            modelId: 'gpt-5',
            role: 'primary',
            costInputPer1M: 1.25,
            costOutputPer1M: 10,
            costCachedPer1M: 0.125,
            maxContextTokens: 400000,
            maxOutputTokens: 128000,
          },
          {
            id: 'default-openai-gpt-5-mini',
            modelId: 'gpt-5-mini',
            role: 'fast',
            costInputPer1M: 0.25,
            costOutputPer1M: 2,
            costCachedPer1M: 0.025,
            maxContextTokens: 400000,
            maxOutputTokens: 128000,
          },
          {
            id: 'default-openai-gpt-5-1',
            modelId: 'gpt-5.1',
            role: 'primary',
            costInputPer1M: 1.25,
            costOutputPer1M: 10,
            costCachedPer1M: 0.125,
            maxContextTokens: 400000,
            maxOutputTokens: 128000,
          },
          {
            id: 'default-openai-gpt-5-2',
            modelId: 'gpt-5.2',
            role: 'primary',
            costInputPer1M: 1.75,
            costOutputPer1M: 14,
            costCachedPer1M: 0.175,
            maxContextTokens: 400000,
            maxOutputTokens: 128000,
          },
          {
            id: 'default-openai-gpt-5-2-pro',
            modelId: 'gpt-5.2-pro',
            role: 'reasoning',
            costInputPer1M: 21,
            costOutputPer1M: 168,
            costCachedPer1M: 2.1,
            maxContextTokens: 400000,
            maxOutputTokens: 128000,
          },
        ],
      },
    ]),
    llmPhaseOverridesJson: '{}',
    scannedPdfOcrEnabled: true,
    scannedPdfOcrPromoteCandidates: true,
    reextractIndexed: true,
    discoveryEnabled: true,
    fetchCandidateSources: true,
    discoveryMaxQueries: 10,
    discoveryMaxDiscovered: 60,
    manufacturerAutoPromote: true,
    maxUrlsPerProduct: 50,
    maxCandidateUrls: 80,
    maxPagesPerDomain: 5,
    maxRunSeconds: 480,
    maxJsonBytes: 6000000,
    maxPdfBytes: 30000000,
    specDbDir: '.specfactory_tmp',
    pdfBackendRouterEnabled: true,
    pdfPreferredBackend: 'auto',
    pdfBackendRouterTimeoutMs: 120000,
    pdfBackendRouterMaxPages: 60,
    pdfBackendRouterMaxPairs: 5000,
    pdfBackendRouterMaxTextPreviewChars: 20000,
    capturePageScreenshotEnabled: true,
    capturePageScreenshotFormat: 'jpeg',
    capturePageScreenshotQuality: 50,
    capturePageScreenshotMaxBytes: 5000000,
    capturePageScreenshotSelectors: 'table,[data-spec-table],.specs-table,.spec-table,.specifications',
    runtimeControlFile: '_runtime/control/runtime_overrides.json',
    articleExtractorV2Enabled: true,
    articleExtractorMinChars: 700,
    articleExtractorMinScore: 45,
    articleExtractorMaxChars: 24000,
    articleExtractorDomainPolicyMapJson: '',
    htmlTableExtractorV2: true,
    staticDomExtractorEnabled: true,
    staticDomMode: 'cheerio',
    staticDomTargetMatchThreshold: 0.55,
    staticDomMaxEvidenceSnippets: 120,
    domSnippetMaxChars: 3600,
    structuredMetadataExtructEnabled: false,
    structuredMetadataExtructUrl: '',
    structuredMetadataExtructTimeoutMs: 10000,
    structuredMetadataExtructMaxItemsPerSurface: 50,
    structuredMetadataExtructCacheEnabled: true,
    structuredMetadataExtructCacheLimit: 512,
    categoryAuthorityEnabled: true,
    categoryAuthorityRoot: 'category_authority',
    helperFilesRoot: 'category_authority',
    helperSupportiveFillMissing: true,
    fieldRewardHalfLifeDays: 45,
    batchStrategy: 'bandit',
    driftDetectionEnabled: true,
    driftPollSeconds: 86400,
    driftScanMaxProducts: 250,
    driftAutoRepublish: true,
    reCrawlStaleAfterDays: 30,
    outputMode: 'local',
    localMode: true,
    dryRun: false,
    mirrorToS3: false,
    mirrorToS3Input: false,
    localInputRoot: 'fixtures/s3',
    localOutputRoot: 'C:\\Users\\Chris\\AppData\\Local\\Temp\\spec-factory\\output',
    runtimeEventsKey: '_runtime/events.jsonl',
    writeMarkdownSummary: true,
    awsRegion: 'us-east-2',
    s3Bucket: 'my-spec-harvester-data',
    s3InputPrefix: 'specs/inputs',
    s3OutputPrefix: 'specs/outputs',
    eloSupabaseAnonKey: '',
    eloSupabaseEndpoint: '',
    llmWriteSummary: false,
    llmProvider: 'gemini',
    llmBaseUrl: 'https://generativelanguage.googleapis.com/v1beta/openai',
    openaiApiKey: '',
    anthropicApiKey: '',
    geminiApiKey: '',
    deepseekApiKey: '',
    indexingCategoryAuthorityEnabled: false,
    llmPlanProvider: 'gemini',
    llmPlanBaseUrl: 'https://generativelanguage.googleapis.com/v1beta/openai',
    userAgent: 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/125.0.0.0 Safari/537.36',
    selfImproveEnabled: true,
    maxHypothesisItems: 120,
    hypothesisAutoFollowupRounds: 2,
    hypothesisFollowupUrlsPerRound: 24,
    endpointSignalLimit: 120,
    endpointSuggestionLimit: 36,
    endpointNetworkScanLimit: 1800,
    dynamicCrawleeEnabled: true,
    crawleeHeadless: true,
    fetchSchedulerEnabled: true,
    fetchSchedulerMaxRetries: 1,
    fetchSchedulerFallbackWaitMs: 60000,
    fetchSchedulerInternalsMapJson: '{"defaultDelayMs":300,"defaultConcurrency":3,"defaultMaxRetries":1,"retryWaitMs":15000}',
    fetchBudgetMs: 45000,
    preferHttpFetcher: true,
    pageGotoTimeoutMs: 12000,
    pageNetworkIdleTimeoutMs: 2000,
    postLoadWaitMs: 200,
    frontierDbPath: '_intel/frontier/frontier.json',
    frontierEnableSqlite: true,
    frontierStripTrackingParams: true,
    frontierQueryCooldownSeconds: 21600,
    frontierCooldown404Seconds: 259200,
    frontierCooldown404RepeatSeconds: 1209600,
    frontierCooldown410Seconds: 7776000,
    frontierCooldownTimeoutSeconds: 21600,
    frontierCooldown403BaseSeconds: 1800,
    frontierCooldown429BaseSeconds: 600,
    frontierBackoffMaxExponent: 4,
    frontierPathPenaltyNotfoundThreshold: 3,
    frontierBlockedDomainThreshold: 1,
    frontierRepairSearchEnabled: true,
    repairDedupeRule: 'domain_once',
    autoScrollEnabled: true,
    autoScrollPasses: 2,
    autoScrollDelayMs: 1200,
    graphqlReplayEnabled: true,
    maxGraphqlReplays: 20,
    maxNetworkResponsesPerPage: 2500,
    robotsTxtCompliant: true,
    robotsTxtTimeoutMs: 6000,
    runtimeTraceEnabled: true,
    runtimeTraceFetchRing: 30,
    runtimeTraceLlmRing: 50,
    runtimeTraceLlmPayloads: true,
    eventsJsonWrite: true,
    queueJsonWrite: false,
    billingJsonWrite: false,
    intelJsonWrite: false,
    corpusJsonWrite: false,
    learningJsonWrite: false,
    cacheJsonWrite: false,
    daemonConcurrency: 1,
    daemonGracefulShutdownTimeoutMs: 30000,
    importsRoot: 'imports',
    importsPollSeconds: 10,
    authoritySnapshotEnabled: true,
    runtimeScreencastEnabled: true,
    runtimeScreencastFps: 10,
    runtimeScreencastQuality: 50,
    runtimeScreencastMaxWidth: 1280,
    runtimeScreencastMaxHeight: 720,
    runtimeAutoSaveEnabled: true,
    indexingResumeMode: 'auto',
    concurrency: 4,
    indexingResumeMaxAgeHours: 48,
    indexingReextractAfterHours: 24,
    indexingReextractEnabled: true,
    dynamicFetchPolicyMap: Object.freeze({}),
    serpTriageMaxUrls: 20
  }),
  storage: Object.freeze({
    enabled: false,
    destinationType: 'local',
    localDirectory: '',
    awsRegion: 'us-east-2',
    s3Bucket: '',
    s3Prefix: 'spec-factory-runs',
    s3AccessKeyId: ''
  }),
  ui: Object.freeze({
    studioAutoSaveAllEnabled: false,
    studioAutoSaveEnabled: true,
    studioAutoSaveMapEnabled: true,
    runtimeAutoSaveEnabled: true,
    storageAutoSaveEnabled: false,
    llmSettingsAutoSaveEnabled: true
  }),
  autosave: Object.freeze({
    debounceMs: Object.freeze({
      runtime: 1500,
      storage: 700,
      llmRoutes: 700,
      uiSettings: 250,
      studioDocs: 1500,
      studioMap: 1500
    }),
    statusMs: Object.freeze({
      studioSavedIndicatorReset: 2000
    })
  })
});

export const SETTINGS_OPTION_VALUES = Object.freeze({
  runtime: Object.freeze({
    searchProvider: Object.freeze(['none', 'google', 'bing', 'searxng', 'dual']),
    resumeMode: Object.freeze(['auto', 'force_resume', 'start_over']),
    scannedPdfOcrBackend: Object.freeze(['auto', 'tesseract', 'none']),
    repairDedupeRule: Object.freeze(['domain_once', 'domain_and_status', 'none']),
    outputMode: Object.freeze(['local', 'dual', 's3'])
  }),
  storage: Object.freeze({
    destinationType: Object.freeze(['local', 's3'])
  })
});
