// WHY: Settings key constants needed by config.js at assembly time.
// Extracted from features/settings-authority to fix dependency inversion
// (core must not import from features).

export const CATEGORY_AUTHORITY_ROOT_KEY = 'categoryAuthorityRoot';
export const CATEGORY_AUTHORITY_ENABLED_KEY = 'categoryAuthorityEnabled';
export const INDEXING_CATEGORY_AUTHORITY_ENABLED_KEY = 'indexingCategoryAuthorityEnabled';

export const RUNTIME_SETTINGS_ROUTE_GET = Object.freeze({
  dynamicFetchPolicyMapJsonKey: 'dynamicFetchPolicyMapJson',
  stringMap: Object.freeze({
    searchProvider: 'searchProvider',
    searxngBaseUrl: 'searxngBaseUrl',
    llmPlanApiKey: 'llmPlanApiKey',
    llmModelPlan: 'llmModelPlan',
    llmModelTriage: 'llmModelTriage',
    llmModelFast: 'llmModelFast',
    llmModelReasoning: 'llmModelReasoning',
    llmModelExtract: 'llmModelExtract',
    llmModelValidate: 'llmModelValidate',
    llmModelWrite: 'llmModelWrite',
    resumeMode: 'indexingResumeMode',
    importsRoot: 'importsRoot',
    outputMode: 'outputMode',
    localInputRoot: 'localInputRoot',
    localOutputRoot: 'localOutputRoot',
    runtimeEventsKey: 'runtimeEventsKey',
    awsRegion: 'awsRegion',
    s3Bucket: 's3Bucket',
    s3InputPrefix: 's3InputPrefix',
    s3OutputPrefix: 's3OutputPrefix',
    eloSupabaseAnonKey: 'eloSupabaseAnonKey',
    eloSupabaseEndpoint: 'eloSupabaseEndpoint',
    llmProvider: 'llmProvider',
    llmBaseUrl: 'llmBaseUrl',
    openaiApiKey: 'openaiApiKey',
    anthropicApiKey: 'anthropicApiKey',
    llmPlanProvider: 'llmPlanProvider',
    llmPlanBaseUrl: 'llmPlanBaseUrl',
    llmExtractProvider: 'llmExtractProvider',
    llmExtractBaseUrl: 'llmExtractBaseUrl',
    llmExtractApiKey: 'llmExtractApiKey',
    llmValidateProvider: 'llmValidateProvider',
    llmValidateBaseUrl: 'llmValidateBaseUrl',
    llmValidateApiKey: 'llmValidateApiKey',
    llmWriteProvider: 'llmWriteProvider',
    llmWriteBaseUrl: 'llmWriteBaseUrl',
    llmWriteApiKey: 'llmWriteApiKey',
    scannedPdfOcrBackend: 'scannedPdfOcrBackend',
    pdfPreferredBackend: 'pdfPreferredBackend',
    capturePageScreenshotFormat: 'capturePageScreenshotFormat',
    capturePageScreenshotSelectors: 'capturePageScreenshotSelectors',
    runtimeScreenshotMode: 'runtimeScreenshotMode',
    runtimeControlFile: 'runtimeControlFile',
    staticDomMode: 'staticDomMode',
    [CATEGORY_AUTHORITY_ROOT_KEY]: CATEGORY_AUTHORITY_ROOT_KEY,
    helperFilesRoot: 'helperFilesRoot',
    batchStrategy: 'batchStrategy',
    specDbDir: 'specDbDir',
    articleExtractorDomainPolicyMapJson: 'articleExtractorDomainPolicyMapJson',
    llmExtractionCacheDir: 'llmExtractionCacheDir',
    frontierDbPath: 'frontierDbPath',
    dynamicFetchPolicyMapJson: 'dynamicFetchPolicyMapJson',
    fetchSchedulerInternalsMapJson: 'fetchSchedulerInternalsMapJson',
    repairDedupeRule: 'repairDedupeRule',
    automationQueueStorageEngine: 'automationQueueStorageEngine',
    searchProfileCapMapJson: 'searchProfileCapMapJson',
    serpRerankerWeightMapJson: 'serpRerankerWeightMapJson',
    llmProviderRegistryJson: 'llmProviderRegistryJson',
    llmPhaseOverridesJson: 'llmPhaseOverridesJson',
    userAgent: 'userAgent',
    cortexBaseUrl: 'cortexBaseUrl',
    cortexApiKey: 'cortexApiKey',
    cortexAsyncBaseUrl: 'cortexAsyncBaseUrl',
    cortexAsyncSubmitPath: 'cortexAsyncSubmitPath',
    cortexAsyncStatusPath: 'cortexAsyncStatusPath',
    cortexModelFast: 'cortexModelFast',
    cortexModelDom: 'cortexModelDom',
    cortexModelReasoningDeep: 'cortexModelReasoningDeep',
    cortexModelVision: 'cortexModelVision',
    cortexModelSearchFast: 'cortexModelSearchFast',
    cortexModelRerankFast: 'cortexModelRerankFast',
  }),
  intMap: Object.freeze({
    fetchBudgetMs: 'fetchBudgetMs',
    fetchConcurrency: 'concurrency',
    perHostMinDelayMs: 'perHostMinDelayMs',
    searchGlobalRps: 'searchGlobalRps',
    searchGlobalBurst: 'searchGlobalBurst',
    searchPerHostRps: 'searchPerHostRps',
    searchPerHostBurst: 'searchPerHostBurst',
    domainRequestRps: 'domainRequestRps',
    domainRequestBurst: 'domainRequestBurst',
    globalRequestRps: 'globalRequestRps',
    globalRequestBurst: 'globalRequestBurst',
    fetchPerHostConcurrencyCap: 'fetchPerHostConcurrencyCap',
    discoveryMaxQueries: 'discoveryMaxQueries',
    maxPagesPerDomain: 'maxPagesPerDomain',
    maxUrlsPerProduct: 'maxUrlsPerProduct',
    maxCandidateUrls: 'maxCandidateUrls',
    maxRunSeconds: 'maxRunSeconds',
    maxJsonBytes: 'maxJsonBytes',
    maxPdfBytes: 'maxPdfBytes',
    pdfBackendRouterTimeoutMs: 'pdfBackendRouterTimeoutMs',
    pdfBackendRouterMaxPages: 'pdfBackendRouterMaxPages',
    pdfBackendRouterMaxPairs: 'pdfBackendRouterMaxPairs',
    pdfBackendRouterMaxTextPreviewChars: 'pdfBackendRouterMaxTextPreviewChars',
    capturePageScreenshotQuality: 'capturePageScreenshotQuality',
    capturePageScreenshotMaxBytes: 'capturePageScreenshotMaxBytes',
    articleExtractorMinChars: 'articleExtractorMinChars',
    articleExtractorMinScore: 'articleExtractorMinScore',
    articleExtractorMaxChars: 'articleExtractorMaxChars',
    staticDomMaxEvidenceSnippets: 'staticDomMaxEvidenceSnippets',
    domSnippetMaxChars: 'domSnippetMaxChars',
    llmExtractionCacheTtlMs: 'llmExtractionCacheTtlMs',
    llmMaxCallsPerProductTotal: 'llmMaxCallsPerProductTotal',
    llmMaxCallsPerProductFast: 'llmMaxCallsPerProductFast',
    helperSupportiveMaxSources: 'helperSupportiveMaxSources',
    helperActiveSyncLimit: 'helperActiveSyncLimit',
    fieldRewardHalfLifeDays: 'fieldRewardHalfLifeDays',
    driftPollSeconds: 'driftPollSeconds',
    driftScanMaxProducts: 'driftScanMaxProducts',
    cortexSyncTimeoutMs: 'cortexSyncTimeoutMs',
    cortexAsyncPollIntervalMs: 'cortexAsyncPollIntervalMs',
    cortexAsyncMaxWaitMs: 'cortexAsyncMaxWaitMs',
    cortexEnsureReadyTimeoutMs: 'cortexEnsureReadyTimeoutMs',
    cortexStartReadyTimeoutMs: 'cortexStartReadyTimeoutMs',
    cortexFailureThreshold: 'cortexFailureThreshold',
    cortexCircuitOpenMs: 'cortexCircuitOpenMs',
    cortexMaxDeepFieldsPerProduct: 'cortexMaxDeepFieldsPerProduct',
    discoveryMaxDiscovered: 'discoveryMaxDiscovered',
    maxHypothesisItems: 'maxHypothesisItems',
    hypothesisAutoFollowupRounds: 'hypothesisAutoFollowupRounds',
    hypothesisFollowupUrlsPerRound: 'hypothesisFollowupUrlsPerRound',
    serpTriageMaxUrls: 'serpTriageMaxUrls',
    llmMaxOutputTokensPlan: 'llmMaxOutputTokensPlan',
    llmMaxOutputTokensTriage: 'llmMaxOutputTokensTriage',
    llmMaxOutputTokensFast: 'llmMaxOutputTokensFast',
    llmMaxOutputTokensReasoning: 'llmMaxOutputTokensReasoning',
    llmMaxOutputTokensExtract: 'llmMaxOutputTokensExtract',
    llmMaxOutputTokensValidate: 'llmMaxOutputTokensValidate',
    llmMaxOutputTokensWrite: 'llmMaxOutputTokensWrite',
    llmMaxOutputTokensPlanFallback: 'llmMaxOutputTokensPlanFallback',
    llmMaxOutputTokensReasoningFallback: 'llmMaxOutputTokensReasoningFallback',
    llmMaxOutputTokensExtractFallback: 'llmMaxOutputTokensExtractFallback',
    llmMaxOutputTokensValidateFallback: 'llmMaxOutputTokensValidateFallback',
    llmMaxOutputTokensWriteFallback: 'llmMaxOutputTokensWriteFallback',
    llmExtractMaxTokens: 'llmExtractMaxTokens',
    llmExtractMaxSnippetsPerBatch: 'llmExtractMaxSnippetsPerBatch',
    llmExtractMaxSnippetChars: 'llmExtractMaxSnippetChars',
    llmExtractReasoningBudget: 'llmExtractReasoningBudget',
    llmReasoningBudget: 'llmReasoningBudget',
    llmMaxCallsPerRound: 'llmMaxCallsPerRound',
    llmMaxOutputTokens: 'llmMaxOutputTokens',
    llmVerifySampleRate: 'llmVerifySampleRate',
    llmMaxBatchesPerProduct: 'llmMaxBatchesPerProduct',
    llmMaxEvidenceChars: 'llmMaxEvidenceChars',
    llmMaxTokens: 'llmMaxTokens',
    llmTimeoutMs: 'llmTimeoutMs',
    resumeWindowHours: 'indexingResumeMaxAgeHours',
    indexingResumeSeedLimit: 'indexingResumeSeedLimit',
    indexingResumePersistLimit: 'indexingResumePersistLimit',
    reextractAfterHours: 'indexingReextractAfterHours',
    reCrawlStaleAfterDays: 'reCrawlStaleAfterDays',
    scannedPdfOcrMaxPages: 'scannedPdfOcrMaxPages',
    scannedPdfOcrMaxPairs: 'scannedPdfOcrMaxPairs',
    scannedPdfOcrMinCharsPerPage: 'scannedPdfOcrMinCharsPerPage',
    scannedPdfOcrMinLinesPerPage: 'scannedPdfOcrMinLinesPerPage',
    crawleeRequestHandlerTimeoutSecs: 'crawleeRequestHandlerTimeoutSecs',
    dynamicFetchRetryBudget: 'dynamicFetchRetryBudget',
    dynamicFetchRetryBackoffMs: 'dynamicFetchRetryBackoffMs',
    fetchSchedulerMaxRetries: 'fetchSchedulerMaxRetries',
    fetchSchedulerFallbackWaitMs: 'fetchSchedulerFallbackWaitMs',
    pageGotoTimeoutMs: 'pageGotoTimeoutMs',
    pageNetworkIdleTimeoutMs: 'pageNetworkIdleTimeoutMs',
    postLoadWaitMs: 'postLoadWaitMs',
    frontierQueryCooldownSeconds: 'frontierQueryCooldownSeconds',
    frontierCooldown404Seconds: 'frontierCooldown404Seconds',
    frontierCooldown404RepeatSeconds: 'frontierCooldown404RepeatSeconds',
    frontierCooldown410Seconds: 'frontierCooldown410Seconds',
    frontierCooldownTimeoutSeconds: 'frontierCooldownTimeoutSeconds',
    frontierCooldown403BaseSeconds: 'frontierCooldown403BaseSeconds',
    frontierCooldown429BaseSeconds: 'frontierCooldown429BaseSeconds',
    frontierBackoffMaxExponent: 'frontierBackoffMaxExponent',
    frontierPathPenaltyNotfoundThreshold: 'frontierPathPenaltyNotfoundThreshold',
    frontierBlockedDomainThreshold: 'frontierBlockedDomainThreshold',
    autoScrollPasses: 'autoScrollPasses',
    autoScrollDelayMs: 'autoScrollDelayMs',
    maxGraphqlReplays: 'maxGraphqlReplays',
    maxNetworkResponsesPerPage: 'maxNetworkResponsesPerPage',
    robotsTxtTimeoutMs: 'robotsTxtTimeoutMs',
    endpointSignalLimit: 'endpointSignalLimit',
    endpointSuggestionLimit: 'endpointSuggestionLimit',
    endpointNetworkScanLimit: 'endpointNetworkScanLimit',
    runtimeTraceFetchRing: 'runtimeTraceFetchRing',
    runtimeTraceLlmRing: 'runtimeTraceLlmRing',
    daemonConcurrency: 'daemonConcurrency',
    importsPollSeconds: 'importsPollSeconds',
    runtimeScreencastFps: 'runtimeScreencastFps',
    runtimeScreencastQuality: 'runtimeScreencastQuality',
    runtimeScreencastMaxWidth: 'runtimeScreencastMaxWidth',
    runtimeScreencastMaxHeight: 'runtimeScreencastMaxHeight',
  }),
  floatMap: Object.freeze({
    scannedPdfOcrMinConfidence: 'scannedPdfOcrMinConfidence',
    staticDomTargetMatchThreshold: 'staticDomTargetMatchThreshold',
    cortexEscalateConfidenceLt: 'cortexEscalateConfidenceLt',
    llmMonthlyBudgetUsd: 'llmMonthlyBudgetUsd',
    llmPerProductBudgetUsd: 'llmPerProductBudgetUsd',
    llmCostInputPer1M: 'llmCostInputPer1M',
    llmCostOutputPer1M: 'llmCostOutputPer1M',
    llmCostCachedInputPer1M: 'llmCostCachedInputPer1M',
  }),
  boolMap: Object.freeze({
    // discoveryEnabled removed — hardcoded invariant, no GUI toggle
    enableQueryIndex: 'enableQueryIndex',
    enableUrlIndex: 'enableUrlIndex',
    fetchCandidateSources: 'fetchCandidateSources',
    manufacturerAutoPromote: 'manufacturerAutoPromote',
    pdfBackendRouterEnabled: 'pdfBackendRouterEnabled',
    capturePageScreenshotEnabled: 'capturePageScreenshotEnabled',
    runtimeCaptureScreenshots: 'runtimeCaptureScreenshots',
    chartExtractionEnabled: 'chartExtractionEnabled',
    articleExtractorV2Enabled: 'articleExtractorV2Enabled',
    staticDomExtractorEnabled: 'staticDomExtractorEnabled',
    htmlTableExtractorV2: 'htmlTableExtractorV2',
    [CATEGORY_AUTHORITY_ENABLED_KEY]: CATEGORY_AUTHORITY_ENABLED_KEY,
    helperSupportiveEnabled: 'helperSupportiveEnabled',
    helperSupportiveFillMissing: 'helperSupportiveFillMissing',
    helperAutoSeedTargets: 'helperAutoSeedTargets',
    driftDetectionEnabled: 'driftDetectionEnabled',
    driftAutoRepublish: 'driftAutoRepublish',
    cortexEnabled: 'cortexEnabled',
    cortexAsyncEnabled: 'cortexAsyncEnabled',
    cortexAutoStart: 'cortexAutoStart',
    cortexEscalateIfConflict: 'cortexEscalateIfConflict',
    cortexEscalateCriticalOnly: 'cortexEscalateCriticalOnly',
    [INDEXING_CATEGORY_AUTHORITY_ENABLED_KEY]: INDEXING_CATEGORY_AUTHORITY_ENABLED_KEY,
    selfImproveEnabled: 'selfImproveEnabled',
    llmExtractionCacheEnabled: 'llmExtractionCacheEnabled',
    reextractIndexed: 'indexingReextractEnabled',
    scannedPdfOcrEnabled: 'scannedPdfOcrEnabled',
    scannedPdfOcrPromoteCandidates: 'scannedPdfOcrPromoteCandidates',
    dynamicCrawleeEnabled: 'dynamicCrawleeEnabled',
    crawleeHeadless: 'crawleeHeadless',
    llmExtractSkipLowSignal: 'llmExtractSkipLowSignal',
    llmReasoningMode: 'llmReasoningMode',
    llmPlanUseReasoning: 'llmPlanUseReasoning',
    llmTriageUseReasoning: 'llmTriageUseReasoning',
    llmDisableBudgetGuards: 'llmDisableBudgetGuards',
    llmVerifyMode: 'llmVerifyMode',
    localMode: 'localMode',
    dryRun: 'dryRun',
    mirrorToS3: 'mirrorToS3',
    mirrorToS3Input: 'mirrorToS3Input',
    writeMarkdownSummary: 'writeMarkdownSummary',
    llmWriteSummary: 'llmWriteSummary',
    fetchSchedulerEnabled: 'fetchSchedulerEnabled',
    preferHttpFetcher: 'preferHttpFetcher',
    frontierEnableSqlite: 'frontierEnableSqlite',
    frontierStripTrackingParams: 'frontierStripTrackingParams',
    frontierRepairSearchEnabled: 'frontierRepairSearchEnabled',
    autoScrollEnabled: 'autoScrollEnabled',
    graphqlReplayEnabled: 'graphqlReplayEnabled',
    robotsTxtCompliant: 'robotsTxtCompliant',
    runtimeTraceEnabled: 'runtimeTraceEnabled',
    runtimeTraceLlmPayloads: 'runtimeTraceLlmPayloads',
    eventsJsonWrite: 'eventsJsonWrite',
    indexingSchemaPacketsValidationEnabled: 'indexingSchemaPacketsValidationEnabled',
    indexingSchemaPacketsValidationStrict: 'indexingSchemaPacketsValidationStrict',
    queueJsonWrite: 'queueJsonWrite',
    billingJsonWrite: 'billingJsonWrite',
    intelJsonWrite: 'intelJsonWrite',
    corpusJsonWrite: 'corpusJsonWrite',
    learningJsonWrite: 'learningJsonWrite',
    cacheJsonWrite: 'cacheJsonWrite',
    authoritySnapshotEnabled: 'authoritySnapshotEnabled',
    runtimeScreencastEnabled: 'runtimeScreencastEnabled',
    helperFilesEnabled: 'helperFilesEnabled',
    indexingHelperFilesEnabled: 'indexingHelperFilesEnabled',
  }),
});

export const CONVERGENCE_SETTINGS_KEYS = Object.freeze([
  'serpTriageMinScore',
  'serpTriageMaxUrls',
]);

// WHY: Dual-key pairs must have identical values. Self-referencing pairs
// remain for fallback models (keyA === keyB) as no-ops. All GUI aliases retired.
export const DUAL_KEY_PAIRS = Object.freeze([
  ['llmPlanFallbackModel', 'llmPlanFallbackModel'],
  ['llmReasoningFallbackModel', 'llmReasoningFallbackModel'],
  ['llmExtractFallbackModel', 'llmExtractFallbackModel'],
  ['llmValidateFallbackModel', 'llmValidateFallbackModel'],
  ['llmWriteFallbackModel', 'llmWriteFallbackModel'],
]);

export function assertDualKeyConsistency(defaults) {
  for (const [keyA, keyB] of DUAL_KEY_PAIRS) {
    if (keyA === keyB) continue;
    if (!Object.hasOwn(defaults, keyA) || !Object.hasOwn(defaults, keyB)) continue;
    const valA = defaults[keyA];
    const valB = defaults[keyB];
    if (valA !== valB) {
      throw new Error(
        `Dual-key drift: ${keyA} (${JSON.stringify(valA)}) !== ${keyB} (${JSON.stringify(valB)})`
      );
    }
  }
}
