import fs from 'node:fs';
import path from 'node:path';

import { runWithRetry } from '../pipelineSharedHelpers.js';
import { wait } from '../../utils/common.js';
import { createFetchScheduler } from '../../concurrency/fetchScheduler.js';
import {
  normalizeHostToken,
  hostFromHttpUrl,
  buildRepairSearchQuery,
  classifyFetchOutcome,
  ensureHostBudgetRow,
  noteHostRetryTs,
  bumpHostOutcome,
  applyHostBudgetBackoff,
  resolveHostBudgetState,
} from '../fetchParseWorker.js';
import { extractCandidatesFromPage, buildEvidencePack, extractCandidatesLLM } from '../../features/indexing/extraction/index.js';
import { evaluateAnchorConflicts, evaluateSourceIdentity } from '../../features/indexing/validation/index.js';
import {
  sha256, sha256Buffer, screenshotMimeType, screenshotExtension,
  isDiscoveryOnlySourceUrl, isRobotsTxtUrl, isSitemapUrl,
  hasSitemapXmlSignals, isLikelyIndexableEndpointUrl,
  isSafeManufacturerFollowupUrl, isHelperSyntheticSource,
  mergePhase08Rows,
  buildCandidateFieldMap, dedupeCandidates,
  buildDomSnippetArtifact, enrichFieldCandidatesWithEvidenceRefs,
  toInt, toFloat,
  isIdentityLockedField,
  applyRuntimeOverridesToPlanner,
  markSatisfiedLlmFields, isAnchorLocked,
} from '../../features/indexing/orchestration/shared/index.js';
import { defaultIndexLabRoot } from '../../core/config/runtimeArtifactRoots.js';
import { recordQueryResult } from '../../features/indexing/discovery/index.js';
import {
  buildHypothesisFollowupsContext,
  buildProcessPlannerQueuePhaseCallsiteContext,
  runProcessPlannerQueuePhase,
  runHypothesisFollowups,
  resolveHypothesisFollowupState,
  runRepairSearchPhase,
  runPhase08SourceIngestionPhase,
  runSourceIdentityCandidateMergePhase,
  runSourceLlmFieldCandidatePhase,
  runSourceIdentityEvaluationPhase,
  buildSourceArtifactsContextPhase,
  buildSourceProcessedPayload,
  collectKnownCandidatesFromSource,
  buildSourceFetchClassificationPhase,
  maybeEmitRepairQuery,
  maybeApplyBlockedDomainCooldown,
  runSourcePreflightPhase,
  runSourceFinalizationPhase,
  runSourceEvidenceIndexPhase,
  runSourcePostFetchStatusPhase,
  runSourceKnownCandidatesPhase,
  runSourceConflictTelemetryPhase,
  runSourceResultsAppendPhase,
  runSourceFrontierPersistencePhase,
  runSourceHostBudgetPhase,
  runSourceArtifactAggregationPhase,
  runSourceProcessedTelemetryPhase,
  runSourceArtifactsPhase,
} from '../../features/indexing/orchestration/execution/index.js';
import { extractTemporalSignals } from '../../intel/temporalSignals.js';
import { mineEndpointSignals } from '../../intel/endpointMiner.js';
import { buildSiteFingerprint, computeParserHealth } from '../../intel/siteFingerprint.js';
import { applyIdentityGateToCandidates } from '../identityGateExtraction.js';
import { shouldQueueLlmRetry } from '../../runtime/indexingResume.js';

const DEFAULT_DEPS = {
  buildProcessPlannerQueuePhaseCallsiteContextFn: buildProcessPlannerQueuePhaseCallsiteContext,
  runProcessPlannerQueuePhaseFn: runProcessPlannerQueuePhase,
  importSearchProvidersFn: async () => import('../../features/indexing/search/searchProviders.js'),
  defaultIndexLabRootFn: defaultIndexLabRoot,
  mkdirSyncFn: fs.mkdirSync,
  recordQueryResultFn: recordQueryResult,
  pathJoinFn: path.join,
  buildHypothesisFollowupsContextFn: buildHypothesisFollowupsContext,
  runRepairSearchPhaseFn: runRepairSearchPhase,
  runHypothesisFollowupsFn: runHypothesisFollowups,
  resolveHypothesisFollowupStateFn: resolveHypothesisFollowupState,
  nowFn: Date.now,
};

export function buildRunProductPlannerProcessingContext({
  bootstrapState,
  config,
  getRuntimeOverridesFn = () => bootstrapState.runtimeOverrides,
  modeAwareFetcherRegistry = bootstrapState.modeAwareFetcherRegistry,
  deps = {},
} = {}) {
  const runtimeDeps = { ...DEFAULT_DEPS, ...deps };

  const runProcessPlannerQueue = async (plannerProcessingState = {}) => {
    const processPlannerQueueState = await runtimeDeps.runProcessPlannerQueuePhaseFn({
      initialState: {
        runtimePauseAnnounced: plannerProcessingState.runtimePauseAnnounced,
        artifactSequence: plannerProcessingState.artifactSequence,
        phase08FieldContexts: plannerProcessingState.phase08FieldContexts,
        phase08PrimeRows: plannerProcessingState.phase08PrimeRows,
        llmSourcesUsed: plannerProcessingState.llmSourcesUsed,
        llmCandidatesAccepted: plannerProcessingState.llmCandidatesAccepted,
        runtimeOverrides: getRuntimeOverridesFn(),
      },
      ...runtimeDeps.buildProcessPlannerQueuePhaseCallsiteContextFn({
        maybeApplyBlockedDomainCooldown,
        blockedDomainHitCount: bootstrapState.blockedDomainHitCount,
        blockedDomainThreshold: bootstrapState.blockedDomainThreshold,
        blockedDomainsApplied: bootstrapState.blockedDomainsApplied,
        planner: bootstrapState.planner,
        logger: bootstrapState.logger,
        normalizeHostToken,
        hostFromHttpUrl,
        isRobotsTxtUrl,
        isSitemapUrl,
        hasSitemapXmlSignals,
        isDiscoveryOnlySourceUrl,
        mineEndpointSignals,
        categoryConfig: bootstrapState.categoryConfig,
        config,
        buildSiteFingerprint,
        isLikelyIndexableEndpointUrl,
        isSafeManufacturerFollowupUrl,
        extractCandidatesFromPage,
        job: bootstrapState.job,
        adapterManager: bootstrapState.adapterManager,
        runId: bootstrapState.runId,
        dedupeCandidates,
        buildEvidencePack,
        llmTargetFields: bootstrapState.focus_fields,
        fetcherMode: bootstrapState.fetcherMode,
        productId: bootstrapState.productId,
        category: bootstrapState.category,
        sha256,
        deterministicParser: bootstrapState.deterministicParser,
        componentResolver: bootstrapState.componentResolver,
        llmSatisfiedFields: bootstrapState.llmSatisfiedFields,
        anchors: bootstrapState.anchors,
        isIdentityLockedField,
        isAnchorLocked,
        extractCandidatesLLM,
        goldenExamples: bootstrapState.goldenExamples,
        llmContext: bootstrapState.llmContext,
        runtimeFieldRulesEngine: bootstrapState.runtimeFieldRulesEngine,
        shouldQueueLlmRetry,
        llmRetryReasonByUrl: bootstrapState.llmRetryReasonByUrl,
        runPhase08SourceIngestionPhase,
        phase08BatchRows: bootstrapState.phase08BatchRows,
        mergePhase08Rows,
        runSourceLlmFieldCandidatePhase,
        enrichFieldCandidatesWithEvidenceRefs,
        extractTemporalSignals,
        runSourceIdentityCandidateMergePhase,
        runSourceIdentityEvaluationPhase,
        buildCandidateFieldMap,
        evaluateAnchorConflicts,
        evaluateSourceIdentity,
        applyIdentityGateToCandidates,
        computeParserHealth,
        buildSourceArtifactsContextPhase,
        runSourceFinalizationPhase,
        sourceResults: bootstrapState.sourceResults,
        successfulSourceMetaByUrl: bootstrapState.successfulSourceMetaByUrl,
        frontierDb: bootstrapState.frontierDb,
        repairSearchEnabled: bootstrapState.repairSearchEnabled,
        repairDedupeRule: bootstrapState.repairDedupeRule,
        repairQueryByDomain: bootstrapState.repairQueryByDomain,
        requiredFields: bootstrapState.requiredFields,
        buildRepairSearchQuery,
        maybeEmitRepairQuery,
        toFloat,
        artifactsByHost: bootstrapState.artifactsByHost,
        adapterArtifacts: bootstrapState.adapterArtifacts,
        collectKnownCandidatesFromSource,
        markSatisfiedLlmFields,
        bumpHostOutcome,
        noteHostRetryTs,
        applyHostBudgetBackoff,
        resolveHostBudgetState,
        runSourceResultsAppendPhase,
        runSourceEvidenceIndexPhase,
        runSourcePostFetchStatusPhase,
        runSourceKnownCandidatesPhase,
        runSourceConflictTelemetryPhase,
        runSourceFrontierPersistencePhase,
        runSourceArtifactAggregationPhase,
        runSourceHostBudgetPhase,
        runSourceProcessedTelemetryPhase,
        buildSourceProcessedPayload,
        traceWriter: bootstrapState.traceWriter,
        buildSourceFetchClassificationPhase,
        classifyFetchOutcome,
        runSourceArtifactsPhase,
        runArtifactsBase: bootstrapState.runArtifactsBase,
        storage: bootstrapState.storage,
        buildDomSnippetArtifact,
        toInt,
        screenshotExtension,
        screenshotMimeType,
        sha256Buffer,
        fetcher: bootstrapState.fetcher,
        fetchHostConcurrencyGate: bootstrapState.fetchHostConcurrencyGate,
        fetchWithModeFn: modeAwareFetcherRegistry.fetchWithMode,
        runWithRetry,
        resumeFetchFailedUrls: bootstrapState.resumeFetchFailedUrls,
        resumeCooldownSkippedUrls: bootstrapState.resumeCooldownSkippedUrls,
        syncRuntimeOverrides: bootstrapState.syncRuntimeOverrides || (async () => getRuntimeOverridesFn()),
        applyRuntimeOverridesToPlanner,
        runtimeControlKey: bootstrapState.runtimeControlKey,
        wait,
        startMs: bootstrapState.startMs,
        ensureHostBudgetRow,
        hostBudgetByHost: bootstrapState.hostBudgetByHost,
        attemptedSourceUrls: bootstrapState.attemptedSourceUrls,
        runSourcePreflightPhase,
        createFetchScheduler,
      }),
    });

    return {
      runtimePauseAnnounced: processPlannerQueueState.runtimePauseAnnounced,
      artifactSequence: processPlannerQueueState.artifactSequence,
      phase08FieldContexts: processPlannerQueueState.phase08FieldContexts,
      phase08PrimeRows: processPlannerQueueState.phase08PrimeRows,
      llmSourcesUsed: processPlannerQueueState.llmSourcesUsed,
      llmCandidatesAccepted: processPlannerQueueState.llmCandidatesAccepted,
      terminalReason: String(
        processPlannerQueueState.terminalReason || plannerProcessingState.terminalReason || '',
      ).trim(),
    };
  };

  return {
    initialState: {
      runtimePauseAnnounced: false,
      artifactSequence: bootstrapState.artifactSequence,
      phase08FieldContexts: bootstrapState.phase08FieldContexts,
      phase08PrimeRows: bootstrapState.phase08PrimeRows,
      llmSourcesUsed: bootstrapState.llmSourcesUsed,
      llmCandidatesAccepted: bootstrapState.llmCandidatesAccepted,
      terminalReason: '',
      hypothesisFollowupRoundsExecuted: bootstrapState.hypothesisFollowupRoundsExecuted,
      hypothesisFollowupSeededUrls: bootstrapState.hypothesisFollowupSeededUrls,
    },
    logger: bootstrapState.logger,
    config,
    planner: bootstrapState.planner,
    startMs: bootstrapState.startMs,
    nowFn: runtimeDeps.nowFn,
    processPlannerQueueFn: runProcessPlannerQueue,
    runRepairSearchPhaseFn: runtimeDeps.runRepairSearchPhaseFn,
    runSearchFn: async ({ query: q }) => {
      const { runSearchProviders } = await runtimeDeps.importSearchProvidersFn();
      const results = await runSearchProviders({ config, query: q, limit: 10, logger: bootstrapState.logger });
      try {
        const repairQueryDir = runtimeDeps.pathJoinFn(runtimeDeps.defaultIndexLabRootFn(), bootstrapState.category);
        runtimeDeps.mkdirSyncFn(repairQueryDir, { recursive: true });
        runtimeDeps.recordQueryResultFn({
          query: q,
          provider: config.searchEngines || '',
          result_count: results.length,
          run_id: bootstrapState.runId,
          category: bootstrapState.category,
          product_id: bootstrapState.productId,
        }, runtimeDeps.pathJoinFn(repairQueryDir, 'query-index.ndjson'));
      } catch {
        // Index recording must not crash the pipeline.
      }
      return results;
    },
    buildHypothesisFollowupsContextFn: (currentPlannerProcessingState) => runtimeDeps.buildHypothesisFollowupsContextFn({
      config,
      startMs: bootstrapState.startMs,
      logger: bootstrapState.logger,
      planner: bootstrapState.planner,
      processPlannerQueue: runProcessPlannerQueue,
      sourceResults: bootstrapState.sourceResults,
      categoryConfig: bootstrapState.categoryConfig,
      fieldOrder: bootstrapState.fieldOrder,
      anchors: bootstrapState.anchors,
      job: bootstrapState.job,
      productId: bootstrapState.productId,
      category: bootstrapState.category,
      requiredFields: bootstrapState.requiredFields,
      sourceIntel: bootstrapState.sourceIntel,
      hypothesisFollowupRoundsExecuted: currentPlannerProcessingState.hypothesisFollowupRoundsExecuted,
      hypothesisFollowupSeededUrls: currentPlannerProcessingState.hypothesisFollowupSeededUrls,
      isHelperSyntheticSourceFn: isHelperSyntheticSource,
    }),
    runHypothesisFollowupsFn: runtimeDeps.runHypothesisFollowupsFn,
    resolveHypothesisFollowupStateFn: runtimeDeps.resolveHypothesisFollowupStateFn,
    stopFetchersFn: async () => modeAwareFetcherRegistry.stopAll(),
  };
}
