import {
  buildIdentityReport,
  evaluateSourceIdentity,
  evaluateIdentityGate,
  evaluateAnchorConflicts,
  mergeAnchorConflictLists,
  evaluateValidationGate,
} from '../../features/indexing/validation/index.js';
import {
  computeCompletenessRequired,
  computeCoverageOverall,
  computeConfidence,
} from '../../scoring/qualityScoring.js';
import { executeConsensusPhase } from '../consensusPhase.js';
import {
  createEmptyProvenance,
  tsvRowFromFields,
  buildCandidateFieldMap,
  selectAggressiveEvidencePack,
  buildTopEvidenceReferences,
  emitFieldDecisionEvents,
  bestIdentityFromSources,
  PASS_TARGET_EXEMPT_FIELDS,
  isHelperSyntheticSource,
  writeSummaryMarkdownLLM,
  finalizeRunLifecycle,
} from '../../features/indexing/orchestration/index.js';
import { buildIdentityObject, buildAbortedNormalized, buildValidatedNormalized } from '../../normalizer/mouseNormalizer.js';
import { exportRunArtifacts } from '../../exporter/exporter.js';
import { writeFinalOutputs } from '../../exporter/finalExporter.js';
import { buildMarkdownSummary } from '../../exporter/summaryWriter.js';
import { persistLearningProfile, updateCategoryBrain, UrlMemoryStore, DomainFieldYieldStore, FieldAnchorsStore, ComponentLexiconStore } from '../../features/indexing/learning/index.js';
import { persistSourceIntel } from '../../intel/sourceIntel.js';
import { aggregateEndpointSignals } from '../../intel/endpointMiner.js';
import { aggregateTemporalSignals } from '../../intel/temporalSignals.js';
import { evaluateConstraintGraph } from '../../scoring/constraintSolver.js';
import { updateComponentLibrary } from '../../components/library.js';
import { applyInferencePolicies } from '../../inference/inferField.js';
import { buildIndexingSchemaPackets } from '../../indexlab/indexingSchemaPackets.js';
import { validateIndexingSchemaPackets } from '../../indexlab/indexingSchemaPacketsValidator.js';
import {
  evaluateFieldLearningGates,
  emitLearningGateEvents,
  populateLearningStores,
} from '../learningGatePhase.js';
import { writeCategoryReviewArtifacts, writeProductReviewArtifacts } from '../../review/reviewGridData.js';
import { runLearningExportPhase } from '../learningExportPhase.js';
import { normalizeAmbiguityLevel } from '../../utils/identityNormalize.js';
import { buildSourceSummary } from '../../planner/sourcePlanner.js';

const DEFAULT_DEPS = {
  buildCandidateFieldMapFn: buildCandidateFieldMap,
  evaluateAnchorConflictsFn: evaluateAnchorConflicts,
  evaluateSourceIdentityFn: evaluateSourceIdentity,
  evaluateIdentityGateFn: evaluateIdentityGate,
  buildIdentityReportFn: buildIdentityReport,
  bestIdentityFromSourcesFn: bestIdentityFromSources,
  buildIdentityObjectFn: buildIdentityObject,
  mergeAnchorConflictListsFn: mergeAnchorConflictLists,
  executeConsensusPhaseFn: executeConsensusPhase,
  buildAbortedNormalizedFn: buildAbortedNormalized,
  buildValidatedNormalizedFn: buildValidatedNormalized,
  createEmptyProvenanceFn: createEmptyProvenance,
  selectAggressiveEvidencePackFn: selectAggressiveEvidencePack,
  aggregateTemporalSignalsFn: aggregateTemporalSignals,
  applyInferencePoliciesFn: applyInferencePolicies,
  computeCompletenessRequiredFn: computeCompletenessRequired,
  computeCoverageOverallFn: computeCoverageOverall,
  computeConfidenceFn: computeConfidence,
  evaluateValidationGateFn: evaluateValidationGate,
  aggregateEndpointSignalsFn: aggregateEndpointSignals,
  evaluateConstraintGraphFn: evaluateConstraintGraph,
  writeSummaryMarkdownLLMFn: writeSummaryMarkdownLLM,
  buildMarkdownSummaryFn: buildMarkdownSummary,
  tsvRowFromFieldsFn: tsvRowFromFields,
  buildIndexingSchemaPacketsFn: buildIndexingSchemaPackets,
  validateIndexingSchemaPacketsFn: validateIndexingSchemaPackets,
  persistSourceIntelFn: persistSourceIntel,
  updateCategoryBrainFn: updateCategoryBrain,
  updateComponentLibraryFn: updateComponentLibrary,
  evaluateFieldLearningGatesFn: evaluateFieldLearningGates,
  emitLearningGateEventsFn: emitLearningGateEvents,
  UrlMemoryStoreClass: UrlMemoryStore,
  DomainFieldYieldStoreClass: DomainFieldYieldStore,
  FieldAnchorsStoreClass: FieldAnchorsStore,
  ComponentLexiconStoreClass: ComponentLexiconStore,
  populateLearningStoresFn: populateLearningStores,
  persistLearningProfileFn: persistLearningProfile,
  exportRunArtifactsFn: exportRunArtifacts,
  writeFinalOutputsFn: writeFinalOutputs,
  writeProductReviewArtifactsFn: writeProductReviewArtifacts,
  writeCategoryReviewArtifactsFn: writeCategoryReviewArtifacts,
  runLearningExportPhaseFn: runLearningExportPhase,
  finalizeRunLifecycleFn: finalizeRunLifecycle,
  emitFieldDecisionEventsFn: emitFieldDecisionEvents,
  normalizeAmbiguityLevelFn: normalizeAmbiguityLevel,
  isHelperSyntheticSourceFn: isHelperSyntheticSource,
  buildTopEvidenceReferencesFn: buildTopEvidenceReferences,
  buildSourceSummaryFn: buildSourceSummary,
  importSpecDbFn: async () => import('../../db/specDb.js'),
};

export function buildRunProductFinalizationContext({
  bootstrapState,
  storage = bootstrapState.storage,
  config = bootstrapState.config,
  runId = bootstrapState.runId,
  productId = bootstrapState.productId,
  category = bootstrapState.category,
  terminalReason = '',
  logger = bootstrapState.logger,
  roundContext = null,
  startMs = 0,
  runtimeMode = 'production',
  identityLock = {},
  identityFingerprint = '',
  identityLockStatus = '',
  dedupeMode = bootstrapState.dedupeMode || 'serp_url+content_hash',
  helperContext = bootstrapState.helperContext,
  helperFilledFields = bootstrapState.helperFilledFields,
  helperFilledByMethod = bootstrapState.helperFilledByMethod,
  helperMismatches = bootstrapState.helperMismatches,
  hypothesisFollowupRoundsExecuted = bootstrapState.hypothesisFollowupRoundsExecuted,
  hypothesisFollowupSeededUrls = bootstrapState.hypothesisFollowupSeededUrls,
  resumePersistedPendingCount = 0,
  resumePersistedLlmRetryCount = 0,
  resumePersistedSuccessCount = 0,
  runArtifactsBase = bootstrapState.runArtifactsBase,
  frontierDb = bootstrapState.frontierDb,
  uberOrchestrator = null,
  previousFinalSpec = bootstrapState.previousFinalSpec,
  deps = {},
} = {}) {
  const runtimeDeps = { ...DEFAULT_DEPS, ...deps };

  return {
    adapterManager: bootstrapState.adapterManager,
    job: bootstrapState.job,
    runId,
    storage,
    helperSupportiveSyntheticSources: bootstrapState.helperSupportiveSyntheticSources,
    adapterArtifacts: bootstrapState.adapterArtifacts,
    sourceResults: bootstrapState.sourceResults,
    anchors: bootstrapState.anchors,
    config,
    productId,
    categoryConfig: bootstrapState.categoryConfig,
    fieldOrder: bootstrapState.fieldOrder,
    category,
    runtimeFieldRulesEngine: bootstrapState.runtimeFieldRulesEngine,
    terminalReason,
    learnedConstraints: bootstrapState.learnedConstraints,
    logger,
    llmContext: bootstrapState.llmContext,
    roundContext,
    discoveryResult: bootstrapState.discoveryResult,
    artifactsByHost: bootstrapState.artifactsByHost,
    requiredFields: bootstrapState.requiredFields,
    targets: bootstrapState.targets,
    startMs,
    sourceIntel: bootstrapState.sourceIntel,
    identityLock,
    learnedFieldAvailability: bootstrapState.learnedFieldAvailability,
    learnedFieldYield: bootstrapState.learnedFieldYield,
    llmBudgetGuard: bootstrapState.llmBudgetGuard,
    phase08BatchRows: bootstrapState.phase08BatchRows,
    phase08FieldContexts: bootstrapState.phase08FieldContexts,
    phase08PrimeRows: bootstrapState.phase08PrimeRows,
    llmValidatorDecisions: bootstrapState.llmValidatorDecisions,
    buildCandidateFieldMapFn: runtimeDeps.buildCandidateFieldMapFn,
    evaluateAnchorConflictsFn: runtimeDeps.evaluateAnchorConflictsFn,
    evaluateSourceIdentityFn: runtimeDeps.evaluateSourceIdentityFn,
    evaluateIdentityGateFn: runtimeDeps.evaluateIdentityGateFn,
    buildIdentityReportFn: runtimeDeps.buildIdentityReportFn,
    bestIdentityFromSourcesFn: runtimeDeps.bestIdentityFromSourcesFn,
    buildIdentityObjectFn: runtimeDeps.buildIdentityObjectFn,
    buildSourceSummaryFn: runtimeDeps.buildSourceSummaryFn,
    mergeAnchorConflictListsFn: runtimeDeps.mergeAnchorConflictListsFn,
    executeConsensusPhaseFn: runtimeDeps.executeConsensusPhaseFn,
    buildAbortedNormalizedFn: runtimeDeps.buildAbortedNormalizedFn,
    buildValidatedNormalizedFn: runtimeDeps.buildValidatedNormalizedFn,
    createEmptyProvenanceFn: runtimeDeps.createEmptyProvenanceFn,
    selectAggressiveEvidencePackFn: runtimeDeps.selectAggressiveEvidencePackFn,
    aggregateTemporalSignalsFn: runtimeDeps.aggregateTemporalSignalsFn,
    applyInferencePoliciesFn: runtimeDeps.applyInferencePoliciesFn,
    computeCompletenessRequiredFn: runtimeDeps.computeCompletenessRequiredFn,
    computeCoverageOverallFn: runtimeDeps.computeCoverageOverallFn,
    computeConfidenceFn: runtimeDeps.computeConfidenceFn,
    evaluateValidationGateFn: runtimeDeps.evaluateValidationGateFn,
    aggregateEndpointSignalsFn: runtimeDeps.aggregateEndpointSignalsFn,
    evaluateConstraintGraphFn: runtimeDeps.evaluateConstraintGraphFn,
    passTargetExemptFields: PASS_TARGET_EXEMPT_FIELDS,
    llmRuntime: bootstrapState.llmRuntime,
    runtimeMode,
    identityFingerprint,
    identityLockStatus,
    dedupeMode,
    indexingHelperFlowEnabled: bootstrapState.indexingHelperFlowEnabled,
    helperContext,
    helperFilledFields,
    helperFilledByMethod,
    helperMismatches,
    llmTargetFields: bootstrapState.focus_fields,
    goldenExamples: bootstrapState.goldenExamples,
    llmCandidatesAccepted: bootstrapState.llmCandidatesAccepted,
    llmSourcesUsed: bootstrapState.llmSourcesUsed,
    fetcherMode: bootstrapState.fetcherMode,
    fetcherStartFallbackReason: bootstrapState.fetcherStartFallbackReason,
    indexingResumeKey: bootstrapState.indexingResumeKey,
    resumeMode: bootstrapState.resumeMode,
    resumeMaxAgeHours: bootstrapState.resumeMaxAgeHours,
    previousResumeStateAgeHours: bootstrapState.previousResumeStateAgeHours,
    resumeReextractEnabled: bootstrapState.resumeReextractEnabled,
    resumeReextractAfterHours: bootstrapState.resumeReextractAfterHours,
    resumeSeededPendingCount: bootstrapState.resumeSeededPendingCount,
    resumeSeededLlmRetryCount: bootstrapState.resumeSeededLlmRetryCount,
    resumeSeededReextractCount: bootstrapState.resumeSeededReextractCount,
    resumePersistedPendingCount,
    resumePersistedLlmRetryCount,
    resumePersistedSuccessCount,
    plannerStats: bootstrapState.planner.getStats(),
    hypothesisFollowupRoundsExecuted,
    hypothesisFollowupSeededUrls,
    normalizeAmbiguityLevelFn: runtimeDeps.normalizeAmbiguityLevelFn,
    isHelperSyntheticSourceFn: runtimeDeps.isHelperSyntheticSourceFn,
    buildTopEvidenceReferencesFn: runtimeDeps.buildTopEvidenceReferencesFn,
    runArtifactsBase,
    learningProfile: bootstrapState.learningProfile,
    frontierDb,
    uberOrchestrator,
    previousFinalSpec,
    writeSummaryMarkdownLLMFn: runtimeDeps.writeSummaryMarkdownLLMFn,
    buildMarkdownSummaryFn: runtimeDeps.buildMarkdownSummaryFn,
    tsvRowFromFieldsFn: runtimeDeps.tsvRowFromFieldsFn,
    buildIndexingSchemaPacketsFn: runtimeDeps.buildIndexingSchemaPacketsFn,
    validateIndexingSchemaPacketsFn: runtimeDeps.validateIndexingSchemaPacketsFn,
    persistSourceIntelFn: runtimeDeps.persistSourceIntelFn,
    updateCategoryBrainFn: runtimeDeps.updateCategoryBrainFn,
    updateComponentLibraryFn: runtimeDeps.updateComponentLibraryFn,
    evaluateFieldLearningGatesFn: runtimeDeps.evaluateFieldLearningGatesFn,
    emitLearningGateEventsFn: runtimeDeps.emitLearningGateEventsFn,
    importSpecDbFn: runtimeDeps.importSpecDbFn,
    UrlMemoryStoreClass: runtimeDeps.UrlMemoryStoreClass,
    DomainFieldYieldStoreClass: runtimeDeps.DomainFieldYieldStoreClass,
    FieldAnchorsStoreClass: runtimeDeps.FieldAnchorsStoreClass,
    ComponentLexiconStoreClass: runtimeDeps.ComponentLexiconStoreClass,
    populateLearningStoresFn: runtimeDeps.populateLearningStoresFn,
    persistLearningProfileFn: runtimeDeps.persistLearningProfileFn,
    exportRunArtifactsFn: runtimeDeps.exportRunArtifactsFn,
    writeFinalOutputsFn: runtimeDeps.writeFinalOutputsFn,
    writeProductReviewArtifactsFn: runtimeDeps.writeProductReviewArtifactsFn,
    writeCategoryReviewArtifactsFn: runtimeDeps.writeCategoryReviewArtifactsFn,
    runLearningExportPhaseFn: runtimeDeps.runLearningExportPhaseFn,
    finalizeRunLifecycleFn: runtimeDeps.finalizeRunLifecycleFn,
    emitFieldDecisionEventsFn: runtimeDeps.emitFieldDecisionEventsFn,
  };
}
