import { buildIndexingRunCortexPayload } from './indexingRunCortexPayload';
import { buildIndexingRunDiscoveryPayload } from './indexingRunDiscoveryPayload';
import { buildIndexingRunLearningPayload } from './indexingRunLearningPayload';
import { buildIndexingRunLlmSettingsPayload } from './indexingRunLlmSettingsPayload';
import { buildIndexingRunModelPayload } from './indexingRunModelPayload';
import { buildIndexingRunOcrPolicyPayload } from './indexingRunOcrPolicyPayload';
import { buildIndexingRunRuntimePayload } from './indexingRunRuntimePayload';
import { LLM_SETTING_LIMITS } from '../../../stores/settingsManifest';
import { deriveIndexingRunStartParsedValues } from './indexingRunStartParsedValues';
import type { RuntimeSettings } from '../../pipeline-settings';

const LLM_MIN_OUTPUT_TOKENS = LLM_SETTING_LIMITS.maxTokens.min;
const LLM_EXTRACT_MIN_TOKENS = 128;
const LLM_EXTRACT_MIN_SNIPPET_CHARS = 128;

type StartIndexingRunPayloadValue = string | number | boolean;
type StartIndexingRunPayloadRecord = Record<string, StartIndexingRunPayloadValue>;

interface StartIndexingRunPayloadParsedValues extends ReturnType<typeof deriveIndexingRunStartParsedValues> {}

interface BuildIndexingRunStartPayloadInput {
  requestedRunId: string;
  category: string;
  productId: string;
  runtimeSettingsPayload: RuntimeSettings;
  parsedValues: StartIndexingRunPayloadParsedValues;
  runControlPayload: StartIndexingRunPayloadRecord;
}

const readString = (value: StartIndexingRunPayloadValue | undefined): string => (
  String(value || '').trim()
);

const readBool = (value: StartIndexingRunPayloadValue | undefined): boolean => (
  Boolean(value)
);

export function buildIndexingRunStartPayload(
  input: BuildIndexingRunStartPayloadInput,
): StartIndexingRunPayloadRecord {
  const {
    requestedRunId,
    category,
    productId,
    runtimeSettingsPayload,
    parsedValues,
    runControlPayload,
  } = input;
  const s = runtimeSettingsPayload;
  const p = parsedValues;

  const runtimePayload: StartIndexingRunPayloadRecord = {
    requestedRunId: String(requestedRunId || '').trim(),
    category,
    mode: 'indexlab',
    replaceRunning: true,
    productId,
    profile: 'standard',
    fetchConcurrency: p.parsedConcurrency,
    perHostMinDelayMs: p.parsedPerHostMinDelayMs,
    domainRequestRps: Math.max(0, p.parsedDomainRequestRps),
    domainRequestBurst: Math.max(0, p.parsedDomainRequestBurst),
    globalRequestRps: Math.max(0, p.parsedGlobalRequestRps),
    globalRequestBurst: Math.max(0, p.parsedGlobalRequestBurst),
    fetchPerHostConcurrencyCap: Math.max(1, p.parsedFetchPerHostConcurrencyCap),
    dynamicCrawleeEnabled: readBool(s.dynamicCrawleeEnabled),
    crawleeHeadless: readBool(s.crawleeHeadless),
    crawleeRequestHandlerTimeoutSecs: Math.max(0, p.parsedCrawleeTimeout),
    dynamicFetchRetryBudget: Math.max(0, p.parsedRetryBudget),
    dynamicFetchRetryBackoffMs: Math.max(0, p.parsedRetryBackoff),
    fetchSchedulerEnabled: readBool(s.fetchSchedulerEnabled),
    fetchSchedulerMaxRetries: Math.max(0, p.parsedFetchSchedulerMaxRetries),
    fetchSchedulerFallbackWaitMs: Math.max(0, p.parsedFetchSchedulerFallbackWaitMs),
    preferHttpFetcher: readBool(s.preferHttpFetcher),
    pageGotoTimeoutMs: Math.max(0, p.parsedPageGotoTimeoutMs),
    pageNetworkIdleTimeoutMs: Math.max(0, p.parsedPageNetworkIdleTimeoutMs),
    postLoadWaitMs: Math.max(0, p.parsedPostLoadWaitMs),
    frontierDbPath: readString(s.frontierDbPath),
    frontierEnableSqlite: readBool(s.frontierEnableSqlite),
    frontierStripTrackingParams: readBool(s.frontierStripTrackingParams),
    frontierQueryCooldownSeconds: Math.max(0, p.parsedFrontierQueryCooldownSeconds),
    frontierCooldown404Seconds: Math.max(0, p.parsedFrontierCooldown404Seconds),
    frontierCooldown404RepeatSeconds: Math.max(0, p.parsedFrontierCooldown404RepeatSeconds),
    frontierCooldown410Seconds: Math.max(0, p.parsedFrontierCooldown410Seconds),
    frontierCooldownTimeoutSeconds: Math.max(0, p.parsedFrontierCooldownTimeoutSeconds),
    frontierCooldown403BaseSeconds: Math.max(0, p.parsedFrontierCooldown403BaseSeconds),
    frontierCooldown429BaseSeconds: Math.max(0, p.parsedFrontierCooldown429BaseSeconds),
    frontierBackoffMaxExponent: Math.max(1, p.parsedFrontierBackoffMaxExponent),
    frontierPathPenaltyNotfoundThreshold: Math.max(1, p.parsedFrontierPathPenaltyNotfoundThreshold),
    frontierBlockedDomainThreshold: Math.max(1, p.parsedFrontierBlockedDomainThreshold),
    frontierRepairSearchEnabled: readBool(s.frontierRepairSearchEnabled),
    autoScrollEnabled: readBool(s.autoScrollEnabled),
    autoScrollPasses: Math.max(0, p.parsedAutoScrollPasses),
    autoScrollDelayMs: Math.max(0, p.parsedAutoScrollDelayMs),
    graphqlReplayEnabled: readBool(s.graphqlReplayEnabled),
    maxGraphqlReplays: Math.max(0, p.parsedMaxGraphqlReplays),
    maxNetworkResponsesPerPage: Math.max(100, p.parsedMaxNetworkResponsesPerPage),
    robotsTxtCompliant: readBool(s.robotsTxtCompliant),
    robotsTxtTimeoutMs: Math.max(100, p.parsedRobotsTxtTimeoutMs),
    ...buildIndexingRunRuntimePayload({
      runtimeScreencastEnabled: readBool(s.runtimeScreencastEnabled),
      parsedRuntimeScreencastFps: p.parsedRuntimeScreencastFps,
      parsedRuntimeScreencastQuality: p.parsedRuntimeScreencastQuality,
      parsedRuntimeScreencastMaxWidth: p.parsedRuntimeScreencastMaxWidth,
      parsedRuntimeScreencastMaxHeight: p.parsedRuntimeScreencastMaxHeight,
      runtimeTraceEnabled: readBool(s.runtimeTraceEnabled),
      parsedRuntimeTraceFetchRing: p.parsedRuntimeTraceFetchRing,
      parsedRuntimeTraceLlmRing: p.parsedRuntimeTraceLlmRing,
      runtimeTraceLlmPayloads: readBool(s.runtimeTraceLlmPayloads),
      parsedDaemonConcurrency: p.parsedDaemonConcurrency,
      parsedDaemonGracefulShutdownTimeoutMs: p.parsedDaemonGracefulShutdownTimeoutMs,
      importsRoot: readString(s.importsRoot),
      parsedImportsPollSeconds: p.parsedImportsPollSeconds,
      parsedIndexingResumeSeedLimit: p.parsedIndexingResumeSeedLimit,
      parsedIndexingResumePersistLimit: p.parsedIndexingResumePersistLimit,
      eventsJsonWrite: readBool(s.eventsJsonWrite),
      indexingSchemaPacketsValidationEnabled: readBool(s.indexingSchemaPacketsValidationEnabled),
      indexingSchemaPacketsValidationStrict: readBool(s.indexingSchemaPacketsValidationStrict),
      queueJsonWrite: readBool(s.queueJsonWrite),
      billingJsonWrite: readBool(s.billingJsonWrite),
      intelJsonWrite: readBool(s.intelJsonWrite),
      corpusJsonWrite: readBool(s.corpusJsonWrite),
      learningJsonWrite: readBool(s.learningJsonWrite),
      cacheJsonWrite: readBool(s.cacheJsonWrite),
      authoritySnapshotEnabled: readBool(s.authoritySnapshotEnabled),
    }),
    ...buildIndexingRunOcrPolicyPayload({
      scannedPdfOcrEnabled: readBool(s.scannedPdfOcrEnabled),
      scannedPdfOcrPromoteCandidates: readBool(s.scannedPdfOcrPromoteCandidates),
      scannedPdfOcrBackend: readString(s.scannedPdfOcrBackend),
      parsedScannedPdfOcrMaxPages: p.parsedScannedPdfOcrMaxPages,
      parsedScannedPdfOcrMaxPairs: p.parsedScannedPdfOcrMaxPairs,
      parsedScannedPdfOcrMinChars: p.parsedScannedPdfOcrMinChars,
      parsedScannedPdfOcrMinLines: p.parsedScannedPdfOcrMinLines,
      parsedScannedPdfOcrMinConfidence: p.parsedScannedPdfOcrMinConfidence,
      dynamicFetchPolicyMapJson: readString(s.dynamicFetchPolicyMapJson),
      searchProfileCapMapJson: readString(s.searchProfileCapMapJson),
      serpRerankerWeightMapJson: readString(s.serpRerankerWeightMapJson),
      fetchSchedulerInternalsMapJson: readString(s.fetchSchedulerInternalsMapJson),
      parsingConfidenceBaseMapJson: readString(s.parsingConfidenceBaseMapJson),
      repairDedupeRule: readString(s.repairDedupeRule),
    }),
    ...buildIndexingRunDiscoveryPayload({
      fetchCandidateSources: readBool(s.fetchCandidateSources),
      parsedDiscoveryMaxQueries: p.parsedDiscoveryMaxQueries,
      parsedDiscoveryMaxDiscovered: p.parsedDiscoveryMaxDiscovered,
      parsedMaxUrlsPerProduct: p.parsedMaxUrlsPerProduct,
      parsedMaxCandidateUrls: p.parsedMaxCandidateUrls,
      parsedMaxPagesPerDomain: p.parsedMaxPagesPerDomain,
      parsedMaxRunSeconds: p.parsedMaxRunSeconds,
      parsedMaxJsonBytes: p.parsedMaxJsonBytes,
      parsedMaxPdfBytes: p.parsedMaxPdfBytes,
    }),
    pdfBackendRouterEnabled: readBool(s.pdfBackendRouterEnabled),
    pdfPreferredBackend: readString(s.pdfPreferredBackend),
    pdfBackendRouterTimeoutMs: Math.max(1000, p.parsedPdfBackendRouterTimeoutMs),
    pdfBackendRouterMaxPages: Math.max(1, p.parsedPdfBackendRouterMaxPages),
    pdfBackendRouterMaxPairs: Math.max(1, p.parsedPdfBackendRouterMaxPairs),
    pdfBackendRouterMaxTextPreviewChars: Math.max(256, p.parsedPdfBackendRouterMaxTextPreviewChars),
    capturePageScreenshotEnabled: readBool(s.capturePageScreenshotEnabled),
    capturePageScreenshotFormat: readString(s.capturePageScreenshotFormat),
    capturePageScreenshotQuality: Math.max(1, p.parsedCapturePageScreenshotQuality),
    capturePageScreenshotMaxBytes: Math.max(1024, p.parsedCapturePageScreenshotMaxBytes),
    capturePageScreenshotSelectors: readString(s.capturePageScreenshotSelectors),
    articleExtractorV2Enabled: readBool(s.articleExtractorV2Enabled),
    articleExtractorMinChars: Math.max(50, p.parsedArticleExtractorMinChars),
    articleExtractorMinScore: Math.max(1, p.parsedArticleExtractorMinScore),
    articleExtractorMaxChars: Math.max(256, p.parsedArticleExtractorMaxChars),
    staticDomExtractorEnabled: readBool(s.staticDomExtractorEnabled),
    staticDomMode: readString(s.staticDomMode),
    staticDomTargetMatchThreshold: Math.max(0, Math.min(1, p.parsedStaticDomTargetMatchThreshold)),
    staticDomMaxEvidenceSnippets: Math.max(10, p.parsedStaticDomMaxEvidenceSnippets),
    articleExtractorDomainPolicyMapJson: readString(s.articleExtractorDomainPolicyMapJson),
    htmlTableExtractorV2: readBool(s.htmlTableExtractorV2),
    structuredMetadataExtructEnabled: readBool(s.structuredMetadataExtructEnabled),
    structuredMetadataExtructUrl: readString(s.structuredMetadataExtructUrl),
    structuredMetadataExtructTimeoutMs: Math.max(250, p.parsedStructuredMetadataExtructTimeoutMs),
    structuredMetadataExtructMaxItemsPerSurface: Math.max(1, p.parsedStructuredMetadataExtructMaxItemsPerSurface),
    structuredMetadataExtructCacheEnabled: readBool(s.structuredMetadataExtructCacheEnabled),
    structuredMetadataExtructCacheLimit: Math.max(32, p.parsedStructuredMetadataExtructCacheLimit),
    domSnippetMaxChars: Math.max(600, p.parsedDomSnippetMaxChars),
    runtimeControlFile: readString(s.runtimeControlFile),
    specDbDir: readString(s.specDbDir),
    categoryAuthorityEnabled: readBool(s.categoryAuthorityEnabled),
    categoryAuthorityRoot: readString(s.categoryAuthorityRoot),
    helperSupportiveFillMissing: readBool(s.helperSupportiveFillMissing),
    fieldRewardHalfLifeDays: Math.max(1, p.parsedFieldRewardHalfLifeDays),
    batchStrategy: readString(s.batchStrategy),
    driftDetectionEnabled: readBool(s.driftDetectionEnabled),
    driftPollSeconds: Math.max(60, p.parsedDriftPollSeconds),
    driftScanMaxProducts: Math.max(1, p.parsedDriftScanMaxProducts),
    driftAutoRepublish: readBool(s.driftAutoRepublish),
    reCrawlStaleAfterDays: Math.max(1, p.parsedReCrawlStaleAfterDays),
    ...buildIndexingRunCortexPayload({
      cortexEnabled: readBool(s.cortexEnabled),
      cortexAsyncEnabled: readBool(s.cortexAsyncEnabled),
      cortexBaseUrl: readString(s.cortexBaseUrl),
      cortexApiKey: readString(s.cortexApiKey),
      cortexAsyncBaseUrl: readString(s.cortexAsyncBaseUrl),
      cortexAsyncSubmitPath: readString(s.cortexAsyncSubmitPath),
      cortexAsyncStatusPath: readString(s.cortexAsyncStatusPath),
      parsedCortexSyncTimeoutMs: p.parsedCortexSyncTimeoutMs,
      parsedCortexAsyncPollIntervalMs: p.parsedCortexAsyncPollIntervalMs,
      parsedCortexAsyncMaxWaitMs: p.parsedCortexAsyncMaxWaitMs,
      parsedCortexEnsureReadyTimeoutMs: p.parsedCortexEnsureReadyTimeoutMs,
      parsedCortexStartReadyTimeoutMs: p.parsedCortexStartReadyTimeoutMs,
      parsedCortexFailureThreshold: p.parsedCortexFailureThreshold,
      parsedCortexCircuitOpenMs: p.parsedCortexCircuitOpenMs,
      cortexModelFast: readString(s.cortexModelFast),
      cortexModelDom: readString(s.cortexModelDom),
      cortexModelReasoningDeep: readString(s.cortexModelReasoningDeep),
      cortexModelVision: readString(s.cortexModelVision),
      cortexModelSearchFast: readString(s.cortexModelSearchFast),
      cortexModelRerankFast: readString(s.cortexModelRerankFast),
      cortexAutoStart: readBool(s.cortexAutoStart),
      parsedCortexEscalateConfidenceLt: p.parsedCortexEscalateConfidenceLt,
      cortexEscalateIfConflict: readBool(s.cortexEscalateIfConflict),
      cortexEscalateCriticalOnly: readBool(s.cortexEscalateCriticalOnly),
      parsedCortexMaxDeepFieldsPerProduct: p.parsedCortexMaxDeepFieldsPerProduct,
    }),
    outputMode: readString(s.outputMode),
    localMode: readBool(s.localMode),
    dryRun: readBool(s.dryRun),
    mirrorToS3: readBool(s.mirrorToS3),
    mirrorToS3Input: readBool(s.mirrorToS3Input),
    localInputRoot: readString(s.localInputRoot),
    localOutputRoot: readString(s.localOutputRoot),
    runtimeEventsKey: readString(s.runtimeEventsKey),
    writeMarkdownSummary: readBool(s.writeMarkdownSummary),
    awsRegion: readString(s.awsRegion),
    s3Bucket: readString(s.s3Bucket),
    s3InputPrefix: readString(s.s3InputPrefix),
    s3OutputPrefix: readString(s.s3OutputPrefix),
    eloSupabaseAnonKey: readString(s.eloSupabaseAnonKey),
    eloSupabaseEndpoint: readString(s.eloSupabaseEndpoint),
    ...buildIndexingRunLearningPayload({
      llmWriteSummary: readBool(s.llmWriteSummary),
      llmProvider: readString(s.llmProvider),
      llmBaseUrl: readString(s.llmBaseUrl),
      openaiApiKey: readString(s.openaiApiKey),
      anthropicApiKey: readString(s.anthropicApiKey),
      indexingCategoryAuthorityEnabled: readBool(s.indexingCategoryAuthorityEnabled),
      userAgent: readString(s.userAgent),
      selfImproveEnabled: readBool(s.selfImproveEnabled),
      parsedMaxHypothesisItems: p.parsedMaxHypothesisItems,
      parsedHypothesisAutoFollowupRounds: p.parsedHypothesisAutoFollowupRounds,
      parsedHypothesisFollowupUrlsPerRound: p.parsedHypothesisFollowupUrlsPerRound,
      searxngBaseUrl: readString(s.searxngBaseUrl),
      llmPlanProvider: readString(s.llmPlanProvider),
      llmPlanBaseUrl: readString(s.llmPlanBaseUrl),
      llmPlanApiKey: readString(s.llmPlanApiKey),
      llmExtractionCacheEnabled: readBool(s.llmExtractionCacheEnabled),
      llmExtractionCacheDir: readString(s.llmExtractionCacheDir),
      parsedLlmExtractionCacheTtlMs: p.parsedLlmExtractionCacheTtlMs,
      parsedLlmMaxCallsPerProductTotal: p.parsedLlmMaxCallsPerProductTotal,
      parsedLlmMaxCallsPerProductFast: p.parsedLlmMaxCallsPerProductFast,
      parsedLlmExtractMaxTokens: p.parsedLlmExtractMaxTokens,
      llmExtractMinTokens: LLM_EXTRACT_MIN_TOKENS,
      parsedLlmExtractMaxSnippetsPerBatch: p.parsedLlmExtractMaxSnippetsPerBatch,
      parsedLlmExtractMaxSnippetChars: p.parsedLlmExtractMaxSnippetChars,
      llmExtractMinSnippetChars: LLM_EXTRACT_MIN_SNIPPET_CHARS,
      llmExtractSkipLowSignal: readBool(s.llmExtractSkipLowSignal),
      parsedLlmExtractReasoningBudget: p.parsedLlmExtractReasoningBudget,
      llmReasoningMode: readString(s.llmReasoningMode),
      parsedLlmReasoningBudget: p.parsedLlmReasoningBudget,
      parsedLlmMonthlyBudgetUsd: p.parsedLlmMonthlyBudgetUsd,
      parsedLlmPerProductBudgetUsd: p.parsedLlmPerProductBudgetUsd,
    }),
    ...buildIndexingRunLlmSettingsPayload({
      parsedLlmMaxCallsPerRound: p.parsedLlmMaxCallsPerRound,
      parsedLlmMaxOutputTokens: p.parsedLlmMaxOutputTokens,
      llmMinOutputTokens: LLM_MIN_OUTPUT_TOKENS,
      parsedLlmVerifySampleRate: p.parsedLlmVerifySampleRate,
      llmDisableBudgetGuards: readBool(s.llmDisableBudgetGuards),
      parsedLlmMaxBatchesPerProduct: p.parsedLlmMaxBatchesPerProduct,
      parsedLlmMaxEvidenceChars: p.parsedLlmMaxEvidenceChars,
      parsedLlmMaxTokens: p.parsedLlmMaxTokens,
      parsedLlmTimeoutMs: p.parsedLlmTimeoutMs,
      parsedLlmCostInputPer1M: p.parsedLlmCostInputPer1M,
      parsedLlmCostOutputPer1M: p.parsedLlmCostOutputPer1M,
      parsedLlmCostCachedInputPer1M: p.parsedLlmCostCachedInputPer1M,
      llmVerifyMode: readString(s.llmVerifyMode),
      parsedEndpointSignalLimit: p.parsedEndpointSignalLimit,
      parsedEndpointSuggestionLimit: p.parsedEndpointSuggestionLimit,
      parsedEndpointNetworkScanLimit: p.parsedEndpointNetworkScanLimit,
    }),
    ...buildIndexingRunModelPayload({
      searchProvider: readString(s.searchProvider),
      llmModelPlan: readString(s.llmModelPlan),
      llmModelTriage: readString(s.llmModelTriage),
      llmMaxOutputTokensPlan: Number(s.llmMaxOutputTokensPlan || 0),
      llmModelFast: readString(s.llmModelFast),
      llmMaxOutputTokensFast: Number(s.llmMaxOutputTokensFast || 0),
      llmMaxOutputTokensTriage: Number(s.llmMaxOutputTokensTriage || 0),
      llmModelReasoning: readString(s.llmModelReasoning),
      llmMaxOutputTokensReasoning: Number(s.llmMaxOutputTokensReasoning || 0),
      llmModelExtract: readString(s.llmModelExtract),
      llmMaxOutputTokensExtract: Number(s.llmMaxOutputTokensExtract || 0),
      llmModelValidate: readString(s.llmModelValidate),
      llmMaxOutputTokensValidate: Number(s.llmMaxOutputTokensValidate || 0),
      llmModelWrite: readString(s.llmModelWrite),
      llmMaxOutputTokensWrite: Number(s.llmMaxOutputTokensWrite || 0),
      llmPlanFallbackModel: readString(s.llmPlanFallbackModel),
      llmMaxOutputTokensPlanFallback: Number(s.llmMaxOutputTokensPlanFallback || 0),
      llmMaxOutputTokensExtractFallback: Number(s.llmMaxOutputTokensExtractFallback || 0),
      llmMaxOutputTokensValidateFallback: Number(s.llmMaxOutputTokensValidateFallback || 0),
      llmMaxOutputTokensWriteFallback: Number(s.llmMaxOutputTokensWriteFallback || 0),
    }),
    ...runControlPayload,
  };

  return runtimePayload;
}
