import Ajv2020 from 'ajv/dist/2020.js';
import { SETTINGS_DEFAULTS, SETTINGS_OPTION_VALUES } from '../../shared/settingsDefaults.js';

function asRecord(value) {
  return value && typeof value === 'object' && !Array.isArray(value) ? value : {};
}

function pickKnownKeys(source, keys) {
  const input = asRecord(source);
  const picked = {};
  for (const key of keys) {
    if (Object.hasOwn(input, key)) {
      picked[key] = input[key];
    }
  }
  return picked;
}

function normalizeSchemaVersion(value) {
  const parsed = Number.parseInt(String(value ?? ''), 10);
  return Number.isFinite(parsed) && parsed > 0 ? parsed : 0;
}

export const USER_SETTINGS_FILE = 'user-settings.json';
export const SETTINGS_DOCUMENT_SCHEMA_VERSION = 2;

export const SETTINGS_SCHEMA_MIGRATION_RULES = Object.freeze([
  Object.freeze({
    from: 0,
    to: 1,
    description: 'Normalize legacy payloads without sectioned settings envelopes.',
  }),
  Object.freeze({
    from: 1,
    to: 2,
    description: 'Canonicalize section keys and enforce deterministic authority precedence.',
  }),
]);

export const RUNTIME_SETTINGS_KEYS = Object.freeze([
  'runProfile',
  'searchProvider',
  'searxngBaseUrl',
  'bingSearchEndpoint',
  'bingSearchKey',
  'googleCseCx',
  'googleCseKey',
  'llmPlanApiKey',
  'duckduckgoBaseUrl',
  'duckduckgoTimeoutMs',
  'llmModelPlan',
  'llmModelTriage',
  'llmModelFast',
  'llmModelReasoning',
  'llmModelExtract',
  'llmModelValidate',
  'llmModelWrite',
  'needsetEvidenceDecayDays',
  'needsetEvidenceDecayFloor',
  'needsetRequiredWeightIdentity',
  'needsetRequiredWeightCritical',
  'needsetRequiredWeightRequired',
  'needsetRequiredWeightExpected',
  'needsetRequiredWeightOptional',
  'needsetMissingMultiplier',
  'needsetTierDeficitMultiplier',
  'needsetMinRefsDeficitMultiplier',
  'needsetConflictMultiplier',
  'needsetIdentityLockThreshold',
  'needsetIdentityProvisionalThreshold',
  'needsetDefaultIdentityAuditLimit',
  'consensusMethodWeightNetworkJson',
  'consensusMethodWeightAdapterApi',
  'consensusMethodWeightStructuredMeta',
  'consensusMethodWeightPdf',
  'consensusMethodWeightTableKv',
  'consensusMethodWeightDom',
  'consensusMethodWeightLlmExtractBase',
  'consensusPolicyBonus',
  'consensusWeightedMajorityThreshold',
  'consensusStrictAcceptanceDomainCount',
  'consensusRelaxedAcceptanceDomainCount',
  'consensusInstrumentedFieldThreshold',
  'consensusConfidenceScoringBase',
  'consensusPassTargetIdentityStrong',
  'consensusPassTargetNormal',
  'retrievalTierWeightTier1',
  'retrievalTierWeightTier2',
  'retrievalTierWeightTier3',
  'retrievalTierWeightTier4',
  'retrievalTierWeightTier5',
  'retrievalDocKindWeightManualPdf',
  'retrievalDocKindWeightSpecPdf',
  'retrievalDocKindWeightSupport',
  'retrievalDocKindWeightLabReview',
  'retrievalDocKindWeightProductPage',
  'retrievalDocKindWeightOther',
  'retrievalMethodWeightTable',
  'retrievalMethodWeightKv',
  'retrievalMethodWeightJsonLd',
  'retrievalMethodWeightLlmExtract',
  'retrievalMethodWeightHelperSupportive',
  'retrievalAnchorScorePerMatch',
  'retrievalIdentityScorePerMatch',
  'retrievalUnitMatchBonus',
  'retrievalDirectFieldMatchBonus',
  'evidenceTextMaxChars',
  'llmExtractMaxTokens',
  'llmExtractMaxSnippetsPerBatch',
  'llmExtractMaxSnippetChars',
  'llmExtractSkipLowSignal',
  'llmExtractReasoningBudget',
  'llmReasoningMode',
  'llmReasoningBudget',
  'llmMonthlyBudgetUsd',
  'llmPerProductBudgetUsd',
  'llmDisableBudgetGuards',
  'llmMaxCallsPerRound',
  'llmMaxOutputTokens',
  'llmVerifySampleRate',
  'llmMaxBatchesPerProduct',
  'llmMaxEvidenceChars',
  'llmMaxTokens',
  'llmTimeoutMs',
  'llmCostInputPer1M',
  'llmCostOutputPer1M',
  'llmCostCachedInputPer1M',
  'llmVerifyMode',
  'llmPlanFallbackModel',
  'llmExtractFallbackModel',
  'llmValidateFallbackModel',
  'llmWriteFallbackModel',
  'indexingResumeMode',
  'indexingResumeSeedLimit',
  'indexingResumePersistLimit',
  'indexingSchemaPacketsValidationEnabled',
  'indexingSchemaPacketsValidationStrict',
  'outputMode',
  'localMode',
  'dryRun',
  'mirrorToS3',
  'mirrorToS3Input',
  'localInputRoot',
  'localOutputRoot',
  'runtimeEventsKey',
  'writeMarkdownSummary',
  'awsRegion',
  's3Bucket',
  's3InputPrefix',
  's3OutputPrefix',
  'eloSupabaseAnonKey',
  'eloSupabaseEndpoint',
  'llmEnabled',
  'llmWriteSummary',
  'llmProvider',
  'llmBaseUrl',
  'openaiApiKey',
  'anthropicApiKey',
  'llmPlanProvider',
  'llmPlanBaseUrl',
  'concurrency',
  'perHostMinDelayMs',
  'indexingResumeMaxAgeHours',
  'indexingReextractAfterHours',
  'convergenceIdentityFailFastRounds',
  'identityGatePublishThreshold',
  'identityGateBaseMatchThreshold',
  'identityGateEasyAmbiguityReduction',
  'identityGateMediumAmbiguityReduction',
  'identityGateHardAmbiguityReduction',
  'identityGateVeryHardAmbiguityIncrease',
  'identityGateExtraHardAmbiguityIncrease',
  'identityGateMissingStrongIdPenalty',
  'identityGateHardMissingStrongIdIncrease',
  'identityGateVeryHardMissingStrongIdIncrease',
  'identityGateExtraHardMissingStrongIdIncrease',
  'identityGateNumericTokenBoost',
  'identityGateNumericRangeThreshold',
  'qualityGateIdentityThreshold',
  'scannedPdfOcrBackend',
  'scannedPdfOcrMaxPages',
  'scannedPdfOcrMaxPairs',
  'scannedPdfOcrMinCharsPerPage',
  'scannedPdfOcrMinLinesPerPage',
  'scannedPdfOcrMinConfidence',
  'crawleeRequestHandlerTimeoutSecs',
  'dynamicFetchRetryBudget',
  'dynamicFetchRetryBackoffMs',
  'llmMaxOutputTokensPlan',
  'llmMaxOutputTokensTriage',
  'llmMaxOutputTokensFast',
  'llmMaxOutputTokensReasoning',
  'llmMaxOutputTokensExtract',
  'llmMaxOutputTokensValidate',
  'llmMaxOutputTokensWrite',
  'llmMaxOutputTokensPlanFallback',
  'llmMaxOutputTokensExtractFallback',
  'llmMaxOutputTokensValidateFallback',
  'llmMaxOutputTokensWriteFallback',
  'discoveryEnabled',
  'fetchCandidateSources',
  'discoveryMaxQueries',
  'discoveryResultsPerQuery',
  'discoveryMaxDiscovered',
  'discoveryQueryConcurrency',
  'manufacturerBroadDiscovery',
  'manufacturerSeedSearchUrls',
  'maxUrlsPerProduct',
  'maxCandidateUrls',
  'maxPagesPerDomain',
  'uberMaxUrlsPerProduct',
  'uberMaxUrlsPerDomain',
  'maxRunSeconds',
  'maxJsonBytes',
  'maxPdfBytes',
  'specDbDir',
  'pdfBackendRouterEnabled',
  'pdfPreferredBackend',
  'pdfBackendRouterTimeoutMs',
  'pdfBackendRouterMaxPages',
  'pdfBackendRouterMaxPairs',
  'pdfBackendRouterMaxTextPreviewChars',
  'capturePageScreenshotEnabled',
  'capturePageScreenshotFormat',
  'capturePageScreenshotQuality',
  'capturePageScreenshotMaxBytes',
  'capturePageScreenshotSelectors',
  'runtimeCaptureScreenshots',
  'runtimeScreenshotMode',
  'visualAssetCaptureEnabled',
  'visualAssetCaptureMaxPerSource',
  'visualAssetStoreOriginal',
  'visualAssetRetentionDays',
  'visualAssetPhashEnabled',
  'visualAssetReviewFormat',
  'visualAssetReviewLgMaxSide',
  'visualAssetReviewSmMaxSide',
  'visualAssetReviewLgQuality',
  'visualAssetReviewSmQuality',
  'visualAssetRegionCropMaxSide',
  'visualAssetRegionCropQuality',
  'visualAssetLlmMaxBytes',
  'visualAssetMinWidth',
  'visualAssetMinHeight',
  'visualAssetMinSharpness',
  'visualAssetMinEntropy',
  'visualAssetMaxPhashDistance',
  'visualAssetHeroSelectorMapJson',
  'chartExtractionEnabled',
  'runtimeControlFile',
  'articleExtractorV2Enabled',
  'articleExtractorMinChars',
  'articleExtractorMinScore',
  'articleExtractorMaxChars',
  'articleExtractorDomainPolicyMapJson',
  'htmlTableExtractorV2',
  'staticDomExtractorEnabled',
  'staticDomMode',
  'staticDomTargetMatchThreshold',
  'staticDomMaxEvidenceSnippets',
  'structuredMetadataExtructEnabled',
  'structuredMetadataExtructUrl',
  'structuredMetadataExtructTimeoutMs',
  'structuredMetadataExtructMaxItemsPerSurface',
  'structuredMetadataExtructCacheEnabled',
  'structuredMetadataExtructCacheLimit',
  'domSnippetMaxChars',
  'helperFilesRoot',
  'helperSupportiveMaxSources',
  'helperActiveSyncLimit',
  'fieldRewardHalfLifeDays',
  'batchStrategy',
  'driftPollSeconds',
  'driftScanMaxProducts',
  'reCrawlStaleAfterDays',
  'aggressiveConfidenceThreshold',
  'aggressiveMaxSearchQueries',
  'aggressiveEvidenceAuditBatchSize',
  'aggressiveMaxTimePerProductMs',
  'aggressiveThoroughFromRound',
  'aggressiveRound1MaxUrls',
  'aggressiveRound1MaxCandidateUrls',
  'aggressiveLlmMaxCallsPerRound',
  'aggressiveLlmMaxCallsPerProductTotal',
  'aggressiveLlmTargetMaxFields',
  'aggressiveLlmDiscoveryPasses',
  'aggressiveLlmDiscoveryQueryCap',
  'uberMaxRounds',
  'cortexBaseUrl',
  'cortexApiKey',
  'cortexAsyncBaseUrl',
  'cortexAsyncSubmitPath',
  'cortexAsyncStatusPath',
  'cortexSyncTimeoutMs',
  'cortexAsyncPollIntervalMs',
  'cortexAsyncMaxWaitMs',
  'cortexModelFast',
  'cortexModelAudit',
  'cortexModelDom',
  'cortexModelReasoningDeep',
  'cortexModelVision',
  'cortexModelSearchFast',
  'cortexModelRerankFast',
  'cortexModelSearchDeep',
  'cortexEnsureReadyTimeoutMs',
  'cortexStartReadyTimeoutMs',
  'cortexFailureThreshold',
  'cortexCircuitOpenMs',
  'cortexEscalateConfidenceLt',
  'cortexMaxDeepFieldsPerProduct',
  'manufacturerDeepResearchEnabled',
  'maxManufacturerUrlsPerProduct',
  'maxManufacturerPagesPerDomain',
  'manufacturerReserveUrls',
  'userAgent',
  'selfImproveEnabled',
  'learningConfidenceThreshold',
  'componentLexiconDecayDays',
  'componentLexiconExpireDays',
  'fieldAnchorsDecayDays',
  'urlMemoryDecayDays',
  'maxHypothesisItems',
  'hypothesisAutoFollowupRounds',
  'hypothesisFollowupUrlsPerRound',
  'disableGoogleCse',
  'cseRescueOnlyMode',
  'cseRescueRequiredIteration',
  'duckduckgoEnabled',
  'endpointSignalLimit',
  'endpointSuggestionLimit',
  'endpointNetworkScanLimit',
  'llmPlanDiscoveryQueries',
  'llmSerpRerankEnabled',
  'llmExtractionCacheEnabled',
  'llmExtractionCacheDir',
  'llmExtractionCacheTtlMs',
  'llmMaxCallsPerProductTotal',
  'llmMaxCallsPerProductFast',
  'llmFallbackEnabled',
  'indexingReextractEnabled',
  'scannedPdfOcrEnabled',
  'scannedPdfOcrPromoteCandidates',
  'dynamicFetchPolicyMapJson',
  'fetchSchedulerInternalsMapJson',
  'retrievalInternalsMapJson',
  'evidencePackLimitsMapJson',
  'identityGateThresholdBoundsMapJson',
  'parsingConfidenceBaseMapJson',
  'searchProfileCapMapJson',
  'serpRerankerWeightMapJson',
  'dynamicFetchPolicyMap',
  'dynamicCrawleeEnabled',
  'crawleeHeadless',
  'fetchSchedulerEnabled',
  'fetchSchedulerMaxRetries',
  'fetchSchedulerFallbackWaitMs',
  'preferHttpFetcher',
  'pageGotoTimeoutMs',
  'pageNetworkIdleTimeoutMs',
  'postLoadWaitMs',
  'frontierDbPath',
  'frontierEnableSqlite',
  'frontierStripTrackingParams',
  'frontierQueryCooldownSeconds',
  'frontierCooldown404Seconds',
  'frontierCooldown404RepeatSeconds',
  'frontierCooldown410Seconds',
  'frontierCooldownTimeoutSeconds',
  'frontierCooldown403BaseSeconds',
  'frontierCooldown429BaseSeconds',
  'frontierBackoffMaxExponent',
  'frontierPathPenaltyNotfoundThreshold',
  'frontierBlockedDomainThreshold',
  'frontierRepairSearchEnabled',
  'repairDedupeRule',
  'automationQueueStorageEngine',
  'autoScrollEnabled',
  'autoScrollPasses',
  'autoScrollDelayMs',
  'graphqlReplayEnabled',
  'maxGraphqlReplays',
  'maxNetworkResponsesPerPage',
  'robotsTxtCompliant',
  'robotsTxtTimeoutMs',
  'runtimeTraceEnabled',
  'runtimeTraceFetchRing',
  'runtimeTraceLlmRing',
  'runtimeTraceLlmPayloads',
  'eventsJsonWrite',
  'queueJsonWrite',
  'billingJsonWrite',
  'brainJsonWrite',
  'intelJsonWrite',
  'corpusJsonWrite',
  'learningJsonWrite',
  'cacheJsonWrite',
  'daemonConcurrency',
  'daemonGracefulShutdownTimeoutMs',
  'importsRoot',
  'importsPollSeconds',
  'authoritySnapshotEnabled',
  'runtimeScreencastEnabled',
  'runtimeScreencastFps',
  'runtimeScreencastQuality',
  'runtimeScreencastMaxWidth',
  'runtimeScreencastMaxHeight',
  'helperFilesEnabled',
  'helperSupportiveEnabled',
  'helperSupportiveFillMissing',
  'helperAutoSeedTargets',
  'driftDetectionEnabled',
  'driftAutoRepublish',
  'aggressiveModeEnabled',
  'aggressiveEvidenceAuditEnabled',
  'uberAggressiveEnabled',
  'cortexEnabled',
  'cortexAsyncEnabled',
  'cortexAutoStart',
  'cortexAutoRestartOnAuth',
  'cortexEscalateIfConflict',
  'cortexEscalateCriticalOnly',
  'allowBelowPassTargetFill',
  'indexingHelperFilesEnabled',
]);

export const CONVERGENCE_SETTINGS_KEYS = Object.freeze([
  'convergenceMaxRounds',
  'convergenceNoProgressLimit',
  'convergenceMaxLowQualityRounds',
  'convergenceLowQualityConfidence',
  'convergenceMaxDispatchQueries',
  'convergenceMaxTargetFields',
  'needsetEvidenceDecayDays',
  'needsetEvidenceDecayFloor',
  'needsetCapIdentityLocked',
  'needsetCapIdentityProvisional',
  'needsetCapIdentityConflict',
  'needsetCapIdentityUnlocked',
  'consensusLlmWeightTier1',
  'consensusLlmWeightTier2',
  'consensusLlmWeightTier3',
  'consensusLlmWeightTier4',
  'consensusTier1Weight',
  'consensusTier2Weight',
  'consensusTier3Weight',
  'consensusTier4Weight',
  'serpTriageMinScore',
  'serpTriageMaxUrls',
  'serpTriageEnabled',
  'retrievalMaxHitsPerField',
  'retrievalMaxPrimeSources',
  'retrievalIdentityFilterEnabled',
  'laneConcurrencySearch',
  'laneConcurrencyFetch',
  'laneConcurrencyParse',
  'laneConcurrencyLlm',
]);

export const UI_SETTINGS_KEYS = Object.freeze([
  'studioAutoSaveAllEnabled',
  'studioAutoSaveEnabled',
  'studioAutoSaveMapEnabled',
  'runtimeAutoSaveEnabled',
  'storageAutoSaveEnabled',
  'llmSettingsAutoSaveEnabled',
]);

export const UI_SETTINGS_DEFAULTS = Object.freeze({
  ...SETTINGS_DEFAULTS.ui,
});

export const CONVERGENCE_SETTINGS_ROUTE_PUT = Object.freeze({
  intKeys: Object.freeze([
    'convergenceMaxRounds',
    'convergenceNoProgressLimit',
    'convergenceMaxLowQualityRounds',
    'convergenceMaxDispatchQueries',
    'convergenceMaxTargetFields',
    'needsetEvidenceDecayDays',
    'serpTriageMinScore',
    'serpTriageMaxUrls',
    'retrievalMaxHitsPerField',
    'retrievalMaxPrimeSources',
    'laneConcurrencySearch',
    'laneConcurrencyFetch',
    'laneConcurrencyParse',
    'laneConcurrencyLlm',
  ]),
  floatKeys: Object.freeze([
    'convergenceLowQualityConfidence',
    'needsetEvidenceDecayFloor',
    'needsetCapIdentityLocked',
    'needsetCapIdentityProvisional',
    'needsetCapIdentityConflict',
    'needsetCapIdentityUnlocked',
    'consensusLlmWeightTier1',
    'consensusLlmWeightTier2',
    'consensusLlmWeightTier3',
    'consensusLlmWeightTier4',
    'consensusTier1Weight',
    'consensusTier2Weight',
    'consensusTier3Weight',
    'consensusTier4Weight',
  ]),
  boolKeys: Object.freeze([
    'serpTriageEnabled',
    'retrievalIdentityFilterEnabled',
  ]),
});

export const RUNTIME_SETTINGS_ROUTE_GET = Object.freeze({
  dynamicFetchPolicyMapJsonKey: 'dynamicFetchPolicyMapJson',
  stringMap: Object.freeze({
    profile: 'runProfile',
    searchProvider: 'searchProvider',
    searxngBaseUrl: 'searxngBaseUrl',
    bingSearchEndpoint: 'bingSearchEndpoint',
    bingSearchKey: 'bingSearchKey',
    googleCseCx: 'googleCseCx',
    googleCseKey: 'googleCseKey',
    llmPlanApiKey: 'llmPlanApiKey',
    duckduckgoBaseUrl: 'duckduckgoBaseUrl',
    phase2LlmModel: 'llmModelPlan',
    phase3LlmModel: 'llmModelTriage',
    llmModelFast: 'llmModelFast',
    llmModelReasoning: 'llmModelReasoning',
    llmModelExtract: 'llmModelExtract',
    llmModelValidate: 'llmModelValidate',
    llmModelWrite: 'llmModelWrite',
    llmFallbackPlanModel: 'llmPlanFallbackModel',
    llmFallbackExtractModel: 'llmExtractFallbackModel',
    llmFallbackValidateModel: 'llmValidateFallbackModel',
    llmFallbackWriteModel: 'llmWriteFallbackModel',
    resumeMode: 'indexingResumeMode',
    importsRoot: 'importsRoot',
    outputMode: 'outputMode',
    localInputRoot: 'localInputRoot',
    localOutputRoot: 'localOutputRoot',
    runtimeEventsKey: 'runtimeEventsKey',
    awsRegion: 'awsRegion',
    s3Bucket: 's3Bucket',
    s3InputPrefix: 's3InputPrefix',
    s3OutputPrefix: 's3OutputPrefix',
    eloSupabaseAnonKey: 'eloSupabaseAnonKey',
    eloSupabaseEndpoint: 'eloSupabaseEndpoint',
    llmProvider: 'llmProvider',
    llmBaseUrl: 'llmBaseUrl',
    openaiApiKey: 'openaiApiKey',
    anthropicApiKey: 'anthropicApiKey',
    llmPlanProvider: 'llmPlanProvider',
    llmPlanBaseUrl: 'llmPlanBaseUrl',
    scannedPdfOcrBackend: 'scannedPdfOcrBackend',
    pdfPreferredBackend: 'pdfPreferredBackend',
    capturePageScreenshotFormat: 'capturePageScreenshotFormat',
    capturePageScreenshotSelectors: 'capturePageScreenshotSelectors',
    runtimeScreenshotMode: 'runtimeScreenshotMode',
    visualAssetReviewFormat: 'visualAssetReviewFormat',
    visualAssetHeroSelectorMapJson: 'visualAssetHeroSelectorMapJson',
    runtimeControlFile: 'runtimeControlFile',
    staticDomMode: 'staticDomMode',
    helperFilesRoot: 'helperFilesRoot',
    batchStrategy: 'batchStrategy',
    specDbDir: 'specDbDir',
    articleExtractorDomainPolicyMapJson: 'articleExtractorDomainPolicyMapJson',
    structuredMetadataExtructUrl: 'structuredMetadataExtructUrl',
    llmExtractionCacheDir: 'llmExtractionCacheDir',
    frontierDbPath: 'frontierDbPath',
    dynamicFetchPolicyMapJson: 'dynamicFetchPolicyMapJson',
    fetchSchedulerInternalsMapJson: 'fetchSchedulerInternalsMapJson',
    retrievalInternalsMapJson: 'retrievalInternalsMapJson',
    evidencePackLimitsMapJson: 'evidencePackLimitsMapJson',
    identityGateThresholdBoundsMapJson: 'identityGateThresholdBoundsMapJson',
    parsingConfidenceBaseMapJson: 'parsingConfidenceBaseMapJson',
    repairDedupeRule: 'repairDedupeRule',
    automationQueueStorageEngine: 'automationQueueStorageEngine',
    searchProfileCapMapJson: 'searchProfileCapMapJson',
    serpRerankerWeightMapJson: 'serpRerankerWeightMapJson',
    userAgent: 'userAgent',
    cortexBaseUrl: 'cortexBaseUrl',
    cortexApiKey: 'cortexApiKey',
    cortexAsyncBaseUrl: 'cortexAsyncBaseUrl',
    cortexAsyncSubmitPath: 'cortexAsyncSubmitPath',
    cortexAsyncStatusPath: 'cortexAsyncStatusPath',
    cortexModelFast: 'cortexModelFast',
    cortexModelAudit: 'cortexModelAudit',
    cortexModelDom: 'cortexModelDom',
    cortexModelReasoningDeep: 'cortexModelReasoningDeep',
    cortexModelVision: 'cortexModelVision',
    cortexModelSearchFast: 'cortexModelSearchFast',
    cortexModelRerankFast: 'cortexModelRerankFast',
    cortexModelSearchDeep: 'cortexModelSearchDeep',
  }),
  intMap: Object.freeze({
    fetchConcurrency: 'concurrency',
    perHostMinDelayMs: 'perHostMinDelayMs',
    discoveryMaxQueries: 'discoveryMaxQueries',
    maxPagesPerDomain: 'maxPagesPerDomain',
    maxUrlsPerProduct: 'maxUrlsPerProduct',
    maxCandidateUrls: 'maxCandidateUrls',
    maxRunSeconds: 'maxRunSeconds',
    maxJsonBytes: 'maxJsonBytes',
    maxPdfBytes: 'maxPdfBytes',
    pdfBackendRouterTimeoutMs: 'pdfBackendRouterTimeoutMs',
    pdfBackendRouterMaxPages: 'pdfBackendRouterMaxPages',
    pdfBackendRouterMaxPairs: 'pdfBackendRouterMaxPairs',
    pdfBackendRouterMaxTextPreviewChars: 'pdfBackendRouterMaxTextPreviewChars',
    capturePageScreenshotQuality: 'capturePageScreenshotQuality',
    capturePageScreenshotMaxBytes: 'capturePageScreenshotMaxBytes',
    visualAssetCaptureMaxPerSource: 'visualAssetCaptureMaxPerSource',
    visualAssetRetentionDays: 'visualAssetRetentionDays',
    visualAssetReviewLgMaxSide: 'visualAssetReviewLgMaxSide',
    visualAssetReviewSmMaxSide: 'visualAssetReviewSmMaxSide',
    visualAssetReviewLgQuality: 'visualAssetReviewLgQuality',
    visualAssetReviewSmQuality: 'visualAssetReviewSmQuality',
    visualAssetRegionCropMaxSide: 'visualAssetRegionCropMaxSide',
    visualAssetRegionCropQuality: 'visualAssetRegionCropQuality',
    visualAssetLlmMaxBytes: 'visualAssetLlmMaxBytes',
    visualAssetMinWidth: 'visualAssetMinWidth',
    visualAssetMinHeight: 'visualAssetMinHeight',
    visualAssetMaxPhashDistance: 'visualAssetMaxPhashDistance',
    articleExtractorMinChars: 'articleExtractorMinChars',
    articleExtractorMinScore: 'articleExtractorMinScore',
    articleExtractorMaxChars: 'articleExtractorMaxChars',
    staticDomMaxEvidenceSnippets: 'staticDomMaxEvidenceSnippets',
    structuredMetadataExtructTimeoutMs: 'structuredMetadataExtructTimeoutMs',
    structuredMetadataExtructMaxItemsPerSurface: 'structuredMetadataExtructMaxItemsPerSurface',
    structuredMetadataExtructCacheLimit: 'structuredMetadataExtructCacheLimit',
    domSnippetMaxChars: 'domSnippetMaxChars',
    llmExtractionCacheTtlMs: 'llmExtractionCacheTtlMs',
    llmMaxCallsPerProductTotal: 'llmMaxCallsPerProductTotal',
    llmMaxCallsPerProductFast: 'llmMaxCallsPerProductFast',
    helperSupportiveMaxSources: 'helperSupportiveMaxSources',
    helperActiveSyncLimit: 'helperActiveSyncLimit',
    fieldRewardHalfLifeDays: 'fieldRewardHalfLifeDays',
    driftPollSeconds: 'driftPollSeconds',
    driftScanMaxProducts: 'driftScanMaxProducts',
    aggressiveMaxSearchQueries: 'aggressiveMaxSearchQueries',
    aggressiveEvidenceAuditBatchSize: 'aggressiveEvidenceAuditBatchSize',
    aggressiveMaxTimePerProductMs: 'aggressiveMaxTimePerProductMs',
    aggressiveThoroughFromRound: 'aggressiveThoroughFromRound',
    aggressiveRound1MaxUrls: 'aggressiveRound1MaxUrls',
    aggressiveRound1MaxCandidateUrls: 'aggressiveRound1MaxCandidateUrls',
    aggressiveLlmMaxCallsPerRound: 'aggressiveLlmMaxCallsPerRound',
    aggressiveLlmMaxCallsPerProductTotal: 'aggressiveLlmMaxCallsPerProductTotal',
    aggressiveLlmTargetMaxFields: 'aggressiveLlmTargetMaxFields',
    aggressiveLlmDiscoveryPasses: 'aggressiveLlmDiscoveryPasses',
    aggressiveLlmDiscoveryQueryCap: 'aggressiveLlmDiscoveryQueryCap',
    uberMaxRounds: 'uberMaxRounds',
    cortexSyncTimeoutMs: 'cortexSyncTimeoutMs',
    cortexAsyncPollIntervalMs: 'cortexAsyncPollIntervalMs',
    cortexAsyncMaxWaitMs: 'cortexAsyncMaxWaitMs',
    cortexEnsureReadyTimeoutMs: 'cortexEnsureReadyTimeoutMs',
    cortexStartReadyTimeoutMs: 'cortexStartReadyTimeoutMs',
    cortexFailureThreshold: 'cortexFailureThreshold',
    cortexCircuitOpenMs: 'cortexCircuitOpenMs',
    cortexMaxDeepFieldsPerProduct: 'cortexMaxDeepFieldsPerProduct',
    maxManufacturerUrlsPerProduct: 'maxManufacturerUrlsPerProduct',
    maxManufacturerPagesPerDomain: 'maxManufacturerPagesPerDomain',
    manufacturerReserveUrls: 'manufacturerReserveUrls',
    uberMaxUrlsPerDomain: 'uberMaxUrlsPerDomain',
    uberMaxUrlsPerProduct: 'uberMaxUrlsPerProduct',
    discoveryResultsPerQuery: 'discoveryResultsPerQuery',
    discoveryMaxDiscovered: 'discoveryMaxDiscovered',
    discoveryQueryConcurrency: 'discoveryQueryConcurrency',
    maxHypothesisItems: 'maxHypothesisItems',
    hypothesisAutoFollowupRounds: 'hypothesisAutoFollowupRounds',
    hypothesisFollowupUrlsPerRound: 'hypothesisFollowupUrlsPerRound',
    componentLexiconDecayDays: 'componentLexiconDecayDays',
    componentLexiconExpireDays: 'componentLexiconExpireDays',
    fieldAnchorsDecayDays: 'fieldAnchorsDecayDays',
    urlMemoryDecayDays: 'urlMemoryDecayDays',
    serpTriageMaxUrls: 'serpTriageMaxUrls',
    llmTokensPlan: 'llmMaxOutputTokensPlan',
    llmTokensTriage: 'llmMaxOutputTokensTriage',
    llmTokensFast: 'llmMaxOutputTokensFast',
    llmTokensReasoning: 'llmMaxOutputTokensReasoning',
    llmTokensExtract: 'llmMaxOutputTokensExtract',
    llmTokensValidate: 'llmMaxOutputTokensValidate',
    llmTokensWrite: 'llmMaxOutputTokensWrite',
    llmTokensPlanFallback: 'llmMaxOutputTokensPlanFallback',
    llmTokensExtractFallback: 'llmMaxOutputTokensExtractFallback',
    llmTokensValidateFallback: 'llmMaxOutputTokensValidateFallback',
    llmTokensWriteFallback: 'llmMaxOutputTokensWriteFallback',
    needsetEvidenceDecayDays: 'needsetEvidenceDecayDays',
    needsetDefaultIdentityAuditLimit: 'needsetDefaultIdentityAuditLimit',
    consensusStrictAcceptanceDomainCount: 'consensusStrictAcceptanceDomainCount',
    consensusRelaxedAcceptanceDomainCount: 'consensusRelaxedAcceptanceDomainCount',
    consensusInstrumentedFieldThreshold: 'consensusInstrumentedFieldThreshold',
    consensusPassTargetIdentityStrong: 'consensusPassTargetIdentityStrong',
    consensusPassTargetNormal: 'consensusPassTargetNormal',
    identityGateNumericRangeThreshold: 'identityGateNumericRangeThreshold',
    evidenceTextMaxChars: 'evidenceTextMaxChars',
    llmExtractMaxTokens: 'llmExtractMaxTokens',
    llmExtractMaxSnippetsPerBatch: 'llmExtractMaxSnippetsPerBatch',
    llmExtractMaxSnippetChars: 'llmExtractMaxSnippetChars',
    llmExtractReasoningBudget: 'llmExtractReasoningBudget',
    llmReasoningBudget: 'llmReasoningBudget',
    llmMaxCallsPerRound: 'llmMaxCallsPerRound',
    llmMaxOutputTokens: 'llmMaxOutputTokens',
    llmVerifySampleRate: 'llmVerifySampleRate',
    llmMaxBatchesPerProduct: 'llmMaxBatchesPerProduct',
    llmMaxEvidenceChars: 'llmMaxEvidenceChars',
    llmMaxTokens: 'llmMaxTokens',
    llmTimeoutMs: 'llmTimeoutMs',
    convergenceIdentityFailFastRounds: 'convergenceIdentityFailFastRounds',
    resumeWindowHours: 'indexingResumeMaxAgeHours',
    indexingResumeSeedLimit: 'indexingResumeSeedLimit',
    indexingResumePersistLimit: 'indexingResumePersistLimit',
    reextractAfterHours: 'indexingReextractAfterHours',
    reCrawlStaleAfterDays: 'reCrawlStaleAfterDays',
    scannedPdfOcrMaxPages: 'scannedPdfOcrMaxPages',
    scannedPdfOcrMaxPairs: 'scannedPdfOcrMaxPairs',
    scannedPdfOcrMinCharsPerPage: 'scannedPdfOcrMinCharsPerPage',
    scannedPdfOcrMinLinesPerPage: 'scannedPdfOcrMinLinesPerPage',
    crawleeRequestHandlerTimeoutSecs: 'crawleeRequestHandlerTimeoutSecs',
    dynamicFetchRetryBudget: 'dynamicFetchRetryBudget',
    dynamicFetchRetryBackoffMs: 'dynamicFetchRetryBackoffMs',
    fetchSchedulerMaxRetries: 'fetchSchedulerMaxRetries',
    fetchSchedulerFallbackWaitMs: 'fetchSchedulerFallbackWaitMs',
    pageGotoTimeoutMs: 'pageGotoTimeoutMs',
    pageNetworkIdleTimeoutMs: 'pageNetworkIdleTimeoutMs',
    postLoadWaitMs: 'postLoadWaitMs',
    frontierQueryCooldownSeconds: 'frontierQueryCooldownSeconds',
    frontierCooldown404Seconds: 'frontierCooldown404Seconds',
    frontierCooldown404RepeatSeconds: 'frontierCooldown404RepeatSeconds',
    frontierCooldown410Seconds: 'frontierCooldown410Seconds',
    frontierCooldownTimeoutSeconds: 'frontierCooldownTimeoutSeconds',
    frontierCooldown403BaseSeconds: 'frontierCooldown403BaseSeconds',
    frontierCooldown429BaseSeconds: 'frontierCooldown429BaseSeconds',
    frontierBackoffMaxExponent: 'frontierBackoffMaxExponent',
    frontierPathPenaltyNotfoundThreshold: 'frontierPathPenaltyNotfoundThreshold',
    frontierBlockedDomainThreshold: 'frontierBlockedDomainThreshold',
    autoScrollPasses: 'autoScrollPasses',
    autoScrollDelayMs: 'autoScrollDelayMs',
    maxGraphqlReplays: 'maxGraphqlReplays',
    maxNetworkResponsesPerPage: 'maxNetworkResponsesPerPage',
    robotsTxtTimeoutMs: 'robotsTxtTimeoutMs',
    endpointSignalLimit: 'endpointSignalLimit',
    endpointSuggestionLimit: 'endpointSuggestionLimit',
    endpointNetworkScanLimit: 'endpointNetworkScanLimit',
    cseRescueRequiredIteration: 'cseRescueRequiredIteration',
    duckduckgoTimeoutMs: 'duckduckgoTimeoutMs',
    runtimeTraceFetchRing: 'runtimeTraceFetchRing',
    runtimeTraceLlmRing: 'runtimeTraceLlmRing',
    daemonConcurrency: 'daemonConcurrency',
    daemonGracefulShutdownTimeoutMs: 'daemonGracefulShutdownTimeoutMs',
    importsPollSeconds: 'importsPollSeconds',
    runtimeScreencastFps: 'runtimeScreencastFps',
    runtimeScreencastQuality: 'runtimeScreencastQuality',
    runtimeScreencastMaxWidth: 'runtimeScreencastMaxWidth',
    runtimeScreencastMaxHeight: 'runtimeScreencastMaxHeight',
  }),
  floatMap: Object.freeze({
    scannedPdfOcrMinConfidence: 'scannedPdfOcrMinConfidence',
    staticDomTargetMatchThreshold: 'staticDomTargetMatchThreshold',
    aggressiveConfidenceThreshold: 'aggressiveConfidenceThreshold',
    cortexEscalateConfidenceLt: 'cortexEscalateConfidenceLt',
    needsetEvidenceDecayFloor: 'needsetEvidenceDecayFloor',
    needsetRequiredWeightIdentity: 'needsetRequiredWeightIdentity',
    needsetRequiredWeightCritical: 'needsetRequiredWeightCritical',
    needsetRequiredWeightRequired: 'needsetRequiredWeightRequired',
    needsetRequiredWeightExpected: 'needsetRequiredWeightExpected',
    needsetRequiredWeightOptional: 'needsetRequiredWeightOptional',
    needsetMissingMultiplier: 'needsetMissingMultiplier',
    needsetTierDeficitMultiplier: 'needsetTierDeficitMultiplier',
    needsetMinRefsDeficitMultiplier: 'needsetMinRefsDeficitMultiplier',
    needsetConflictMultiplier: 'needsetConflictMultiplier',
    needsetIdentityLockThreshold: 'needsetIdentityLockThreshold',
    needsetIdentityProvisionalThreshold: 'needsetIdentityProvisionalThreshold',
    learningConfidenceThreshold: 'learningConfidenceThreshold',
    identityGatePublishThreshold: 'identityGatePublishThreshold',
    identityGateBaseMatchThreshold: 'identityGateBaseMatchThreshold',
    identityGateEasyAmbiguityReduction: 'identityGateEasyAmbiguityReduction',
    identityGateMediumAmbiguityReduction: 'identityGateMediumAmbiguityReduction',
    identityGateHardAmbiguityReduction: 'identityGateHardAmbiguityReduction',
    identityGateVeryHardAmbiguityIncrease: 'identityGateVeryHardAmbiguityIncrease',
    identityGateExtraHardAmbiguityIncrease: 'identityGateExtraHardAmbiguityIncrease',
    identityGateMissingStrongIdPenalty: 'identityGateMissingStrongIdPenalty',
    consensusMethodWeightNetworkJson: 'consensusMethodWeightNetworkJson',
    consensusMethodWeightAdapterApi: 'consensusMethodWeightAdapterApi',
    consensusMethodWeightStructuredMeta: 'consensusMethodWeightStructuredMeta',
    consensusMethodWeightPdf: 'consensusMethodWeightPdf',
    consensusMethodWeightTableKv: 'consensusMethodWeightTableKv',
    consensusMethodWeightDom: 'consensusMethodWeightDom',
    consensusMethodWeightLlmExtractBase: 'consensusMethodWeightLlmExtractBase',
    consensusPolicyBonus: 'consensusPolicyBonus',
    consensusWeightedMajorityThreshold: 'consensusWeightedMajorityThreshold',
    consensusConfidenceScoringBase: 'consensusConfidenceScoringBase',
    retrievalTierWeightTier1: 'retrievalTierWeightTier1',
    retrievalTierWeightTier2: 'retrievalTierWeightTier2',
    retrievalTierWeightTier3: 'retrievalTierWeightTier3',
    retrievalTierWeightTier4: 'retrievalTierWeightTier4',
    retrievalTierWeightTier5: 'retrievalTierWeightTier5',
    retrievalDocKindWeightManualPdf: 'retrievalDocKindWeightManualPdf',
    retrievalDocKindWeightSpecPdf: 'retrievalDocKindWeightSpecPdf',
    retrievalDocKindWeightSupport: 'retrievalDocKindWeightSupport',
    retrievalDocKindWeightLabReview: 'retrievalDocKindWeightLabReview',
    retrievalDocKindWeightProductPage: 'retrievalDocKindWeightProductPage',
    retrievalDocKindWeightOther: 'retrievalDocKindWeightOther',
    retrievalMethodWeightTable: 'retrievalMethodWeightTable',
    retrievalMethodWeightKv: 'retrievalMethodWeightKv',
    retrievalMethodWeightJsonLd: 'retrievalMethodWeightJsonLd',
    retrievalMethodWeightLlmExtract: 'retrievalMethodWeightLlmExtract',
    retrievalMethodWeightHelperSupportive: 'retrievalMethodWeightHelperSupportive',
    retrievalAnchorScorePerMatch: 'retrievalAnchorScorePerMatch',
    retrievalIdentityScorePerMatch: 'retrievalIdentityScorePerMatch',
    retrievalUnitMatchBonus: 'retrievalUnitMatchBonus',
    retrievalDirectFieldMatchBonus: 'retrievalDirectFieldMatchBonus',
    identityGateHardMissingStrongIdIncrease: 'identityGateHardMissingStrongIdIncrease',
    identityGateVeryHardMissingStrongIdIncrease: 'identityGateVeryHardMissingStrongIdIncrease',
    identityGateExtraHardMissingStrongIdIncrease: 'identityGateExtraHardMissingStrongIdIncrease',
    identityGateNumericTokenBoost: 'identityGateNumericTokenBoost',
    qualityGateIdentityThreshold: 'qualityGateIdentityThreshold',
    llmMonthlyBudgetUsd: 'llmMonthlyBudgetUsd',
    llmPerProductBudgetUsd: 'llmPerProductBudgetUsd',
    llmCostInputPer1M: 'llmCostInputPer1M',
    llmCostOutputPer1M: 'llmCostOutputPer1M',
    llmCostCachedInputPer1M: 'llmCostCachedInputPer1M',
    visualAssetMinSharpness: 'visualAssetMinSharpness',
    visualAssetMinEntropy: 'visualAssetMinEntropy',
  }),
  boolMap: Object.freeze({
    discoveryEnabled: 'discoveryEnabled',
    fetchCandidateSources: 'fetchCandidateSources',
    manufacturerBroadDiscovery: 'manufacturerBroadDiscovery',
    manufacturerSeedSearchUrls: 'manufacturerSeedSearchUrls',
    manufacturerDeepResearchEnabled: 'manufacturerDeepResearchEnabled',
    pdfBackendRouterEnabled: 'pdfBackendRouterEnabled',
    capturePageScreenshotEnabled: 'capturePageScreenshotEnabled',
    runtimeCaptureScreenshots: 'runtimeCaptureScreenshots',
    visualAssetCaptureEnabled: 'visualAssetCaptureEnabled',
    visualAssetStoreOriginal: 'visualAssetStoreOriginal',
    visualAssetPhashEnabled: 'visualAssetPhashEnabled',
    chartExtractionEnabled: 'chartExtractionEnabled',
    articleExtractorV2Enabled: 'articleExtractorV2Enabled',
    staticDomExtractorEnabled: 'staticDomExtractorEnabled',
    htmlTableExtractorV2: 'htmlTableExtractorV2',
    structuredMetadataExtructEnabled: 'structuredMetadataExtructEnabled',
    structuredMetadataExtructCacheEnabled: 'structuredMetadataExtructCacheEnabled',
    helperFilesEnabled: 'helperFilesEnabled',
    helperSupportiveEnabled: 'helperSupportiveEnabled',
    helperSupportiveFillMissing: 'helperSupportiveFillMissing',
    helperAutoSeedTargets: 'helperAutoSeedTargets',
    driftDetectionEnabled: 'driftDetectionEnabled',
    driftAutoRepublish: 'driftAutoRepublish',
    aggressiveModeEnabled: 'aggressiveModeEnabled',
    aggressiveEvidenceAuditEnabled: 'aggressiveEvidenceAuditEnabled',
    uberAggressiveEnabled: 'uberAggressiveEnabled',
    cortexEnabled: 'cortexEnabled',
    cortexAsyncEnabled: 'cortexAsyncEnabled',
    cortexAutoStart: 'cortexAutoStart',
    cortexAutoRestartOnAuth: 'cortexAutoRestartOnAuth',
    cortexEscalateIfConflict: 'cortexEscalateIfConflict',
    cortexEscalateCriticalOnly: 'cortexEscalateCriticalOnly',
    allowBelowPassTargetFill: 'allowBelowPassTargetFill',
    indexingHelperFilesEnabled: 'indexingHelperFilesEnabled',
    selfImproveEnabled: 'selfImproveEnabled',
    disableGoogleCse: 'disableGoogleCse',
    cseRescueOnlyMode: 'cseRescueOnlyMode',
    duckduckgoEnabled: 'duckduckgoEnabled',
    phase2LlmEnabled: 'llmPlanDiscoveryQueries',
    phase3LlmTriageEnabled: 'llmSerpRerankEnabled',
    llmExtractionCacheEnabled: 'llmExtractionCacheEnabled',
    llmFallbackEnabled: 'llmFallbackEnabled',
    reextractIndexed: 'indexingReextractEnabled',
    scannedPdfOcrEnabled: 'scannedPdfOcrEnabled',
    scannedPdfOcrPromoteCandidates: 'scannedPdfOcrPromoteCandidates',
    dynamicCrawleeEnabled: 'dynamicCrawleeEnabled',
    crawleeHeadless: 'crawleeHeadless',
    llmExtractSkipLowSignal: 'llmExtractSkipLowSignal',
    llmReasoningMode: 'llmReasoningMode',
    llmDisableBudgetGuards: 'llmDisableBudgetGuards',
    llmVerifyMode: 'llmVerifyMode',
    localMode: 'localMode',
    dryRun: 'dryRun',
    mirrorToS3: 'mirrorToS3',
    mirrorToS3Input: 'mirrorToS3Input',
    writeMarkdownSummary: 'writeMarkdownSummary',
    llmEnabled: 'llmEnabled',
    llmWriteSummary: 'llmWriteSummary',
    fetchSchedulerEnabled: 'fetchSchedulerEnabled',
    preferHttpFetcher: 'preferHttpFetcher',
    frontierEnableSqlite: 'frontierEnableSqlite',
    frontierStripTrackingParams: 'frontierStripTrackingParams',
    frontierRepairSearchEnabled: 'frontierRepairSearchEnabled',
    autoScrollEnabled: 'autoScrollEnabled',
    graphqlReplayEnabled: 'graphqlReplayEnabled',
    robotsTxtCompliant: 'robotsTxtCompliant',
    runtimeTraceEnabled: 'runtimeTraceEnabled',
    runtimeTraceLlmPayloads: 'runtimeTraceLlmPayloads',
    eventsJsonWrite: 'eventsJsonWrite',
    indexingSchemaPacketsValidationEnabled: 'indexingSchemaPacketsValidationEnabled',
    indexingSchemaPacketsValidationStrict: 'indexingSchemaPacketsValidationStrict',
    queueJsonWrite: 'queueJsonWrite',
    billingJsonWrite: 'billingJsonWrite',
    brainJsonWrite: 'brainJsonWrite',
    intelJsonWrite: 'intelJsonWrite',
    corpusJsonWrite: 'corpusJsonWrite',
    learningJsonWrite: 'learningJsonWrite',
    cacheJsonWrite: 'cacheJsonWrite',
    authoritySnapshotEnabled: 'authoritySnapshotEnabled',
    runtimeScreencastEnabled: 'runtimeScreencastEnabled',
  }),
});

export const RUNTIME_SETTINGS_ROUTE_PUT = Object.freeze({
  dynamicFetchPolicyMapJsonKey: 'dynamicFetchPolicyMapJson',
  stringEnumMap: Object.freeze({
    profile: Object.freeze({ cfgKey: 'runProfile', allowed: SETTINGS_OPTION_VALUES.runtime.profile }),
    resumeMode: Object.freeze({ cfgKey: 'indexingResumeMode', allowed: SETTINGS_OPTION_VALUES.runtime.resumeMode }),
    scannedPdfOcrBackend: Object.freeze({ cfgKey: 'scannedPdfOcrBackend', allowed: SETTINGS_OPTION_VALUES.runtime.scannedPdfOcrBackend }),
    searchProvider: Object.freeze({ cfgKey: 'searchProvider', allowed: SETTINGS_OPTION_VALUES.runtime.searchProvider }),
    repairDedupeRule: Object.freeze({ cfgKey: 'repairDedupeRule', allowed: SETTINGS_OPTION_VALUES.runtime.repairDedupeRule }),
    automationQueueStorageEngine: Object.freeze({ cfgKey: 'automationQueueStorageEngine', allowed: SETTINGS_OPTION_VALUES.runtime.automationQueueStorageEngine }),
    outputMode: Object.freeze({ cfgKey: 'outputMode', allowed: SETTINGS_OPTION_VALUES.runtime.outputMode }),
  }),
  stringFreeMap: Object.freeze({
    searxngBaseUrl: 'searxngBaseUrl',
    bingSearchEndpoint: 'bingSearchEndpoint',
    bingSearchKey: 'bingSearchKey',
    googleCseCx: 'googleCseCx',
    googleCseKey: 'googleCseKey',
    llmPlanApiKey: 'llmPlanApiKey',
    duckduckgoBaseUrl: 'duckduckgoBaseUrl',
    llmPlanProvider: 'llmPlanProvider',
    llmPlanBaseUrl: 'llmPlanBaseUrl',
    pdfPreferredBackend: 'pdfPreferredBackend',
    capturePageScreenshotFormat: 'capturePageScreenshotFormat',
    capturePageScreenshotSelectors: 'capturePageScreenshotSelectors',
    runtimeScreenshotMode: 'runtimeScreenshotMode',
    visualAssetReviewFormat: 'visualAssetReviewFormat',
    visualAssetHeroSelectorMapJson: 'visualAssetHeroSelectorMapJson',
    runtimeControlFile: 'runtimeControlFile',
    staticDomMode: 'staticDomMode',
    helperFilesRoot: 'helperFilesRoot',
    batchStrategy: 'batchStrategy',
    specDbDir: 'specDbDir',
    articleExtractorDomainPolicyMapJson: 'articleExtractorDomainPolicyMapJson',
    structuredMetadataExtructUrl: 'structuredMetadataExtructUrl',
    llmExtractionCacheDir: 'llmExtractionCacheDir',
    userAgent: 'userAgent',
    frontierDbPath: 'frontierDbPath',
    searchProfileCapMapJson: 'searchProfileCapMapJson',
    serpRerankerWeightMapJson: 'serpRerankerWeightMapJson',
    fetchSchedulerInternalsMapJson: 'fetchSchedulerInternalsMapJson',
    retrievalInternalsMapJson: 'retrievalInternalsMapJson',
    evidencePackLimitsMapJson: 'evidencePackLimitsMapJson',
    identityGateThresholdBoundsMapJson: 'identityGateThresholdBoundsMapJson',
    parsingConfidenceBaseMapJson: 'parsingConfidenceBaseMapJson',
    phase2LlmModel: 'llmModelPlan',
    phase3LlmModel: 'llmModelTriage',
    llmModelFast: 'llmModelFast',
    llmModelReasoning: 'llmModelReasoning',
    llmModelExtract: 'llmModelExtract',
    llmModelValidate: 'llmModelValidate',
    llmModelWrite: 'llmModelWrite',
    llmFallbackPlanModel: 'llmPlanFallbackModel',
    llmFallbackExtractModel: 'llmExtractFallbackModel',
    llmFallbackValidateModel: 'llmValidateFallbackModel',
    llmFallbackWriteModel: 'llmWriteFallbackModel',
    importsRoot: 'importsRoot',
    localInputRoot: 'localInputRoot',
    localOutputRoot: 'localOutputRoot',
    runtimeEventsKey: 'runtimeEventsKey',
    awsRegion: 'awsRegion',
    s3Bucket: 's3Bucket',
    s3InputPrefix: 's3InputPrefix',
    s3OutputPrefix: 's3OutputPrefix',
    eloSupabaseAnonKey: 'eloSupabaseAnonKey',
    eloSupabaseEndpoint: 'eloSupabaseEndpoint',
    llmProvider: 'llmProvider',
    llmBaseUrl: 'llmBaseUrl',
    openaiApiKey: 'openaiApiKey',
    anthropicApiKey: 'anthropicApiKey',
    cortexBaseUrl: 'cortexBaseUrl',
    cortexApiKey: 'cortexApiKey',
    cortexAsyncBaseUrl: 'cortexAsyncBaseUrl',
    cortexAsyncSubmitPath: 'cortexAsyncSubmitPath',
    cortexAsyncStatusPath: 'cortexAsyncStatusPath',
    cortexModelFast: 'cortexModelFast',
    cortexModelAudit: 'cortexModelAudit',
    cortexModelDom: 'cortexModelDom',
    cortexModelReasoningDeep: 'cortexModelReasoningDeep',
    cortexModelVision: 'cortexModelVision',
    cortexModelSearchFast: 'cortexModelSearchFast',
    cortexModelRerankFast: 'cortexModelRerankFast',
    cortexModelSearchDeep: 'cortexModelSearchDeep',
  }),
  stringTrimMap: Object.freeze({
    fetchSchedulerInternalsMapJson: 'fetchSchedulerInternalsMapJson',
    retrievalInternalsMapJson: 'retrievalInternalsMapJson',
    evidencePackLimitsMapJson: 'evidencePackLimitsMapJson',
    identityGateThresholdBoundsMapJson: 'identityGateThresholdBoundsMapJson',
    parsingConfidenceBaseMapJson: 'parsingConfidenceBaseMapJson',
  }),
  intRangeMap: Object.freeze({
    fetchConcurrency: Object.freeze({ cfgKey: 'concurrency', min: 1, max: 64 }),
    perHostMinDelayMs: Object.freeze({ cfgKey: 'perHostMinDelayMs', min: 0, max: 120000 }),
    discoveryMaxQueries: Object.freeze({ cfgKey: 'discoveryMaxQueries', min: 1, max: 100 }),
    discoveryResultsPerQuery: Object.freeze({ cfgKey: 'discoveryResultsPerQuery', min: 1, max: 100 }),
    discoveryMaxDiscovered: Object.freeze({ cfgKey: 'discoveryMaxDiscovered', min: 1, max: 2000 }),
    discoveryQueryConcurrency: Object.freeze({ cfgKey: 'discoveryQueryConcurrency', min: 1, max: 64 }),
    maxUrlsPerProduct: Object.freeze({ cfgKey: 'maxUrlsPerProduct', min: 1, max: 1000 }),
    maxCandidateUrls: Object.freeze({ cfgKey: 'maxCandidateUrls', min: 1, max: 5000 }),
    maxPagesPerDomain: Object.freeze({ cfgKey: 'maxPagesPerDomain', min: 1, max: 100 }),
    uberMaxUrlsPerProduct: Object.freeze({ cfgKey: 'uberMaxUrlsPerProduct', min: 1, max: 2000 }),
    uberMaxUrlsPerDomain: Object.freeze({ cfgKey: 'uberMaxUrlsPerDomain', min: 1, max: 100 }),
    maxRunSeconds: Object.freeze({ cfgKey: 'maxRunSeconds', min: 30, max: 86400 }),
    maxJsonBytes: Object.freeze({ cfgKey: 'maxJsonBytes', min: 1024, max: 100000000 }),
    maxPdfBytes: Object.freeze({ cfgKey: 'maxPdfBytes', min: 1024, max: 100000000 }),
    pdfBackendRouterTimeoutMs: Object.freeze({ cfgKey: 'pdfBackendRouterTimeoutMs', min: 1000, max: 600000 }),
    pdfBackendRouterMaxPages: Object.freeze({ cfgKey: 'pdfBackendRouterMaxPages', min: 1, max: 1000 }),
    pdfBackendRouterMaxPairs: Object.freeze({ cfgKey: 'pdfBackendRouterMaxPairs', min: 1, max: 100000 }),
    pdfBackendRouterMaxTextPreviewChars: Object.freeze({ cfgKey: 'pdfBackendRouterMaxTextPreviewChars', min: 256, max: 200000 }),
    capturePageScreenshotQuality: Object.freeze({ cfgKey: 'capturePageScreenshotQuality', min: 1, max: 100 }),
    capturePageScreenshotMaxBytes: Object.freeze({ cfgKey: 'capturePageScreenshotMaxBytes', min: 1024, max: 100000000 }),
    visualAssetCaptureMaxPerSource: Object.freeze({ cfgKey: 'visualAssetCaptureMaxPerSource', min: 1, max: 100 }),
    visualAssetRetentionDays: Object.freeze({ cfgKey: 'visualAssetRetentionDays', min: 1, max: 3650 }),
    visualAssetReviewLgMaxSide: Object.freeze({ cfgKey: 'visualAssetReviewLgMaxSide', min: 128, max: 4096 }),
    visualAssetReviewSmMaxSide: Object.freeze({ cfgKey: 'visualAssetReviewSmMaxSide', min: 128, max: 4096 }),
    visualAssetReviewLgQuality: Object.freeze({ cfgKey: 'visualAssetReviewLgQuality', min: 1, max: 100 }),
    visualAssetReviewSmQuality: Object.freeze({ cfgKey: 'visualAssetReviewSmQuality', min: 1, max: 100 }),
    visualAssetRegionCropMaxSide: Object.freeze({ cfgKey: 'visualAssetRegionCropMaxSide', min: 128, max: 4096 }),
    visualAssetRegionCropQuality: Object.freeze({ cfgKey: 'visualAssetRegionCropQuality', min: 1, max: 100 }),
    visualAssetLlmMaxBytes: Object.freeze({ cfgKey: 'visualAssetLlmMaxBytes', min: 1024, max: 100000000 }),
    visualAssetMinWidth: Object.freeze({ cfgKey: 'visualAssetMinWidth', min: 1, max: 10000 }),
    visualAssetMinHeight: Object.freeze({ cfgKey: 'visualAssetMinHeight', min: 1, max: 10000 }),
    visualAssetMaxPhashDistance: Object.freeze({ cfgKey: 'visualAssetMaxPhashDistance', min: 0, max: 128 }),
    articleExtractorMinChars: Object.freeze({ cfgKey: 'articleExtractorMinChars', min: 50, max: 200000 }),
    articleExtractorMinScore: Object.freeze({ cfgKey: 'articleExtractorMinScore', min: 1, max: 100 }),
    articleExtractorMaxChars: Object.freeze({ cfgKey: 'articleExtractorMaxChars', min: 256, max: 500000 }),
    staticDomMaxEvidenceSnippets: Object.freeze({ cfgKey: 'staticDomMaxEvidenceSnippets', min: 10, max: 500 }),
    structuredMetadataExtructTimeoutMs: Object.freeze({ cfgKey: 'structuredMetadataExtructTimeoutMs', min: 250, max: 15000 }),
    structuredMetadataExtructMaxItemsPerSurface: Object.freeze({ cfgKey: 'structuredMetadataExtructMaxItemsPerSurface', min: 1, max: 1000 }),
    structuredMetadataExtructCacheLimit: Object.freeze({ cfgKey: 'structuredMetadataExtructCacheLimit', min: 32, max: 5000 }),
    domSnippetMaxChars: Object.freeze({ cfgKey: 'domSnippetMaxChars', min: 600, max: 20000 }),
    llmExtractionCacheTtlMs: Object.freeze({ cfgKey: 'llmExtractionCacheTtlMs', min: 60000, max: 31536000000 }),
    llmMaxCallsPerProductTotal: Object.freeze({ cfgKey: 'llmMaxCallsPerProductTotal', min: 1, max: 100 }),
    llmMaxCallsPerProductFast: Object.freeze({ cfgKey: 'llmMaxCallsPerProductFast', min: 0, max: 100 }),
    helperSupportiveMaxSources: Object.freeze({ cfgKey: 'helperSupportiveMaxSources', min: 0, max: 100 }),
    helperActiveSyncLimit: Object.freeze({ cfgKey: 'helperActiveSyncLimit', min: 0, max: 5000 }),
    fieldRewardHalfLifeDays: Object.freeze({ cfgKey: 'fieldRewardHalfLifeDays', min: 1, max: 365 }),
    driftPollSeconds: Object.freeze({ cfgKey: 'driftPollSeconds', min: 60, max: 604800 }),
    driftScanMaxProducts: Object.freeze({ cfgKey: 'driftScanMaxProducts', min: 1, max: 10000 }),
    aggressiveMaxSearchQueries: Object.freeze({ cfgKey: 'aggressiveMaxSearchQueries', min: 1, max: 100 }),
    aggressiveEvidenceAuditBatchSize: Object.freeze({ cfgKey: 'aggressiveEvidenceAuditBatchSize', min: 1, max: 500 }),
    aggressiveMaxTimePerProductMs: Object.freeze({ cfgKey: 'aggressiveMaxTimePerProductMs', min: 1000, max: 3600000 }),
    aggressiveThoroughFromRound: Object.freeze({ cfgKey: 'aggressiveThoroughFromRound', min: 1, max: 12 }),
    aggressiveRound1MaxUrls: Object.freeze({ cfgKey: 'aggressiveRound1MaxUrls', min: 1, max: 2000 }),
    aggressiveRound1MaxCandidateUrls: Object.freeze({ cfgKey: 'aggressiveRound1MaxCandidateUrls', min: 1, max: 5000 }),
    aggressiveLlmMaxCallsPerRound: Object.freeze({ cfgKey: 'aggressiveLlmMaxCallsPerRound', min: 1, max: 200 }),
    aggressiveLlmMaxCallsPerProductTotal: Object.freeze({ cfgKey: 'aggressiveLlmMaxCallsPerProductTotal', min: 1, max: 500 }),
    aggressiveLlmTargetMaxFields: Object.freeze({ cfgKey: 'aggressiveLlmTargetMaxFields', min: 1, max: 500 }),
    aggressiveLlmDiscoveryPasses: Object.freeze({ cfgKey: 'aggressiveLlmDiscoveryPasses', min: 1, max: 12 }),
    aggressiveLlmDiscoveryQueryCap: Object.freeze({ cfgKey: 'aggressiveLlmDiscoveryQueryCap', min: 1, max: 200 }),
    uberMaxRounds: Object.freeze({ cfgKey: 'uberMaxRounds', min: 1, max: 12 }),
    cortexSyncTimeoutMs: Object.freeze({ cfgKey: 'cortexSyncTimeoutMs', min: 1000, max: 600000 }),
    cortexAsyncPollIntervalMs: Object.freeze({ cfgKey: 'cortexAsyncPollIntervalMs', min: 250, max: 120000 }),
    cortexAsyncMaxWaitMs: Object.freeze({ cfgKey: 'cortexAsyncMaxWaitMs', min: 1000, max: 3600000 }),
    cortexEnsureReadyTimeoutMs: Object.freeze({ cfgKey: 'cortexEnsureReadyTimeoutMs', min: 1000, max: 300000 }),
    cortexStartReadyTimeoutMs: Object.freeze({ cfgKey: 'cortexStartReadyTimeoutMs', min: 1000, max: 300000 }),
    cortexFailureThreshold: Object.freeze({ cfgKey: 'cortexFailureThreshold', min: 1, max: 20 }),
    cortexCircuitOpenMs: Object.freeze({ cfgKey: 'cortexCircuitOpenMs', min: 1000, max: 600000 }),
    cortexMaxDeepFieldsPerProduct: Object.freeze({ cfgKey: 'cortexMaxDeepFieldsPerProduct', min: 1, max: 200 }),
    maxManufacturerUrlsPerProduct: Object.freeze({ cfgKey: 'maxManufacturerUrlsPerProduct', min: 1, max: 1000 }),
    maxManufacturerPagesPerDomain: Object.freeze({ cfgKey: 'maxManufacturerPagesPerDomain', min: 1, max: 200 }),
    manufacturerReserveUrls: Object.freeze({ cfgKey: 'manufacturerReserveUrls', min: 0, max: 1000 }),
    maxHypothesisItems: Object.freeze({ cfgKey: 'maxHypothesisItems', min: 1, max: 1000 }),
    hypothesisAutoFollowupRounds: Object.freeze({ cfgKey: 'hypothesisAutoFollowupRounds', min: 0, max: 10 }),
    hypothesisFollowupUrlsPerRound: Object.freeze({ cfgKey: 'hypothesisFollowupUrlsPerRound', min: 1, max: 200 }),
    componentLexiconDecayDays: Object.freeze({ cfgKey: 'componentLexiconDecayDays', min: 1, max: 3650 }),
    componentLexiconExpireDays: Object.freeze({ cfgKey: 'componentLexiconExpireDays', min: 1, max: 3650 }),
    fieldAnchorsDecayDays: Object.freeze({ cfgKey: 'fieldAnchorsDecayDays', min: 1, max: 3650 }),
    urlMemoryDecayDays: Object.freeze({ cfgKey: 'urlMemoryDecayDays', min: 1, max: 3650 }),
    llmTokensPlan: Object.freeze({ cfgKey: 'llmMaxOutputTokensPlan', min: 128, max: 262144 }),
    llmTokensTriage: Object.freeze({ cfgKey: 'llmMaxOutputTokensTriage', min: 128, max: 262144 }),
    llmTokensFast: Object.freeze({ cfgKey: 'llmMaxOutputTokensFast', min: 128, max: 262144 }),
    llmTokensReasoning: Object.freeze({ cfgKey: 'llmMaxOutputTokensReasoning', min: 128, max: 262144 }),
    llmTokensExtract: Object.freeze({ cfgKey: 'llmMaxOutputTokensExtract', min: 128, max: 262144 }),
    llmTokensValidate: Object.freeze({ cfgKey: 'llmMaxOutputTokensValidate', min: 128, max: 262144 }),
    llmTokensWrite: Object.freeze({ cfgKey: 'llmMaxOutputTokensWrite', min: 128, max: 262144 }),
    llmTokensPlanFallback: Object.freeze({ cfgKey: 'llmMaxOutputTokensPlanFallback', min: 128, max: 262144 }),
    llmTokensExtractFallback: Object.freeze({ cfgKey: 'llmMaxOutputTokensExtractFallback', min: 128, max: 262144 }),
    llmTokensValidateFallback: Object.freeze({ cfgKey: 'llmMaxOutputTokensValidateFallback', min: 128, max: 262144 }),
    llmTokensWriteFallback: Object.freeze({ cfgKey: 'llmMaxOutputTokensWriteFallback', min: 128, max: 262144 }),
    needsetEvidenceDecayDays: Object.freeze({ cfgKey: 'needsetEvidenceDecayDays', min: 1, max: 90 }),
    needsetDefaultIdentityAuditLimit: Object.freeze({ cfgKey: 'needsetDefaultIdentityAuditLimit', min: 1, max: 200 }),
    consensusStrictAcceptanceDomainCount: Object.freeze({ cfgKey: 'consensusStrictAcceptanceDomainCount', min: 1, max: 50 }),
    consensusRelaxedAcceptanceDomainCount: Object.freeze({ cfgKey: 'consensusRelaxedAcceptanceDomainCount', min: 1, max: 50 }),
    consensusInstrumentedFieldThreshold: Object.freeze({ cfgKey: 'consensusInstrumentedFieldThreshold', min: 1, max: 50 }),
    consensusPassTargetIdentityStrong: Object.freeze({ cfgKey: 'consensusPassTargetIdentityStrong', min: 1, max: 50 }),
    consensusPassTargetNormal: Object.freeze({ cfgKey: 'consensusPassTargetNormal', min: 1, max: 50 }),
    identityGateNumericRangeThreshold: Object.freeze({ cfgKey: 'identityGateNumericRangeThreshold', min: 0, max: 500 }),
    evidenceTextMaxChars: Object.freeze({ cfgKey: 'evidenceTextMaxChars', min: 200, max: 200000 }),
    llmExtractMaxTokens: Object.freeze({ cfgKey: 'llmExtractMaxTokens', min: 128, max: 262144 }),
    llmExtractMaxSnippetsPerBatch: Object.freeze({ cfgKey: 'llmExtractMaxSnippetsPerBatch', min: 1, max: 50 }),
    llmExtractMaxSnippetChars: Object.freeze({ cfgKey: 'llmExtractMaxSnippetChars', min: 100, max: 200000 }),
    llmExtractReasoningBudget: Object.freeze({ cfgKey: 'llmExtractReasoningBudget', min: 128, max: 262144 }),
    llmReasoningBudget: Object.freeze({ cfgKey: 'llmReasoningBudget', min: 128, max: 262144 }),
    llmMaxCallsPerRound: Object.freeze({ cfgKey: 'llmMaxCallsPerRound', min: 1, max: 200 }),
    llmMaxOutputTokens: Object.freeze({ cfgKey: 'llmMaxOutputTokens', min: 128, max: 262144 }),
    llmVerifySampleRate: Object.freeze({ cfgKey: 'llmVerifySampleRate', min: 1, max: 1000 }),
    llmMaxBatchesPerProduct: Object.freeze({ cfgKey: 'llmMaxBatchesPerProduct', min: 1, max: 100 }),
    llmMaxEvidenceChars: Object.freeze({ cfgKey: 'llmMaxEvidenceChars', min: 1000, max: 500000 }),
    llmMaxTokens: Object.freeze({ cfgKey: 'llmMaxTokens', min: 128, max: 262144 }),
    llmTimeoutMs: Object.freeze({ cfgKey: 'llmTimeoutMs', min: 1000, max: 600000 }),
    convergenceIdentityFailFastRounds: Object.freeze({ cfgKey: 'convergenceIdentityFailFastRounds', min: 1, max: 12 }),
    resumeWindowHours: Object.freeze({ cfgKey: 'indexingResumeMaxAgeHours', min: 1, max: 8760 }),
    indexingResumeSeedLimit: Object.freeze({ cfgKey: 'indexingResumeSeedLimit', min: 1, max: 10000 }),
    indexingResumePersistLimit: Object.freeze({ cfgKey: 'indexingResumePersistLimit', min: 1, max: 100000 }),
    reextractAfterHours: Object.freeze({ cfgKey: 'indexingReextractAfterHours', min: 1, max: 8760 }),
    reCrawlStaleAfterDays: Object.freeze({ cfgKey: 'reCrawlStaleAfterDays', min: 1, max: 3650 }),
    scannedPdfOcrMaxPages: Object.freeze({ cfgKey: 'scannedPdfOcrMaxPages', min: 1, max: 100 }),
    scannedPdfOcrMaxPairs: Object.freeze({ cfgKey: 'scannedPdfOcrMaxPairs', min: 50, max: 20000 }),
    scannedPdfOcrMinCharsPerPage: Object.freeze({ cfgKey: 'scannedPdfOcrMinCharsPerPage', min: 1, max: 500 }),
    scannedPdfOcrMinLinesPerPage: Object.freeze({ cfgKey: 'scannedPdfOcrMinLinesPerPage', min: 1, max: 100 }),
    crawleeRequestHandlerTimeoutSecs: Object.freeze({ cfgKey: 'crawleeRequestHandlerTimeoutSecs', min: 0, max: 300 }),
    dynamicFetchRetryBudget: Object.freeze({ cfgKey: 'dynamicFetchRetryBudget', min: 0, max: 5 }),
    dynamicFetchRetryBackoffMs: Object.freeze({ cfgKey: 'dynamicFetchRetryBackoffMs', min: 0, max: 30000 }),
    fetchSchedulerMaxRetries: Object.freeze({ cfgKey: 'fetchSchedulerMaxRetries', min: 0, max: 20 }),
    fetchSchedulerFallbackWaitMs: Object.freeze({ cfgKey: 'fetchSchedulerFallbackWaitMs', min: 0, max: 600000 }),
    pageGotoTimeoutMs: Object.freeze({ cfgKey: 'pageGotoTimeoutMs', min: 0, max: 120000 }),
    pageNetworkIdleTimeoutMs: Object.freeze({ cfgKey: 'pageNetworkIdleTimeoutMs', min: 0, max: 60000 }),
    postLoadWaitMs: Object.freeze({ cfgKey: 'postLoadWaitMs', min: 0, max: 60000 }),
    frontierQueryCooldownSeconds: Object.freeze({ cfgKey: 'frontierQueryCooldownSeconds', min: 0, max: 31536000 }),
    frontierCooldown404Seconds: Object.freeze({ cfgKey: 'frontierCooldown404Seconds', min: 0, max: 31536000 }),
    frontierCooldown404RepeatSeconds: Object.freeze({ cfgKey: 'frontierCooldown404RepeatSeconds', min: 0, max: 31536000 }),
    frontierCooldown410Seconds: Object.freeze({ cfgKey: 'frontierCooldown410Seconds', min: 0, max: 31536000 }),
    frontierCooldownTimeoutSeconds: Object.freeze({ cfgKey: 'frontierCooldownTimeoutSeconds', min: 0, max: 31536000 }),
    frontierCooldown403BaseSeconds: Object.freeze({ cfgKey: 'frontierCooldown403BaseSeconds', min: 0, max: 86400 }),
    frontierCooldown429BaseSeconds: Object.freeze({ cfgKey: 'frontierCooldown429BaseSeconds', min: 0, max: 86400 }),
    frontierBackoffMaxExponent: Object.freeze({ cfgKey: 'frontierBackoffMaxExponent', min: 1, max: 12 }),
    frontierPathPenaltyNotfoundThreshold: Object.freeze({ cfgKey: 'frontierPathPenaltyNotfoundThreshold', min: 1, max: 50 }),
    frontierBlockedDomainThreshold: Object.freeze({ cfgKey: 'frontierBlockedDomainThreshold', min: 1, max: 50 }),
    autoScrollPasses: Object.freeze({ cfgKey: 'autoScrollPasses', min: 0, max: 20 }),
    autoScrollDelayMs: Object.freeze({ cfgKey: 'autoScrollDelayMs', min: 0, max: 10000 }),
    maxGraphqlReplays: Object.freeze({ cfgKey: 'maxGraphqlReplays', min: 0, max: 20 }),
    maxNetworkResponsesPerPage: Object.freeze({ cfgKey: 'maxNetworkResponsesPerPage', min: 100, max: 10000 }),
    robotsTxtTimeoutMs: Object.freeze({ cfgKey: 'robotsTxtTimeoutMs', min: 100, max: 120000 }),
    endpointSignalLimit: Object.freeze({ cfgKey: 'endpointSignalLimit', min: 1, max: 500 }),
    endpointSuggestionLimit: Object.freeze({ cfgKey: 'endpointSuggestionLimit', min: 1, max: 200 }),
    endpointNetworkScanLimit: Object.freeze({ cfgKey: 'endpointNetworkScanLimit', min: 50, max: 10000 }),
    cseRescueRequiredIteration: Object.freeze({ cfgKey: 'cseRescueRequiredIteration', min: 1, max: 12 }),
    duckduckgoTimeoutMs: Object.freeze({ cfgKey: 'duckduckgoTimeoutMs', min: 250, max: 120000 }),
    runtimeTraceFetchRing: Object.freeze({ cfgKey: 'runtimeTraceFetchRing', min: 10, max: 2000 }),
    runtimeTraceLlmRing: Object.freeze({ cfgKey: 'runtimeTraceLlmRing', min: 10, max: 2000 }),
    daemonConcurrency: Object.freeze({ cfgKey: 'daemonConcurrency', min: 1, max: 128 }),
    daemonGracefulShutdownTimeoutMs: Object.freeze({ cfgKey: 'daemonGracefulShutdownTimeoutMs', min: 1000, max: 600000 }),
    importsPollSeconds: Object.freeze({ cfgKey: 'importsPollSeconds', min: 1, max: 3600 }),
    runtimeScreencastFps: Object.freeze({ cfgKey: 'runtimeScreencastFps', min: 1, max: 60 }),
    runtimeScreencastQuality: Object.freeze({ cfgKey: 'runtimeScreencastQuality', min: 10, max: 100 }),
    runtimeScreencastMaxWidth: Object.freeze({ cfgKey: 'runtimeScreencastMaxWidth', min: 320, max: 3840 }),
    runtimeScreencastMaxHeight: Object.freeze({ cfgKey: 'runtimeScreencastMaxHeight', min: 240, max: 2160 }),
  }),
  floatRangeMap: Object.freeze({
    scannedPdfOcrMinConfidence: Object.freeze({ cfgKey: 'scannedPdfOcrMinConfidence', min: 0, max: 1 }),
    staticDomTargetMatchThreshold: Object.freeze({ cfgKey: 'staticDomTargetMatchThreshold', min: 0, max: 1 }),
    aggressiveConfidenceThreshold: Object.freeze({ cfgKey: 'aggressiveConfidenceThreshold', min: 0, max: 1 }),
    cortexEscalateConfidenceLt: Object.freeze({ cfgKey: 'cortexEscalateConfidenceLt', min: 0, max: 1 }),
    needsetEvidenceDecayFloor: Object.freeze({ cfgKey: 'needsetEvidenceDecayFloor', min: 0, max: 0.9 }),
    needsetRequiredWeightIdentity: Object.freeze({ cfgKey: 'needsetRequiredWeightIdentity', min: 0.1, max: 100 }),
    needsetRequiredWeightCritical: Object.freeze({ cfgKey: 'needsetRequiredWeightCritical', min: 0.1, max: 100 }),
    needsetRequiredWeightRequired: Object.freeze({ cfgKey: 'needsetRequiredWeightRequired', min: 0.1, max: 100 }),
    needsetRequiredWeightExpected: Object.freeze({ cfgKey: 'needsetRequiredWeightExpected', min: 0.1, max: 100 }),
    needsetRequiredWeightOptional: Object.freeze({ cfgKey: 'needsetRequiredWeightOptional', min: 0.1, max: 100 }),
    needsetMissingMultiplier: Object.freeze({ cfgKey: 'needsetMissingMultiplier', min: 0.1, max: 100 }),
    needsetTierDeficitMultiplier: Object.freeze({ cfgKey: 'needsetTierDeficitMultiplier', min: 0.1, max: 100 }),
    needsetMinRefsDeficitMultiplier: Object.freeze({ cfgKey: 'needsetMinRefsDeficitMultiplier', min: 0.1, max: 100 }),
    needsetConflictMultiplier: Object.freeze({ cfgKey: 'needsetConflictMultiplier', min: 0.1, max: 100 }),
    needsetIdentityLockThreshold: Object.freeze({ cfgKey: 'needsetIdentityLockThreshold', min: 0, max: 1 }),
    needsetIdentityProvisionalThreshold: Object.freeze({ cfgKey: 'needsetIdentityProvisionalThreshold', min: 0, max: 1 }),
    learningConfidenceThreshold: Object.freeze({ cfgKey: 'learningConfidenceThreshold', min: 0, max: 1 }),
    identityGatePublishThreshold: Object.freeze({ cfgKey: 'identityGatePublishThreshold', min: 0, max: 1 }),
    identityGateBaseMatchThreshold: Object.freeze({ cfgKey: 'identityGateBaseMatchThreshold', min: 0, max: 1 }),
    identityGateEasyAmbiguityReduction: Object.freeze({ cfgKey: 'identityGateEasyAmbiguityReduction', min: -1, max: 1 }),
    identityGateMediumAmbiguityReduction: Object.freeze({ cfgKey: 'identityGateMediumAmbiguityReduction', min: -1, max: 1 }),
    identityGateHardAmbiguityReduction: Object.freeze({ cfgKey: 'identityGateHardAmbiguityReduction', min: -1, max: 1 }),
    identityGateVeryHardAmbiguityIncrease: Object.freeze({ cfgKey: 'identityGateVeryHardAmbiguityIncrease', min: -1, max: 1 }),
    identityGateExtraHardAmbiguityIncrease: Object.freeze({ cfgKey: 'identityGateExtraHardAmbiguityIncrease', min: -1, max: 1 }),
    identityGateMissingStrongIdPenalty: Object.freeze({ cfgKey: 'identityGateMissingStrongIdPenalty', min: -1, max: 1 }),
    consensusMethodWeightNetworkJson: Object.freeze({ cfgKey: 'consensusMethodWeightNetworkJson', min: 0, max: 2 }),
    consensusMethodWeightAdapterApi: Object.freeze({ cfgKey: 'consensusMethodWeightAdapterApi', min: 0, max: 2 }),
    consensusMethodWeightStructuredMeta: Object.freeze({ cfgKey: 'consensusMethodWeightStructuredMeta', min: 0, max: 2 }),
    consensusMethodWeightPdf: Object.freeze({ cfgKey: 'consensusMethodWeightPdf', min: 0, max: 2 }),
    consensusMethodWeightTableKv: Object.freeze({ cfgKey: 'consensusMethodWeightTableKv', min: 0, max: 2 }),
    consensusMethodWeightDom: Object.freeze({ cfgKey: 'consensusMethodWeightDom', min: 0, max: 2 }),
    consensusMethodWeightLlmExtractBase: Object.freeze({ cfgKey: 'consensusMethodWeightLlmExtractBase', min: 0, max: 2 }),
    consensusPolicyBonus: Object.freeze({ cfgKey: 'consensusPolicyBonus', min: -5, max: 5 }),
    consensusWeightedMajorityThreshold: Object.freeze({ cfgKey: 'consensusWeightedMajorityThreshold', min: 1, max: 10 }),
    consensusConfidenceScoringBase: Object.freeze({ cfgKey: 'consensusConfidenceScoringBase', min: 0, max: 1 }),
    retrievalTierWeightTier1: Object.freeze({ cfgKey: 'retrievalTierWeightTier1', min: 0, max: 10 }),
    retrievalTierWeightTier2: Object.freeze({ cfgKey: 'retrievalTierWeightTier2', min: 0, max: 10 }),
    retrievalTierWeightTier3: Object.freeze({ cfgKey: 'retrievalTierWeightTier3', min: 0, max: 10 }),
    retrievalTierWeightTier4: Object.freeze({ cfgKey: 'retrievalTierWeightTier4', min: 0, max: 10 }),
    retrievalTierWeightTier5: Object.freeze({ cfgKey: 'retrievalTierWeightTier5', min: 0, max: 10 }),
    retrievalDocKindWeightManualPdf: Object.freeze({ cfgKey: 'retrievalDocKindWeightManualPdf', min: 0, max: 10 }),
    retrievalDocKindWeightSpecPdf: Object.freeze({ cfgKey: 'retrievalDocKindWeightSpecPdf', min: 0, max: 10 }),
    retrievalDocKindWeightSupport: Object.freeze({ cfgKey: 'retrievalDocKindWeightSupport', min: 0, max: 10 }),
    retrievalDocKindWeightLabReview: Object.freeze({ cfgKey: 'retrievalDocKindWeightLabReview', min: 0, max: 10 }),
    retrievalDocKindWeightProductPage: Object.freeze({ cfgKey: 'retrievalDocKindWeightProductPage', min: 0, max: 10 }),
    retrievalDocKindWeightOther: Object.freeze({ cfgKey: 'retrievalDocKindWeightOther', min: 0, max: 10 }),
    retrievalMethodWeightTable: Object.freeze({ cfgKey: 'retrievalMethodWeightTable', min: 0, max: 10 }),
    retrievalMethodWeightKv: Object.freeze({ cfgKey: 'retrievalMethodWeightKv', min: 0, max: 10 }),
    retrievalMethodWeightJsonLd: Object.freeze({ cfgKey: 'retrievalMethodWeightJsonLd', min: 0, max: 10 }),
    retrievalMethodWeightLlmExtract: Object.freeze({ cfgKey: 'retrievalMethodWeightLlmExtract', min: 0, max: 10 }),
    retrievalMethodWeightHelperSupportive: Object.freeze({ cfgKey: 'retrievalMethodWeightHelperSupportive', min: 0, max: 10 }),
    retrievalAnchorScorePerMatch: Object.freeze({ cfgKey: 'retrievalAnchorScorePerMatch', min: 0, max: 2 }),
    retrievalIdentityScorePerMatch: Object.freeze({ cfgKey: 'retrievalIdentityScorePerMatch', min: 0, max: 2 }),
    retrievalUnitMatchBonus: Object.freeze({ cfgKey: 'retrievalUnitMatchBonus', min: 0, max: 2 }),
    retrievalDirectFieldMatchBonus: Object.freeze({ cfgKey: 'retrievalDirectFieldMatchBonus', min: 0, max: 2 }),
    identityGateHardMissingStrongIdIncrease: Object.freeze({ cfgKey: 'identityGateHardMissingStrongIdIncrease', min: -1, max: 1 }),
    identityGateVeryHardMissingStrongIdIncrease: Object.freeze({ cfgKey: 'identityGateVeryHardMissingStrongIdIncrease', min: -1, max: 1 }),
    identityGateExtraHardMissingStrongIdIncrease: Object.freeze({ cfgKey: 'identityGateExtraHardMissingStrongIdIncrease', min: -1, max: 1 }),
    identityGateNumericTokenBoost: Object.freeze({ cfgKey: 'identityGateNumericTokenBoost', min: -1, max: 1 }),
    qualityGateIdentityThreshold: Object.freeze({ cfgKey: 'qualityGateIdentityThreshold', min: 0, max: 1 }),
    llmMonthlyBudgetUsd: Object.freeze({ cfgKey: 'llmMonthlyBudgetUsd', min: 0, max: 100000 }),
    llmPerProductBudgetUsd: Object.freeze({ cfgKey: 'llmPerProductBudgetUsd', min: 0, max: 1000 }),
    llmCostInputPer1M: Object.freeze({ cfgKey: 'llmCostInputPer1M', min: 0, max: 1000 }),
    llmCostOutputPer1M: Object.freeze({ cfgKey: 'llmCostOutputPer1M', min: 0, max: 1000 }),
    llmCostCachedInputPer1M: Object.freeze({ cfgKey: 'llmCostCachedInputPer1M', min: 0, max: 1000 }),
    visualAssetMinSharpness: Object.freeze({ cfgKey: 'visualAssetMinSharpness', min: 0, max: 1000 }),
    visualAssetMinEntropy: Object.freeze({ cfgKey: 'visualAssetMinEntropy', min: 0, max: 100 }),
  }),
  boolMap: Object.freeze({
    discoveryEnabled: 'discoveryEnabled',
    fetchCandidateSources: 'fetchCandidateSources',
    manufacturerBroadDiscovery: 'manufacturerBroadDiscovery',
    manufacturerSeedSearchUrls: 'manufacturerSeedSearchUrls',
    manufacturerDeepResearchEnabled: 'manufacturerDeepResearchEnabled',
    pdfBackendRouterEnabled: 'pdfBackendRouterEnabled',
    capturePageScreenshotEnabled: 'capturePageScreenshotEnabled',
    runtimeCaptureScreenshots: 'runtimeCaptureScreenshots',
    visualAssetCaptureEnabled: 'visualAssetCaptureEnabled',
    visualAssetStoreOriginal: 'visualAssetStoreOriginal',
    visualAssetPhashEnabled: 'visualAssetPhashEnabled',
    chartExtractionEnabled: 'chartExtractionEnabled',
    articleExtractorV2Enabled: 'articleExtractorV2Enabled',
    staticDomExtractorEnabled: 'staticDomExtractorEnabled',
    htmlTableExtractorV2: 'htmlTableExtractorV2',
    structuredMetadataExtructEnabled: 'structuredMetadataExtructEnabled',
    structuredMetadataExtructCacheEnabled: 'structuredMetadataExtructCacheEnabled',
    helperFilesEnabled: 'helperFilesEnabled',
    helperSupportiveEnabled: 'helperSupportiveEnabled',
    helperSupportiveFillMissing: 'helperSupportiveFillMissing',
    helperAutoSeedTargets: 'helperAutoSeedTargets',
    driftDetectionEnabled: 'driftDetectionEnabled',
    driftAutoRepublish: 'driftAutoRepublish',
    aggressiveModeEnabled: 'aggressiveModeEnabled',
    aggressiveEvidenceAuditEnabled: 'aggressiveEvidenceAuditEnabled',
    uberAggressiveEnabled: 'uberAggressiveEnabled',
    cortexEnabled: 'cortexEnabled',
    cortexAsyncEnabled: 'cortexAsyncEnabled',
    cortexAutoStart: 'cortexAutoStart',
    cortexAutoRestartOnAuth: 'cortexAutoRestartOnAuth',
    cortexEscalateIfConflict: 'cortexEscalateIfConflict',
    cortexEscalateCriticalOnly: 'cortexEscalateCriticalOnly',
    allowBelowPassTargetFill: 'allowBelowPassTargetFill',
    indexingHelperFilesEnabled: 'indexingHelperFilesEnabled',
    selfImproveEnabled: 'selfImproveEnabled',
    disableGoogleCse: 'disableGoogleCse',
    cseRescueOnlyMode: 'cseRescueOnlyMode',
    duckduckgoEnabled: 'duckduckgoEnabled',
    phase2LlmEnabled: 'llmPlanDiscoveryQueries',
    phase3LlmTriageEnabled: 'llmSerpRerankEnabled',
    llmExtractionCacheEnabled: 'llmExtractionCacheEnabled',
    llmFallbackEnabled: 'llmFallbackEnabled',
    reextractIndexed: 'indexingReextractEnabled',
    scannedPdfOcrEnabled: 'scannedPdfOcrEnabled',
    scannedPdfOcrPromoteCandidates: 'scannedPdfOcrPromoteCandidates',
    dynamicCrawleeEnabled: 'dynamicCrawleeEnabled',
    crawleeHeadless: 'crawleeHeadless',
    llmExtractSkipLowSignal: 'llmExtractSkipLowSignal',
    llmReasoningMode: 'llmReasoningMode',
    llmDisableBudgetGuards: 'llmDisableBudgetGuards',
    llmVerifyMode: 'llmVerifyMode',
    localMode: 'localMode',
    dryRun: 'dryRun',
    mirrorToS3: 'mirrorToS3',
    mirrorToS3Input: 'mirrorToS3Input',
    writeMarkdownSummary: 'writeMarkdownSummary',
    llmEnabled: 'llmEnabled',
    llmWriteSummary: 'llmWriteSummary',
    fetchSchedulerEnabled: 'fetchSchedulerEnabled',
    preferHttpFetcher: 'preferHttpFetcher',
    frontierEnableSqlite: 'frontierEnableSqlite',
    frontierStripTrackingParams: 'frontierStripTrackingParams',
    frontierRepairSearchEnabled: 'frontierRepairSearchEnabled',
    autoScrollEnabled: 'autoScrollEnabled',
    graphqlReplayEnabled: 'graphqlReplayEnabled',
    robotsTxtCompliant: 'robotsTxtCompliant',
    runtimeTraceEnabled: 'runtimeTraceEnabled',
    runtimeTraceLlmPayloads: 'runtimeTraceLlmPayloads',
    eventsJsonWrite: 'eventsJsonWrite',
    indexingSchemaPacketsValidationEnabled: 'indexingSchemaPacketsValidationEnabled',
    indexingSchemaPacketsValidationStrict: 'indexingSchemaPacketsValidationStrict',
    queueJsonWrite: 'queueJsonWrite',
    billingJsonWrite: 'billingJsonWrite',
    brainJsonWrite: 'brainJsonWrite',
    intelJsonWrite: 'intelJsonWrite',
    corpusJsonWrite: 'corpusJsonWrite',
    learningJsonWrite: 'learningJsonWrite',
    cacheJsonWrite: 'cacheJsonWrite',
    authoritySnapshotEnabled: 'authoritySnapshotEnabled',
    runtimeScreencastEnabled: 'runtimeScreencastEnabled',
  }),
});

const runtimeValueTypeMap = {};
for (const value of Object.values(RUNTIME_SETTINGS_ROUTE_PUT.stringEnumMap)) {
  runtimeValueTypeMap[value.cfgKey] = 'string';
}
for (const value of Object.values(RUNTIME_SETTINGS_ROUTE_PUT.stringFreeMap)) {
  runtimeValueTypeMap[value] = 'string';
}
for (const value of Object.values(RUNTIME_SETTINGS_ROUTE_PUT.intRangeMap)) {
  runtimeValueTypeMap[value.cfgKey] = 'integer';
}
for (const value of Object.values(RUNTIME_SETTINGS_ROUTE_PUT.floatRangeMap)) {
  runtimeValueTypeMap[value.cfgKey] = 'number';
}
for (const value of Object.values(RUNTIME_SETTINGS_ROUTE_PUT.boolMap)) {
  runtimeValueTypeMap[value] = 'boolean';
}
runtimeValueTypeMap.dynamicFetchPolicyMapJson = 'string';
runtimeValueTypeMap.dynamicFetchPolicyMap = 'object';

export const RUNTIME_SETTINGS_VALUE_TYPES = Object.freeze(runtimeValueTypeMap);

const convergenceValueTypeMap = {};
for (const key of CONVERGENCE_SETTINGS_ROUTE_PUT.intKeys) {
  convergenceValueTypeMap[key] = 'integer';
}
for (const key of CONVERGENCE_SETTINGS_ROUTE_PUT.floatKeys) {
  convergenceValueTypeMap[key] = 'number';
}
for (const key of CONVERGENCE_SETTINGS_ROUTE_PUT.boolKeys) {
  convergenceValueTypeMap[key] = 'boolean';
}

export const CONVERGENCE_SETTINGS_VALUE_TYPES = Object.freeze(convergenceValueTypeMap);

export const UI_SETTINGS_VALUE_TYPES = Object.freeze({
  studioAutoSaveAllEnabled: 'boolean',
  studioAutoSaveEnabled: 'boolean',
  studioAutoSaveMapEnabled: 'boolean',
  runtimeAutoSaveEnabled: 'boolean',
  storageAutoSaveEnabled: 'boolean',
  llmSettingsAutoSaveEnabled: 'boolean',
});

export const STORAGE_SETTINGS_VALUE_TYPES = Object.freeze({
  enabled: 'boolean',
  destinationType: 'string',
  localDirectory: 'string',
  s3Region: 'string',
  s3Bucket: 'string',
  s3Prefix: 'string',
  s3AccessKeyId: 'string',
  s3SecretAccessKey: 'string',
  s3SessionToken: 'string',
  updatedAt: 'string_or_null',
});

export const SETTINGS_AUTHORITY_PRECEDENCE = Object.freeze({
  runtime: Object.freeze(['user']),
  convergence: Object.freeze(['user']),
  storage: Object.freeze(['user']),
  studio: Object.freeze(['user']),
  ui: Object.freeze(['user']),
});

export function readUserSettingsDocumentMeta(rawPayload) {
  const source = asRecord(rawPayload);
  const hasPayload = Object.keys(source).length > 0;
  const schemaVersion = normalizeSchemaVersion(source.schemaVersion);
  return {
    hasPayload,
    schemaVersion,
    targetSchemaVersion: SETTINGS_DOCUMENT_SCHEMA_VERSION,
    stale: hasPayload && schemaVersion < SETTINGS_DOCUMENT_SCHEMA_VERSION,
  };
}

export function migrateUserSettingsDocument(rawPayload) {
  const source = asRecord(rawPayload);
  const currentVersion = normalizeSchemaVersion(source.schemaVersion);
  const migratedFrom = currentVersion;
  const runtime = {
    ...pickKnownKeys(source.runtime, RUNTIME_SETTINGS_KEYS),
    ...pickKnownKeys(source, RUNTIME_SETTINGS_KEYS),
  };
  const convergence = {
    ...pickKnownKeys(source.convergence, CONVERGENCE_SETTINGS_KEYS),
    ...pickKnownKeys(source, CONVERGENCE_SETTINGS_KEYS),
  };
  const ui = {
    ...pickKnownKeys(source.ui, UI_SETTINGS_KEYS),
    ...pickKnownKeys(source, UI_SETTINGS_KEYS),
  };
  return {
    schemaVersion: SETTINGS_DOCUMENT_SCHEMA_VERSION,
    migratedFrom,
    runtime,
    convergence,
    storage: asRecord(source.storage),
    studio: asRecord(source.studio),
    ui,
  };
}

function schemaForSettingType(typeToken) {
  if (typeToken === 'integer') return { type: 'integer' };
  if (typeToken === 'number') return { type: 'number' };
  if (typeToken === 'boolean') return { type: 'boolean' };
  if (typeToken === 'string') return { type: 'string' };
  if (typeToken === 'string_or_null') return { anyOf: [{ type: 'string' }, { type: 'null' }] };
  if (typeToken === 'object') return { type: 'object', additionalProperties: true };
  return {};
}

function sectionSchemaFromTypeMap(typeMap) {
  const properties = {};
  for (const [key, typeToken] of Object.entries(typeMap || {})) {
    properties[key] = schemaForSettingType(typeToken);
  }
  return {
    type: 'object',
    properties,
    additionalProperties: false,
  };
}

const USER_SETTINGS_SNAPSHOT_SCHEMA = {
  type: 'object',
  properties: {
    schemaVersion: { type: 'integer', const: SETTINGS_DOCUMENT_SCHEMA_VERSION },
    runtime: sectionSchemaFromTypeMap(RUNTIME_SETTINGS_VALUE_TYPES),
    convergence: sectionSchemaFromTypeMap(CONVERGENCE_SETTINGS_VALUE_TYPES),
    storage: sectionSchemaFromTypeMap(STORAGE_SETTINGS_VALUE_TYPES),
    studio: {
      type: 'object',
      additionalProperties: {
        type: 'object',
        properties: {
          map: {
            type: 'object',
            additionalProperties: true,
          },
          file_path: { type: 'string' },
          version_snapshot: {},
          map_hash: {},
          map_path: {},
          updated_at: {},
        },
        required: ['map'],
        additionalProperties: false,
      },
    },
    ui: sectionSchemaFromTypeMap(UI_SETTINGS_VALUE_TYPES),
  },
  required: ['schemaVersion', 'runtime', 'convergence', 'storage', 'studio', 'ui'],
  additionalProperties: false,
};

const settingsSchemaAjv = new Ajv2020({
  allErrors: true,
  strict: false,
  allowUnionTypes: true,
});

const validateUserSettingsSnapshotSchema = settingsSchemaAjv.compile(USER_SETTINGS_SNAPSHOT_SCHEMA);

function normalizeSchemaErrors(errors) {
  if (!Array.isArray(errors)) return [];
  return errors.map((entry) => ({
    instancePath: String(entry.instancePath || ''),
    keyword: String(entry.keyword || ''),
    message: String(entry.message || 'validation_error'),
  }));
}

export function validateUserSettingsSnapshot(payload) {
  const valid = Boolean(validateUserSettingsSnapshotSchema(payload));
  return {
    valid,
    errors: valid ? [] : normalizeSchemaErrors(validateUserSettingsSnapshotSchema.errors),
  };
}
