export const runtimeGroup = Object.freeze({
  id: "runtime",
  title: "Runtime Pipeline and Fetching",
  notes: "Execution behavior, parsing, OCR, browser automation, and screenshot controls.",
  entries: Object.freeze([
    { key: "CAPTURE_PAGE_SCREENSHOT_ENABLED", defaultValue: "true", type: "boolean", secret: false, userMutable: false, description: "System-level setting. User/domain-generated values must not be stored here." },
    { key: "CAPTURE_PAGE_SCREENSHOT_FORMAT", defaultValue: "jpeg", type: "string", secret: false, userMutable: false, description: "System-level setting. User/domain-generated values must not be stored here." },
    { key: "CAPTURE_PAGE_SCREENSHOT_MAX_BYTES", defaultValue: "5000000", type: "integer", secret: false, userMutable: false, description: "System-level setting. User/domain-generated values must not be stored here." },
    { key: "CAPTURE_PAGE_SCREENSHOT_QUALITY", defaultValue: "50", type: "integer", secret: false, userMutable: false, description: "System-level setting. User/domain-generated values must not be stored here." },
    { key: "CAPTURE_PAGE_SCREENSHOT_SELECTORS", defaultValue: "table,[data-spec-table],.specs-table,.spec-table,.specifications", type: "string", secret: false, userMutable: false, description: "System-level setting. User/domain-generated values must not be stored here." },
    { key: "CRAWLEE_HEADLESS", defaultValue: "true", type: "boolean", secret: false, userMutable: false, description: "System-level setting. User/domain-generated values must not be stored here." },
    { key: "CRAWLEE_REQUEST_HANDLER_TIMEOUT_SECS", defaultValue: "75", type: "integer", secret: false, userMutable: false, description: "System-level setting. User/domain-generated values must not be stored here." },
    { key: "FETCH_SCHEDULER_DEFAULT_CONCURRENCY", defaultValue: "3", type: "integer", secret: false, userMutable: false, description: "System-level setting. User/domain-generated values must not be stored here." },
    { key: "FETCH_SCHEDULER_DEFAULT_DELAY_MS", defaultValue: "300", type: "integer", secret: false, userMutable: false, description: "System-level setting. User/domain-generated values must not be stored here." },
    { key: "FETCH_SCHEDULER_DEFAULT_MAX_RETRIES", defaultValue: "1", type: "integer", secret: false, userMutable: false, description: "System-level setting. User/domain-generated values must not be stored here." },
    { key: "FETCH_SCHEDULER_RETRY_WAIT_MS", defaultValue: "15000", type: "integer", secret: false, userMutable: false, description: "System-level setting. User/domain-generated values must not be stored here." },
    { key: "INDEXING_REEXTRACT_AFTER_HOURS", defaultValue: "24", type: "integer", secret: false, userMutable: false, description: "System-level setting. User/domain-generated values must not be stored here." },
    { key: "INDEXING_REEXTRACT_ENABLED", defaultValue: "true", type: "boolean", secret: false, userMutable: false, description: "System-level setting. User/domain-generated values must not be stored here." },
    { key: "INDEXING_REEXTRACT_SEED_LIMIT", defaultValue: "8", type: "integer", secret: false, userMutable: false, description: "System-level setting. User/domain-generated values must not be stored here." },
    { key: "INDEXING_RESUME_MAX_AGE_HOURS", defaultValue: "48", type: "integer", secret: false, userMutable: false, description: "System-level setting. User/domain-generated values must not be stored here." },
    { key: "INDEXING_RESUME_MODE", defaultValue: "auto", type: "string", secret: false, userMutable: false, description: "System-level setting. User/domain-generated values must not be stored here." },
    { key: "INDEXING_RESUME_PERSIST_LIMIT", defaultValue: "160", type: "integer", secret: false, userMutable: false, description: "System-level setting. User/domain-generated values must not be stored here." },
    { key: "INDEXING_RESUME_RETRY_PERSIST_LIMIT", defaultValue: "80", type: "integer", secret: false, userMutable: false, description: "System-level setting. User/domain-generated values must not be stored here." },
    { key: "INDEXING_RESUME_SEED_LIMIT", defaultValue: "24", type: "integer", secret: false, userMutable: false, description: "System-level setting. User/domain-generated values must not be stored here." },
    { key: "INDEXING_RESUME_SUCCESS_PERSIST_LIMIT", defaultValue: "240", type: "integer", secret: false, userMutable: false, description: "System-level setting. User/domain-generated values must not be stored here." },
    { key: "INDEXING_SCHEMA_PACKETS_SCHEMA_ROOT", defaultValue: "", type: "string", secret: false, userMutable: false, description: "System-level setting. User/domain-generated values must not be stored here." },
    { key: "RUNTIME_AUTOSAVE_ENABLED", defaultValue: "true", type: "boolean", secret: false, userMutable: false, description: "System-level setting. User/domain-generated values must not be stored here." },
    { key: "RUNTIME_CONTROL_FILE", defaultValue: "_runtime/control/runtime_overrides.json", type: "string", secret: false, userMutable: false, description: "System-level setting. User/domain-generated values must not be stored here." },
    { key: "RUNTIME_EVENTS_KEY", defaultValue: "_runtime/events.jsonl", type: "string", secret: true, userMutable: false, description: "System-level setting. User/domain-generated values must not be stored here." },
    { key: "RUNTIME_OPS_WORKBENCH_ENABLED", defaultValue: "true", type: "boolean", secret: false, userMutable: false, description: "System-level setting. User/domain-generated values must not be stored here." },
    { key: "RUNTIME_SCREENCAST_ENABLED", defaultValue: "true", type: "boolean", secret: false, userMutable: false, description: "System-level setting. User/domain-generated values must not be stored here." },
    { key: "RUNTIME_SCREENCAST_FPS", defaultValue: "2", type: "integer", secret: false, userMutable: false, description: "System-level setting. User/domain-generated values must not be stored here." },
    { key: "RUNTIME_SCREENCAST_MAX_HEIGHT", defaultValue: "720", type: "integer", secret: false, userMutable: false, description: "System-level setting. User/domain-generated values must not be stored here." },
    { key: "RUNTIME_SCREENCAST_MAX_WIDTH", defaultValue: "1280", type: "integer", secret: false, userMutable: false, description: "System-level setting. User/domain-generated values must not be stored here." },
    { key: "RUNTIME_SCREENCAST_QUALITY", defaultValue: "50", type: "integer", secret: false, userMutable: false, description: "System-level setting. User/domain-generated values must not be stored here." },
    { key: "RUNTIME_TRACE_ENABLED", defaultValue: "true", type: "boolean", secret: false, userMutable: false, description: "System-level setting. User/domain-generated values must not be stored here." },
    { key: "RUNTIME_TRACE_FETCH_RING", defaultValue: "30", type: "integer", secret: false, userMutable: false, description: "System-level setting. User/domain-generated values must not be stored here." },
    { key: "RUNTIME_TRACE_LLM_PAYLOADS", defaultValue: "true", type: "boolean", secret: false, userMutable: false, description: "System-level setting. User/domain-generated values must not be stored here." },
    { key: "RUNTIME_TRACE_LLM_RING", defaultValue: "50", type: "integer", secret: false, userMutable: false, description: "System-level setting. User/domain-generated values must not be stored here." },
    { key: "VISUAL_ASSET_CAPTURE_ENABLED", defaultValue: "true", type: "boolean", secret: false, userMutable: false, description: "System-level setting. User/domain-generated values must not be stored here." },
    { key: "VISUAL_ASSET_CAPTURE_MAX_PER_SOURCE", defaultValue: "5", type: "integer", secret: false, userMutable: false, description: "System-level setting. User/domain-generated values must not be stored here." },
    { key: "VISUAL_ASSET_HERO_SELECTOR_MAP_JSON", defaultValue: "", type: "string", secret: false, userMutable: false, description: "System-level setting. User/domain-generated values must not be stored here." },
    { key: "VISUAL_ASSET_LLM_MAX_BYTES", defaultValue: "512000", type: "integer", secret: false, userMutable: false, description: "System-level setting. User/domain-generated values must not be stored here." },
    { key: "VISUAL_ASSET_MAX_PHASH_DISTANCE", defaultValue: "10", type: "integer", secret: false, userMutable: false, description: "System-level setting. User/domain-generated values must not be stored here." },
    { key: "VISUAL_ASSET_MIN_ENTROPY", defaultValue: "2.5", type: "number", secret: false, userMutable: false, description: "System-level setting. User/domain-generated values must not be stored here." },
    { key: "VISUAL_ASSET_MIN_HEIGHT", defaultValue: "320", type: "integer", secret: false, userMutable: false, description: "System-level setting. User/domain-generated values must not be stored here." },
    { key: "VISUAL_ASSET_MIN_SHARPNESS", defaultValue: "80", type: "integer", secret: false, userMutable: false, description: "System-level setting. User/domain-generated values must not be stored here." },
    { key: "VISUAL_ASSET_MIN_WIDTH", defaultValue: "320", type: "integer", secret: false, userMutable: false, description: "System-level setting. User/domain-generated values must not be stored here." },
    { key: "VISUAL_ASSET_PHASH_ENABLED", defaultValue: "true", type: "boolean", secret: false, userMutable: false, description: "System-level setting. User/domain-generated values must not be stored here." },
    { key: "VISUAL_ASSET_REGION_CROP_MAX_SIDE", defaultValue: "1024", type: "integer", secret: false, userMutable: false, description: "System-level setting. User/domain-generated values must not be stored here." },
    { key: "VISUAL_ASSET_REGION_CROP_QUALITY", defaultValue: "70", type: "integer", secret: false, userMutable: false, description: "System-level setting. User/domain-generated values must not be stored here." },
    { key: "VISUAL_ASSET_RETENTION_DAYS", defaultValue: "30", type: "integer", secret: false, userMutable: false, description: "System-level setting. User/domain-generated values must not be stored here." },
    { key: "VISUAL_ASSET_REVIEW_FORMAT", defaultValue: "webp", type: "string", secret: false, userMutable: false, description: "System-level setting. User/domain-generated values must not be stored here." },
    { key: "VISUAL_ASSET_REVIEW_LG_MAX_SIDE", defaultValue: "1600", type: "integer", secret: false, userMutable: false, description: "System-level setting. User/domain-generated values must not be stored here." },
    { key: "VISUAL_ASSET_REVIEW_LG_QUALITY", defaultValue: "75", type: "integer", secret: false, userMutable: false, description: "System-level setting. User/domain-generated values must not be stored here." },
    { key: "VISUAL_ASSET_REVIEW_SM_MAX_SIDE", defaultValue: "768", type: "integer", secret: false, userMutable: false, description: "System-level setting. User/domain-generated values must not be stored here." },
    { key: "VISUAL_ASSET_REVIEW_SM_QUALITY", defaultValue: "65", type: "integer", secret: false, userMutable: false, description: "System-level setting. User/domain-generated values must not be stored here." },
    { key: "VISUAL_ASSET_STORE_ORIGINAL", defaultValue: "true", type: "boolean", secret: false, userMutable: false, description: "System-level setting. User/domain-generated values must not be stored here." }
  ]),
});
