// WHY: Orchestration descriptor for Domain Classifier phase.
// Includes final result assembly — merges discoveryResult + seedSearchPlan
// + classifier output into the pipeline's return value.
// When planner is absent (new path), this phase is a pass-through —
// buildOrderedFetchPlan runs after discovery completes in bootstrap.

import { runDomainClassifier } from './runDomainClassifier.js';

export const domainClassifierPhase = {
  id: 'domainClassifier',
  phaseCursor: 'phase_08_domain_classifier',
  checkpoint: 'final',

  execute(ctx) {
    let classifierResult;

    if (ctx.planner) {
      const fn = ctx._di?.runDomainClassifierFn || runDomainClassifier;
      classifierResult = fn({
        discoveryResult: ctx.discoveryResult,
        planner: ctx.planner,
        config: ctx.config,
        logger: ctx.logger,
      });
    }
    // WHY: When planner is absent, buildOrderedFetchPlan runs post-discovery
    // in bootstrapRunProductExecutionState. This phase just assembles the
    // final result without enqueuing to a planner.

    const finalResult = {
      ...ctx.discoveryResult,
      ...(ctx.seedSearchPlan ? { seed_search_plan_output: ctx.seedSearchPlan } : {}),
      enqueue_summary: classifierResult || {},
      // WHY: Pass through manufacturer seed URLs generated by bootstrapPhase
      // so buildOrderedFetchPlan can merge them into the fetch plan.
      ...(ctx.manufacturerSeedUrls?.length ? { manufacturerSeedUrls: ctx.manufacturerSeedUrls } : {}),
    };

    return { discoveryResult: finalResult, finalResult };
  },
};
